// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT Browser/common/org/eclipse/swt/browser/BrowserFunction.java @ af630a9093. DO NOT EDIT.

package browser

import (
	"github.com/haiodo/gowt/internal/jrt"
	"github.com/haiodo/gowt/swt"
	"strconv"
)

type BrowserFunctionImpl interface {
	function_(a0 []any) any
}

// j2go: wraps a subclass from another package; its exported hook names override the defaults.
type browserFunctionHooked struct {
	BrowserFunctionImpl
	hook   BrowserFunctionImpl
	active string
}

func (this *browserFunctionHooked) enter(name string) func() {
	prev := this.active
	this.active = name
	return func() { this.active = prev }
}

func (this *browserFunctionHooked) function_(a0 []any) any {
	if h, ok := this.hook.(interface{ Function_(a0 []any) any }); ok && this.active != "function_" {
		defer this.enter("function_")()
		return h.Function_(a0)
	}
	return this.BrowserFunctionImpl.function_(a0)
}

type BrowserFunction struct {
	browser        *Browser
	name           string
	functionString string
	index          int32
	isEvaluate     bool
	top            bool
	token          string
	frameNames     []string
	impl           BrowserFunctionImpl
}

func (this *BrowserFunction) Impl() BrowserFunctionImpl {
	if h, ok := this.impl.(*browserFunctionHooked); ok {
		return h.hook
	}
	return this.impl
}

func (this *BrowserFunction) SetImpl_(impl BrowserFunctionImpl) {
	this.impl = &browserFunctionHooked{BrowserFunctionImpl: this.impl, hook: impl}
}

func init() { jrt.RegisterClassPackage("BrowserFunction", "org.eclipse.swt.browser") }

func (this *BrowserFunction) AsBrowserFunction() *BrowserFunction { return this }

type BrowserFunctionLike interface {
	AsBrowserFunction() *BrowserFunction
}

func NewBrowserFunction(browser_Like BrowserLike, name string) *BrowserFunction {
	var browser_ *Browser
	if browser_Like != nil {
		browser_ = browser_Like.AsBrowser()
	}
	_ = browser_
	this := &BrowserFunction{}
	this.impl = this
	this.initBrowserFunction(browser_, name)
	return this
}

func (this *BrowserFunction) initBrowserFunction(browser_ *Browser, name string) {
	this.initBrowserFunctionBrowserNameTopFrameNamesCreate(browser_, name, true, nil, true)
}

func NewBrowserFunctionBrowserNameTopFrameNames(browser_Like BrowserLike, name string, top bool, frameNames []string) *BrowserFunction {
	var browser_ *Browser
	if browser_Like != nil {
		browser_ = browser_Like.AsBrowser()
	}
	_ = browser_
	this := &BrowserFunction{}
	this.impl = this
	this.initBrowserFunctionBrowserNameTopFrameNames(browser_, name, top, frameNames)
	return this
}

func (this *BrowserFunction) initBrowserFunctionBrowserNameTopFrameNames(browser_ *Browser, name string, top bool, frameNames []string) {
	this.initBrowserFunctionBrowserNameTopFrameNamesCreate(browser_, name, top, frameNames, true)
}

func newBrowserFunctionBrowserNameTopFrameNamesCreate(browser_ *Browser, name string, top bool, frameNames []string, create bool) *BrowserFunction {
	this := &BrowserFunction{}
	this.impl = this
	this.initBrowserFunctionBrowserNameTopFrameNamesCreate(browser_, name, top, frameNames, create)
	return this
}

func (this *BrowserFunction) initBrowserFunctionBrowserNameTopFrameNamesCreate(browser_ *Browser, name string, top bool, frameNames []string, create bool) {
	if browser_ == (nil) {
		swt.Error(swt.ERROR_NULL_ARGUMENT)
	}
	if name == jrt.NullString {
		swt.Error(swt.ERROR_NULL_ARGUMENT)
	}
	if browser_.IsDisposed() {
		swt.Error(swt.ERROR_WIDGET_DISPOSED)
	}
	browser_.CheckWidget()
	this.browser = browser_
	this.name = name
	this.top = top
	this.frameNames = frameNames
	var random *jrt.Random = jrt.NewRandom()
	var bytes []int8 = make([]int8, 16)
	random.NextBytes(bytes)
	var buffer *jrt.StringBuilder = jrt.NewStringBuilder()
	for _, b := range bytes {
		buffer.Append(strconv.FormatUint(uint64(uint32(int32(b)&0xff)), 16))
	}
	this.token = buffer.ToString()
	if create {
		browser_.webBrowser.impl.createFunction_(this)
	}
}

func (this *BrowserFunction) Dispose() {
	this.DisposeRemove(true)
}

func (this *BrowserFunction) DisposeRemove(remove bool) {
	if this.index < 0 {
		return
	}
	if remove {
		this.browser.webBrowser.impl.destroyFunction_(this)
	}
	this.browser = nil
	this.functionString = ""
	this.name = this.functionString
	this.index = -1
}

func (this *BrowserFunction) Function(arguments []any) any {
	return this.impl.function_(arguments)
}

func (this *BrowserFunction) function_(arguments []any) any {
	if this.index < 0 {
		swt.Error(swt.ERROR_FUNCTION_DISPOSED)
	}
	this.browser.CheckWidget()
	return nil
}

func (this *BrowserFunction) GetBrowser() *Browser {
	if this.index < 0 {
		swt.Error(swt.ERROR_FUNCTION_DISPOSED)
	}
	this.browser.CheckWidget()
	return this.browser
}

func (this *BrowserFunction) GetName() string {
	if this.index < 0 {
		swt.Error(swt.ERROR_FUNCTION_DISPOSED)
	}
	this.browser.CheckWidget()
	return this.name
}

func (this *BrowserFunction) IsDisposed() bool {
	return this.index < 0
}
