// Code generated by j2go from examples/org.eclipse.swt.examples/src/org/eclipse/swt/examples/controlexample/TabFolderTab.java @ af630a9093. DO NOT EDIT.

package controlexample

import (
	"fmt"
	"github.com/haiodo/gowt/swt"
	"os"
)

type TabFolderTab struct {
	Tab
	tabFolder1     *swt.TabFolder
	tabFolderGroup *swt.Group
	topButton      *swt.Button
	bottomButton   *swt.Button
}

var TabFolderTabTabItems1 []string = func() (r []string) {
	defer func() {
		if e := recover(); e != nil {
			fmt.Fprintln(os.Stderr, "gowt: deferred init TabFolderTabTabItems1:", e)
		}
	}()
	r = []string{ControlExampleGetResourceString("TabItem1_0"), ControlExampleGetResourceString("TabItem1_1"), ControlExampleGetResourceString("TabItem1_2")}
	return
}()

func newTabFolderTab(instance *ControlExample) *TabFolderTab {
	this := &TabFolderTab{}
	this.impl = this
	this.initTabFolderTab(instance)
	return this
}

func (this *TabFolderTab) initTabFolderTab(instance *ControlExample) {
	this.Tab.initTab(instance)
}

func (this *TabFolderTab) createExampleGroup_() {
	this.Tab.createExampleGroup_()
	this.tabFolderGroup = swt.NewGroup(upcastswtGroupToswtComposite(this.exampleGroup), swt.NONE)
	this.tabFolderGroup.SetLayout(upcastswtGridLayoutToswtLayout(swt.NewGridLayout()))
	this.tabFolderGroup.SetLayoutData(swt.NewGridDataHorizontalAlignmentVerticalAlignmentGrabExcessHorizontalSpaceGrabExcessVerticalSpace(swt.FILL, swt.FILL, true, true))
	this.tabFolderGroup.SetText("TabFolder")
}

func (this *TabFolderTab) createExampleWidgets_() {
	var style int32 = this.GetDefaultStyle()
	if this.topButton.GetSelection() {
		style |= swt.TOP
	}
	if this.bottomButton.GetSelection() {
		style |= swt.BOTTOM
	}
	if this.borderButton.GetSelection() {
		style |= swt.BORDER
	}
	this.tabFolder1 = swt.NewTabFolder(upcastswtGroupToswtComposite(this.tabFolderGroup), style)
	for i := int32(0); i < int32(len(TabFolderTabTabItems1)); i++ {
		var item *swt.TabItem = swt.NewTabItem(this.tabFolder1, swt.NONE)
		item.SetText(TabFolderTabTabItems1[i])
		item.SetToolTipText(ControlExampleGetResourceStringKeyArgs("Tooltip", []any{TabFolderTabTabItems1[i]}))
		var content *swt.Text = swt.NewText(upcastswtTabFolderToswtComposite(this.tabFolder1), swt.WRAP|swt.MULTI)
		content.SetText(fmt.Sprintf("%s: %d", ControlExampleGetResourceString("TabItem_content"), i))
		item.SetControl(upcastswtTextToswtControl(content))
	}
}

func (this *TabFolderTab) createStyleGroup_() {
	this.Tab.createStyleGroup_()
	this.topButton = swt.NewButton(upcastswtGroupToswtComposite(this.styleGroup), swt.RADIO)
	this.topButton.SetText("SWT.TOP")
	this.topButton.SetSelection(true)
	this.bottomButton = swt.NewButton(upcastswtGroupToswtComposite(this.styleGroup), swt.RADIO)
	this.bottomButton.SetText("SWT.BOTTOM")
	this.borderButton = swt.NewButton(upcastswtGroupToswtComposite(this.styleGroup), swt.CHECK)
	this.borderButton.SetText("SWT.BORDER")
}

func (this *TabFolderTab) getExampleWidgetItems_() []*swt.Item {
	return upcastArrswtTabItemToswtItem(this.tabFolder1.GetItems())
}

func (this *TabFolderTab) getExampleWidgets_() []*swt.Widget {
	return []*swt.Widget{upcastswtTabFolderToswtWidget(this.tabFolder1)}
}

func (this *TabFolderTab) getMethodNames_() []string {
	return []string{"Selection", "SelectionIndex", "ToolTipText"}
}

func (this *TabFolderTab) setMethodName_(methodRoot string) string {
	var cond1 string
	if methodRoot == "SelectionIndex" {
		cond1 = "setSelection"
	} else {
		cond1 = fmt.Sprintf("set%s", methodRoot)
	}
	return cond1
}

func (this *TabFolderTab) parameterForType_(typeName string, value string, widget *swt.Widget) []any {
	if len(value) == 0 {
		return []any{make([]*swt.TabItem, 0)}
	}
	if typeName == "org.eclipse.swt.widgets.TabItem" {
		var item *swt.TabItem = this.FindItem(value, (castswtWidgetToswtTabFolder(widget)).GetItems())
		if item != (nil) {
			return []any{item}
		}
	}
	if typeName == "[Lorg.eclipse.swt.widgets.TabItem;" {
		var values []string = this.Split(value, ',')
		var items []*swt.TabItem = make([]*swt.TabItem, int32(len(values)))
		for i := int32(0); i < int32(len(values)); i++ {
			items[i] = this.FindItem(values[i], (castswtWidgetToswtTabFolder(widget)).GetItems())
		}
		return []any{items}
	}
	return this.Tab.parameterForType_(typeName, value, widget)
}

func (this *TabFolderTab) FindItem(value string, items []*swt.TabItem) *swt.TabItem {
	for _, item := range items {
		if item.GetText() == value {
			return item
		}
	}
	return nil
}

func (this *TabFolderTab) getShortTabText_() string {
	return "TF"
}

func (this *TabFolderTab) getTabText_() string {
	return "TabFolder"
}

func (this *TabFolderTab) setExampleWidgetState_() {
	this.Tab.setExampleWidgetState_()
	this.topButton.SetSelection((this.tabFolder1.GetStyle() & swt.TOP) != 0)
	this.bottomButton.SetSelection((this.tabFolder1.GetStyle() & swt.BOTTOM) != 0)
	this.borderButton.SetSelection((this.tabFolder1.GetStyle() & swt.BORDER) != 0)
}

func upcastswtTextToswtControl(x *swt.Text) *swt.Control {
	if x == nil {
		return nil
	}
	return &x.Control
}

func upcastswtTabItemToswtItem(x *swt.TabItem) *swt.Item {
	if x == nil {
		return nil
	}
	return &x.Item
}

func upcastArrswtTabItemToswtItem(x []*swt.TabItem) []*swt.Item {
	if x == nil {
		return nil
	}
	r := make([]*swt.Item, len(x))
	for i, e := range x {
		r[i] = upcastswtTabItemToswtItem(e)
	}
	return r
}

func upcastswtTabFolderToswtWidget(x *swt.TabFolder) *swt.Widget {
	if x == nil {
		return nil
	}
	return &x.Widget
}

// j2go: instanceof helper for swt.TabFolder and its subclasses within the translated set.
func widgetImplAsTabFolder(x any) (*swt.TabFolder, bool) {
	switch v := x.(type) {
	case *swt.TabFolder:
		if v == nil {
			return nil, false
		}
		return v, true
	}
	return nil, false
}

func castswtWidgetToswtTabFolder(x *swt.Widget) *swt.TabFolder {
	if x == nil {
		return nil
	}
	v, ok := widgetImplAsTabFolder(x.Impl())
	if !ok {
		panic("java.lang.ClassCastException: swt.TabFolder")
	}
	return v
}
