// Code generated by j2go from examples/org.eclipse.swt.examples/src/org/eclipse/swt/examples/controlexample/MenuTab.java @ af630a9093. DO NOT EDIT.

package controlexample

import (
	"fmt"
	"github.com/haiodo/gowt/swt"
	"unicode/utf16"
)

type MenuTab struct {
	Tab
	barButton          *swt.Button
	dropDownButton     *swt.Button
	popUpButton        *swt.Button
	noRadioGroupButton *swt.Button
	leftToRightButton  *swt.Button
	rightToLeftButton  *swt.Button
	checkButton        *swt.Button
	cascadeButton      *swt.Button
	pushButton         *swt.Button
	radioButton        *swt.Button
	separatorButton    *swt.Button
	imagesButton       *swt.Button
	acceleratorsButton *swt.Button
	mnemonicsButton    *swt.Button
	subMenuButton      *swt.Button
	subSubMenuButton   *swt.Button
	tooltipButton      *swt.Button
	createButton       *swt.Button
	closeAllButton     *swt.Button
	menuItemStyleGroup *swt.Group
	shellCount         int32
	shells             []*swt.Shell
}

func newMenuTab(instance *ControlExample) *MenuTab {
	this := &MenuTab{}
	this.impl = this
	this.initMenuTab(instance)
	return this
}

func (this *MenuTab) initMenuTab(instance *ControlExample) {
	this.Tab.initTab(instance)
	this.shellCount = 0
	this.shells = make([]*swt.Shell, 4)
}

func (this *MenuTab) CloseAllShells() {
	for i := int32(0); i < this.shellCount; i++ {
		if this.shells[i] != (nil) && !this.shells[i].IsDisposed() {
			this.shells[i].Dispose()
		}
	}
	this.shellCount = 0
}

func (this *MenuTab) CreateButtonSelected(event *swt.SelectionEvent) {
	if this.shellCount >= int32(len(this.shells)) {
		var newShells []*swt.Shell = make([]*swt.Shell, int32(len(this.shells))+4)
		copy(newShells[0:], this.shells[0:0+int32(len(this.shells))])
		this.shells = newShells
	}
	var orientation int32 = 0
	if this.leftToRightButton.GetSelection() {
		orientation |= swt.LEFT_TO_RIGHT
	}
	if this.rightToLeftButton.GetSelection() {
		orientation |= swt.RIGHT_TO_LEFT
	}
	var radioBehavior int32 = 0
	if this.noRadioGroupButton.GetSelection() {
		radioBehavior |= swt.NO_RADIO_GROUP
	}
	var shell *swt.Shell = swt.NewShellStyle(swt.SHELL_TRIM | orientation)
	this.shells[this.shellCount] = shell
	if this.barButton.GetSelection() {
		var menuBar *swt.Menu = swt.NewMenuParentStyle(upcastswtShellToswtDecorations(shell), swt.BAR|radioBehavior)
		shell.SetMenuBar(menuBar)
		this.HookListeners(upcastswtMenuToswtWidget(menuBar))
		if this.dropDownButton.GetSelection() && this.cascadeButton.GetSelection() {
			var item *swt.MenuItem = swt.NewMenuItem(menuBar, swt.CASCADE)
			item.SetText(this.GetMenuItemText("Cascade"))
			if this.imagesButton.GetSelection() {
				item.SetImage(this.instance.images[ControlExampleCiOpenFolder])
			}
			if this.tooltipButton.GetSelection() {
				item.SetToolTipText(ControlExampleGetResourceStringKeyArgs("Tooltip", []any{item.GetText()}))
			}
			this.HookListeners(upcastswtMenuItemToswtWidget(item))
			var dropDownMenu *swt.Menu = swt.NewMenuParentStyle(upcastswtShellToswtDecorations(shell), swt.DROP_DOWN|radioBehavior)
			item.SetMenu(dropDownMenu)
			this.HookListeners(upcastswtMenuToswtWidget(dropDownMenu))
			this.CreateMenuItems(dropDownMenu, this.subMenuButton.GetSelection(), this.subSubMenuButton.GetSelection())
		}
	}
	if this.popUpButton.GetSelection() {
		var popUpMenu *swt.Menu = swt.NewMenuParentStyle(upcastswtShellToswtDecorations(shell), swt.POP_UP|radioBehavior)
		shell.SetMenu(popUpMenu)
		this.HookListeners(upcastswtMenuToswtWidget(popUpMenu))
		this.CreateMenuItems(popUpMenu, this.subMenuButton.GetSelection(), this.subSubMenuButton.GetSelection())
	}
	shell.SetSize(300, 100)
	shell.SetText(fmt.Sprintf("%s%d", ControlExampleGetResourceString("Title"), this.shellCount))
	shell.AddPaintListener(&PaintListenerFunc{fn: func(e *swt.PaintEvent) {
		e.Gc.DrawString(ControlExampleGetResourceString("PopupMenuHere"), 20, 20)
	}})
	shell.Open()
	this.shellCount++
}

func (this *MenuTab) createControlGroup_() {
	this.controlGroup = swt.NewGroup(this.tabFolderPage, swt.NONE)
	this.controlGroup.SetLayout(upcastswtGridLayoutToswtLayout(swt.NewGridLayoutNumColumnsMakeColumnsEqualWidth(2, true)))
	this.controlGroup.SetLayoutData(swt.NewGridDataStyle(swt.GridDataHORIZONTAL_ALIGN_FILL | swt.GridDataVERTICAL_ALIGN_FILL))
	this.controlGroup.SetText(ControlExampleGetResourceString("Parameters"))
	this.styleGroup = swt.NewGroup(upcastswtGroupToswtComposite(this.controlGroup), swt.NONE)
	this.styleGroup.SetLayout(upcastswtGridLayoutToswtLayout(swt.NewGridLayout()))
	this.styleGroup.SetLayoutData(swt.NewGridDataStyle(swt.GridDataHORIZONTAL_ALIGN_FILL | swt.GridDataVERTICAL_ALIGN_FILL))
	this.styleGroup.SetText(ControlExampleGetResourceString("Menu_Styles"))
	this.menuItemStyleGroup = swt.NewGroup(upcastswtGroupToswtComposite(this.controlGroup), swt.NONE)
	this.menuItemStyleGroup.SetLayout(upcastswtGridLayoutToswtLayout(swt.NewGridLayout()))
	this.menuItemStyleGroup.SetLayoutData(swt.NewGridDataStyle(swt.GridDataHORIZONTAL_ALIGN_FILL | swt.GridDataVERTICAL_ALIGN_FILL))
	this.menuItemStyleGroup.SetText(ControlExampleGetResourceString("MenuItem_Styles"))
	this.otherGroup = swt.NewGroup(upcastswtGroupToswtComposite(this.controlGroup), swt.NONE)
	this.otherGroup.SetLayout(upcastswtGridLayoutToswtLayout(swt.NewGridLayout()))
	this.otherGroup.SetLayoutData(swt.NewGridDataStyle(swt.GridDataHORIZONTAL_ALIGN_FILL | swt.GridDataVERTICAL_ALIGN_FILL))
	this.otherGroup.SetText(ControlExampleGetResourceString("Other"))
}

func (this *MenuTab) createControlWidgets_() {
	this.barButton = swt.NewButton(upcastswtGroupToswtComposite(this.styleGroup), swt.CHECK)
	this.barButton.SetText("SWT.BAR")
	this.dropDownButton = swt.NewButton(upcastswtGroupToswtComposite(this.styleGroup), swt.CHECK)
	this.dropDownButton.SetText("SWT.DROP_DOWN")
	this.popUpButton = swt.NewButton(upcastswtGroupToswtComposite(this.styleGroup), swt.CHECK)
	this.popUpButton.SetText("SWT.POP_UP")
	this.noRadioGroupButton = swt.NewButton(upcastswtGroupToswtComposite(this.styleGroup), swt.CHECK)
	this.noRadioGroupButton.SetText("SWT.NO_RADIO_GROUP")
	this.leftToRightButton = swt.NewButton(upcastswtGroupToswtComposite(this.styleGroup), swt.RADIO)
	this.leftToRightButton.SetText("SWT.LEFT_TO_RIGHT")
	this.leftToRightButton.SetSelection(true)
	this.rightToLeftButton = swt.NewButton(upcastswtGroupToswtComposite(this.styleGroup), swt.RADIO)
	this.rightToLeftButton.SetText("SWT.RIGHT_TO_LEFT")
	this.cascadeButton = swt.NewButton(upcastswtGroupToswtComposite(this.menuItemStyleGroup), swt.CHECK)
	this.cascadeButton.SetText("SWT.CASCADE")
	this.checkButton = swt.NewButton(upcastswtGroupToswtComposite(this.menuItemStyleGroup), swt.CHECK)
	this.checkButton.SetText("SWT.CHECK")
	this.pushButton = swt.NewButton(upcastswtGroupToswtComposite(this.menuItemStyleGroup), swt.CHECK)
	this.pushButton.SetText("SWT.PUSH")
	this.radioButton = swt.NewButton(upcastswtGroupToswtComposite(this.menuItemStyleGroup), swt.CHECK)
	this.radioButton.SetText("SWT.RADIO")
	this.separatorButton = swt.NewButton(upcastswtGroupToswtComposite(this.menuItemStyleGroup), swt.CHECK)
	this.separatorButton.SetText("SWT.SEPARATOR")
	this.enabledButton = swt.NewButton(upcastswtGroupToswtComposite(this.otherGroup), swt.CHECK)
	this.enabledButton.SetText(ControlExampleGetResourceString("Enabled"))
	this.enabledButton.SetSelection(true)
	this.imagesButton = swt.NewButton(upcastswtGroupToswtComposite(this.otherGroup), swt.CHECK)
	this.imagesButton.SetText(ControlExampleGetResourceString("Images"))
	this.acceleratorsButton = swt.NewButton(upcastswtGroupToswtComposite(this.otherGroup), swt.CHECK)
	this.acceleratorsButton.SetText(ControlExampleGetResourceString("Accelerators"))
	this.mnemonicsButton = swt.NewButton(upcastswtGroupToswtComposite(this.otherGroup), swt.CHECK)
	this.mnemonicsButton.SetText(ControlExampleGetResourceString("Mnemonics"))
	this.subMenuButton = swt.NewButton(upcastswtGroupToswtComposite(this.otherGroup), swt.CHECK)
	this.subMenuButton.SetText(ControlExampleGetResourceString("SubMenu"))
	this.subSubMenuButton = swt.NewButton(upcastswtGroupToswtComposite(this.otherGroup), swt.CHECK)
	this.subSubMenuButton.SetText(ControlExampleGetResourceString("SubSubMenu"))
	this.tooltipButton = swt.NewButton(upcastswtGroupToswtComposite(this.otherGroup), swt.CHECK)
	this.tooltipButton.SetText(ControlExampleGetResourceString("Show_Tooltip"))
	swt.NewLabel(upcastswtGroupToswtComposite(this.controlGroup), swt.NONE)
	this.createButton = swt.NewButton(upcastswtGroupToswtComposite(this.controlGroup), swt.NONE)
	this.createButton.SetLayoutData(swt.NewGridDataStyle(swt.GridDataHORIZONTAL_ALIGN_END))
	this.createButton.SetText(ControlExampleGetResourceString("Create_Shell"))
	this.closeAllButton = swt.NewButton(upcastswtGroupToswtComposite(this.controlGroup), swt.NONE)
	this.closeAllButton.SetLayoutData(swt.NewGridDataStyle(swt.GridDataHORIZONTAL_ALIGN_BEGINNING))
	this.closeAllButton.SetText(ControlExampleGetResourceString("Close_All_Shells"))
	this.createButton.AddSelectionListener(swt.SelectionListenerWidgetSelectedAdapter(this.CreateButtonSelected))
	this.closeAllButton.AddSelectionListener(swt.SelectionListenerWidgetSelectedAdapter(func(e *swt.SelectionEvent) {
		this.CloseAllShells()
	}))
	this.subMenuButton.AddSelectionListener(swt.SelectionListenerWidgetSelectedAdapter(func(e *swt.SelectionEvent) {
		this.subSubMenuButton.SetEnabled(this.subMenuButton.GetSelection())
	}))
	this.barButton.SetSelection(true)
	this.dropDownButton.SetSelection(true)
	this.popUpButton.SetSelection(true)
	this.cascadeButton.SetSelection(true)
	this.checkButton.SetSelection(true)
	this.pushButton.SetSelection(true)
	this.radioButton.SetSelection(true)
	this.separatorButton.SetSelection(true)
	this.subSubMenuButton.SetEnabled(this.subMenuButton.GetSelection())
}

func (this *MenuTab) CreateMenuItems(menuLike swt.MenuLike, createSubMenu bool, createSubSubMenu bool) {
	var menu *swt.Menu
	if menuLike != nil {
		menu = menuLike.AsMenu()
	}
	_ = menu
	var item *swt.MenuItem
	if this.pushButton.GetSelection() {
		item = swt.NewMenuItem(menu, swt.PUSH)
		item.SetText(this.GetMenuItemText("Push"))
		if this.acceleratorsButton.GetSelection() {
			item.SetAccelerator(swt.MOD1 + swt.MOD2 + int32('P'))
		}
		if this.imagesButton.GetSelection() {
			item.SetImage(this.instance.images[ControlExampleCiClosedFolder])
		}
		item.SetEnabled(this.enabledButton.GetSelection())
		if this.tooltipButton.GetSelection() {
			item.SetToolTipText(ControlExampleGetResourceStringKeyArgs("Tooltip", []any{item.GetText()}))
		}
		this.HookListeners(upcastswtMenuItemToswtWidget(item))
	}
	if this.separatorButton.GetSelection() {
		item = swt.NewMenuItem(menu, swt.SEPARATOR)
		if this.tooltipButton.GetSelection() {
			item.SetToolTipText(ControlExampleGetResourceStringKeyArgs("Tooltip", []any{item.GetText()}))
		}
	}
	if this.checkButton.GetSelection() {
		item = swt.NewMenuItem(menu, swt.CHECK)
		item.SetText(this.GetMenuItemText("Check"))
		if this.acceleratorsButton.GetSelection() {
			item.SetAccelerator(swt.MOD1 + swt.MOD2 + int32('C'))
		}
		if this.imagesButton.GetSelection() {
			item.SetImage(this.instance.images[ControlExampleCiOpenFolder])
		}
		item.SetEnabled(this.enabledButton.GetSelection())
		if this.tooltipButton.GetSelection() {
			item.SetToolTipText(ControlExampleGetResourceStringKeyArgs("Tooltip", []any{item.GetText()}))
		}
		this.HookListeners(upcastswtMenuItemToswtWidget(item))
	}
	if this.radioButton.GetSelection() {
		item = swt.NewMenuItem(menu, swt.RADIO)
		item.SetText(this.GetMenuItemText("1Radio"))
		if this.acceleratorsButton.GetSelection() {
			item.SetAccelerator(swt.MOD1 + swt.MOD2 + int32('1'))
		}
		if this.imagesButton.GetSelection() {
			item.SetImage(this.instance.images[ControlExampleCiTarget])
		}
		item.SetSelection(true)
		item.SetEnabled(this.enabledButton.GetSelection())
		if this.tooltipButton.GetSelection() {
			item.SetToolTipText(ControlExampleGetResourceStringKeyArgs("Tooltip", []any{item.GetText()}))
		}
		this.HookListeners(upcastswtMenuItemToswtWidget(item))
		item = swt.NewMenuItem(menu, swt.RADIO)
		item.SetText(this.GetMenuItemText("2Radio"))
		if this.acceleratorsButton.GetSelection() {
			item.SetAccelerator(swt.MOD1 + swt.MOD2 + int32('2'))
		}
		if this.imagesButton.GetSelection() {
			item.SetImage(this.instance.images[ControlExampleCiTarget])
		}
		item.SetEnabled(this.enabledButton.GetSelection())
		if this.tooltipButton.GetSelection() {
			item.SetToolTipText(ControlExampleGetResourceStringKeyArgs("Tooltip", []any{item.GetText()}))
		}
		this.HookListeners(upcastswtMenuItemToswtWidget(item))
	}
	if createSubMenu && this.cascadeButton.GetSelection() {
		item = swt.NewMenuItem(menu, swt.CASCADE)
		item.SetText(this.GetMenuItemText("Cascade"))
		if this.imagesButton.GetSelection() {
			item.SetImage(this.instance.images[ControlExampleCiOpenFolder])
		}
		this.HookListeners(upcastswtMenuItemToswtWidget(item))
		var subMenu *swt.Menu = swt.NewMenuParentStyle(upcastswtShellToswtDecorations(menu.GetShell()), swt.DROP_DOWN)
		item.SetMenu(subMenu)
		item.SetEnabled(this.enabledButton.GetSelection())
		this.HookListeners(upcastswtMenuToswtWidget(subMenu))
		if this.tooltipButton.GetSelection() {
			item.SetToolTipText(ControlExampleGetResourceStringKeyArgs("Tooltip", []any{item.GetText()}))
		}
		this.CreateMenuItems(subMenu, createSubSubMenu, false)
	}
}

func (this *MenuTab) GetMenuItemText(item string) string {
	var cascade bool = (item == "Cascade")
	var mnemonic bool = this.mnemonicsButton.GetSelection()
	var accelerator bool = this.acceleratorsButton.GetSelection()
	var acceleratorKey uint16 = utf16.Encode([]rune(item))[0]
	if mnemonic && accelerator && !cascade {
		return fmt.Sprintf("%s\tCtrl+Shift+%d", ControlExampleGetResourceString(fmt.Sprintf("%sWithMnemonic", item)), acceleratorKey)
	}
	if accelerator && !cascade {
		return fmt.Sprintf("%s\tCtrl+Shift+%d", ControlExampleGetResourceString(item), acceleratorKey)
	}
	if mnemonic {
		return ControlExampleGetResourceString(fmt.Sprintf("%sWithMnemonic", item))
	}
	return ControlExampleGetResourceString(item)
}

func (this *MenuTab) getTabText_() string {
	return "Menu"
}

func upcastswtMenuToswtWidget(x *swt.Menu) *swt.Widget {
	if x == nil {
		return nil
	}
	return &x.Widget
}

func upcastswtMenuItemToswtWidget(x *swt.MenuItem) *swt.Widget {
	if x == nil {
		return nil
	}
	return &x.Widget
}
