// Code generated by j2go from examples/org.eclipse.swt.examples/src/org/eclipse/swt/examples/controlexample/ShellTab.java @ af630a9093. DO NOT EDIT.

package controlexample

import (
	"fmt"
	"github.com/haiodo/gowt/swt"
)

type ShellTab struct {
	Tab
	noParentButton         *swt.Button
	parentButton           *swt.Button
	noTrimButton           *swt.Button
	closeButton            *swt.Button
	titleButton            *swt.Button
	minButton              *swt.Button
	maxButton              *swt.Button
	borderButton           *swt.Button
	resizeButton           *swt.Button
	onTopButton            *swt.Button
	toolButton             *swt.Button
	sheetButton            *swt.Button
	shellTrimButton        *swt.Button
	dialogTrimButton       *swt.Button
	noMoveButton           *swt.Button
	createButton           *swt.Button
	closeAllButton         *swt.Button
	modelessButton         *swt.Button
	primaryModalButton     *swt.Button
	applicationModalButton *swt.Button
	systemModalButton      *swt.Button
	imageButton            *swt.Button
	parentStyleGroup       *swt.Group
	modalStyleGroup        *swt.Group
	shellCount             int32
	shells                 []*swt.Shell
}

func newShellTab(instance *ControlExample) *ShellTab {
	this := &ShellTab{}
	this.impl = this
	this.initShellTab(instance)
	return this
}

func (this *ShellTab) initShellTab(instance *ControlExample) {
	this.Tab.initTab(instance)
	this.shellCount = 0
	this.shells = make([]*swt.Shell, 4)
}

func (this *ShellTab) CloseAllShells() {
	for i := int32(0); i < this.shellCount; i++ {
		if this.shells[i] != (nil) && !this.shells[i].IsDisposed() {
			this.shells[i].Dispose()
			this.shells[i] = nil
		}
	}
	this.shellCount = 0
}

func (this *ShellTab) CreateButtonSelected(event *swt.SelectionEvent) {
	if this.shellCount >= int32(len(this.shells)) {
		var newShells []*swt.Shell = make([]*swt.Shell, int32(len(this.shells))+4)
		copy(newShells[0:], this.shells[0:0+int32(len(this.shells))])
		this.shells = newShells
	}
	var style int32 = swt.NONE
	if this.noTrimButton.GetSelection() {
		style |= swt.NO_TRIM
	}
	if this.noMoveButton.GetSelection() {
		style |= swt.NO_MOVE
	}
	if this.closeButton.GetSelection() {
		style |= swt.CLOSE
	}
	if this.titleButton.GetSelection() {
		style |= swt.TITLE
	}
	if this.minButton.GetSelection() {
		style |= swt.MIN
	}
	if this.maxButton.GetSelection() {
		style |= swt.MAX
	}
	if this.borderButton.GetSelection() {
		style |= swt.BORDER
	}
	if this.resizeButton.GetSelection() {
		style |= swt.RESIZE
	}
	if this.onTopButton.GetSelection() {
		style |= swt.ON_TOP
	}
	if this.toolButton.GetSelection() {
		style |= swt.TOOL
	}
	if this.sheetButton.GetSelection() {
		style |= swt.SHEET
	}
	if this.modelessButton.GetSelection() {
		style |= swt.MODELESS
	}
	if this.primaryModalButton.GetSelection() {
		style |= swt.PRIMARY_MODAL
	}
	if this.applicationModalButton.GetSelection() {
		style |= swt.APPLICATION_MODAL
	}
	if this.systemModalButton.GetSelection() {
		style |= swt.SYSTEM_MODAL
	}
	if this.noParentButton.GetSelection() {
		this.shells[this.shellCount] = swt.NewShellStyle(style)
	} else {
		this.shells[this.shellCount] = swt.NewShellParentStyle(this.shell, style)
	}
	var currentShell *swt.Shell = this.shells[this.shellCount]
	currentShell.SetBackgroundMode(swt.INHERIT_DEFAULT)
	var button *swt.Button = swt.NewButton(upcastswtShellToswtComposite(currentShell), swt.CHECK)
	button.SetBounds(20, 20, 120, 30)
	button.SetText(ControlExampleGetResourceString("FullScreen"))
	button.AddSelectionListener(swt.SelectionListenerWidgetSelectedAdapter(func(e *swt.SelectionEvent) {
		currentShell.SetFullScreen(button.GetSelection())
	}))
	var close *swt.Button = swt.NewButton(upcastswtShellToswtComposite(currentShell), swt.PUSH)
	close.SetBounds(160, 20, 120, 30)
	close.SetText(ControlExampleGetResourceString("Close"))
	close.AddListener(swt.Selection, &ListenerFunc{fn: func(event1 *swt.Event) {
		currentShell.Dispose()
		this.shellCount--
	}})
	currentShell.SetSize(300, 100)
	currentShell.SetText(fmt.Sprintf("%s%d", ControlExampleGetResourceString("Title"), this.shellCount))
	if this.imageButton.GetSelection() {
		currentShell.SetImage(this.instance.images[ControlExampleCiTarget])
	}
	if this.backgroundImageButton.GetSelection() {
		currentShell.SetBackgroundImage(this.instance.images[ControlExampleCiBackground])
	}
	this.HookListeners(upcastswtShellToswtWidget(currentShell))
	currentShell.Open()
	this.shellCount++
}

func (this *ShellTab) createControlGroup_() {
	this.controlGroup = swt.NewGroup(this.tabFolderPage, swt.NONE)
	this.controlGroup.SetLayout(upcastswtGridLayoutToswtLayout(swt.NewGridLayoutNumColumnsMakeColumnsEqualWidth(2, true)))
	this.controlGroup.SetLayoutData(swt.NewGridDataStyle(swt.GridDataHORIZONTAL_ALIGN_FILL | swt.GridDataVERTICAL_ALIGN_FILL))
	this.controlGroup.SetText(ControlExampleGetResourceString("Parameters"))
	this.styleGroup = swt.NewGroup(upcastswtGroupToswtComposite(this.controlGroup), swt.NONE)
	this.styleGroup.SetLayout(upcastswtGridLayoutToswtLayout(swt.NewGridLayout()))
	this.styleGroup.SetLayoutData(swt.NewGridDataHorizontalAlignmentVerticalAlignmentGrabExcessHorizontalSpaceGrabExcessVerticalSpaceHorizontalSpanVerticalSpan(swt.FILL, swt.FILL, false, false, 1, 3))
	this.styleGroup.SetText(ControlExampleGetResourceString("Decoration_Styles"))
	this.modalStyleGroup = swt.NewGroup(upcastswtGroupToswtComposite(this.controlGroup), swt.NONE)
	this.modalStyleGroup.SetLayout(upcastswtGridLayoutToswtLayout(swt.NewGridLayout()))
	this.modalStyleGroup.SetLayoutData(swt.NewGridDataStyle(swt.GridDataHORIZONTAL_ALIGN_FILL | swt.GridDataVERTICAL_ALIGN_FILL))
	this.modalStyleGroup.SetText(ControlExampleGetResourceString("Modal_Styles"))
	this.otherGroup = swt.NewGroup(upcastswtGroupToswtComposite(this.controlGroup), swt.NONE)
	this.otherGroup.SetLayout(upcastswtGridLayoutToswtLayout(swt.NewGridLayout()))
	this.otherGroup.SetLayoutData(swt.NewGridDataHorizontalAlignmentVerticalAlignmentGrabExcessHorizontalSpaceGrabExcessVerticalSpace(swt.FILL, swt.FILL, false, false))
	this.otherGroup.SetText(ControlExampleGetResourceString("Other"))
	this.parentStyleGroup = swt.NewGroup(upcastswtGroupToswtComposite(this.controlGroup), swt.NONE)
	this.parentStyleGroup.SetLayout(upcastswtGridLayoutToswtLayout(swt.NewGridLayout()))
	var gridData *swt.GridData = swt.NewGridDataStyle(swt.GridDataHORIZONTAL_ALIGN_FILL)
	this.parentStyleGroup.SetLayoutData(gridData)
	this.parentStyleGroup.SetText(ControlExampleGetResourceString("Parent"))
}

func (this *ShellTab) createControlWidgets_() {
	this.noParentButton = swt.NewButton(upcastswtGroupToswtComposite(this.parentStyleGroup), swt.RADIO)
	this.noParentButton.SetText(ControlExampleGetResourceString("No_Parent"))
	this.parentButton = swt.NewButton(upcastswtGroupToswtComposite(this.parentStyleGroup), swt.RADIO)
	this.parentButton.SetText(ControlExampleGetResourceString("Parent"))
	this.noTrimButton = swt.NewButton(upcastswtGroupToswtComposite(this.styleGroup), swt.CHECK)
	this.noTrimButton.SetText("SWT.NO_TRIM")
	this.noMoveButton = swt.NewButton(upcastswtGroupToswtComposite(this.styleGroup), swt.CHECK)
	this.noMoveButton.SetText("SWT.NO_MOVE")
	this.closeButton = swt.NewButton(upcastswtGroupToswtComposite(this.styleGroup), swt.CHECK)
	this.closeButton.SetText("SWT.CLOSE")
	this.titleButton = swt.NewButton(upcastswtGroupToswtComposite(this.styleGroup), swt.CHECK)
	this.titleButton.SetText("SWT.TITLE")
	this.minButton = swt.NewButton(upcastswtGroupToswtComposite(this.styleGroup), swt.CHECK)
	this.minButton.SetText("SWT.MIN")
	this.maxButton = swt.NewButton(upcastswtGroupToswtComposite(this.styleGroup), swt.CHECK)
	this.maxButton.SetText("SWT.MAX")
	this.borderButton = swt.NewButton(upcastswtGroupToswtComposite(this.styleGroup), swt.CHECK)
	this.borderButton.SetText("SWT.BORDER")
	this.resizeButton = swt.NewButton(upcastswtGroupToswtComposite(this.styleGroup), swt.CHECK)
	this.resizeButton.SetText("SWT.RESIZE")
	this.onTopButton = swt.NewButton(upcastswtGroupToswtComposite(this.styleGroup), swt.CHECK)
	this.onTopButton.SetText("SWT.ON_TOP")
	this.toolButton = swt.NewButton(upcastswtGroupToswtComposite(this.styleGroup), swt.CHECK)
	this.toolButton.SetText("SWT.TOOL")
	this.sheetButton = swt.NewButton(upcastswtGroupToswtComposite(this.styleGroup), swt.CHECK)
	this.sheetButton.SetText("SWT.SHEET")
	var separator *swt.Label = swt.NewLabel(upcastswtGroupToswtComposite(this.styleGroup), swt.SEPARATOR|swt.HORIZONTAL)
	separator.SetLayoutData(swt.NewGridDataHorizontalAlignmentVerticalAlignmentGrabExcessHorizontalSpaceGrabExcessVerticalSpace(swt.FILL, swt.CENTER, true, false))
	this.shellTrimButton = swt.NewButton(upcastswtGroupToswtComposite(this.styleGroup), swt.CHECK)
	this.shellTrimButton.SetText("SWT.SHELL_TRIM")
	this.dialogTrimButton = swt.NewButton(upcastswtGroupToswtComposite(this.styleGroup), swt.CHECK)
	this.dialogTrimButton.SetText("SWT.DIALOG_TRIM")
	this.modelessButton = swt.NewButton(upcastswtGroupToswtComposite(this.modalStyleGroup), swt.RADIO)
	this.modelessButton.SetText("SWT.MODELESS")
	this.primaryModalButton = swt.NewButton(upcastswtGroupToswtComposite(this.modalStyleGroup), swt.RADIO)
	this.primaryModalButton.SetText("SWT.PRIMARY_MODAL")
	this.applicationModalButton = swt.NewButton(upcastswtGroupToswtComposite(this.modalStyleGroup), swt.RADIO)
	this.applicationModalButton.SetText("SWT.APPLICATION_MODAL")
	this.systemModalButton = swt.NewButton(upcastswtGroupToswtComposite(this.modalStyleGroup), swt.RADIO)
	this.systemModalButton.SetText("SWT.SYSTEM_MODAL")
	this.imageButton = swt.NewButton(upcastswtGroupToswtComposite(this.otherGroup), swt.CHECK)
	this.imageButton.SetText(ControlExampleGetResourceString("Image"))
	this.backgroundImageButton = swt.NewButton(upcastswtGroupToswtComposite(this.otherGroup), swt.CHECK)
	this.backgroundImageButton.SetText(ControlExampleGetResourceString("BackgroundImage"))
	this.CreateSetGetGroup()
	this.createButton = swt.NewButton(upcastswtGroupToswtComposite(this.controlGroup), swt.NONE)
	var gridData *swt.GridData = swt.NewGridDataStyle(swt.GridDataHORIZONTAL_ALIGN_END)
	this.createButton.SetLayoutData(gridData)
	this.createButton.SetText(ControlExampleGetResourceString("Create_Shell"))
	this.closeAllButton = swt.NewButton(upcastswtGroupToswtComposite(this.controlGroup), swt.NONE)
	gridData = swt.NewGridDataStyle(swt.GridDataHORIZONTAL_ALIGN_BEGINNING)
	this.closeAllButton.SetText(ControlExampleGetResourceString("Close_All_Shells"))
	this.closeAllButton.SetLayoutData(gridData)
	this.createButton.AddSelectionListener(swt.SelectionListenerWidgetSelectedAdapter(this.CreateButtonSelected))
	this.closeAllButton.AddSelectionListener(swt.SelectionListenerWidgetSelectedAdapter(func(e *swt.SelectionEvent) {
		this.CloseAllShells()
	}))
	var decorationButtonListener swt.SelectionListener = swt.SelectionListenerWidgetSelectedAdapter(this.DecorationButtonSelected)
	this.noTrimButton.AddSelectionListener(decorationButtonListener)
	this.noMoveButton.AddSelectionListener(decorationButtonListener)
	this.closeButton.AddSelectionListener(decorationButtonListener)
	this.titleButton.AddSelectionListener(decorationButtonListener)
	this.minButton.AddSelectionListener(decorationButtonListener)
	this.maxButton.AddSelectionListener(decorationButtonListener)
	this.borderButton.AddSelectionListener(decorationButtonListener)
	this.resizeButton.AddSelectionListener(decorationButtonListener)
	this.dialogTrimButton.AddSelectionListener(decorationButtonListener)
	this.shellTrimButton.AddSelectionListener(decorationButtonListener)
	this.applicationModalButton.AddSelectionListener(decorationButtonListener)
	this.systemModalButton.AddSelectionListener(decorationButtonListener)
	this.noParentButton.SetSelection(true)
	this.modelessButton.SetSelection(true)
}

func (this *ShellTab) DecorationButtonSelected(event *swt.SelectionEvent) {
	var widget *swt.Button = castswtWidgetToswtButton(event.Widget)
	if widget == this.applicationModalButton || widget == this.systemModalButton {
		if widget.GetSelection() {
			this.closeButton.SetSelection(true)
			this.noTrimButton.SetSelection(false)
		}
		return
	}
	if widget == this.closeButton {
		if this.applicationModalButton.GetSelection() || this.systemModalButton.GetSelection() {
			this.closeButton.SetSelection(true)
		}
	}
	if widget.GetSelection() {
		if widget == this.noTrimButton {
			if this.applicationModalButton.GetSelection() || this.systemModalButton.GetSelection() {
				this.noTrimButton.SetSelection(false)
				return
			}
			this.closeButton.SetSelection(false)
			this.titleButton.SetSelection(false)
			this.minButton.SetSelection(false)
			this.maxButton.SetSelection(false)
			this.borderButton.SetSelection(false)
			this.resizeButton.SetSelection(false)
		} else {
			this.noTrimButton.SetSelection(false)
		}
	}
	if widget == this.dialogTrimButton || widget == this.shellTrimButton {
		if widget.GetSelection() && widget == this.dialogTrimButton {
			this.shellTrimButton.SetSelection(false)
		} else {
			this.dialogTrimButton.SetSelection(false)
		}
		this.closeButton.SetSelection(widget.GetSelection())
		this.titleButton.SetSelection(widget.GetSelection())
		this.minButton.SetSelection(widget == this.shellTrimButton && widget.GetSelection())
		this.maxButton.SetSelection(widget == this.shellTrimButton && widget.GetSelection())
		this.borderButton.SetSelection(widget == this.dialogTrimButton && widget.GetSelection())
		this.resizeButton.SetSelection(widget == this.shellTrimButton && widget.GetSelection())
	} else {
		var title bool = this.titleButton.GetSelection()
		var close bool = this.closeButton.GetSelection()
		var min bool = this.minButton.GetSelection()
		var max bool = this.maxButton.GetSelection()
		var border bool = this.borderButton.GetSelection()
		var resize bool = this.resizeButton.GetSelection()
		this.dialogTrimButton.SetSelection(title && close && border && !min && !max && !resize)
		this.shellTrimButton.SetSelection(title && close && min && max && resize && !border)
	}
}

func (this *ShellTab) getTabText_() string {
	return "Shell"
}

func (this *ShellTab) getMethodNames_() []string {
	return []string{"Alpha", "Bounds", "MinimumSize", "MaximumSize", "Modified", "Text"}
}

func (this *ShellTab) getExampleWidgets_() []*swt.Widget {
	var cond27 []*swt.Widget
	if this.shellCount == 0 {
		cond27 = make([]*swt.Widget, 0)
	} else {
		cond27 = upcastArrswtShellToswtWidget(this.shells)
	}
	return cond27
}

func upcastswtShellToswtWidget(x *swt.Shell) *swt.Widget {
	if x == nil {
		return nil
	}
	return &x.Widget
}

func upcastArrswtShellToswtWidget(x []*swt.Shell) []*swt.Widget {
	if x == nil {
		return nil
	}
	r := make([]*swt.Widget, len(x))
	for i, e := range x {
		r[i] = upcastswtShellToswtWidget(e)
	}
	return r
}
