// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/ole/win32/ICoreWebView2Settings.java @ af630a9093. DO NOT EDIT.
//go:build windows

package win32

type ICoreWebView2Settings struct {
	IUnknown
}

func NewICoreWebView2Settings(address int64) *ICoreWebView2Settings {
	this := &ICoreWebView2Settings{}
	this.initICoreWebView2Settings(address)
	return this
}

func (this *ICoreWebView2Settings) initICoreWebView2Settings(address int64) {
	this.IUnknown.initIUnknown(address)
}

func (this *ICoreWebView2Settings) Get_IsScriptEnabled(isScriptEnabled []int32) int32 {
	return COMVtblCallOverload7(3, this.address, isScriptEnabled)
}

func (this *ICoreWebView2Settings) Put_IsScriptEnabled(isScriptEnabled bool) int32 {
	var cond1 int32
	if isScriptEnabled {
		cond1 = 1
	} else {
		cond1 = 0
	}
	return COMVtblCallOverload1(4, this.address, cond1)
}

func (this *ICoreWebView2Settings) Get_IsWebMessageEnabled(isWebMessageEnabled []int32) int32 {
	return COMVtblCallOverload7(5, this.address, isWebMessageEnabled)
}

func (this *ICoreWebView2Settings) Put_IsWebMessageEnabled(isWebMessageEnabled bool) int32 {
	var cond2 int32
	if isWebMessageEnabled {
		cond2 = 1
	} else {
		cond2 = 0
	}
	return COMVtblCallOverload1(6, this.address, cond2)
}

func (this *ICoreWebView2Settings) Get_AreDefaultScriptDialogsEnabled(areDefaultScriptDialogsEnabled []int32) int32 {
	return COMVtblCallOverload7(7, this.address, areDefaultScriptDialogsEnabled)
}

func (this *ICoreWebView2Settings) Put_AreDefaultScriptDialogsEnabled(areDefaultScriptDialogsEnabled bool) int32 {
	var cond3 int32
	if areDefaultScriptDialogsEnabled {
		cond3 = 1
	} else {
		cond3 = 0
	}
	return COMVtblCallOverload1(8, this.address, cond3)
}

func (this *ICoreWebView2Settings) Get_IsStatusBarEnabled(isStatusBarEnabled []int32) int32 {
	return COMVtblCallOverload7(9, this.address, isStatusBarEnabled)
}

func (this *ICoreWebView2Settings) Put_IsStatusBarEnabled(isStatusBarEnabled bool) int32 {
	var cond4 int32
	if isStatusBarEnabled {
		cond4 = 1
	} else {
		cond4 = 0
	}
	return COMVtblCallOverload1(10, this.address, cond4)
}

func (this *ICoreWebView2Settings) Get_AreDevToolsEnabled(areDevToolsEnabled []int32) int32 {
	return COMVtblCallOverload7(11, this.address, areDevToolsEnabled)
}

func (this *ICoreWebView2Settings) Put_AreDevToolsEnabled(areDevToolsEnabled bool) int32 {
	var cond5 int32
	if areDevToolsEnabled {
		cond5 = 1
	} else {
		cond5 = 0
	}
	return COMVtblCallOverload1(12, this.address, cond5)
}

func (this *ICoreWebView2Settings) Get_AreDefaultContextMenusEnabled(enabled []int32) int32 {
	return COMVtblCallOverload7(13, this.address, enabled)
}

func (this *ICoreWebView2Settings) Put_AreDefaultContextMenusEnabled(enabled bool) int32 {
	var cond6 int32
	if enabled {
		cond6 = 1
	} else {
		cond6 = 0
	}
	return COMVtblCallOverload1(14, this.address, cond6)
}

func (this *ICoreWebView2Settings) Get_AreHostObjectsAllowed(allowed []int32) int32 {
	return COMVtblCallOverload7(15, this.address, allowed)
}

func (this *ICoreWebView2Settings) Put_AreHostObjectsAllowed(allowed bool) int32 {
	var cond7 int32
	if allowed {
		cond7 = 1
	} else {
		cond7 = 0
	}
	return COMVtblCallOverload1(16, this.address, cond7)
}

func (this *ICoreWebView2Settings) Get_IsZoomControlEnabled(enabled []int32) int32 {
	return COMVtblCallOverload7(17, this.address, enabled)
}

func (this *ICoreWebView2Settings) Put_IsZoomControlEnabled(enabled bool) int32 {
	var cond8 int32
	if enabled {
		cond8 = 1
	} else {
		cond8 = 0
	}
	return COMVtblCallOverload1(18, this.address, cond8)
}

func (this *ICoreWebView2Settings) Get_IsBuiltInErrorPageEnabled(enabled []int32) int32 {
	return COMVtblCallOverload7(19, this.address, enabled)
}

func (this *ICoreWebView2Settings) Put_IsBuiltInErrorPageEnabled(enabled bool) int32 {
	var cond9 int32
	if enabled {
		cond9 = 1
	} else {
		cond9 = 0
	}
	return COMVtblCallOverload1(20, this.address, cond9)
}
