// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/win32/WINDOWPLACEMENT.java @ af630a9093. DO NOT EDIT.
//go:build windows


package win32

import (
	"unsafe"
	"os"
	"fmt"
)

type WINDOWPLACEMENT struct {
	Length int32
	Flags int32
	ShowCmd int32
	PtMinPosition_x int32
	PtMinPosition_y int32
	PtMaxPosition_x int32
	PtMaxPosition_y int32
	Left int32
	Top int32
	Right int32
	Bottom int32
}

func (this *WINDOWPLACEMENT) toC(p unsafe.Pointer) {
	*(*int32)(unsafe.Add(p, 40)) = int32(this.Bottom)
	*(*int32)(unsafe.Add(p, 28)) = int32(this.Left)
	*(*int32)(unsafe.Add(p, 20)) = int32(this.PtMaxPosition_x)
	*(*int32)(unsafe.Add(p, 24)) = int32(this.PtMaxPosition_y)
	*(*int32)(unsafe.Add(p, 12)) = int32(this.PtMinPosition_x)
	*(*int32)(unsafe.Add(p, 16)) = int32(this.PtMinPosition_y)
	*(*int32)(unsafe.Add(p, 36)) = int32(this.Right)
	*(*int32)(unsafe.Add(p, 32)) = int32(this.Top)
}

func (this *WINDOWPLACEMENT) fromC(p unsafe.Pointer) {
	this.Bottom = int32(*(*int32)(unsafe.Add(p, 40)))
	this.Left = int32(*(*int32)(unsafe.Add(p, 28)))
	this.PtMaxPosition_x = int32(*(*int32)(unsafe.Add(p, 20)))
	this.PtMaxPosition_y = int32(*(*int32)(unsafe.Add(p, 24)))
	this.PtMinPosition_x = int32(*(*int32)(unsafe.Add(p, 12)))
	this.PtMinPosition_y = int32(*(*int32)(unsafe.Add(p, 16)))
	this.Right = int32(*(*int32)(unsafe.Add(p, 36)))
	this.Top = int32(*(*int32)(unsafe.Add(p, 32)))
}

var WINDOWPLACEMENTSizeof int32

func NewWINDOWPLACEMENT() *WINDOWPLACEMENT {
	this := &WINDOWPLACEMENT{}
	this.initWINDOWPLACEMENT()
	return this
}

func (this *WINDOWPLACEMENT) initWINDOWPLACEMENT() {
}

func init() {
	func() {
		defer func() {
			if r := recover(); r != nil {
				fmt.Fprintln(os.Stderr, "gowt/internal/win32: deferred init WINDOWPLACEMENTSizeof:", r)
			}
		}()
	WINDOWPLACEMENTSizeof = OSWINDOWPLACEMENT_sizeof()
	}()
}

