// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/win32/TCHAR.java @ af630a9093. DO NOT EDIT.
//go:build windows

package win32

import (
	"github.com/haiodo/gowt/internal/jrt"
	"unicode/utf16"
)

type TCHAR struct {
	Chars []uint16
}

const TCHARSizeof int32 = 2

func NewTCHAR(length int32) *TCHAR {
	this := &TCHAR{}
	this.initTCHAR(length)
	return this
}

func (this *TCHAR) initTCHAR(length int32) {
	this.Chars = make([]uint16, length)
}

func NewTCHARChTerminate(ch uint16, terminate bool) *TCHAR {
	this := &TCHAR{}
	this.initTCHARChTerminate(ch, terminate)
	return this
}

func (this *TCHAR) initTCHARChTerminate(ch uint16, terminate bool) {
	var cond1 []uint16
	if terminate {
		cond1 = []uint16{ch, '\u0000'}
	} else {
		cond1 = []uint16{ch}
	}
	this.initTCHARCharsTerminate(cond1, false)
}

func NewTCHARCharsTerminate(chars []uint16, terminate bool) *TCHAR {
	this := &TCHAR{}
	this.initTCHARCharsTerminate(chars, terminate)
	return this
}

func (this *TCHAR) initTCHARCharsTerminate(chars []uint16, terminate bool) {
	var charCount int32 = int32(len(chars))
	if terminate {
		if charCount == 0 || (charCount > 0 && int32(chars[charCount-1]) != 0) {
			var newChars []uint16 = make([]uint16, charCount+1)
			copy(newChars[0:], chars[0:0+charCount])
			chars = newChars
		}
	}
	this.Chars = chars
}

func NewTCHARStringTerminate(string_ string, terminate bool) *TCHAR {
	this := &TCHAR{}
	this.initTCHARStringTerminate(string_, terminate)
	return this
}

func (this *TCHAR) initTCHARStringTerminate(string_ string, terminate bool) {
	this.initTCHARCharsTerminate(TCHARGetChars(string_, terminate), false)
}

func (this *TCHAR) Clear() {
	jrt.Fill(this.Chars, uint16(0))
}

func (this *TCHAR) Length() int32 {
	return int32(len(this.Chars))
}

func (this *TCHAR) Strlen() int32 {
	for i := int32(0); i < int32(len(this.Chars)); i++ {
		if int32(this.Chars[i]) == int32('\u0000') {
			return i
		}
	}
	return int32(len(this.Chars))
}

func (this *TCHAR) TcharAt(index int32) int32 {
	return int32(this.Chars[index])
}

func (this *TCHAR) String() string {
	return this.StringStartLength(0, this.Length())
}

func (this *TCHAR) StringStartLength(start int32, length int32) string {
	return string(utf16.Decode(this.Chars[start : start+length]))
}

func TCHARGetChars(string_ string, terminate bool) []uint16 {
	var length int32 = jrt.StringLength(string_)
	var cond2 int32
	if terminate {
		cond2 = 1
	} else {
		cond2 = 0
	}
	var chars []uint16 = make([]uint16, length+(cond2))
	jrt.GetChars(string_, 0, length, chars, 0)
	return chars
}
