// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/win32/HIGHCONTRAST.java @ af630a9093. DO NOT EDIT.
//go:build windows

package win32

import (
	"fmt"
	"os"
	"unsafe"
)

type HIGHCONTRAST struct {
	CbSize            int32
	DwFlags           int32
	LpszDefaultScheme int64
}

func (this *HIGHCONTRAST) toC(p unsafe.Pointer) {
	*(*int32)(unsafe.Add(p, 0)) = int32(this.CbSize)
	*(*int32)(unsafe.Add(p, 4)) = int32(this.DwFlags)
	*(*int64)(unsafe.Add(p, 8)) = int64(this.LpszDefaultScheme)
}

func (this *HIGHCONTRAST) fromC(p unsafe.Pointer) {
	this.CbSize = int32(*(*int32)(unsafe.Add(p, 0)))
	this.DwFlags = int32(*(*int32)(unsafe.Add(p, 4)))
	this.LpszDefaultScheme = int64(*(*int64)(unsafe.Add(p, 8)))
}

var HIGHCONTRASTSizeof int32

func NewHIGHCONTRAST() *HIGHCONTRAST {
	this := &HIGHCONTRAST{}
	this.initHIGHCONTRAST()
	return this
}

func (this *HIGHCONTRAST) initHIGHCONTRAST() {
}

func init() {
	func() {
		defer func() {
			if r := recover(); r != nil {
				fmt.Fprintln(os.Stderr, "gowt: deferred init HIGHCONTRASTSizeof:", r)
			}
		}()
		HIGHCONTRASTSizeof = OSHIGHCONTRAST_sizeof()
	}()
}
