// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/ole/win32/EXCEPINFO.java @ af630a9093. DO NOT EDIT.
//go:build windows

package win32

import (
	"fmt"
	"os"
	"unsafe"
)

type EXCEPINFO struct {
	WCode             int16
	WReserved         int16
	BstrSource        int64
	BstrDescription   int64
	BstrHelpFile      int64
	DwHelpContext     int32
	PvReserved        int64
	PfnDeferredFillIn int64
	Scode             int32
}

func (this *EXCEPINFO) toC(p unsafe.Pointer) {
	*(*int64)(unsafe.Add(p, 16)) = int64(this.BstrDescription)
	*(*int64)(unsafe.Add(p, 24)) = int64(this.BstrHelpFile)
	*(*int64)(unsafe.Add(p, 8)) = int64(this.BstrSource)
	*(*int32)(unsafe.Add(p, 32)) = int32(this.DwHelpContext)
	*(*int64)(unsafe.Add(p, 48)) = int64(this.PfnDeferredFillIn)
	*(*int64)(unsafe.Add(p, 40)) = int64(this.PvReserved)
	*(*int32)(unsafe.Add(p, 56)) = int32(this.Scode)
}

func (this *EXCEPINFO) fromC(p unsafe.Pointer) {
	this.BstrDescription = int64(*(*int64)(unsafe.Add(p, 16)))
	this.BstrHelpFile = int64(*(*int64)(unsafe.Add(p, 24)))
	this.BstrSource = int64(*(*int64)(unsafe.Add(p, 8)))
	this.DwHelpContext = int32(*(*int32)(unsafe.Add(p, 32)))
	this.PfnDeferredFillIn = int64(*(*int64)(unsafe.Add(p, 48)))
	this.PvReserved = int64(*(*int64)(unsafe.Add(p, 40)))
	this.Scode = int32(*(*int32)(unsafe.Add(p, 56)))
}

var EXCEPINFOSizeof int32

func NewEXCEPINFO() *EXCEPINFO {
	this := &EXCEPINFO{}
	this.initEXCEPINFO()
	return this
}

func (this *EXCEPINFO) initEXCEPINFO() {
}

func init() {
	func() {
		defer func() {
			if r := recover(); r != nil {
				fmt.Fprintln(os.Stderr, "gowt/internal/win32: deferred init EXCEPINFOSizeof:", r)
			}
		}()
		EXCEPINFOSizeof = COMEXCEPINFO_sizeof()
	}()
}
