// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/win32/ICONINFO.java @ af630a9093. DO NOT EDIT.
//go:build windows

package win32

import (
	"fmt"
	"os"
	"unsafe"
)

type ICONINFO struct {
	FIcon    bool
	XHotspot int32
	YHotspot int32
	HbmMask  int64
	HbmColor int64
}

func (this *ICONINFO) toC(p unsafe.Pointer) {
	*(*int32)(unsafe.Add(p, 0)) = 0
	if this.FIcon {
		*(*int32)(unsafe.Add(p, 0)) = 1
	}
	*(*int64)(unsafe.Add(p, 24)) = int64(this.HbmColor)
	*(*int64)(unsafe.Add(p, 16)) = int64(this.HbmMask)
	*(*int32)(unsafe.Add(p, 4)) = int32(this.XHotspot)
	*(*int32)(unsafe.Add(p, 8)) = int32(this.YHotspot)
}

func (this *ICONINFO) fromC(p unsafe.Pointer) {
	this.FIcon = *(*int32)(unsafe.Add(p, 0)) != 0
	this.HbmColor = int64(*(*int64)(unsafe.Add(p, 24)))
	this.HbmMask = int64(*(*int64)(unsafe.Add(p, 16)))
	this.XHotspot = int32(*(*int32)(unsafe.Add(p, 4)))
	this.YHotspot = int32(*(*int32)(unsafe.Add(p, 8)))
}

var ICONINFOSizeof int32

func NewICONINFO() *ICONINFO {
	this := &ICONINFO{}
	this.initICONINFO()
	return this
}

func (this *ICONINFO) initICONINFO() {
}

func init() {
	func() {
		defer func() {
			if r := recover(); r != nil {
				fmt.Fprintln(os.Stderr, "gowt: deferred init ICONINFOSizeof:", r)
			}
		}()
		ICONINFOSizeof = OSICONINFO_sizeof()
	}()
}
