// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/win32/SCRIPT_CONTROL.java @ af630a9093. DO NOT EDIT.
//go:build windows

package win32

import (
	"fmt"
	"os"
)

type SCRIPT_CONTROL struct {
	UDefaultLanguage    int32
	FContextDigits      bool
	FInvertPreBoundDir  bool
	FInvertPostBoundDir bool
	FLinkStringBefore   bool
	FLinkStringAfter    bool
	FNeutralOverride    bool
	FNumericOverride    bool
	FLegacyBidiClass    bool
	FMergeNeutralItems  bool
	FUseStandardBidi    bool
	FReserved           int32
}

var SCRIPT_CONTROLSizeof int32

func NewSCRIPT_CONTROL() *SCRIPT_CONTROL {
	this := &SCRIPT_CONTROL{}
	this.initSCRIPT_CONTROL()
	return this
}

func (this *SCRIPT_CONTROL) initSCRIPT_CONTROL() {
}

func init() {
	func() {
		defer func() {
			if r := recover(); r != nil {
				fmt.Fprintln(os.Stderr, "gowt/internal/win32: deferred init SCRIPT_CONTROLSizeof:", r)
			}
		}()
		SCRIPT_CONTROLSizeof = OSSCRIPT_CONTROL_sizeof()
	}()
}
