// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/win32/MENUINFO.java @ af630a9093. DO NOT EDIT.
//go:build windows

package win32

import (
	"fmt"
	"os"
	"unsafe"
)

type MENUINFO struct {
	CbSize          int32
	FMask           int32
	DwStyle         int32
	CyMax           int32
	HbrBack         int64
	DwContextHelpID int32
	DwMenuData      int64
}

func (this *MENUINFO) toC(p unsafe.Pointer) {
	*(*int32)(unsafe.Add(p, 24)) = int32(this.DwContextHelpID)
	*(*int64)(unsafe.Add(p, 32)) = int64(this.DwMenuData)
	*(*int64)(unsafe.Add(p, 16)) = int64(this.HbrBack)
}

func (this *MENUINFO) fromC(p unsafe.Pointer) {
	this.DwContextHelpID = int32(*(*int32)(unsafe.Add(p, 24)))
	this.DwMenuData = int64(*(*int64)(unsafe.Add(p, 32)))
	this.HbrBack = int64(*(*int64)(unsafe.Add(p, 16)))
}

var MENUINFOSizeof int32

func NewMENUINFO() *MENUINFO {
	this := &MENUINFO{}
	this.initMENUINFO()
	return this
}

func (this *MENUINFO) initMENUINFO() {
}

func init() {
	func() {
		defer func() {
			if r := recover(); r != nil {
				fmt.Fprintln(os.Stderr, "gowt: deferred init MENUINFOSizeof:", r)
			}
		}()
		MENUINFOSizeof = OSMENUINFO_sizeof()
	}()
}
