// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/win32/LOGBRUSH.java @ af630a9093. DO NOT EDIT.
//go:build windows

package win32

import (
	"fmt"
	"os"
	"unsafe"
)

type LOGBRUSH struct {
	LbStyle int32
	LbColor int32
	LbHatch int64
}

func (this *LOGBRUSH) toC(p unsafe.Pointer) {
	*(*int32)(unsafe.Add(p, 4)) = int32(this.LbColor)
	*(*int64)(unsafe.Add(p, 8)) = int64(this.LbHatch)
	*(*int32)(unsafe.Add(p, 0)) = int32(this.LbStyle)
}

func (this *LOGBRUSH) fromC(p unsafe.Pointer) {
	this.LbColor = int32(*(*int32)(unsafe.Add(p, 4)))
	this.LbHatch = int64(*(*int64)(unsafe.Add(p, 8)))
	this.LbStyle = int32(*(*int32)(unsafe.Add(p, 0)))
}

var LOGBRUSHSizeof int32

func NewLOGBRUSH() *LOGBRUSH {
	this := &LOGBRUSH{}
	this.initLOGBRUSH()
	return this
}

func (this *LOGBRUSH) initLOGBRUSH() {
}

func init() {
	func() {
		defer func() {
			if r := recover(); r != nil {
				fmt.Fprintln(os.Stderr, "gowt/internal/win32: deferred init LOGBRUSHSizeof:", r)
			}
		}()
		LOGBRUSHSizeof = OSLOGBRUSH_sizeof()
	}()
}
