// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/win32/NMTOOLBAR.java @ af630a9093. DO NOT EDIT.
//go:build windows

package win32

import (
	"fmt"
	"os"
	"unsafe"
)

type NMTOOLBAR struct {
	NMHDR
	IItem     int32
	IBitmap   int32
	IdCommand int32
	FsState   int8
	FsStyle   int8
	DwData    int64
	IString   int64
	CchText   int32
	PszText   int64
	Left      int32
	Top       int32
	Right     int32
	Bottom    int32
}

func (this *NMTOOLBAR) toC(p unsafe.Pointer) {
	this.NMHDR.toC(p)
	*(*int32)(unsafe.Add(p, 92)) = int32(this.Bottom)
	*(*int32)(unsafe.Add(p, 64)) = int32(this.CchText)
	*(*int64)(unsafe.Add(p, 48)) = int64(this.DwData)
	*(*int8)(unsafe.Add(p, 40)) = int8(this.FsState)
	*(*int8)(unsafe.Add(p, 41)) = int8(this.FsStyle)
	*(*int32)(unsafe.Add(p, 32)) = int32(this.IBitmap)
	*(*int64)(unsafe.Add(p, 56)) = int64(this.IString)
	*(*int32)(unsafe.Add(p, 36)) = int32(this.IdCommand)
	*(*int32)(unsafe.Add(p, 80)) = int32(this.Left)
	*(*int64)(unsafe.Add(p, 72)) = int64(this.PszText)
	*(*int32)(unsafe.Add(p, 88)) = int32(this.Right)
	*(*int32)(unsafe.Add(p, 84)) = int32(this.Top)
}

func (this *NMTOOLBAR) fromC(p unsafe.Pointer) {
	this.NMHDR.fromC(p)
	this.Bottom = int32(*(*int32)(unsafe.Add(p, 92)))
	this.CchText = int32(*(*int32)(unsafe.Add(p, 64)))
	this.DwData = int64(*(*int64)(unsafe.Add(p, 48)))
	this.FsState = int8(*(*int8)(unsafe.Add(p, 40)))
	this.FsStyle = int8(*(*int8)(unsafe.Add(p, 41)))
	this.IBitmap = int32(*(*int32)(unsafe.Add(p, 32)))
	this.IString = int64(*(*int64)(unsafe.Add(p, 56)))
	this.IdCommand = int32(*(*int32)(unsafe.Add(p, 36)))
	this.Left = int32(*(*int32)(unsafe.Add(p, 80)))
	this.PszText = int64(*(*int64)(unsafe.Add(p, 72)))
	this.Right = int32(*(*int32)(unsafe.Add(p, 88)))
	this.Top = int32(*(*int32)(unsafe.Add(p, 84)))
}

var NMTOOLBARSizeof int32

func NewNMTOOLBAR() *NMTOOLBAR {
	this := &NMTOOLBAR{}
	this.initNMTOOLBAR()
	return this
}

func (this *NMTOOLBAR) initNMTOOLBAR() {
	this.NMHDR.initNMHDR()
}

func init() {
	func() {
		defer func() {
			if r := recover(); r != nil {
				fmt.Fprintln(os.Stderr, "gowt/internal/win32: deferred init NMTOOLBARSizeof:", r)
			}
		}()
		NMTOOLBARSizeof = OSNMTOOLBAR_sizeof()
	}()
}
