// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/win32/LOGFONT.java @ af630a9093. DO NOT EDIT.
//go:build windows

package win32

import (
	"fmt"
	"os"
	"unsafe"
)

type LOGFONT struct {
	LfHeight         int32
	LfWidth          int32
	LfEscapement     int32
	LfOrientation    int32
	LfWeight         int32
	LfItalic         int8
	LfUnderline      int8
	LfStrikeOut      int8
	LfCharSet        int8
	LfOutPrecision   int8
	LfClipPrecision  int8
	LfQuality        int8
	LfPitchAndFamily int8
	LfFaceName       []uint16
}

func (this *LOGFONT) toC(p unsafe.Pointer) {
	*(*int8)(unsafe.Add(p, 23)) = int8(this.LfCharSet)
	*(*int8)(unsafe.Add(p, 25)) = int8(this.LfClipPrecision)
	*(*int32)(unsafe.Add(p, 8)) = int32(this.LfEscapement)
	for i := 0; i < 32 && i < len(this.LfFaceName); i++ {
		*(*uint16)(unsafe.Add(unsafe.Add(p, 28), i*2)) = uint16(this.LfFaceName[i])
	}
	*(*int32)(unsafe.Add(p, 0)) = int32(this.LfHeight)
	*(*int8)(unsafe.Add(p, 20)) = int8(this.LfItalic)
	*(*int32)(unsafe.Add(p, 12)) = int32(this.LfOrientation)
	*(*int8)(unsafe.Add(p, 24)) = int8(this.LfOutPrecision)
	*(*int8)(unsafe.Add(p, 27)) = int8(this.LfPitchAndFamily)
	*(*int8)(unsafe.Add(p, 26)) = int8(this.LfQuality)
	*(*int8)(unsafe.Add(p, 22)) = int8(this.LfStrikeOut)
	*(*int8)(unsafe.Add(p, 21)) = int8(this.LfUnderline)
	*(*int32)(unsafe.Add(p, 16)) = int32(this.LfWeight)
	*(*int32)(unsafe.Add(p, 4)) = int32(this.LfWidth)
}

func (this *LOGFONT) fromC(p unsafe.Pointer) {
	this.LfCharSet = int8(*(*int8)(unsafe.Add(p, 23)))
	this.LfClipPrecision = int8(*(*int8)(unsafe.Add(p, 25)))
	this.LfEscapement = int32(*(*int32)(unsafe.Add(p, 8)))
	for i := 0; i < 32 && i < len(this.LfFaceName); i++ {
		this.LfFaceName[i] = uint16(*(*uint16)(unsafe.Add(unsafe.Add(p, 28), i*2)))
	}
	this.LfHeight = int32(*(*int32)(unsafe.Add(p, 0)))
	this.LfItalic = int8(*(*int8)(unsafe.Add(p, 20)))
	this.LfOrientation = int32(*(*int32)(unsafe.Add(p, 12)))
	this.LfOutPrecision = int8(*(*int8)(unsafe.Add(p, 24)))
	this.LfPitchAndFamily = int8(*(*int8)(unsafe.Add(p, 27)))
	this.LfQuality = int8(*(*int8)(unsafe.Add(p, 26)))
	this.LfStrikeOut = int8(*(*int8)(unsafe.Add(p, 22)))
	this.LfUnderline = int8(*(*int8)(unsafe.Add(p, 21)))
	this.LfWeight = int32(*(*int32)(unsafe.Add(p, 16)))
	this.LfWidth = int32(*(*int32)(unsafe.Add(p, 4)))
}

var LOGFONTSizeof int32

func NewLOGFONT() *LOGFONT {
	this := &LOGFONT{}
	this.initLOGFONT()
	return this
}

func (this *LOGFONT) initLOGFONT() {
	this.LfFaceName = make([]uint16, OSLF_FACESIZE)
}

func init() {
	func() {
		defer func() {
			if r := recover(); r != nil {
				fmt.Fprintln(os.Stderr, "gowt/internal/win32: deferred init LOGFONTSizeof:", r)
			}
		}()
		LOGFONTSizeof = OSLOGFONT_sizeof()
	}()
}
