// Code generated by j2go from ../eclipse.platform.ui/bundles/org.eclipse.jface/src/org/eclipse/jface/layout/TreeColumnLayout.java @ af630a9093. DO NOT EDIT.

package jface

import (
	"github.com/haiodo/gowt/internal/jrt"
	"github.com/haiodo/gowt/swt"
)

type TreeColumnLayout struct {
	AbstractColumnLayout
	addListener bool
}

var TreeColumnLayoutListener *TreeColumnLayout_TreeLayoutListener = newTreeColumnLayoutTreeLayoutListener()

func NewTreeColumnLayout() *TreeColumnLayout {
	this := &TreeColumnLayout{}
	this.impl = this
	this.initTreeColumnLayout()
	return this
}

func (this *TreeColumnLayout) initTreeColumnLayout() {
	this.AbstractColumnLayout.initAbstractColumnLayout()
	this.addListener = true
}

func NewTreeColumnLayoutAdjustForScrollBar(adjustForScrollBar bool) *TreeColumnLayout {
	this := &TreeColumnLayout{}
	this.impl = this
	this.initTreeColumnLayoutAdjustForScrollBar(adjustForScrollBar)
	return this
}

func (this *TreeColumnLayout) initTreeColumnLayoutAdjustForScrollBar(adjustForScrollBar bool) {
	this.AbstractColumnLayout.initAbstractColumnLayoutAdjustForScrollBar(adjustForScrollBar)
	this.addListener = true
}

func (this *TreeColumnLayout) layoutFn_(composite *swt.Composite, flushCache bool) {
	this.AbstractColumnLayout.layoutFn_(composite, flushCache)
	if this.addListener {
		this.addListener = false
		(castswtScrollableToswtTree(this.GetControl(composite))).AddTreeListener(TreeColumnLayoutListener)
	}
}

func (this *TreeColumnLayout) getColumnCount_(tree *swt.Scrollable) int32 {
	return (castswtScrollableToswtTree(tree)).GetColumnCount()
}

func (this *TreeColumnLayout) setColumnWidths_(tree *swt.Scrollable, widths []int32) {
	var columns []*swt.TreeColumn = (castswtScrollableToswtTree(tree)).GetColumns()
	for i := int32(0); i < int32(len(widths)); i++ {
		columns[i].SetWidth(widths[i])
	}
}

func (this *TreeColumnLayout) getLayoutData_(tableTree *swt.Scrollable, columnIndex int32) *ColumnLayoutData {
	var column *swt.TreeColumn = (castswtScrollableToswtTree(tableTree)).GetColumnIndex(columnIndex)
	return castanyToColumnLayoutData(column.GetDataKey(AbstractColumnLayoutLAYOUT_DATA))
}

func (this *TreeColumnLayout) updateColumnData_(column *swt.Widget) {
	var tColumn *swt.TreeColumn = castswtWidgetToswtTreeColumn(column)
	var t *swt.Tree = tColumn.GetParent()
	if !AbstractColumnLayoutIS_GTK || t.GetColumnIndex(t.GetColumnCount()-1) != tColumn {
		tColumn.SetDataKeyValue(AbstractColumnLayoutLAYOUT_DATA, NewColumnPixelData(tColumn.GetWidth()))
		this.impl.layoutFn_(t.GetParent(), true)
	}
}

type TreeColumnLayout_TreeLayoutListener struct {
}

func newTreeColumnLayoutTreeLayoutListener() *TreeColumnLayout_TreeLayoutListener {
	this := &TreeColumnLayout_TreeLayoutListener{}
	this.initTreeColumnLayoutTreeLayoutListener()
	return this
}

func (this *TreeColumnLayout_TreeLayoutListener) initTreeColumnLayoutTreeLayoutListener() {
}

func (this *TreeColumnLayout_TreeLayoutListener) TreeCollapsed(e *swt.TreeEvent) {
	this.Update(castswtWidgetToswtTree(e.Widget))
}

func (this *TreeColumnLayout_TreeLayoutListener) TreeExpanded(e *swt.TreeEvent) {
	this.Update(castswtWidgetToswtTree(e.Widget))
}

func (this *TreeColumnLayout_TreeLayoutListener) Update(treeLike swt.TreeLike) {
	var tree *swt.Tree
	if treeLike != nil {
		tree = treeLike.AsTree()
	}
	_ = tree
	tree.GetDisplay().AsyncExec(jrt.NewRunnable(func() {
		if !tree.IsDisposed() {
			tree.Update()
			tree.GetParent().Layout()
		}
	}))
}

// j2go: instanceof helper for swt.Tree and its subclasses within the translated set.
func widgetImplAsTree(x any) (*swt.Tree, bool) {
	switch v := x.(type) {
	case *swt.Tree:
		if v == nil {
			return nil, false
		}
		return v, true
	}
	return nil, false
}

func castswtScrollableToswtTree(x *swt.Scrollable) *swt.Tree {
	if x == nil {
		return nil
	}
	v, ok := widgetImplAsTree(x.Impl())
	if !ok {
		panic("java.lang.ClassCastException: swt.Tree")
	}
	return v
}

// j2go: instanceof helper for swt.TreeColumn and its subclasses within the translated set.
func widgetImplAsTreeColumn(x any) (*swt.TreeColumn, bool) {
	switch v := x.(type) {
	case *swt.TreeColumn:
		if v == nil {
			return nil, false
		}
		return v, true
	}
	return nil, false
}

func castswtWidgetToswtTreeColumn(x *swt.Widget) *swt.TreeColumn {
	if x == nil {
		return nil
	}
	v, ok := widgetImplAsTreeColumn(x.Impl())
	if !ok {
		panic("java.lang.ClassCastException: swt.TreeColumn")
	}
	return v
}

func castswtWidgetToswtTree(x *swt.Widget) *swt.Tree {
	if x == nil {
		return nil
	}
	v, ok := widgetImplAsTree(x.Impl())
	if !ok {
		panic("java.lang.ClassCastException: swt.Tree")
	}
	return v
}
