// Code generated by j2go from ../eclipse.platform.ui/bundles/org.eclipse.jface/src/org/eclipse/jface/layout/GridLayoutFactory.java @ 618d26a101. DO NOT EDIT.

package jface

import (
	"github.com/haiodo/gowt/internal/jrt"
	"github.com/haiodo/gowt/swt"
)

type GridLayoutFactory struct {
	l *swt.GridLayout
}

func (this *GridLayoutFactory) AsGridLayoutFactory() *GridLayoutFactory { return this }

type GridLayoutFactoryLike interface {
	AsGridLayoutFactory() *GridLayoutFactory
}

func newGridLayoutFactory(l *swt.GridLayout) *GridLayoutFactory {
	this := &GridLayoutFactory{}
	this.initGridLayoutFactory(l)
	return this
}

func (this *GridLayoutFactory) initGridLayoutFactory(l *swt.GridLayout) {
	this.l = l
}

func (this *GridLayoutFactory) Copy() *GridLayoutFactory {
	return newGridLayoutFactory(this.Create())
}

func (this *GridLayoutFactory) EqualWidth(equal bool) *GridLayoutFactory {
	this.l.MakeColumnsEqualWidth = equal
	return this
}

func (this *GridLayoutFactory) Spacing(hSpacing int32, vSpacing int32) *GridLayoutFactory {
	this.l.HorizontalSpacing = hSpacing
	this.l.VerticalSpacing = vSpacing
	return this
}

func (this *GridLayoutFactory) SpacingSpacing(spacingLike swt.PointLike) *GridLayoutFactory {
	var spacing *swt.Point
	if spacingLike != nil {
		spacing = spacingLike.AsPoint()
	}
	_ = spacing
	this.l.HorizontalSpacing = spacing.X
	this.l.VerticalSpacing = spacing.Y
	return this
}

func (this *GridLayoutFactory) Margins(marginsLike swt.PointLike) *GridLayoutFactory {
	var margins *swt.Point
	if marginsLike != nil {
		margins = marginsLike.AsPoint()
	}
	_ = margins
	this.l.MarginWidth = margins.X
	this.l.MarginHeight = margins.Y
	return this
}

func (this *GridLayoutFactory) MarginsWidthHeight(width int32, height int32) *GridLayoutFactory {
	this.l.MarginWidth = width
	this.l.MarginHeight = height
	return this
}

func (this *GridLayoutFactory) ExtendedMargins(left int32, right int32, top int32, bottom int32) *GridLayoutFactory {
	this.l.MarginLeft = left
	this.l.MarginRight = right
	this.l.MarginTop = top
	this.l.MarginBottom = bottom
	return this
}

func (this *GridLayoutFactory) ExtendedMarginsDifferenceRect(differenceRectLike swt.RectangleLike) *GridLayoutFactory {
	var differenceRect *swt.Rectangle
	if differenceRectLike != nil {
		differenceRect = differenceRectLike.AsRectangle()
	}
	_ = differenceRect
	this.l.MarginLeft = -differenceRect.X
	this.l.MarginTop = -differenceRect.Y
	this.l.MarginBottom = differenceRect.Y + differenceRect.Height
	this.l.MarginRight = differenceRect.X + differenceRect.Width
	return this
}

func (this *GridLayoutFactory) NumColumns(numColumns int32) *GridLayoutFactory {
	this.l.NumColumns = numColumns
	return this
}

func (this *GridLayoutFactory) Create() *swt.GridLayout {
	return GridLayoutFactoryCopyLayout(this.l)
}

func (this *GridLayoutFactory) ApplyTo(cLike swt.CompositeLike) {
	var c *swt.Composite
	if cLike != nil {
		c = cLike.AsComposite()
	}
	_ = c
	c.SetLayout(upcastswtGridLayoutToswtLayout(GridLayoutFactoryCopyLayout(this.l)))
}

func (this *GridLayoutFactory) GenerateLayout(cLike swt.CompositeLike) {
	var c *swt.Composite
	if cLike != nil {
		c = cLike.AsComposite()
	}
	_ = c
	this.ApplyTo(c)
	LayoutGeneratorGenerateLayout(c)
}

func (this *GridLayoutFactory) String() string {
	var builder *jrt.StringBuilder = jrt.NewStringBuilder()
	builder.Append("GridLayoutFactory.fillDefaults()\n")
	if this.l.NumColumns > 1 {
		builder.Append("    .numColumns(")
		builder.Append(this.l.NumColumns)
		builder.Append(")\n")
	}
	if this.l.MakeColumnsEqualWidth {
		builder.Append("    .equalWidth(true)\n")
	}
	if this.l.MarginBottom != 0 || this.l.MarginTop != 0 || this.l.MarginLeft != 0 || this.l.MarginRight != 0 {
		builder.Append("    .extendedMargins(")
		builder.Append(this.l.MarginLeft)
		builder.Append(", ")
		builder.Append(this.l.MarginRight)
		builder.Append(", ")
		builder.Append(this.l.MarginTop)
		builder.Append(", ")
		builder.Append(this.l.MarginBottom)
		builder.Append(")\n")
	}
	if this.l.MarginWidth != 0 || this.l.MarginHeight != 0 {
		builder.Append("    .margins(")
		builder.Append(this.l.MarginWidth)
		builder.Append(", ")
		builder.Append(this.l.MarginHeight)
		builder.Append(")\n")
	}
	var defaultSpacing *swt.Point = LayoutConstantsGetSpacing()
	if defaultSpacing.X != this.l.HorizontalSpacing || defaultSpacing.Y != this.l.VerticalSpacing {
		builder.Append("    .spacing(")
		builder.Append(this.l.HorizontalSpacing)
		builder.Append(", ")
		builder.Append(this.l.VerticalSpacing)
		builder.Append(")\n")
	}
	return builder.ToString()
}

func GridLayoutFactoryCreateFrom(lLike swt.GridLayoutLike) *GridLayoutFactory {
	var l *swt.GridLayout
	if lLike != nil {
		l = lLike.AsGridLayout()
	}
	_ = l
	return newGridLayoutFactory(GridLayoutFactoryCopyLayout(l))
}

func GridLayoutFactorySwtDefaults() *GridLayoutFactory {
	return newGridLayoutFactory(swt.NewGridLayout())
}

func GridLayoutFactoryFillDefaults() *GridLayoutFactory {
	var layout *swt.GridLayout = swt.NewGridLayout()
	layout.MarginWidth = 0
	layout.MarginHeight = 0
	var defaultSpacing *swt.Point = LayoutConstantsGetSpacing()
	layout.HorizontalSpacing = defaultSpacing.X
	layout.VerticalSpacing = defaultSpacing.Y
	return newGridLayoutFactory(layout)
}

func GridLayoutFactoryCopyLayout(lLike swt.GridLayoutLike) *swt.GridLayout {
	var l *swt.GridLayout
	if lLike != nil {
		l = lLike.AsGridLayout()
	}
	_ = l
	var result *swt.GridLayout = swt.NewGridLayoutNumColumnsMakeColumnsEqualWidth(l.NumColumns, l.MakeColumnsEqualWidth)
	result.HorizontalSpacing = l.HorizontalSpacing
	result.MarginBottom = l.MarginBottom
	result.MarginHeight = l.MarginHeight
	result.MarginLeft = l.MarginLeft
	result.MarginRight = l.MarginRight
	result.MarginTop = l.MarginTop
	result.MarginWidth = l.MarginWidth
	result.VerticalSpacing = l.VerticalSpacing
	return result
}

func upcastswtGridLayoutToswtLayout(x *swt.GridLayout) *swt.Layout {
	if x == nil {
		return nil
	}
	return &x.Layout
}
