// Code generated by j2go from ../eclipse.platform.ui/bundles/org.eclipse.jface/src/org/eclipse/jface/widgets/Property.java @ 618d26a101. DO NOT EDIT.

package jface

import (
	"github.com/haiodo/gowt/swt"
)

type Property interface {
	Apply(widget *swt.Widget)
}
