// Code generated by j2go from ../eclipse.platform.ui/bundles/org.eclipse.jface/src/org/eclipse/jface/widgets/LinkFactory.java @ 618d26a101. DO NOT EDIT.

package jface

import (
	"github.com/haiodo/gowt/swt"
	"reflect"
)

type LinkFactory struct {
	AbstractControlFactory
}

func (this *LinkFactory) AsLinkFactory() *LinkFactory { return this }

type LinkFactoryLike interface {
	AsLinkFactory() *LinkFactory
}

func newLinkFactory(style int32) *LinkFactory {
	this := &LinkFactory{}
	this.impl = this
	this.initLinkFactory(style)
	return this
}

func (this *LinkFactory) initLinkFactory(style int32) {
	this.AbstractControlFactory.initAbstractControlFactory(reflect.TypeFor[*LinkFactory](), &WidgetSupplierFunc{fn: func(a0 *swt.Widget) *swt.Widget {
		return upcastswtLinkToswtWidget((func(parent *swt.Composite) *swt.Link {
			return swt.NewLink(parent, style)
		})(castswtWidgetToswtComposite(a0)))
	}})
}

func (this *LinkFactory) Text(text string) *LinkFactory {
	this.AddProperty(&PropertyFunc{fn: func(a0 *swt.Widget) {
		(func(l *swt.Link) {
			l.SetText(text)
		})(castswtWidgetToswtLink(a0))
	}})
	return this
}

func (this *LinkFactory) OnSelect(consumer func(*swt.SelectionEvent)) *LinkFactory {
	this.AddProperty(&PropertyFunc{fn: func(a0 *swt.Widget) {
		(func(c *swt.Link) {
			c.AddSelectionListener(swt.SelectionListenerWidgetSelectedAdapter(consumer))
		})(castswtWidgetToswtLink(a0))
	}})
	return this
}

func LinkFactoryNewLink(style int32) *LinkFactory {
	return newLinkFactory(style)
}

func (this *LinkFactory) Background(a0Like swt.ColorLike) *LinkFactory {
	var a0 *swt.Color
	if a0Like != nil {
		a0 = a0Like.AsColor()
	}
	_ = a0
	return castAbstractControlFactoryToLinkFactory(this.AbstractControlFactory.Background(a0))
}

func (this *LinkFactory) Enabled(a0 bool) *LinkFactory {
	return castAbstractControlFactoryToLinkFactory(this.AbstractControlFactory.Enabled(a0))
}

func (this *LinkFactory) Font(a0Like swt.FontLike) *LinkFactory {
	var a0 *swt.Font
	if a0Like != nil {
		a0 = a0Like.AsFont()
	}
	_ = a0
	return castAbstractControlFactoryToLinkFactory(this.AbstractControlFactory.Font(a0))
}

func (this *LinkFactory) Foreground(a0Like swt.ColorLike) *LinkFactory {
	var a0 *swt.Color
	if a0Like != nil {
		a0 = a0Like.AsColor()
	}
	_ = a0
	return castAbstractControlFactoryToLinkFactory(this.AbstractControlFactory.Foreground(a0))
}

func (this *LinkFactory) LayoutData(a0 any) *LinkFactory {
	return castAbstractControlFactoryToLinkFactory(this.AbstractControlFactory.LayoutData(a0))
}

func (this *LinkFactory) Orientation(a0 int32) *LinkFactory {
	return castAbstractControlFactoryToLinkFactory(this.AbstractControlFactory.Orientation(a0))
}

func (this *LinkFactory) SupplyLayoutData(a0 func() any) *LinkFactory {
	return castAbstractControlFactoryToLinkFactory(this.AbstractControlFactory.SupplyLayoutData(a0))
}

func (this *LinkFactory) Tooltip(a0 string) *LinkFactory {
	return castAbstractControlFactoryToLinkFactory(this.AbstractControlFactory.Tooltip(a0))
}

func (this *LinkFactory) Create(a0Like swt.CompositeLike) *swt.Link {
	var a0 *swt.Composite
	if a0Like != nil {
		a0 = a0Like.AsComposite()
	}
	_ = a0
	return castswtWidgetToswtLink(this.AbstractControlFactory.Create(a0))
}

func (this *LinkFactory) Data(a0 any) *LinkFactory {
	return castAbstractWidgetFactoryToLinkFactory(this.AbstractControlFactory.Data(a0))
}

func (this *LinkFactory) DataKeyValue(a0 string, a1 any) *LinkFactory {
	return castAbstractWidgetFactoryToLinkFactory(this.AbstractControlFactory.DataKeyValue(a0, a1))
}

func upcastswtLinkToswtWidget(x *swt.Link) *swt.Widget {
	if x == nil {
		return nil
	}
	return &x.Widget
}

func castswtWidgetToswtLink(x *swt.Widget) *swt.Link {
	if x == nil {
		return nil
	}
	v, ok := widgetImplAsLink(x.Impl())
	if !ok {
		panic("java.lang.ClassCastException: swt.Link")
	}
	return v
}

// j2go: instanceof helper for LinkFactory and its subclasses within the translated set.
func abstractWidgetFactoryImplAsLinkFactory(x any) (*LinkFactory, bool) {
	if h, ok := x.(*abstractWidgetFactoryHooked); ok {
		x = h.hook
	}
	switch v := x.(type) {
	case *LinkFactory:
		if v == nil {
			return nil, false
		}
		return v, true
	}
	if l, ok := x.(interface{ AsLinkFactory() *LinkFactory }); ok {
		return l.AsLinkFactory(), true
	}
	return nil, false
}

func castAbstractControlFactoryToLinkFactory(x *AbstractControlFactory) *LinkFactory {
	if x == nil {
		return nil
	}
	v, ok := abstractWidgetFactoryImplAsLinkFactory(x.impl)
	if !ok {
		panic("java.lang.ClassCastException: LinkFactory")
	}
	return v
}

func castAbstractWidgetFactoryToLinkFactory(x *AbstractWidgetFactory) *LinkFactory {
	if x == nil {
		return nil
	}
	v, ok := abstractWidgetFactoryImplAsLinkFactory(x.impl)
	if !ok {
		panic("java.lang.ClassCastException: LinkFactory")
	}
	return v
}
