package dev.gowt.j2go;

import org.eclipse.jdt.core.dom.IMethodBinding;
import org.eclipse.jdt.core.dom.ITypeBinding;
import org.eclipse.jdt.core.dom.Modifier;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;

/** Naming: capitalization, overload suffixes, names.properties overrides (see AGENTS contract). */
public class Names {

	// binaryName#method(erasures) -> overrideName, loaded from names.properties.
	private final Map<String, String> overrides = new HashMap<>();

	// (declaringTypeKey#methodName) -> ordered method keys, in declaration source order.
	private final Map<String, List<String>> overloadOrder = new HashMap<>();

	// method key -> its declared Java parameter names, for the overload-suffix rule.
	private final Map<String, List<String>> paramNamesByKey = new HashMap<>();

	/** Registers a computed (not user-configured) override - see TypeModel's cross-family
	 * instance-method collision pass. */
	void addOverride(String erasureKey, String goName) {
		overrides.put(erasureKey, goName);
	}

	void dumpOverloads(Path file) throws IOException {
		// One file over the several j2go runs of a port: merge into what earlier runs wrote.
		Map<String, String> all = new TreeMap<>();
		if (Files.exists(file)) {
			Properties p = new Properties();
			try (var in = Files.newInputStream(file)) {
				p.load(in);
			}
			for (String k : p.stringPropertyNames()) all.put(k, p.getProperty(k));
		}
		all.putAll(computedOverloads);
		StringBuilder b = new StringBuilder("# Generated by j2go (J2GO_DUMP_OVERLOADS): the reference platform's names for overloaded members.\n");
		all.forEach((k, v) -> b.append(k.replace(" ", "\\ ")).append('=').append(v).append('\n'));
		Files.writeString(file, b.toString());
	}

	void loadOverrides(Path propsFile) throws IOException {
		if (!Files.exists(propsFile)) return;
		Properties p = new Properties();
		try (var in = Files.newInputStream(propsFile)) {
			p.load(in);
		}
		for (String key : p.stringPropertyNames()) {
			overrides.put(key, p.getProperty(key));
		}
	}

	public static String capitalize(String s) {
		if (s.isEmpty()) return s;
		return Character.toUpperCase(s.charAt(0)) + s.substring(1);
	}

	/** Go base name for a Java method: toString -> String, else Capitalize(name). Shared by a
	 * plain call/declaration and the override cascade, so both land on the same Go name. */
	public static String javaMethodBaseGoName(String javaMethodName) {
		return switch (javaMethodName) {
			case "equals" -> "Equals";
			case "hashCode" -> "HashCode";
			case "toString" -> "String";
			// '$' is legal in a Java identifier, not in Go (JUnit names: test_Constructor...Device$L...).
			default -> capitalize(javaMethodName.replace('$', '_'));
		};
	}

	public static String decapitalize(String s) {
		if (s.isEmpty()) return s;
		return Character.toLowerCase(s.charAt(0)) + s.substring(1);
	}

	/** Outer.Inner Go TYPE name: underscore joined, per contract. */
	static String goTypeName(ITypeBinding t) {
		ITypeBinding decl = t;
		LinkedList<String> parts = new LinkedList<>();
		while (decl != null) {
			parts.addFirst(decl.getName());
			decl = decl.getDeclaringClass();
		}
		return exportedPi(String.join("_", parts));
	}

	/** Outer.Inner Go function-name prefix: concatenated, no underscore (New<Class>, package statics). */
	static String goFuncPrefix(ITypeBinding t) {
		ITypeBinding decl = t;
		LinkedList<String> parts = new LinkedList<>();
		while (decl != null) {
			parts.addFirst(decl.getName());
			decl = decl.getDeclaringClass();
		}
		return exportedPi(String.join("", parts));
	}

	// gtk's C struct mirrors are named like the C type (cairo_path_t) and must still be exported across packages.
	private static String exportedPi(String name) {
		return GoTypes.platform == Platform.GTK ? capitalize(name) : name;
	}

	public static String erasureKey(IMethodBinding m) {
		IMethodBinding decl = m.getMethodDeclaration();
		StringBuilder sb = new StringBuilder();
		sb.append(decl.getDeclaringClass().getErasure().getBinaryName()).append('#');
		sb.append(decl.isConstructor() ? "<init>" : decl.getName()).append('(');
		ITypeBinding[] params = decl.getParameterTypes();
		for (int i = 0; i < params.length; i++) {
			if (i > 0) sb.append(',');
			sb.append(params[i].getErasure().getBinaryName());
		}
		sb.append(')');
		return sb.toString();
	}

	/** Registers a declaration (method or constructor) in source order, with its Java parameter names. */
	void registerDeclaration(IMethodBinding m, List<String> paramNames) {
		String declKey = m.getDeclaringClass().getErasure().getBinaryName();
		String name = m.isConstructor() ? "<init>" : m.getName();
		String key = erasureKey(m);
		overloadOrder.computeIfAbsent(declKey + "#" + name, k -> new ArrayList<>()).add(key);
		paramNamesByKey.put(key, paramNames);
		if (java.lang.reflect.Modifier.isPublic(m.getModifiers())) publicKeys.add(key);
		if (!m.isConstructor()) declsByName.computeIfAbsent(m.getName(), k -> new ArrayList<>()).add(m);
	}

	/**
	 * Go name for a resolved method/constructor use: base name for the first-declared overload,
	 * base+CapitalizedParamNames for the others, unless overridden via names.properties.
	 */
	public String goMemberName(IMethodBinding m, String baseName) {
		String key = erasureKey(m);
		String override = overrides.get(key);
		if (override != null) return override;
		String pinned = pinnedSuffix.get(key);
		if (pinned != null) return baseName + pinned;
		// An implementation or override keeps the name pinned on what it implements.
		String inherited = inheritedPin(m.getMethodDeclaration());
		if (inherited != null) return inherited;
		String name = computeMemberName(m, baseName);
		if (shadowsAncestorOverload(m.getMethodDeclaration())) name += shadowSuffix(m.getMethodDeclaration());
		// An unpinned member (a platform's own) must not take a name the pins gave to another member of its class.
		// (Statics are functions named by class: they cannot clash with a method.)
		String declClass = m.getMethodDeclaration().getDeclaringClass().getErasure().getBinaryName();
		if (m.isConstructor() && name.startsWith(baseName)) {
			// Constructors: the pins' suffixes of this class (the base differs per Go function: New<C>, new<C>, init<C>).
			Set<String> suffixes = pinnedNamesOf(declClass + "#<init>");
			String suffix = name.substring(baseName.length());
			for (int n = 1; suffixes.contains(suffix); n++) suffix = "Local" + n;
			name = baseName + suffix;
		}
		Set<String> taken = Modifier.isStatic(m.getModifiers()) || m.isConstructor() ? Set.of() : pinnedNamesOf(declClass);
		for (int n = 1; taken.contains(name); n++) name = baseName + "Local" + n;
		if (overloaded(m) && name.startsWith(baseName)) computedOverloads.put(key, name.substring(baseName.length()));
		return name;
	}

	// Go has no overloading: a subclass's method named like an ancestor's overload (other parameters) would hide it.
	private boolean shadowsAncestorOverload(IMethodBinding decl) {
		// Public API names stay as the overload rule gave them (one API for every platform); the reference
		// platform's own names are what the pins freeze, so only the other platforms need this.
		if (GoTypes.platform == Platform.COCOA || decl.isConstructor() || Modifier.isStatic(decl.getModifiers()) || Modifier.isPublic(decl.getModifiers())
				|| decl.getDeclaringClass().getQualifiedName().contains(".internal.")) return false;
		for (ITypeBinding t = decl.getDeclaringClass().getSuperclass(); t != null && t.getQualifiedName().startsWith("org.eclipse.swt"); t = t.getSuperclass()) {
			for (IMethodBinding o : t.getDeclaredMethods()) {
				if (!o.isConstructor() && !Modifier.isStatic(o.getModifiers()) && o.getName().equals(decl.getName())
						&& !Arrays.equals(erasedParams(o), erasedParams(decl))) return true;
			}
		}
		// ... or a descendant's overload that hides this one.
		for (IMethodBinding o : declsByName.getOrDefault(decl.getName(), List.of())) {
			ITypeBinding oc = o.getDeclaringClass();
			if (!Modifier.isStatic(o.getModifiers()) && !oc.isEqualTo(decl.getDeclaringClass()) && oc.getErasure().isSubTypeCompatible(decl.getDeclaringClass().getErasure())
					&& !Arrays.equals(erasedParams(o), erasedParams(decl))) return true;
		}
		return false;
	}

	private static String[] erasedParams(IMethodBinding m) {
		return Arrays.stream(m.getParameterTypes()).map(p -> p.getErasure().getQualifiedName()).toArray(String[]::new);
	}

	private String shadowSuffix(IMethodBinding decl) {
		List<String> params = paramNamesByKey.getOrDefault(erasureKey(decl), List.of());
		StringBuilder sb = new StringBuilder();
		for (String p : params) sb.append(capitalize(p));
		return sb.length() == 0 ? "NoArgs" : sb.toString();
	}

	// Every registered method by Java name: an ancestor's overload hidden by a descendant's is found through it.
	private final Map<String, List<IMethodBinding>> declsByName = new HashMap<>();

	private String inheritedPin(IMethodBinding decl) {
		if (decl.isConstructor() || Modifier.isStatic(decl.getModifiers())) return null;
		List<ITypeBinding> todo = new ArrayList<>();
		for (ITypeBinding t = decl.getDeclaringClass(); t != null; t = t.getSuperclass()) {
			todo.add(t);
			todo.addAll(List.of(t.getInterfaces()));
		}
		for (int i = 0; i < todo.size(); i++) {
			ITypeBinding t = todo.get(i);
			for (ITypeBinding x : t.getInterfaces()) if (!todo.contains(x)) todo.add(x);
			if (t.getErasure().isEqualTo(decl.getDeclaringClass().getErasure())) continue;
			for (IMethodBinding o : t.getDeclaredMethods()) {
				if (!decl.overrides(o)) continue;
				String ov = overrides.get(erasureKey(o));
				if (ov != null) return ov;
			}
		}
		return null;
	}

	private final Set<String> publicKeys = new HashSet<>();

	private final Map<String, Set<String>> pinnedNamesByClass = new HashMap<>();

	private Set<String> pinnedNamesOf(String classBinaryName) {
		if (pinnedNamesByClass.isEmpty() && !pinnedSuffix.isEmpty()) {
			for (var e : pinnedSuffix.entrySet()) {
				int hash = e.getKey().indexOf('#');
				int paren = e.getKey().indexOf('(');
				String method = e.getKey().substring(hash + 1, paren);
				// Constructors are filed under "<class>#<init>" with the bare suffix.
				if (method.equals("<init>")) pinnedNamesByClass.computeIfAbsent(e.getKey().substring(0, hash) + "#<init>", k -> new HashSet<>()).add(e.getValue());
				else pinnedNamesByClass.computeIfAbsent(e.getKey().substring(0, hash), k -> new HashSet<>()).add(javaMethodBaseGoName(method) + e.getValue());
			}
		}
		return pinnedNamesByClass.getOrDefault(classBinaryName, Set.of());
	}

	private boolean overloaded(IMethodBinding m) {
		IMethodBinding decl = m.getMethodDeclaration();
		String declName = decl.isConstructor() ? "<init>" : decl.getName();
		return overloadOrder.getOrDefault(decl.getDeclaringClass().getErasure().getBinaryName() + "#" + declName, List.of()).size() > 1;
	}

	// Overloaded members' chosen names; Main writes them to overloads.properties, which every platform
	// run loads again so the public API names do not depend on a platform source's declaration order.
	final Map<String, String> computedOverloads = new TreeMap<>();
	private final Map<String, String> pinnedSuffix = new HashMap<>();

	/** overloads.properties: key -> the suffix after the base name (empty for the overload that keeps it). */
	void loadPins(Path file) throws IOException {
		if (!Files.exists(file)) return;
		Properties p = new Properties();
		try (var in = Files.newInputStream(file)) {
			p.load(in);
		}
		for (String k : p.stringPropertyNames()) pinnedSuffix.put(k, p.getProperty(k));
	}

	private String computeMemberName(IMethodBinding m, String baseName) {
		String key = erasureKey(m);

		IMethodBinding decl = m.getMethodDeclaration();
		String declKey = decl.getDeclaringClass().getErasure().getBinaryName();
		String name = decl.isConstructor() ? "<init>" : decl.getName();
		List<String> order = overloadOrder.getOrDefault(declKey + "#" + name, List.of());
		// Other platforms: public overloads come first, so the API keeps the bare name over a package-private helper declared before it.
		if (GoTypes.platform != Platform.COCOA && order.size() > 1) {
			order = new ArrayList<>(order);
			order.sort(Comparator.comparing(k -> !publicKeys.contains(k)));
		}
		int idx = order.indexOf(key);
		if (idx <= 0) return withTypeNameGuard(decl, baseName); // first declared, or external -> base name.

		if (!nameBasedSuffixesUnique(order)) {
			// JNIGen natives reuse arg0/arg1/... across overloads that differ only by type.
			return baseName + "Overload" + idx;
		}

		List<String> params = paramNamesByKey.getOrDefault(key, List.of());
		StringBuilder sb = new StringBuilder();
		for (String p : params) {
			sb.append(capitalize(p));
		}
		// No contract rule for a later zero-param overload (nothing to append); fall back to arity.
		if (params.isEmpty()) sb.append(params.size());
		// setBackground(Color color) must not become the natural name of setBackgroundColor(NSColor).
		String name_ = baseName + sb;
		if (!decl.isConstructor() && isNaturalNameOfOther(decl, name_)) name_ = baseName + "With" + sb;
		return withTypeNameGuard(decl, name_);
	}

	// Unsuffixed Go name of a differently-named Java method of the same kind (instance: declared
	// or inherited below Object; static: same class) - from bindings, so it never depends on the
	// translated set.
	private static boolean isNaturalNameOfOther(IMethodBinding decl, String goName) {
		boolean isStatic = Modifier.isStatic(decl.getModifiers());
		for (ITypeBinding t = decl.getDeclaringClass(); t != null && !t.getQualifiedName().equals("java.lang.Object");
				t = isStatic ? null : t.getSuperclass()) {
			for (IMethodBinding o : t.getDeclaredMethods()) {
				if (o.isConstructor() || Modifier.isStatic(o.getModifiers()) != isStatic || o.getName().equals(decl.getName())) continue;
				if (javaMethodBaseGoName(o.getName()).equals(goName)) return true;
			}
		}
		return false;
	}

	// Layout.layout() -> "Layout" is also the embedded field every subclass reaches it through;
	// an instance method named like its own or an ancestor's type gets "Fn".
	private static String withTypeNameGuard(IMethodBinding decl, String goName) {
		if (decl.isConstructor() || Modifier.isStatic(decl.getModifiers())) return goName;
		for (ITypeBinding t = decl.getDeclaringClass(); t != null && !t.getQualifiedName().equals("java.lang.Object");
				t = t.getSuperclass()) {
			if (goTypeName(t.getErasure()).equals(goName)) return goName + "Fn";
		}
		return goName;
	}

	private final Map<String, Boolean> uniqueCache = new HashMap<>();

	// Suffixes for overloads after the first (which always keeps the bare base name and so
	// can't collide) - unique means name-based suffixing is fine, else fall back to position.
	private boolean nameBasedSuffixesUnique(List<String> order) {
		return uniqueCache.computeIfAbsent(String.join(",", order), k -> {
			Set<String> seen = new HashSet<>();
			for (int i = 1; i < order.size(); i++) {
				List<String> params = paramNamesByKey.getOrDefault(order.get(i), List.of());
				StringBuilder sb = new StringBuilder();
				for (String p : params) sb.append(capitalize(p));
				if (params.isEmpty()) sb.append(0);
				if (!seen.add(sb.toString())) return false;
			}
			return true;
		});
	}
}
