// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT Accessibility/common/org/eclipse/swt/accessibility/AccessibleHyperlinkAdapter.java @ af630a9093. DO NOT EDIT.

package swt

import (
	"github.com/haiodo/gowt/internal/jrt"
)

type AccessibleHyperlinkAdapter struct {
}

func init() { jrt.RegisterClassPackage("AccessibleHyperlinkAdapter", "org.eclipse.swt.accessibility") }

func (this *AccessibleHyperlinkAdapter) AsAccessibleHyperlinkAdapter() *AccessibleHyperlinkAdapter {
	return this
}

type AccessibleHyperlinkAdapterLike interface {
	AsAccessibleHyperlinkAdapter() *AccessibleHyperlinkAdapter
}

func NewAccessibleHyperlinkAdapter() *AccessibleHyperlinkAdapter {
	this := &AccessibleHyperlinkAdapter{}
	this.initAccessibleHyperlinkAdapter()
	return this
}

func (this *AccessibleHyperlinkAdapter) initAccessibleHyperlinkAdapter() {
}

func (this *AccessibleHyperlinkAdapter) GetAnchor(e *AccessibleHyperlinkEvent) {
}

func (this *AccessibleHyperlinkAdapter) GetAnchorTarget(e *AccessibleHyperlinkEvent) {
}

func (this *AccessibleHyperlinkAdapter) GetStartIndex(e *AccessibleHyperlinkEvent) {
}

func (this *AccessibleHyperlinkAdapter) GetEndIndex(e *AccessibleHyperlinkEvent) {
}
