// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/StyledTextContent.java @ af630a9093. DO NOT EDIT.

package swt

type StyledTextContent interface {
	AddTextChangeListener(listener TextChangeListener)
	GetCharCount() int32
	GetLine(lineIndex int32) string
	GetLineAtOffset(offset int32) int32
	GetLineCount() int32
	GetLineDelimiter() string
	GetOffsetAtLine(lineIndex int32) int32
	GetTextRange(start int32, length int32) string
	RemoveTextChangeListener(listener TextChangeListener)
	ReplaceTextRange(start int32, replaceLength int32, text string)
	SetText(text string)
}
