// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/StyledTextPrintOptions.java @ af630a9093. DO NOT EDIT.

package swt

import (
	"github.com/haiodo/gowt/internal/jrt"
)

type StyledTextPrintOptions struct {
	Header              string
	Footer              string
	JobName             string
	PrintTextForeground bool
	PrintTextBackground bool
	PrintTextFontStyle  bool
	PrintLineBackground bool
	PrintLineNumbers    bool
	LineLabels          []string
}

func init() { jrt.RegisterClassPackage("StyledTextPrintOptions", "org.eclipse.swt.custom") }

func (this *StyledTextPrintOptions) AsStyledTextPrintOptions() *StyledTextPrintOptions { return this }

type StyledTextPrintOptionsLike interface {
	AsStyledTextPrintOptions() *StyledTextPrintOptions
}

const StyledTextPrintOptionsPAGE_TAG string = "<page>"

const StyledTextPrintOptionsSEPARATOR string = "\t"

func NewStyledTextPrintOptions() *StyledTextPrintOptions {
	this := &StyledTextPrintOptions{}
	this.initStyledTextPrintOptions()
	return this
}

func (this *StyledTextPrintOptions) initStyledTextPrintOptions() {
	this.Header = ""
	this.Footer = ""
	this.JobName = ""
	this.PrintTextForeground = false
	this.PrintTextBackground = false
	this.PrintTextFontStyle = false
	this.PrintLineBackground = false
	this.PrintLineNumbers = false
	this.LineLabels = nil
}
