// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/ExtendedModifyListener.java @ af630a9093. DO NOT EDIT.

package swt

type ExtendedModifyListener interface {
	ModifyText(event *ExtendedModifyEvent)
}
