// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/gtk/org/eclipse/swt/dnd/TextTransfer.java @ af630a9093. DO NOT EDIT.

package swt

import (
	"fmt"
	"github.com/haiodo/gowt/internal/gtk"
	"github.com/haiodo/gowt/internal/jrt"
	"os"
	"unicode/utf16"
)

type TextTransfer struct {
	ByteArrayTransfer
}

func init() { jrt.RegisterClassPackage("TextTransfer", "org.eclipse.swt.dnd") }

func (this *TextTransfer) AsTextTransfer() *TextTransfer { return this }

type TextTransferLike interface {
	AsTextTransfer() *TextTransfer
}

var TextTransfer_instance *TextTransfer = newTextTransfer()

const TextTransferCOMPOUND_TEXT string = "COMPOUND_TEXT"

const TextTransferUTF8_STRING string = "UTF8_STRING"

const TextTransferSTRING string = "STRING"

const TextTransferTEXT_PLAIN string = "text/plain"

const TextTransferTEXT_PLAIN_UTF8 string = "text/plain;charset=utf-8"

var TextTransferCOMPOUND_TEXT_ID int32 = func() (r int32) {
	defer func() {
		if e := recover(); e != nil {
			fmt.Fprintln(os.Stderr, "gowt: deferred init TextTransferCOMPOUND_TEXT_ID:", e)
		}
	}()
	r = TransferRegisterType(TextTransferCOMPOUND_TEXT)
	return
}()

var TextTransferUTF8_STRING_ID int32 = func() (r int32) {
	defer func() {
		if e := recover(); e != nil {
			fmt.Fprintln(os.Stderr, "gowt: deferred init TextTransferUTF8_STRING_ID:", e)
		}
	}()
	r = TransferRegisterType(TextTransferUTF8_STRING)
	return
}()

var TextTransferSTRING_ID int32 = func() (r int32) {
	defer func() {
		if e := recover(); e != nil {
			fmt.Fprintln(os.Stderr, "gowt: deferred init TextTransferSTRING_ID:", e)
		}
	}()
	r = TransferRegisterType(TextTransferSTRING)
	return
}()

var TextTransferTEXT_PLAIN_ID int32 = func() (r int32) {
	defer func() {
		if e := recover(); e != nil {
			fmt.Fprintln(os.Stderr, "gowt: deferred init TextTransferTEXT_PLAIN_ID:", e)
		}
	}()
	r = TransferRegisterType(TextTransferTEXT_PLAIN)
	return
}()

var TextTransferTEXT_PLAIN_UTF8_ID int32 = func() (r int32) {
	defer func() {
		if e := recover(); e != nil {
			fmt.Fprintln(os.Stderr, "gowt: deferred init TextTransferTEXT_PLAIN_UTF8_ID:", e)
		}
	}()
	r = TransferRegisterType(TextTransferTEXT_PLAIN_UTF8)
	return
}()

func newTextTransfer() *TextTransfer {
	this := &TextTransfer{}
	this.impl = this
	this.initTextTransfer()
	return this
}

func (this *TextTransfer) initTextTransfer() {
	this.ByteArrayTransfer.initByteArrayTransfer()
}

func (this *TextTransfer) javaToNative_(object any, transferData *TransferData) {
	if gtk.GTKGTK4 {
		this.JavaToNativeGTK4(object, transferData)
		return
	}
	transferData.Result = 0
	if !this.CheckText(object) || !this.impl.isSupportedType_(transferData) {
		DNDError(DNDERROR_INVALID_DATA)
	}
	var string_ string = object.(string)
	var utf8 []int8 = gtk.ConverterWcsToMbcs(string_, true)
	if gtk.OSIsX11() && transferData.Type == int64(TextTransferCOMPOUND_TEXT_ID) {
		var encoding []int64 = make([]int64, 1)
		var format []int32 = make([]int32, 1)
		var ctext []int64 = make([]int64, 1)
		var length []int32 = make([]int32, 1)
		var result bool = gtk.GDKGdk_x11_display_utf8_to_compound_text(gtk.GDKGdk_display_get_default(), utf8, encoding, format, ctext, length)
		if !result {
			return
		}
		transferData.Type = encoding[0]
		transferData.Format = format[0]
		transferData.Length = length[0]
		transferData.PValue = ctext[0]
		transferData.Result = 1
	}
	if transferData.Type == int64(TextTransferUTF8_STRING_ID) || transferData.Type == int64(TextTransferTEXT_PLAIN_UTF8_ID) {
		var pValue int64 = gtk.OSG_malloc(int64(int32(len(utf8))))
		if pValue == 0 {
			return
		}
		gtk.CMemmove(pValue, utf8, int64(int32(len(utf8))))
		transferData.Format = 8
		transferData.Length = int32(len(utf8)) - 1
		transferData.PValue = pValue
		transferData.Result = 1
	}
	if transferData.Type == int64(TextTransferSTRING_ID) {
		var string_target int64 = gtk.GDKGdk_utf8_to_string_target(utf8)
		if string_target == 0 {
			return
		}
		transferData.Type = int64(TextTransferSTRING_ID)
		transferData.Format = 8
		transferData.Length = gtk.CStrlen(string_target)
		transferData.PValue = string_target
		transferData.Result = 1
	}
}

func (this *TextTransfer) JavaToNativeGTK4(object any, transferDataLike TransferDataLike) {
	var transferData *TransferData
	if transferDataLike != nil {
		transferData = transferDataLike.AsTransferData()
	}
	_ = transferData
	if !this.CheckText(object) || !this.impl.isSupportedType_(transferData) {
		DNDError(DNDERROR_INVALID_DATA)
	}
	this.ByteArrayTransfer.javaToNative_(gtk.ConverterWcsToMbcs(object.(string), false), transferData)
}

func (this *TextTransfer) nativeToJava_(transferData *TransferData) any {
	if gtk.GTKGTK4 {
		return this.NativeToJavaGTK4(transferData)
	}
	if !this.impl.isSupportedType_(transferData) || transferData.PValue == 0 {
		return nil
	}
	var list []int64 = make([]int64, 1)
	var count int32 = gtk.GDKGdk_text_property_to_utf8_list_for_display(gtk.GDKGdk_display_get_default(), transferData.Type, transferData.Format, transferData.PValue, transferData.Length, list)
	if count == 0 {
		return nil
	}
	var ptr []int64 = make([]int64, 1)
	gtk.CMemmoveOverload16(ptr, list[0], int64(gtk.CPTR_SIZEOF))
	var length int32 = gtk.CStrlen(ptr[0])
	var utf8 []int8 = make([]int8, length)
	gtk.CMemmoveOverload8(utf8, ptr[0], int64(length))
	gtk.OSG_strfreev(list[0])
	var unicode []uint16 = gtk.ConverterMbcsToWcs(utf8)
	var string_ string = string(utf16.Decode(unicode))
	var end int32 = jrt.IndexFrom(string_, string(rune('\u0000')), 0)
	var cond784 any
	if end == -1 {
		cond784 = string_
	} else {
		cond784 = jrt.Substring(string_, 0, end)
	}
	return cond784
}

func (this *TextTransfer) NativeToJavaGTK4(transferDataLike TransferDataLike) any {
	var transferData *TransferData
	if transferDataLike != nil {
		transferData = transferDataLike.AsTransferData()
	}
	_ = transferData
	var buffer any = this.ByteArrayTransfer.nativeToJava_(transferData)
	bytes, ok785 := buffer.([]int8)
	if ok785 {
		return string(utf16.Decode(gtk.ConverterMbcsToWcs(bytes)))
	}
	return nil
}

func (this *TextTransfer) getTypeIds_() []int32 {
	if gtk.GTKGTK4 {
		return []int32{TextTransferTEXT_PLAIN_UTF8_ID, TextTransferTEXT_PLAIN_ID, TextTransferSTRING_ID}
	}
	if gtk.OSIsX11() {
		return []int32{TextTransferUTF8_STRING_ID, TextTransferCOMPOUND_TEXT_ID, TextTransferSTRING_ID}
	}
	return []int32{TextTransferUTF8_STRING_ID, TextTransferSTRING_ID, TextTransferTEXT_PLAIN_UTF8_ID}
}

func (this *TextTransfer) getTypeNames_() []string {
	if gtk.GTKGTK4 {
		return []string{TextTransferTEXT_PLAIN_UTF8, TextTransferTEXT_PLAIN, TextTransferSTRING}
	}
	if gtk.OSIsX11() {
		return []string{TextTransferUTF8_STRING, TextTransferCOMPOUND_TEXT, TextTransferSTRING}
	}
	return []string{TextTransferUTF8_STRING, TextTransferSTRING, TextTransferTEXT_PLAIN_UTF8}
}

func (this *TextTransfer) CheckText(object any) bool {
	_, ok787 := object.(string)
	return (ok787 && !(len((object.(string))) == 0))
}

func (this *TextTransfer) validate_(object any) bool {
	return this.CheckText(object)
}

func TextTransferGetInstance() *TextTransfer {
	return TextTransfer_instance
}
