// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/cocoa/org/eclipse/swt/dnd/FileTransfer.java @ af630a9093. DO NOT EDIT.

package swt

import (
	"fmt"
	"github.com/haiodo/gowt/internal/cocoa"
	"github.com/haiodo/gowt/internal/jrt"
	"os"
)

type FileTransfer struct {
	ByteArrayTransfer
}

func init() { jrt.RegisterClassPackage("FileTransfer", "org.eclipse.swt.dnd") }

func (this *FileTransfer) AsFileTransfer() *FileTransfer { return this }

type FileTransferLike interface {
	AsFileTransfer() *FileTransfer
}

var FileTransfer_instance *FileTransfer = newFileTransfer()

var FileTransferID_NAME string = func() (r string) {
	defer func() {
		if e := recover(); e != nil {
			fmt.Fprintln(os.Stderr, "gowt: deferred init FileTransferID_NAME:", e)
		}
	}()
	r = cocoa.OSNSFilenamesPboardType_.GetString()
	return
}()

var FileTransferID int32 = func() (r int32) {
	defer func() {
		if e := recover(); e != nil {
			fmt.Fprintln(os.Stderr, "gowt: deferred init FileTransferID:", e)
		}
	}()
	r = TransferRegisterType(FileTransferID_NAME)
	return
}()

var FileTransferID1_NAME string = func() (r string) {
	defer func() {
		if e := recover(); e != nil {
			fmt.Fprintln(os.Stderr, "gowt: deferred init FileTransferID1_NAME:", e)
		}
	}()
	r = cocoa.OSKUTTypeFileURL_.GetString()
	return
}()

var FileTransferID1 int32 = func() (r int32) {
	defer func() {
		if e := recover(); e != nil {
			fmt.Fprintln(os.Stderr, "gowt: deferred init FileTransferID1:", e)
		}
	}()
	r = TransferRegisterType(FileTransferID1_NAME)
	return
}()

func newFileTransfer() *FileTransfer {
	this := &FileTransfer{}
	this.impl = this
	this.initFileTransfer()
	return this
}

func (this *FileTransfer) initFileTransfer() {
	this.ByteArrayTransfer.initByteArrayTransfer()
}

func (this *FileTransfer) javaToNative_(object any, transferData *TransferData) {
	if !this.CheckFile(object) || !this.impl.isSupportedType_(transferData) {
		DNDError(DNDERROR_INVALID_DATA)
	}
	var files []string = jrt.Cast[[]string](object)
	var length int32 = int32(len(files))
	var array *cocoa.NSMutableArray = cocoa.NSMutableArrayArrayWithCapacity(int64(length))
	for i := int32(0); i < length; i++ {
		var fileName string = files[i]
		var string_ *cocoa.NSString = cocoa.NSStringStringWith(fileName)
		array.AddObject(upcastcocoaNSStringTococoaId(string_))
	}
	transferData.Data = upcastcocoaNSMutableArrayTococoaNSObject(array)
}

func (this *FileTransfer) nativeToJava_(transferData *TransferData) any {
	if !this.impl.isSupportedType_(transferData) || transferData.Data == (nil) {
		return nil
	}
	var array *cocoa.NSArray = castcocoaNSObjectTococoaNSArray(transferData.Data)
	if array.Count() == 0 {
		return nil
	}
	var count int32 = int32(array.Count())
	var fileNames []string = make([]string, count)
	for i := int32(0); i < count; i++ {
		var string_ *cocoa.NSString = cocoa.NewNSStringOverload2(array.ObjectAtIndex(int64(i)))
		fileNames[i] = string_.GetString()
	}
	return fileNames
}

func (this *FileTransfer) getTypeIds_() []int32 {
	return []int32{FileTransferID, FileTransferID1}
}

func (this *FileTransfer) getTypeNames_() []string {
	return []string{FileTransferID_NAME, FileTransferID1_NAME}
}

func (this *FileTransfer) CheckFile(object any) bool {
	var strings []string
	if jrt.IsNil(object) || func() bool { pv, ok1007 := object.([]string); strings = pv; return !(ok1007) }() || int32(len((jrt.Cast[[]string](object)))) == 0 {
		return false
	}
	for i := int32(0); i < int32(len(strings)); i++ {
		if strings[i] == "" || jrt.StringLength(strings[i]) == 0 {
			return false
		}
	}
	return true
}

func (this *FileTransfer) validate_(object any) bool {
	return this.CheckFile(object)
}

func FileTransferGetInstance() *FileTransfer {
	return FileTransfer_instance
}

func upcastcocoaNSMutableArrayTococoaNSObject(x *cocoa.NSMutableArray) *cocoa.NSObject {
	if x == nil {
		return nil
	}
	return &x.NSObject
}
