// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/win32/org/eclipse/swt/dnd/DragSource.java @ af630a9093. DO NOT EDIT.

package swt

import (
	"fmt"
	"github.com/haiodo/gowt/internal/jrt"
	"github.com/haiodo/gowt/internal/win32"
	"os"
	"reflect"
)

type DragSource struct {
	Widget
	control         *Control
	controlListener Listener
	transferAgents  []*Transfer
	dragEffect      *DragSourceEffect
	topControl      *Composite
	hwndDrag        int64
	iDropSource     *DragSource_COMIDropSource
	iDataObject     *DragSource_COMIDataObject
	dataEffect      int32
}

func init() { jrt.RegisterClassPackage("DragSource", "org.eclipse.swt.dnd") }

func (this *DragSource) AsDragSource() *DragSource { return this }

type DragSourceLike interface {
	AsDragSource() *DragSource
}

const DragSourceDEFAULT_DRAG_SOURCE_EFFECT string = "DEFAULT_DRAG_SOURCE_EFFECT"

var DragSourceCFSTR_PERFORMEDDROPEFFECT int32 = func() (r int32) {
	defer func() {
		if e := recover(); e != nil {
			fmt.Fprintln(os.Stderr, "gowt: deferred init DragSourceCFSTR_PERFORMEDDROPEFFECT:", e)
		}
	}()
	r = TransferRegisterType("Performed DropEffect")
	return
}()

var DragSourceWindowClass *win32.TCHAR = win32.NewTCHARStringTerminate("#32770", true)

func NewDragSource(controlLike ControlLike, style int32) *DragSource {
	var control *Control
	if controlLike != nil {
		control = controlLike.AsControl()
	}
	_ = control
	this := &DragSource{}
	this.impl = this
	this.initDragSource(control, style)
	return this
}

func (this *DragSource) initDragSource(control *Control, style int32) {
	this.Widget.initWidgetParentStyle(upcastControlToWidget(control), DragSourceCheckStyle(style))
	this.transferAgents = make([]*Transfer, 0)
	this.dataEffect = DNDDROP_NONE
	this.control = control
	if !jrt.IsNil(control.impl.getDataKey_(DNDDRAG_SOURCE_KEY)) {
		DNDError(DNDERROR_CANNOT_INIT_DRAG)
	}
	control.impl.setDataKeyValue_(DNDDRAG_SOURCE_KEY, this)
	this.controlListener = &ListenerFunc{fn: func(event *Event) {
		if event.Type == Dispose {
			if !this.IsDisposed() {
				this.impl.dispose_()
			}
		}
		if event.Type == DragDetect {
			if !this.IsDisposed() {
				this.Drag(event)
			}
		}
		if event.Type == ZoomChanged {
			if !this.IsDisposed() {
				this.NativeZoom = event.Detail
			}
		}
	}}
	control.AddListener(Dispose, this.controlListener)
	control.AddListener(DragDetect, this.controlListener)
	control.AddListener(ZoomChanged, this.controlListener)
	this.AddListener(Dispose, &ListenerFunc{fn: func(e *Event) {
		this.OnDispose()
	}})
	var effect any = control.impl.getDataKey_(DragSourceDEFAULT_DRAG_SOURCE_EFFECT)
	_, ok1124 := dragSourceAdapterImplAsDragSourceEffect(effect)
	if ok1124 {
		this.dragEffect = castanyToDragSourceEffect(effect)
	} else {
		_, ok1125 := isControlToTree(control)
		if ok1125 {
			this.dragEffect = upcastTreeDragSourceEffectToDragSourceEffect(NewTreeDragSourceEffect(castControlToTree(control)))
		} else {
			_, ok1126 := isControlToTable(control)
			if ok1126 {
				this.dragEffect = upcastTableDragSourceEffectToDragSourceEffect(NewTableDragSourceEffect(castControlToTable(control)))
			}
		}
	}
}

func (this *DragSource) AddDragListener(listener DragSourceListener) {
	if listener == (nil) {
		DNDError(ERROR_NULL_ARGUMENT)
	}
	var typedListener *DNDListener = newDNDListener(listener)
	typedListener.dndWidget = upcastDragSourceToWidget(this)
	this.AddListener(DNDDragStart, upcastDNDListenerToListener(typedListener))
	this.AddListener(DNDDragSetData, upcastDNDListenerToListener(typedListener))
	this.AddListener(DNDDragEnd, upcastDNDListenerToListener(typedListener))
}

func (this *DragSource) CreateCOMInterfaces() {
	this.ReleaseCOMInterfaces()
	this.iDropSource = NewDragSourceCOMIDropSource(this)
	this.iDataObject = NewDragSourceCOMIDataObject(this, this.transferAgents)
}

func (this *DragSource) checkSubclass_() {
	var name string = jrt.ClassName(reflect.TypeOf(this.Impl()))
	var validName string = jrt.ClassName(reflect.TypeFor[*DragSource]())
	if !(validName == name) {
		DNDError(ERROR_INVALID_SUBCLASS)
	}
}

func (this *DragSource) ReleaseCOMInterfaces() {
	if this.iDropSource != (nil) {
		this.iDropSource.Release()
	}
	this.iDropSource = nil
	if this.iDataObject != (nil) {
		this.iDataObject.Release()
	}
	this.iDataObject = nil
}

func (this *DragSource) CanBeginDrag() bool {
	if this.transferAgents == (nil) || int32(len(this.transferAgents)) == 0 {
		return false
	}
	return true
}

func (this *DragSource) Drag(dragEventLike EventLike) {
	var dragEvent *Event
	if dragEventLike != nil {
		dragEvent = dragEventLike.AsEvent()
	}
	_ = dragEvent
	var event *DNDEvent = newDNDEvent()
	event.Widget = upcastDragSourceToWidget(this)
	event.X = dragEvent.X
	event.Y = dragEvent.Y
	event.Time = win32.OSGetMessageTime()
	event.Doit = true
	this.NotifyListeners(DNDDragStart, upcastDNDEventToEvent(event))
	if !event.Doit || !this.CanBeginDrag() {
		return
	}
	var pdwEffect []int32 = make([]int32, 1)
	var operations int32 = this.OpToOs(this.impl.getStyle_())
	var display *Display = this.control.GetDisplay()
	var key string = "org.eclipse.swt.internal.win32.runMessagesInIdle"
	var oldValue any = display.GetData(key)
	display.SetData(key, true)
	var imagelist *ImageList = nil
	var image *Image = event.Image
	this.hwndDrag = int64(0)
	this.topControl = nil
	if image != (nil) {
		var zoom int32 = DPIUtilGetZoomForAutoscaleProperty(this.NativeZoom)
		imagelist = NewImageList(NONE, zoom)
		imagelist.Add(image)
		this.topControl = upcastShellToComposite(this.control.impl.getShell_())
		var offsetX int32 = event.OffsetX
		this.hwndDrag = this.topControl.Handle
		if (this.topControl.impl.getStyle_() & RIGHT_TO_LEFT) != 0 {
			offsetX = Win32DPIUtilsPointToPixelOverload6(image.GetBounds(), zoom).Width - offsetX
			var rect *win32.RECT = win32.NewRECT()
			win32.OSGetClientRect(this.topControl.Handle, rect)
			this.hwndDrag = win32.OSCreateWindowEx(win32.OSWS_EX_TRANSPARENT|win32.OSWS_EX_NOINHERITLAYOUT, DragSourceWindowClass, nil, win32.OSWS_CHILD|win32.OSWS_CLIPSIBLINGS, 0, 0, rect.Right-rect.Left, rect.Bottom-rect.Top, this.topControl.Handle, int64(0), win32.OSGetModuleHandle(nil), nil)
			win32.OSShowWindow(this.hwndDrag, win32.OSSW_SHOW)
		}
		win32.OSImageList_BeginDrag(imagelist.GetHandle(zoom), 0, offsetX, event.OffsetY)
		var flags int32 = win32.OSRDW_UPDATENOW | win32.OSRDW_ALLCHILDREN
		win32.OSRedrawWindow(this.topControl.Handle, nil, int64(0), flags)
		var pt *win32.POINT = win32.NewPOINT()
		pt.X = DPIUtilPointToPixel(dragEvent.X, zoom)
		pt.Y = DPIUtilPointToPixel(dragEvent.Y, zoom)
		win32.OSMapWindowPoints(this.control.Handle, int64(0), pt, 1)
		var rect *win32.RECT = win32.NewRECT()
		win32.OSGetWindowRect(this.hwndDrag, rect)
		win32.OSImageList_DragEnter(this.hwndDrag, pt.X-rect.Left, pt.Y-rect.Top)
	}
	var externalLoopKey string = "org.eclipse.swt.internal.win32.externalEventLoop"
	var result int32 = win32.COMDRAGDROP_S_CANCEL
	func() {
		defer func() {
			display.SetData(externalLoopKey, false)
			if this.hwndDrag != 0 {
				win32.OSImageList_DragLeave(this.hwndDrag)
				win32.OSImageList_EndDrag()
				imagelist.Dispose()
				if this.hwndDrag != this.topControl.Handle {
					win32.OSDestroyWindow(this.hwndDrag)
				}
				this.hwndDrag = int64(0)
				this.topControl = nil
			}
			display.SetData(key, oldValue)
			this.ReleaseCOMInterfaces()
		}()
		this.CreateCOMInterfaces()
		display.SetData(externalLoopKey, true)
		result = win32.COMDoDragDrop(this.iDataObject.GetAddress(), this.iDropSource.GetAddress(), operations, pdwEffect)
	}()
	var operation int32 = this.OsToOp(pdwEffect[0])
	if this.dataEffect == DNDDROP_MOVE {
		if operation == DNDDROP_NONE || operation == DNDDROP_COPY {
			operation = DNDDROP_TARGET_MOVE
		} else {
			operation = DNDDROP_MOVE
		}
	} else {
		if this.dataEffect != DNDDROP_NONE {
			operation = this.dataEffect
		}
	}
	event = newDNDEvent()
	event.Widget = upcastDragSourceToWidget(this)
	event.Time = win32.OSGetMessageTime()
	event.Doit = (result == win32.COMDRAGDROP_S_DROP)
	event.Detail = operation
	this.NotifyListeners(DNDDragEnd, upcastDNDEventToEvent(event))
	this.dataEffect = DNDDROP_NONE
}

func (this *DragSource) GetControl() *Control {
	return this.control
}

func (this *DragSource) GetDragListeners() []DragSourceListener {
	return jrt.ToSlice[DragSourceListener](this.GetTypedListeners(DNDDragStart, reflect.TypeFor[DragSourceListener]()))
}

func (this *DragSource) GetDragSourceEffect() *DragSourceEffect {
	return this.dragEffect
}

func (this *DragSource) GetTransfer() []*Transfer {
	return this.transferAgents
}

func (this *DragSource) GiveFeedback(dwEffect int32) int32 {
	return win32.COMDRAGDROP_S_USEDEFAULTCURSORS
}

func (this *DragSource) QueryContinueDrag(fEscapePressed int32, grfKeyState int32) int32 {
	if this.topControl != (nil) && this.topControl.IsDisposed() {
		return win32.COMDRAGDROP_S_CANCEL
	}
	if fEscapePressed != 0 {
		if this.hwndDrag != 0 {
			win32.OSImageList_DragLeave(this.hwndDrag)
		}
		return win32.COMDRAGDROP_S_CANCEL
	}
	var mask int32 = win32.OSMK_LBUTTON | win32.OSMK_MBUTTON | win32.OSMK_RBUTTON
	if (grfKeyState & mask) == 0 {
		if this.hwndDrag != 0 {
			win32.OSImageList_DragLeave(this.hwndDrag)
		}
		return win32.COMDRAGDROP_S_DROP
	}
	if this.hwndDrag != 0 {
		var pt *win32.POINT = win32.NewPOINT()
		win32.OSGetCursorPos(pt)
		var rect *win32.RECT = win32.NewRECT()
		win32.OSGetWindowRect(this.hwndDrag, rect)
		win32.OSImageList_DragMove(pt.X-rect.Left, pt.Y-rect.Top)
	}
	return win32.COMS_OK
}

func (this *DragSource) OnDispose() {
	if this.control == (nil) {
		return
	}
	this.ReleaseCOMInterfaces()
	if this.controlListener != (nil) {
		this.control.RemoveListener(Dispose, this.controlListener)
		this.control.RemoveListener(DragDetect, this.controlListener)
	}
	this.controlListener = nil
	this.control.impl.setDataKeyValue_(DNDDRAG_SOURCE_KEY, nil)
	this.control = nil
	this.transferAgents = nil
}

func (this *DragSource) OpToOs(operation int32) int32 {
	var osOperation int32 = 0
	if (operation & DNDDROP_COPY) != 0 {
		osOperation |= win32.COMDROPEFFECT_COPY
	}
	if (operation & DNDDROP_LINK) != 0 {
		osOperation |= win32.COMDROPEFFECT_LINK
	}
	if (operation & DNDDROP_MOVE) != 0 {
		osOperation |= win32.COMDROPEFFECT_MOVE
	}
	return osOperation
}

func (this *DragSource) OsToOp(osOperation int32) int32 {
	var operation int32 = 0
	if (osOperation & win32.COMDROPEFFECT_COPY) != 0 {
		operation |= DNDDROP_COPY
	}
	if (osOperation & win32.COMDROPEFFECT_LINK) != 0 {
		operation |= DNDDROP_LINK
	}
	if (osOperation & win32.COMDROPEFFECT_MOVE) != 0 {
		operation |= DNDDROP_MOVE
	}
	return operation
}

func (this *DragSource) RemoveDragListener(listener DragSourceListener) {
	if listener == (nil) {
		DNDError(ERROR_NULL_ARGUMENT)
	}
	this.RemoveTypedListener(DNDDragStart, listener)
	this.RemoveTypedListener(DNDDragSetData, listener)
	this.RemoveTypedListener(DNDDragEnd, listener)
}

func (this *DragSource) SetDragSourceEffect(effectLike DragSourceEffectLike) {
	var effect *DragSourceEffect
	if effectLike != nil {
		effect = effectLike.AsDragSourceEffect()
	}
	_ = effect
	this.dragEffect = effect
}

func (this *DragSource) SetTransfer(transferAgents []*Transfer) {
	this.transferAgents = transferAgents
}

func DragSourceCheckStyle(style int32) int32 {
	if style == NONE {
		return DNDDROP_MOVE
	}
	return style
}

func DragSourceEnumFormatEtc(transferAgents []*Transfer, dwDirection int32, ppenumFormatetc int64) int32 {
	if dwDirection == win32.COMDATADIR_SET {
		return win32.COME_NOTIMPL
	}
	var allowedDataTypes []*TransferData = make([]*TransferData, 0)
	for _, transferAgent := range transferAgents {
		if transferAgent != (nil) {
			var formats []*TransferData = transferAgent.impl.getSupportedTypes_()
			var newAllowedDataTypes []*TransferData = make([]*TransferData, int32(len(allowedDataTypes))+int32(len(formats)))
			copy(newAllowedDataTypes[0:], allowedDataTypes[0:0+int32(len(allowedDataTypes))])
			copy(newAllowedDataTypes[int32(len(allowedDataTypes)):], formats[0:0+int32(len(formats))])
			allowedDataTypes = newAllowedDataTypes
		}
	}
	var enumFORMATETC *OleEnumFORMATETC = newOleEnumFORMATETC()
	enumFORMATETC.AddRef()
	var formats []*win32.FORMATETC = make([]*win32.FORMATETC, int32(len(allowedDataTypes)))
	for i := int32(0); i < int32(len(formats)); i++ {
		formats[i] = allowedDataTypes[i].Formatetc
	}
	enumFORMATETC.SetFormats(formats)
	win32.OSMoveMemoryOverload79(ppenumFormatetc, []int64{enumFORMATETC.GetAddress()}, win32.CPTR_SIZEOF)
	return win32.COMS_OK
}

func DragSourceQueryGetData(transferAgents []*Transfer, pFormatetc int64) int32 {
	if transferAgents == (nil) {
		return win32.COME_FAIL
	}
	var transferData *TransferData = NewTransferData()
	transferData.Formatetc = win32.NewFORMATETC()
	win32.COMMoveMemoryOverload5(transferData.Formatetc, pFormatetc, win32.FORMATETCSizeof)
	transferData.Type = transferData.Formatetc.CfFormat
	for _, transferAgent := range transferAgents {
		if transferAgent != (nil) && transferAgent.impl.isSupportedType_(transferData) {
			return win32.COMS_OK
		}
	}
	return win32.COMDV_E_FORMATETC
}

func DragSourceQueryInterface(comObjectLike COMObjectLike, riid int64, ppvObject int64) int32 {
	var comObject *COMObject
	if comObjectLike != nil {
		comObject = comObjectLike.AsCOMObject()
	}
	_ = comObject
	if riid == 0 || ppvObject == 0 {
		return win32.COME_INVALIDARG
	}
	var guid *win32.GUID = win32.NewGUID()
	win32.COMMoveMemoryOverload6(guid, riid, win32.GUIDSizeof)
	if comObject != (nil) && win32.COMIsEqualGUID(guid, win32.COMIIDIUnknown) || (win32.COMIsEqualGUID(guid, win32.COMIIDIDropSource) && func() bool { _, ok1134 := isCOMObjectToDragSource_COMIDropSource(comObject); return (ok1134) }()) || (win32.COMIsEqualGUID(guid, win32.COMIIDIDataObject) && func() bool { _, ok1136 := isCOMObjectToDragSource_COMIDataObject(comObject); return (ok1136) }()) {
		win32.OSMoveMemoryOverload79(ppvObject, []int64{comObject.GetAddress()}, win32.CPTR_SIZEOF)
		comObject.impl.method1_(nil)
		return win32.COMS_OK
	}
	win32.OSMoveMemoryOverload79(ppvObject, []int64{int64(0)}, win32.CPTR_SIZEOF)
	return win32.COME_NOINTERFACE
}

type DragSource_COMIDropSource struct {
	COMObject
	this_0   *DragSource
	refCount int64
}

func init() { jrt.RegisterClassPackage("DragSource_COMIDropSource", "org.eclipse.swt.dnd") }

func (this *DragSource_COMIDropSource) AsDragSource_COMIDropSource() *DragSource_COMIDropSource {
	return this
}

type DragSource_COMIDropSourceLike interface {
	AsDragSource_COMIDropSource() *DragSource_COMIDropSource
}

func NewDragSourceCOMIDropSource(this_0 *DragSource) *DragSource_COMIDropSource {
	this := &DragSource_COMIDropSource{}
	this.this_0 = this_0
	this.impl = this
	this.initDragSourceCOMIDropSource()
	return this
}

func (this *DragSource_COMIDropSource) initDragSourceCOMIDropSource() {
	this.COMObject.initCOMObject([]int32{2, 0, 0, 2, 1})
	this.refCount = int64(0)
	this.AddRef()
}

func (this *DragSource_COMIDropSource) method0_(args []int64) int64 {
	return int64(DragSourceQueryInterface(upcastDragSource_COMIDropSourceToCOMObject(this), args[0], args[1]))
}

func (this *DragSource_COMIDropSource) method1_(args []int64) int64 {
	return this.AddRef()
}

func (this *DragSource_COMIDropSource) method2_(args []int64) int64 {
	return this.Release()
}

func (this *DragSource_COMIDropSource) method3_(args []int64) int64 {
	return int64(this.this_0.QueryContinueDrag(int32(args[0]), int32(args[1])))
}

func (this *DragSource_COMIDropSource) method4_(args []int64) int64 {
	return int64(this.this_0.GiveFeedback(int32(args[0])))
}

func (this *DragSource_COMIDropSource) AddRef() int64 {
	this.refCount++
	return this.refCount
}

func (this *DragSource_COMIDropSource) Release() int64 {
	this.refCount--
	if this.refCount == 0 {
		if this.this_0.iDropSource == this {
			this.this_0.iDropSource = nil
		}
		this.Dispose()
		if win32.COMFreeUnusedLibraries {
			win32.COMCoFreeUnusedLibraries()
		}
	}
	return this.refCount
}

type DragSource_COMIDataObject struct {
	COMObject
	this_0         *DragSource
	refCount       int64
	transferAgents []*Transfer
	lastData       any
}

func init() { jrt.RegisterClassPackage("DragSource_COMIDataObject", "org.eclipse.swt.dnd") }

func (this *DragSource_COMIDataObject) AsDragSource_COMIDataObject() *DragSource_COMIDataObject {
	return this
}

type DragSource_COMIDataObjectLike interface {
	AsDragSource_COMIDataObject() *DragSource_COMIDataObject
}

func NewDragSourceCOMIDataObject(this_0 *DragSource, transferAgents []*Transfer) *DragSource_COMIDataObject {
	this := &DragSource_COMIDataObject{}
	this.this_0 = this_0
	this.impl = this
	this.initDragSourceCOMIDataObject(transferAgents)
	return this
}

func (this *DragSource_COMIDataObject) initDragSourceCOMIDataObject(transferAgents []*Transfer) {
	this.COMObject.initCOMObject([]int32{2, 0, 0, 2, 2, 1, 2, 3, 2, 4, 1, 1})
	this.refCount = int64(0)
	this.lastData = nil
	this.AddRef()
	this.transferAgents = transferAgents
}

func (this *DragSource_COMIDataObject) method0_(args []int64) int64 {
	return int64(DragSourceQueryInterface(upcastDragSource_COMIDataObjectToCOMObject(this), args[0], args[1]))
}

func (this *DragSource_COMIDataObject) method1_(args []int64) int64 {
	return this.AddRef()
}

func (this *DragSource_COMIDataObject) method2_(args []int64) int64 {
	return this.Release()
}

func (this *DragSource_COMIDataObject) method3_(args []int64) int64 {
	return int64(this.GetData(args[0], args[1]))
}

func (this *DragSource_COMIDataObject) method5_(args []int64) int64 {
	return int64(DragSourceQueryGetData(this.transferAgents, args[0]))
}

func (this *DragSource_COMIDataObject) method7_(args []int64) int64 {
	return int64(this.SetData(args[0], args[1], int32(args[2])))
}

func (this *DragSource_COMIDataObject) method8_(args []int64) int64 {
	return int64(DragSourceEnumFormatEtc(this.transferAgents, int32(args[0]), args[1]))
}

func (this *DragSource_COMIDataObject) AddRef() int64 {
	this.refCount++
	return this.refCount
}

func (this *DragSource_COMIDataObject) Release() int64 {
	this.refCount--
	if this.refCount == 0 {
		if this.this_0.iDataObject == this {
			this.this_0.iDataObject = nil
		}
		this.Dispose()
		if win32.COMFreeUnusedLibraries {
			win32.COMCoFreeUnusedLibraries()
		}
	}
	return this.refCount
}

func (this *DragSource_COMIDataObject) IsActive() bool {
	return this.this_0.iDataObject == this
}

func (this *DragSource_COMIDataObject) GetData(pFormatetc int64, pmedium int64) int32 {
	if pFormatetc == 0 || pmedium == 0 {
		return win32.COME_INVALIDARG
	}
	if DragSourceQueryGetData(this.transferAgents, pFormatetc) != win32.COMS_OK {
		return win32.COMDV_E_FORMATETC
	}
	var transferData *TransferData = NewTransferData()
	transferData.Formatetc = win32.NewFORMATETC()
	win32.COMMoveMemoryOverload5(transferData.Formatetc, pFormatetc, win32.FORMATETCSizeof)
	transferData.Type = transferData.Formatetc.CfFormat
	transferData.Stgmedium = win32.NewSTGMEDIUM()
	transferData.Result = win32.COME_FAIL
	var data any
	if this.IsActive() {
		var event *DNDEvent = newDNDEvent()
		event.Widget = upcastDragSourceToWidget(this.this_0)
		event.Time = win32.OSGetMessageTime()
		event.DataType = transferData
		this.this_0.NotifyListeners(DNDDragSetData, upcastDNDEventToEvent(event))
		if !event.Doit {
			return win32.COME_FAIL
		}
		this.lastData = event.Data
		data = event.Data
	} else {
		if jrt.IsNil(this.lastData) {
			return win32.COME_FAIL
		}
		data = this.lastData
	}
	var transfer *Transfer = nil
	for _, transferAgent := range this.transferAgents {
		if transferAgent != (nil) && transferAgent.impl.isSupportedType_(transferData) {
			transfer = transferAgent
			break
		}
	}
	if transfer == (nil) {
		return win32.COMDV_E_FORMATETC
	}
	transfer.impl.javaToNative_(data, transferData)
	if transferData.Result != win32.COMS_OK {
		return transferData.Result
	}
	win32.COMMoveMemoryOverload2(pmedium, transferData.Stgmedium, win32.STGMEDIUMSizeof)
	return transferData.Result
}

func (this *DragSource_COMIDataObject) SetData(pFormatetc int64, pmedium int64, fRelease int32) int32 {
	if pFormatetc == 0 || pmedium == 0 {
		return win32.COME_INVALIDARG
	}
	var formatetc *win32.FORMATETC = win32.NewFORMATETC()
	win32.COMMoveMemoryOverload5(formatetc, pFormatetc, win32.FORMATETCSizeof)
	if formatetc.CfFormat == DragSourceCFSTR_PERFORMEDDROPEFFECT && formatetc.Tymed == win32.COMTYMED_HGLOBAL {
		var stgmedium *win32.STGMEDIUM = win32.NewSTGMEDIUM()
		win32.COMMoveMemoryOverload3(stgmedium, pmedium, win32.STGMEDIUMSizeof)
		var ptrEffect []int64 = make([]int64, 1)
		win32.OSMoveMemoryOverload7(ptrEffect, stgmedium.UnionField, win32.CPTR_SIZEOF)
		var effect []int32 = make([]int32, 1)
		win32.OSMoveMemoryOverload6(effect, ptrEffect[0], 4)
		if this.IsActive() {
			this.this_0.dataEffect = this.this_0.OsToOp(effect[0])
		}
	}
	if fRelease == 1 {
		win32.COMReleaseStgMedium(pmedium)
	}
	return win32.COMS_OK
}

// j2go: instanceof helper for DragSourceEffect and its subclasses within the translated set.
func dragSourceAdapterImplAsDragSourceEffect(x any) (*DragSourceEffect, bool) {
	if h, ok := x.(*dragSourceAdapterHooked); ok {
		x = h.hook
	}
	switch v := x.(type) {
	case *DragSourceEffect:
		if v == nil {
			return nil, false
		}
		return v, true
	case *TableDragSourceEffect:
		if v == nil {
			return nil, false
		}
		return &v.DragSourceEffect, true
	case *TreeDragSourceEffect:
		if v == nil {
			return nil, false
		}
		return &v.DragSourceEffect, true
	}
	if l, ok := x.(interface{ AsDragSourceEffect() *DragSourceEffect }); ok {
		return l.AsDragSourceEffect(), true
	}
	return nil, false
}

func castanyToDragSourceEffect(x any) *DragSourceEffect {
	if x == nil {
		return nil
	}
	v, ok := dragSourceAdapterImplAsDragSourceEffect(x)
	if !ok {
		panic("java.lang.ClassCastException: DragSourceEffect")
	}
	return v
}

func upcastTreeDragSourceEffectToDragSourceEffect(x *TreeDragSourceEffect) *DragSourceEffect {
	if x == nil {
		return nil
	}
	return &x.DragSourceEffect
}

func upcastTableDragSourceEffectToDragSourceEffect(x *TableDragSourceEffect) *DragSourceEffect {
	if x == nil {
		return nil
	}
	return &x.DragSourceEffect
}

func upcastDragSourceToWidget(x *DragSource) *Widget {
	if x == nil {
		return nil
	}
	return &x.Widget
}

func upcastDNDListenerToListener(x *DNDListener) Listener {
	if x == nil {
		return nil
	}
	return x
}

// j2go: instanceof helper for DragSource_COMIDropSource and its subclasses within the translated set.
func cOMObjectImplAsDragSourceCOMIDropSource(x any) (*DragSource_COMIDropSource, bool) {
	if h, ok := x.(*cOMObjectHooked); ok {
		x = h.hook
	}
	switch v := x.(type) {
	case *DragSource_COMIDropSource:
		if v == nil {
			return nil, false
		}
		return v, true
	}
	if l, ok := x.(interface {
		AsDragSource_COMIDropSource() *DragSource_COMIDropSource
	}); ok {
		return l.AsDragSource_COMIDropSource(), true
	}
	return nil, false
}

func isCOMObjectToDragSource_COMIDropSource(x *COMObject) (*DragSource_COMIDropSource, bool) {
	if x == nil {
		return nil, false
	}
	return cOMObjectImplAsDragSourceCOMIDropSource(x.impl)
}

// j2go: instanceof helper for DragSource_COMIDataObject and its subclasses within the translated set.
func cOMObjectImplAsDragSourceCOMIDataObject(x any) (*DragSource_COMIDataObject, bool) {
	if h, ok := x.(*cOMObjectHooked); ok {
		x = h.hook
	}
	switch v := x.(type) {
	case *DragSource_COMIDataObject:
		if v == nil {
			return nil, false
		}
		return v, true
	}
	if l, ok := x.(interface {
		AsDragSource_COMIDataObject() *DragSource_COMIDataObject
	}); ok {
		return l.AsDragSource_COMIDataObject(), true
	}
	return nil, false
}

func isCOMObjectToDragSource_COMIDataObject(x *COMObject) (*DragSource_COMIDataObject, bool) {
	if x == nil {
		return nil, false
	}
	return cOMObjectImplAsDragSourceCOMIDataObject(x.impl)
}

func upcastDragSource_COMIDropSourceToCOMObject(x *DragSource_COMIDropSource) *COMObject {
	if x == nil {
		return nil
	}
	return &x.COMObject
}

func upcastDragSource_COMIDataObjectToCOMObject(x *DragSource_COMIDataObject) *COMObject {
	if x == nil {
		return nil
	}
	return &x.COMObject
}
