// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/events/DisposeEvent.java @ af630a9093. DO NOT EDIT.

package swt

type DisposeEvent struct {
	TypedEvent
}

func NewDisposeEvent(e *Event) *DisposeEvent {
	this := &DisposeEvent{}
	this.Impl = this
	this.initDisposeEvent(e)
	return this
}

func (this *DisposeEvent) initDisposeEvent(e *Event) {
	this.TypedEvent.initTypedEventE(e)
}
