// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/events/VerifyEvent.java @ af630a9093. DO NOT EDIT.

package swt

import (
	"fmt"
)

type VerifyEvent struct {
	KeyEvent
	Start int32
	End   int32
	Text  string
}

func NewVerifyEvent(e *Event) *VerifyEvent {
	this := &VerifyEvent{}
	this.impl = this
	this.initVerifyEvent(e)
	return this
}

func (this *VerifyEvent) initVerifyEvent(e *Event) {
	this.KeyEvent.initKeyEvent(e)
	this.Start = e.Start
	this.End = e.End
	this.Text = e.Text
}

func (this *VerifyEvent) String() string {
	var string_ string = this.KeyEvent.String()
	return fmt.Sprintf("%s start=%d end=%d text=%s}", string_[0:int32(len(string_))-1], this.Start, this.End, this.Text)
}
