// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/DeviceData.java @ af630a9093. DO NOT EDIT.

package swt

import (
	"github.com/haiodo/gowt/internal/jrt"
)

type DeviceDataImpl interface {
}

// j2go: wraps a subclass from another package; its exported hook names override the defaults.
type deviceDataHooked struct {
	DeviceDataImpl
	hook   DeviceDataImpl
	active string
}

func (this *deviceDataHooked) enter(name string) func() {
	prev := this.active
	this.active = name
	return func() { this.active = prev }
}

type DeviceData struct {
	Debug    bool
	Tracking bool
	Errors   []error
	Objects  []any
	impl     DeviceDataImpl
}

func (this *DeviceData) Impl() DeviceDataImpl {
	if h, ok := this.impl.(*deviceDataHooked); ok {
		return h.hook
	}
	return this.impl
}

func (this *DeviceData) SetImpl_(impl DeviceDataImpl) {
	this.impl = &deviceDataHooked{DeviceDataImpl: this.impl, hook: impl}
}

func init() { jrt.RegisterClassPackage("DeviceData", "org.eclipse.swt.graphics") }

func (this *DeviceData) AsDeviceData() *DeviceData { return this }

type DeviceDataLike interface {
	AsDeviceData() *DeviceData
}

func NewDeviceData() *DeviceData {
	this := &DeviceData{}
	this.impl = this
	this.initDeviceData()
	return this
}

func (this *DeviceData) initDeviceData() {
}
