// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/ImageDataProvider.java @ af630a9093. DO NOT EDIT.

package swt

type ImageDataProvider interface {
	GetImageData(zoom int32) *ImageData
}
