// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/GCData.java @ af630a9093. DO NOT EDIT.

package swt

import (
	"github.com/haiodo/gowt/internal/jrt"
	"github.com/haiodo/gowt/internal/win32"
)

type GCData struct {
	Device                  *Device
	Style                   int32
	State                   int32
	Foreground              int32
	Background              int32
	Font                    *Font
	ForegroundPattern       *Pattern
	GdipFgPatternBrushAlpha int64
	BackgroundPattern       *Pattern
	GdipBgPatternBrushAlpha int64
	LineStyle               int32
	LineWidth               float32
	LineCap                 int32
	LineJoin                int32
	LineDashesOffset        float32
	LineDashes              []float32
	LineMiterLimit          float32
	Alpha                   int32
	NativeZoom              int32
	imageZoom               int32
	reapplicable            bool
	Image                   *Image
	Ps                      *win32.PAINTSTRUCT
	Layout                  int32
	HPen                    int64
	HOldPen                 int64
	HBrush                  int64
	HOldBrush               int64
	HNullBitmap             int64
	Hwnd                    int64
	GdipGraphics            int64
	GdipPen                 int64
	GdipBrush               int64
	GdipFgBrush             int64
	GdipBgBrush             int64
	GdipFont                int64
	HGDIFont                int64
	GdipXOffset             float32
	GdipYOffset             float32
	UiState                 int32
	FocusDrawn              bool
}

func init() { jrt.RegisterClassPackage("GCData", "org.eclipse.swt.graphics") }

func (this *GCData) AsGCData() *GCData { return this }

type GCDataLike interface {
	AsGCData() *GCData
}

func NewGCData() *GCData {
	this := &GCData{}
	this.initGCData()
	return this
}

func (this *GCData) initGCData() {
	this.State = -1
	this.Foreground = -1
	this.Background = -1
	this.LineStyle = LINE_SOLID
	this.LineCap = CAP_FLAT
	this.LineJoin = JOIN_MITER
	this.LineMiterLimit = float32(10)
	this.Alpha = 0xFF
	this.Layout = -1
	this.UiState = 0
}

func (this *GCData) CopyTo(originalDataLike GCDataLike) {
	var originalData *GCData
	if originalDataLike != nil {
		originalData = originalDataLike.AsGCData()
	}
	_ = originalData
	originalData.Device = this.Device
	originalData.Style = this.Style
	originalData.Foreground = this.Foreground
	originalData.Background = this.Background
	originalData.Font = this.Font
	originalData.NativeZoom = this.NativeZoom
	originalData.Image = this.Image
	originalData.imageZoom = this.imageZoom
	originalData.Ps = this.Ps
	originalData.Layout = this.Layout
	originalData.Hwnd = this.Hwnd
	originalData.UiState = this.UiState
	originalData.FocusDrawn = this.FocusDrawn
}
