// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/PaletteData.java @ af630a9093. DO NOT EDIT.

package swt

type PaletteData struct {
	IsDirect   bool
	Colors     []*RGB
	RedMask    int32
	GreenMask  int32
	BlueMask   int32
	RedShift   int32
	GreenShift int32
	BlueShift  int32
}

func NewPaletteData(colors []*RGB) *PaletteData {
	this := &PaletteData{}
	this.initPaletteData(colors)
	return this
}

func (this *PaletteData) initPaletteData(colors []*RGB) {
	if colors == (nil) {
		SWTErrorFn(SWTERROR_NULL_ARGUMENT)
	}
	this.Colors = colors
	this.IsDirect = false
}

func NewPaletteDataRedMaskGreenMaskBlueMask(redMask int32, greenMask int32, blueMask int32) *PaletteData {
	this := &PaletteData{}
	this.initPaletteDataRedMaskGreenMaskBlueMask(redMask, greenMask, blueMask)
	return this
}

func (this *PaletteData) initPaletteDataRedMaskGreenMaskBlueMask(redMask int32, greenMask int32, blueMask int32) {
	this.RedMask = redMask
	this.GreenMask = greenMask
	this.BlueMask = blueMask
	this.IsDirect = true
	this.RedShift = this.ShiftForMask(redMask)
	this.GreenShift = this.ShiftForMask(greenMask)
	this.BlueShift = this.ShiftForMask(blueMask)
}

func (this *PaletteData) GetPixel(rgb *RGB) int32 {
	if rgb == (nil) {
		SWTErrorFn(SWTERROR_NULL_ARGUMENT)
	}
	if this.IsDirect {
		var pixel int32 = 0
		var cond419 int32
		if this.RedShift < 0 {
			cond419 = rgb.Red << -this.RedShift
		} else {
			cond419 = int32(uint32(rgb.Red) >> (this.RedShift))
		}
		pixel |= (cond419) & this.RedMask
		var cond420 int32
		if this.GreenShift < 0 {
			cond420 = rgb.Green << -this.GreenShift
		} else {
			cond420 = int32(uint32(rgb.Green) >> (this.GreenShift))
		}
		pixel |= (cond420) & this.GreenMask
		var cond421 int32
		if this.BlueShift < 0 {
			cond421 = rgb.Blue << -this.BlueShift
		} else {
			cond421 = int32(uint32(rgb.Blue) >> (this.BlueShift))
		}
		pixel |= (cond421) & this.BlueMask
		return pixel
	} else {
		for i := int32(0); i < int32(len(this.Colors)); i++ {
			if this.Colors[i].Equals(rgb) {
				return i
			}
		}
		SWTErrorFn(SWTERROR_INVALID_ARGUMENT)
		return 0
	}
}

func (this *PaletteData) GetRGB(pixel int32) *RGB {
	if this.IsDirect {
		var r int32 = pixel & this.RedMask
		if this.RedShift < 0 {
			r = int32(uint32(r) >> (-this.RedShift))
		} else {
			r = r << this.RedShift
		}
		var g int32 = pixel & this.GreenMask
		if this.GreenShift < 0 {
			g = int32(uint32(g) >> (-this.GreenShift))
		} else {
			g = g << this.GreenShift
		}
		var b int32 = pixel & this.BlueMask
		if this.BlueShift < 0 {
			b = int32(uint32(b) >> (-this.BlueShift))
		} else {
			b = b << this.BlueShift
		}
		return NewRGB(r, g, b)
	} else {
		if pixel < 0 || pixel >= int32(len(this.Colors)) {
			SWTErrorFn(SWTERROR_INVALID_ARGUMENT)
		}
		return this.Colors[pixel]
	}
}

func (this *PaletteData) GetRGBs() []*RGB {
	return this.Colors
}

func (this *PaletteData) ShiftForMask(mask int32) int32 {
	for i := int32(31); i >= 0; i-- {
		if ((mask >> i) & 0x1) != 0 {
			return 7 - i
		}
	}
	return 32
}
