// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/LegacySWTFontRegistry.java @ af630a9093. DO NOT EDIT.

package swt

import (
	"github.com/haiodo/gowt/internal/jrt"
	"github.com/haiodo/gowt/internal/win32"
)

type LegacySWTFontRegistry struct {
	fontsMap *jrt.Map
	device   *Device
}

func init() { jrt.RegisterClassPackage("LegacySWTFontRegistry", "org.eclipse.swt.internal") }

func (this *LegacySWTFontRegistry) AsLegacySWTFontRegistry() *LegacySWTFontRegistry { return this }

type LegacySWTFontRegistryLike interface {
	AsLegacySWTFontRegistry() *LegacySWTFontRegistry
}

var LegacySWTFontRegistryKEY_SYSTEM_FONTS *FontData = NewFontData()

func newLegacySWTFontRegistry(device *Device) *LegacySWTFontRegistry {
	this := &LegacySWTFontRegistry{}
	this.initLegacySWTFontRegistry(device)
	return this
}

func (this *LegacySWTFontRegistry) initLegacySWTFontRegistry(device *Device) {
	this.fontsMap = jrt.NewMap()
	this.device = device
}

func (this *LegacySWTFontRegistry) GetSystemFont(zoom int32) *Font {
	if this.fontsMap.ContainsKey(LegacySWTFontRegistryKEY_SYSTEM_FONTS) {
		return jrt.Cast[*Font](this.fontsMap.Get(LegacySWTFontRegistryKEY_SYSTEM_FONTS))
	}
	var hFont int64 = int64(0)
	var info *win32.NONCLIENTMETRICS = win32.NewNONCLIENTMETRICS()
	info.CbSize = win32.NONCLIENTMETRICSSizeof
	if win32.OSSystemParametersInfoOverload2(win32.OSSPI_GETNONCLIENTMETRICS, 0, info, 0) {
		hFont = win32.OSCreateFontIndirectLplf(info.LfMessageFont)
	}
	if hFont == 0 {
		hFont = win32.OSGetStockObject(win32.OSDEFAULT_GUI_FONT)
	}
	if hFont == 0 {
		hFont = win32.OSGetStockObject(win32.OSSYSTEM_FONT)
	}
	var font *Font = FontWin32_newDeviceHandleZoom(this.device, hFont, zoom)
	this.RegisterFont(LegacySWTFontRegistryKEY_SYSTEM_FONTS, font)
	this.RegisterFont(font.GetFontData()[0], font)
	return font
}

func (this *LegacySWTFontRegistry) GetFont(fontData *FontData, zoom int32) *Font {
	if this.fontsMap.ContainsKey(fontData) {
		var font *Font = jrt.Cast[*Font](this.fontsMap.Get(fontData))
		if font.impl.isDisposed_() {
			jrt.Cast[*Font](this.fontsMap.Remove(fontData))
		} else {
			return font
		}
	}
	var font *Font = NewFontDeviceFd(this.device, fontData)
	this.RegisterFont(fontData, font)
	return font
}

func (this *LegacySWTFontRegistry) GetFontFontHandleZoom(fontHandle int64, zoom int32) *Font {
	return FontWin32_newDeviceHandleZoom(this.device, fontHandle, zoom)
}

func (this *LegacySWTFontRegistry) RegisterFont(fontDataLike FontDataLike, fontLike FontLike) *Font {
	var fontData *FontData
	if fontDataLike != nil {
		fontData = fontDataLike.AsFontData()
	}
	_ = fontData
	var font *Font
	if fontLike != nil {
		font = fontLike.AsFont()
	}
	_ = font
	var clonedFontData *FontData = NewFontDataOverload2(fontData)
	jrt.Cast[*Font](this.fontsMap.Put(clonedFontData, font))
	return font
}

func (this *LegacySWTFontRegistry) Dispose() {
	for _, elem1 := range this.fontsMap.Values().ToArray() {
		font := jrt.Cast[*Font](elem1)
		if font != (nil) {
			font.impl.dispose_()
		}
	}
}
