// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/layout/FillLayout.java @ af630a9093. DO NOT EDIT.

package swt

import (
	"fmt"
	"math"
	"reflect"
	"strings"
)

type FillLayout struct {
	Layout
	Type         int32
	MarginWidth  int32
	MarginHeight int32
	Spacing      int32
}

func (this *FillLayout) AsFillLayout() *FillLayout { return this }

type FillLayoutLike interface {
	AsFillLayout() *FillLayout
}

func NewFillLayout() *FillLayout {
	this := &FillLayout{}
	this.impl = this
	this.initFillLayout()
	return this
}

func (this *FillLayout) initFillLayout() {
	this.Layout.initLayout()
	this.Type = HORIZONTAL
	this.MarginWidth = 0
	this.MarginHeight = 0
	this.Spacing = 0
}

func NewFillLayoutType(type_ int32) *FillLayout {
	this := &FillLayout{}
	this.impl = this
	this.initFillLayoutType(type_)
	return this
}

func (this *FillLayout) initFillLayoutType(type_ int32) {
	this.Layout.initLayout()
	this.Type = HORIZONTAL
	this.MarginWidth = 0
	this.MarginHeight = 0
	this.Spacing = 0
	this.Type = type_
}

func (this *FillLayout) computeSize_(composite *Composite, wHint int32, hHint int32, flushCache bool) *Point {
	var children []*Control = composite.GetChildren()
	var count int32 = int32(len(children))
	var maxWidth int32 = 0
	var maxHeight int32 = 0
	for i := int32(0); i < count; i++ {
		var child *Control = children[i]
		var w int32 = wHint
		var h int32 = hHint
		if count > 0 {
			if this.Type == HORIZONTAL && wHint != DEFAULT {
				w = int32(math.Max(float64(0), float64((wHint-(count-1)*this.Spacing)/count)))
			}
			if this.Type == VERTICAL && hHint != DEFAULT {
				h = int32(math.Max(float64(0), float64((hHint-(count-1)*this.Spacing)/count)))
			}
		}
		var size *Point = this.ComputeChildSize(child, w, h, flushCache)
		maxWidth = int32(math.Max(float64(maxWidth), float64(size.X)))
		maxHeight = int32(math.Max(float64(maxHeight), float64(size.Y)))
	}
	var width int32 = 0
	var height int32 = 0
	if this.Type == HORIZONTAL {
		width = count * maxWidth
		if count != 0 {
			width += (count - 1) * this.Spacing
		}
		height = maxHeight
	} else {
		width = maxWidth
		height = count * maxHeight
		if count != 0 {
			height += (count - 1) * this.Spacing
		}
	}
	width += this.MarginWidth * 2
	height += this.MarginHeight * 2
	if wHint != DEFAULT {
		width = wHint
	}
	if hHint != DEFAULT {
		height = hHint
	}
	return NewPoint(width, height)
}

func (this *FillLayout) ComputeChildSize(controlLike ControlLike, wHint int32, hHint int32, flushCache bool) *Point {
	var control *Control
	if controlLike != nil {
		control = controlLike.AsControl()
	}
	_ = control
	var data any = control.GetLayoutData()
	var fillData *FillData
	_, ok89 := fillDataImplAsFillData(data)
	if ok89 {
		fillData = castanyToFillData(data)
	} else {
		fillData = newFillData()
		if data == (nil) {
			control.SetLayoutData(fillData)
		}
	}
	var size *Point = nil
	if wHint == DEFAULT && hHint == DEFAULT {
		size = fillData.ComputeSize(control, wHint, hHint, flushCache)
	} else {
		var trimX int32
		var trimY int32
		_, ok90 := isControlToScrollable(control)
		if ok90 {
			var rect *Rectangle = (castControlToScrollable(control)).impl.computeTrim_(0, 0, 0, 0)
			trimX = rect.Width
			trimY = rect.Height
		} else {
			trimY = control.GetBorderWidth() * 2
			trimX = trimY
		}
		var w int32
		if wHint == DEFAULT {
			w = wHint
		} else {
			w = int32(math.Max(float64(0), float64(wHint-trimX)))
		}
		var h int32
		if hHint == DEFAULT {
			h = hHint
		} else {
			h = int32(math.Max(float64(0), float64(hHint-trimY)))
		}
		size = fillData.ComputeSize(control, w, h, flushCache)
	}
	return size
}

func (this *FillLayout) flushCache_(control *Control) bool {
	var data any = control.GetLayoutData()
	_, ok91 := fillDataImplAsFillData(data)
	if ok91 {
		(castanyToFillData(data)).FlushCache()
		return true
	}
	return false
}

func (this *FillLayout) GetName() string {
	var string_ string = reflect.TypeOf(this).String()
	var index int32 = int32(strings.LastIndexByte(string_, byte('.')))
	if index == -1 {
		return string_
	}
	return string_[index+1 : int32(len(string_))]
}

func (this *FillLayout) layoutFn_(composite *Composite, flushCache bool) {
	var rect *Rectangle = composite.impl.getClientArea_()
	var children []*Control = composite.GetChildren()
	var count int32 = int32(len(children))
	if count == 0 {
		return
	}
	var width int32 = rect.Width - this.MarginWidth*2
	var height int32 = rect.Height - this.MarginHeight*2
	if this.Type == HORIZONTAL {
		width -= (count - 1) * this.Spacing
		var x int32 = rect.X + this.MarginWidth
		var extra int32 = width % count
		var y int32 = rect.Y + this.MarginHeight
		var cellWidth int32 = width / count
		for i := int32(0); i < count; i++ {
			var child *Control = children[i]
			var childWidth int32 = cellWidth
			if i == 0 {
				childWidth += extra / 2
			} else {
				if i == count-1 {
					childWidth += (extra + 1) / 2
				}
			}
			child.SetBounds(x, y, childWidth, height)
			x += childWidth + this.Spacing
		}
	} else {
		height -= (count - 1) * this.Spacing
		var x int32 = rect.X + this.MarginWidth
		var cellHeight int32 = height / count
		var y int32 = rect.Y + this.MarginHeight
		var extra int32 = height % count
		for i := int32(0); i < count; i++ {
			var child *Control = children[i]
			var childHeight int32 = cellHeight
			if i == 0 {
				childHeight += extra / 2
			} else {
				if i == count-1 {
					childHeight += (extra + 1) / 2
				}
			}
			child.SetBounds(x, y, width, childHeight)
			y += childHeight + this.Spacing
		}
	}
}

func (this *FillLayout) String() string {
	var string_ string = fmt.Sprintf("%s {", this.GetName())
	var cond92 string
	if this.Type == VERTICAL {
		cond92 = "SWT.VERTICAL"
	} else {
		cond92 = "SWT.HORIZONTAL"
	}
	string_ += fmt.Sprintf("type=%s ", (cond92))
	if this.MarginWidth != 0 {
		string_ += fmt.Sprintf("marginWidth=%d ", this.MarginWidth)
	}
	if this.MarginHeight != 0 {
		string_ += fmt.Sprintf("marginHeight=%d ", this.MarginHeight)
	}
	if this.Spacing != 0 {
		string_ += fmt.Sprintf("spacing=%d ", this.Spacing)
	}
	string_ = strings.TrimSpace(string_)
	string_ += "}"
	return string_
}

// j2go: instanceof helper for FillData and its subclasses within the translated set.
func fillDataImplAsFillData(x any) (*FillData, bool) {
	switch v := x.(type) {
	case *FillData:
		return v, true
	}
	return nil, false
}

func castanyToFillData(x any) *FillData {
	if x == nil {
		return nil
	}
	v, ok := fillDataImplAsFillData(x)
	if !ok {
		panic("java.lang.ClassCastException: FillData")
	}
	return v
}

// j2go: instanceof helper for Scrollable and its subclasses within the translated set.
func widgetImplAsScrollable(x any) (*Scrollable, bool) {
	switch v := x.(type) {
	case *Scrollable:
		return v, true
	case *Composite:
		return &v.Scrollable, true
	case *Canvas:
		return &v.Scrollable, true
	case *Decorations:
		return &v.Scrollable, true
	case *Shell:
		return &v.Scrollable, true
	case *Group:
		return &v.Scrollable, true
	case *SashForm:
		return &v.Scrollable, true
	case *Tree:
		return &v.Scrollable, true
	case *TabFolder:
		return &v.Scrollable, true
	case *Combo:
		return &v.Scrollable, true
	case *Table:
		return &v.Scrollable, true
	case *ScrolledComposite:
		return &v.Scrollable, true
	case *Text:
		return &v.Scrollable, true
	}
	return nil, false
}

func isControlToScrollable(x *Control) (*Scrollable, bool) {
	if x == nil {
		return nil, false
	}
	return widgetImplAsScrollable(x.impl)
}

func castControlToScrollable(x *Control) *Scrollable {
	if x == nil {
		return nil
	}
	v, ok := widgetImplAsScrollable(x.impl)
	if !ok {
		panic("java.lang.ClassCastException: Scrollable")
	}
	return v
}
