// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/layout/FormLayout.java @ af630a9093. DO NOT EDIT.

package swt

import (
	"fmt"
	"math"
	"reflect"
	"strings"
)

type FormLayout struct {
	Layout
	MarginWidth  int32
	MarginHeight int32
	MarginLeft   int32
	MarginTop    int32
	MarginRight  int32
	MarginBottom int32
	Spacing      int32
}

func (this *FormLayout) AsFormLayout() *FormLayout { return this }

type FormLayoutLike interface {
	AsFormLayout() *FormLayout
}

func NewFormLayout() *FormLayout {
	this := &FormLayout{}
	this.impl = this
	this.initFormLayout()
	return this
}

func (this *FormLayout) initFormLayout() {
	this.Layout.initLayout()
	this.MarginWidth = 0
	this.MarginHeight = 0
	this.MarginLeft = 0
	this.MarginTop = 0
	this.MarginRight = 0
	this.MarginBottom = 0
	this.Spacing = 0
}

func (this *FormLayout) ComputeHeight(controlLike ControlLike, dataLike FormDataLike, flushCache bool) int32 {
	var control *Control
	if controlLike != nil {
		control = controlLike.AsControl()
	}
	_ = control
	var data *FormData
	if dataLike != nil {
		data = dataLike.AsFormData()
	}
	_ = data
	var top *FormAttachment = data.GetTopAttachment(control, this.Spacing, flushCache)
	var bottom *FormAttachment = data.GetBottomAttachment(control, this.Spacing, flushCache)
	var height *FormAttachment = bottom.Minus(top)
	if height.Numerator == 0 {
		if bottom.Numerator == 0 {
			return bottom.Offset
		}
		if bottom.Numerator == bottom.Denominator {
			return -top.Offset
		}
		if bottom.Offset <= 0 {
			return -top.Offset * top.Denominator / bottom.Numerator
		}
		var divider int32 = bottom.Denominator - bottom.Numerator
		return bottom.Denominator * bottom.Offset / divider
	}
	return height.SolveY(data.GetHeight(control, flushCache))
}

func (this *FormLayout) ComputeSizeOnLayout(composite *Composite, wHint int32, hHint int32, flushCache bool) *Point {
	var size *Point = this.LayoutCompositeMoveXYWidthHeightFlushCache(composite, false, 0, 0, wHint, hHint, flushCache)
	if wHint != DEFAULT {
		size.X = wHint
	}
	if hHint != DEFAULT {
		size.Y = hHint
	}
	return size
}

func (this *FormLayout) FlushCache(control *Control) bool {
	var data any = control.GetLayoutData()
	if data != (nil) {
		(castanyToFormData(data)).FlushCache()
	}
	return true
}

func (this *FormLayout) GetName() string {
	var string_ string = reflect.TypeOf(this).String()
	var index int32 = int32(strings.LastIndexByte(string_, byte('.')))
	if index == -1 {
		return string_
	}
	return string_[index+1 : int32(len(string_))]
}

func (this *FormLayout) ComputeWidth(controlLike ControlLike, dataLike FormDataLike, flushCache bool) int32 {
	var control *Control
	if controlLike != nil {
		control = controlLike.AsControl()
	}
	_ = control
	var data *FormData
	if dataLike != nil {
		data = dataLike.AsFormData()
	}
	_ = data
	var left *FormAttachment = data.GetLeftAttachment(control, this.Spacing, flushCache)
	var right *FormAttachment = data.GetRightAttachment(control, this.Spacing, flushCache)
	var width *FormAttachment = right.Minus(left)
	if width.Numerator == 0 {
		if right.Numerator == 0 {
			return right.Offset
		}
		if right.Numerator == right.Denominator {
			return -left.Offset
		}
		if right.Offset <= 0 {
			return -left.Offset * left.Denominator / left.Numerator
		}
		var divider int32 = right.Denominator - right.Numerator
		return right.Denominator * right.Offset / divider
	}
	return width.SolveY(data.GetWidth(control, flushCache))
}

func (this *FormLayout) LayoutOnLayout(composite *Composite, flushCache bool) {
	var rect *Rectangle = composite.impl.GetClientArea()
	var x int32 = rect.X + this.MarginLeft + this.MarginWidth
	var y int32 = rect.Y + this.MarginTop + this.MarginHeight
	var width int32 = int32(math.Max(float64(0), float64(rect.Width-this.MarginLeft-2*this.MarginWidth-this.MarginRight)))
	var height int32 = int32(math.Max(float64(0), float64(rect.Height-this.MarginTop-2*this.MarginHeight-this.MarginBottom)))
	this.LayoutCompositeMoveXYWidthHeightFlushCache(composite, true, x, y, width, height, flushCache)
}

func (this *FormLayout) LayoutCompositeMoveXYWidthHeightFlushCache(compositeLike CompositeLike, move bool, x int32, y int32, width int32, height int32, flushCache bool) *Point {
	var composite *Composite
	if compositeLike != nil {
		composite = compositeLike.AsComposite()
	}
	_ = composite
	var children []*Control = composite.GetChildren()
	for _, child := range children {
		var data *FormData = castanyToFormData(child.GetLayoutData())
		if data == (nil) {
			cond117 := NewFormData()
			data = cond117
			child.SetLayoutData(cond117)
		}
		if flushCache {
			data.FlushCache()
		}
		data.cacheBottom = nil
		data.cacheTop = data.cacheBottom
		data.cacheRight = data.cacheTop
		data.cacheLeft = data.cacheRight
	}
	var flush []bool = nil
	var bounds []*Rectangle = nil
	var w int32 = 0
	var h int32 = 0
	for i := int32(0); i < int32(len(children)); i++ {
		var child *Control = children[i]
		var data *FormData = castanyToFormData(child.GetLayoutData())
		if width != DEFAULT {
			data.needed = false
			var left *FormAttachment = data.GetLeftAttachment(child, this.Spacing, flushCache)
			var right *FormAttachment = data.GetRightAttachment(child, this.Spacing, flushCache)
			var x1 int32 = left.SolveX(width)
			var x2 int32 = right.SolveX(width)
			if data.Height == DEFAULT && !data.needed {
				var trim int32 = 0
				_, ok118 := isControlToScrollable(child)
				if ok118 {
					var rect *Rectangle = (castControlToScrollable(child)).impl.ComputeTrim(0, 0, 0, 0)
					trim = rect.Width
				} else {
					trim = child.GetBorderWidth() * 2
				}
				data.cacheHeight = -1
				data.cacheWidth = data.cacheHeight
				var currentWidth int32 = int32(math.Max(float64(0), float64(x2-x1-trim)))
				data.ComputeSize(child, currentWidth, data.Height, flushCache)
				if flush == (nil) {
					flush = make([]bool, int32(len(children)))
				}
				flush[i] = true
			}
			w = int32(math.Max(float64(x2), float64(w)))
			if move {
				if bounds == (nil) {
					bounds = make([]*Rectangle, int32(len(children)))
				}
				bounds[i] = NewRectangle(0, 0, 0, 0)
				bounds[i].X = x + x1
				bounds[i].Width = x2 - x1
			}
		} else {
			w = int32(math.Max(float64(this.ComputeWidth(child, data, flushCache)), float64(w)))
		}
	}
	for i := int32(0); i < int32(len(children)); i++ {
		var child *Control = children[i]
		var data *FormData = castanyToFormData(child.GetLayoutData())
		if height != DEFAULT {
			var y1 int32 = data.GetTopAttachment(child, this.Spacing, flushCache).SolveX(height)
			var y2 int32 = data.GetBottomAttachment(child, this.Spacing, flushCache).SolveX(height)
			h = int32(math.Max(float64(y2), float64(h)))
			if move {
				bounds[i].Y = y + y1
				bounds[i].Height = y2 - y1
			}
		} else {
			h = int32(math.Max(float64(this.ComputeHeight(child, data, flushCache)), float64(h)))
		}
	}
	for i := int32(0); i < int32(len(children)); i++ {
		var child *Control = children[i]
		var data *FormData = castanyToFormData(child.GetLayoutData())
		if flush != (nil) && flush[i] {
			data.cacheHeight = -1
			data.cacheWidth = data.cacheHeight
		}
		data.cacheBottom = nil
		data.cacheTop = data.cacheBottom
		data.cacheRight = data.cacheTop
		data.cacheLeft = data.cacheRight
	}
	if move {
		for i := int32(0); i < int32(len(children)); i++ {
			children[i].SetBoundsRect(bounds[i])
		}
	}
	w += this.MarginLeft + this.MarginWidth*2 + this.MarginRight
	h += this.MarginTop + this.MarginHeight*2 + this.MarginBottom
	return NewPoint(w, h)
}

func (this *FormLayout) String() string {
	var string_ string = fmt.Sprintf("%s {", this.GetName())
	if this.MarginWidth != 0 {
		string_ += fmt.Sprintf("marginWidth=%d ", this.MarginWidth)
	}
	if this.MarginHeight != 0 {
		string_ += fmt.Sprintf("marginHeight=%d ", this.MarginHeight)
	}
	if this.MarginLeft != 0 {
		string_ += fmt.Sprintf("marginLeft=%d ", this.MarginLeft)
	}
	if this.MarginRight != 0 {
		string_ += fmt.Sprintf("marginRight=%d ", this.MarginRight)
	}
	if this.MarginTop != 0 {
		string_ += fmt.Sprintf("marginTop=%d ", this.MarginTop)
	}
	if this.MarginBottom != 0 {
		string_ += fmt.Sprintf("marginBottom=%d ", this.MarginBottom)
	}
	if this.Spacing != 0 {
		string_ += fmt.Sprintf("spacing=%d ", this.Spacing)
	}
	string_ = strings.TrimSpace(string_)
	string_ += "}"
	return string_
}

// j2go: instanceof helper for FormData and its subclasses within the translated set.
func formDataImplAsFormData(x any) (*FormData, bool) {
	switch v := x.(type) {
	case *FormData:
		return v, true
	}
	return nil, false
}

func castanyToFormData(x any) *FormData {
	if x == nil {
		return nil
	}
	v, ok := formDataImplAsFormData(x)
	if !ok {
		panic("java.lang.ClassCastException: FormData")
	}
	return v
}
