// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT Printing/win32/org/eclipse/swt/printing/PrintDialog.java @ af630a9093. DO NOT EDIT.

package swt

import (
	"github.com/haiodo/gowt/internal/jrt"
	"github.com/haiodo/gowt/internal/win32"
	"math"
	"reflect"
	"unicode/utf16"
)

type PrintDialog struct {
	Dialog
	printerData *PrinterData
}

func init() { jrt.RegisterClassPackage("PrintDialog", "org.eclipse.swt.printing") }

func (this *PrintDialog) AsPrintDialog() *PrintDialog { return this }

type PrintDialogLike interface {
	AsPrintDialog() *PrintDialog
}

var PrintDialogDialogClass *win32.TCHAR = win32.NewTCHARStringTerminate("#32770", true)

func NewPrintDialog(parentLike ShellLike) *PrintDialog {
	var parent *Shell
	if parentLike != nil {
		parent = parentLike.AsShell()
	}
	_ = parent
	this := &PrintDialog{}
	this.impl = this
	this.initPrintDialog(parent)
	return this
}

func (this *PrintDialog) initPrintDialog(parent *Shell) {
	this.initPrintDialogParentStyle(parent, PRIMARY_MODAL)
}

func NewPrintDialogParentStyle(parentLike ShellLike, style int32) *PrintDialog {
	var parent *Shell
	if parentLike != nil {
		parent = parentLike.AsShell()
	}
	_ = parent
	this := &PrintDialog{}
	this.impl = this
	this.initPrintDialogParentStyle(parent, style)
	return this
}

func (this *PrintDialog) initPrintDialogParentStyle(parent *Shell, style int32) {
	this.Dialog.initDialogParentStyle(parent, PrintDialogCheckStyle(parent, style))
	this.printerData = NewPrinterData()
	this.impl.checkSubclass_()
}

func (this *PrintDialog) SetPrinterData(dataLike PrinterDataLike) {
	var data *PrinterData
	if dataLike != nil {
		data = dataLike.AsPrinterData()
	}
	_ = data
	if data == (nil) {
		data = NewPrinterData()
	}
	this.printerData = data
}

func (this *PrintDialog) GetPrinterData() *PrinterData {
	return this.printerData
}

func (this *PrintDialog) GetScope() int32 {
	return this.printerData.Scope
}

func (this *PrintDialog) SetScope(scope int32) {
	this.printerData.Scope = scope
}

func (this *PrintDialog) GetStartPage() int32 {
	return this.printerData.StartPage
}

func (this *PrintDialog) SetStartPage(startPage int32) {
	this.printerData.StartPage = startPage
}

func (this *PrintDialog) GetEndPage() int32 {
	return this.printerData.EndPage
}

func (this *PrintDialog) SetEndPage(endPage int32) {
	this.printerData.EndPage = endPage
}

func (this *PrintDialog) GetPrintToFile() bool {
	return this.printerData.PrintToFile
}

func (this *PrintDialog) SetPrintToFile(printToFile bool) {
	this.printerData.PrintToFile = printToFile
}

func (this *PrintDialog) checkSubclass_() {
	var name string = jrt.ClassName(reflect.TypeOf(this.Impl()))
	var validName string = jrt.ClassName(reflect.TypeFor[*PrintDialog]())
	if !(validName == name) {
		Error(ERROR_INVALID_SUBCLASS)
	}
}

func (this *PrintDialog) Open() *PrinterData {
	var parent *Control = upcastShellToControl(this.GetParent())
	var style int32 = this.GetStyle()
	var hwndOwner int64 = parent.Handle
	var hwndParent int64 = parent.Handle
	var enabled bool = false
	var dialogOrientation int32 = style & (LEFT_TO_RIGHT | RIGHT_TO_LEFT)
	var parentOrientation int32 = parent.impl.getStyle_() & (LEFT_TO_RIGHT | RIGHT_TO_LEFT)
	if dialogOrientation != parentOrientation {
		var exStyle int32 = win32.OSWS_EX_NOINHERITLAYOUT
		if dialogOrientation == RIGHT_TO_LEFT {
			exStyle |= win32.OSWS_EX_LAYOUTRTL
		}
		hwndOwner = win32.OSCreateWindowEx(exStyle, PrintDialogDialogClass, nil, 0, win32.OSCW_USEDEFAULT, 0, win32.OSCW_USEDEFAULT, 0, hwndParent, int64(0), win32.OSGetModuleHandle(nil), nil)
		enabled = win32.OSIsWindowEnabled(hwndParent)
		if enabled {
			win32.OSEnableWindow(hwndParent, false)
		}
	}
	var data *PrinterData = nil
	var pd *win32.PRINTDLG = win32.NewPRINTDLG()
	pd.LStructSize = win32.PRINTDLGSizeof
	pd.HwndOwner = hwndOwner
	var success bool = false
	if this.printerData.Name != "" {
		for _, element := range PrinterGetPrinterList() {
			if element.Name == this.printerData.Name {
				success = true
				break
			}
		}
		if success {
			var buffer *win32.TCHAR = win32.NewTCHARStringTerminate(this.printerData.Name, true)
			var size int32 = buffer.Length() * win32.TCHARSizeof
			var offsets []int16 = make([]int16, 4)
			var offsetsSize int32 = int32(len(offsets)) * 2
			offsets[1] = int16(int32(len(offsets)))
			var hMem int64 = win32.OSGlobalAlloc(win32.OSGMEM_MOVEABLE|win32.OSGMEM_ZEROINIT, offsetsSize+size)
			var ptr int64 = win32.OSGlobalLock(hMem)
			win32.OSMoveMemoryOverload80(ptr, offsets, offsetsSize)
			win32.OSMoveMemory(ptr+int64(offsetsSize), buffer, size)
			win32.OSGlobalUnlock(hMem)
			pd.HDevNames = hMem
		}
	}
	var display *Display = parent.GetDisplay()
	var externalLoopKey string = "org.eclipse.swt.internal.win32.externalEventLoop"
	if !success {
		pd.Flags = win32.OSPD_RETURNDEFAULT
		display.SetData(externalLoopKey, true)
		display.SendPreExternalEventDispatchEvent()
		success = win32.OSPrintDlg(pd)
		display.SetData(externalLoopKey, false)
		display.SendPostExternalEventDispatchEvent()
		if success {
			if pd.HDevNames != 0 {
				win32.OSGlobalFree(pd.HDevNames)
				pd.HDevNames = int64(0)
			}
		}
	}
	if success {
		var devmodeData []int8 = this.printerData.otherData
		if devmodeData != (nil) && int32(len(devmodeData)) != 0 {
			var hMem int64 = win32.OSGlobalAlloc(win32.OSGMEM_MOVEABLE|win32.OSGMEM_ZEROINIT, int32(len(devmodeData)))
			var ptr int64 = win32.OSGlobalLock(hMem)
			win32.OSMoveMemoryOverload11(ptr, devmodeData, int32(len(devmodeData)))
			win32.OSGlobalUnlock(hMem)
			if pd.HDevMode != 0 {
				win32.OSGlobalFree(pd.HDevMode)
			}
			pd.HDevMode = hMem
		}
		var hMem int64 = pd.HDevMode
		if hMem == 0 {
			hMem = win32.OSGlobalAlloc(win32.OSGMEM_MOVEABLE|win32.OSGMEM_ZEROINIT, win32.DEVMODESizeof)
			pd.HDevMode = hMem
		}
		var ptr int64 = win32.OSGlobalLock(hMem)
		var devmode *win32.DEVMODE = win32.NewDEVMODE()
		win32.OSMoveMemoryOverload31(devmode, ptr, win32.DEVMODESizeof)
		if this.printerData.Name != "" {
			var max int32 = int32(math.Min(float64(jrt.StringLength(this.printerData.Name)), float64(win32.OSCCHDEVICENAME-1)))
			for i := int32(0); i < max; i++ {
				devmode.DmDeviceName[i] = utf16.Encode([]rune(this.printerData.Name))[i]
			}
		}
		devmode.DmFields |= win32.OSDM_ORIENTATION
		if this.printerData.Orientation == PrinterDataPORTRAIT {
			devmode.DmOrientation = win32.OSDMORIENT_PORTRAIT
		} else {
			devmode.DmOrientation = win32.OSDMORIENT_LANDSCAPE
		}
		if this.printerData.CopyCount != 1 {
			devmode.DmFields |= win32.OSDM_COPIES
			devmode.DmCopies = int16(this.printerData.CopyCount)
		}
		if this.printerData.Collate {
			devmode.DmFields |= win32.OSDM_COLLATE
			devmode.DmCollate = win32.OSDMCOLLATE_TRUE
		}
		if this.printerData.Duplex != DEFAULT {
			devmode.DmFields |= win32.OSDM_DUPLEX
			switch this.printerData.Duplex {
			case PrinterDataDUPLEX_SHORT_EDGE:
				devmode.DmDuplex = win32.OSDMDUP_HORIZONTAL
				break
			case PrinterDataDUPLEX_LONG_EDGE:
				devmode.DmDuplex = win32.OSDMDUP_VERTICAL
				break
			default:
				devmode.DmDuplex = win32.OSDMDUP_SIMPLEX
			}
		}
		win32.OSMoveMemoryOverload15(ptr, devmode, win32.DEVMODESizeof)
		win32.OSGlobalUnlock(hMem)
		pd.Flags = win32.OSPD_USEDEVMODECOPIESANDCOLLATE
		if this.printerData.PrintToFile {
			pd.Flags |= win32.OSPD_PRINTTOFILE
		}
		switch this.printerData.Scope {
		case PrinterDataPAGE_RANGE:
			pd.Flags |= win32.OSPD_PAGENUMS
			break
		case PrinterDataSELECTION:
			pd.Flags |= win32.OSPD_SELECTION
			break
		default:
			pd.Flags |= win32.OSPD_ALLPAGES
		}
		pd.NMinPage = int16(1)
		pd.NMaxPage = int16(-1)
		pd.NFromPage = int16(int32(math.Min(float64(0xFFFF), float64(int32(math.Max(float64(1), float64(this.printerData.StartPage)))))))
		pd.NToPage = int16(int32(math.Min(float64(0xFFFF), float64(int32(math.Max(float64(1), float64(this.printerData.EndPage)))))))
		var shells []*Shell = display.GetShells()
		if (this.GetStyle() & (APPLICATION_MODAL | SYSTEM_MODAL)) != 0 {
			for i := int32(0); i < int32(len(shells)); i++ {
				if shells[i].impl.isEnabled_() && upcastShellToControl(shells[i]) != parent {
					shells[i].impl.setEnabled_(false)
				} else {
					shells[i] = nil
				}
			}
		}
		var key string = "org.eclipse.swt.internal.win32.runMessagesInIdle"
		var oldValue any = display.GetData(key)
		display.SetData(key, true)
		display.SetData(externalLoopKey, true)
		display.SendPreExternalEventDispatchEvent()
		success = win32.OSPrintDlg(pd)
		display.SetData(externalLoopKey, false)
		display.SendPostExternalEventDispatchEvent()
		display.SetData(key, oldValue)
		if (this.GetStyle() & (APPLICATION_MODAL | SYSTEM_MODAL)) != 0 {
			for _, shell := range shells {
				if shell != (nil) && !shell.IsDisposed() {
					shell.impl.setEnabled_(true)
				}
			}
		}
		if success {
			hMem = pd.HDevNames
			var size int32 = win32.OSGlobalSize(hMem) / win32.TCHARSizeof * win32.TCHARSizeof
			ptr = win32.OSGlobalLock(hMem)
			var offsets []int16 = make([]int16, 4)
			win32.OSMoveMemoryOverload10(offsets, ptr, 2*int32(len(offsets)))
			var buffer []uint16 = make([]uint16, size)
			win32.OSMoveMemoryOverload2(buffer, ptr, size)
			win32.OSGlobalUnlock(hMem)
			var driverOffset int32 = int32(offsets[0])
			var i int32 = 0
			for driverOffset+i < size {
				if int32(buffer[driverOffset+i]) == 0 {
					break
				}
				i++
			}
			var driver string = string(utf16.Decode(buffer[driverOffset : driverOffset+i]))
			var deviceOffset int32 = int32(offsets[1])
			i = 0
			for deviceOffset+i < size {
				if int32(buffer[deviceOffset+i]) == 0 {
					break
				}
				i++
			}
			var device string = string(utf16.Decode(buffer[deviceOffset : deviceOffset+i]))
			data = NewPrinterDataDriverName(driver, device)
			if (pd.Flags & win32.OSPD_PAGENUMS) != 0 {
				data.Scope = PrinterDataPAGE_RANGE
				data.StartPage = int32(pd.NFromPage) & 0xFFFF
				data.EndPage = int32(pd.NToPage) & 0xFFFF
			} else {
				if (pd.Flags & win32.OSPD_SELECTION) != 0 {
					data.Scope = PrinterDataSELECTION
				}
			}
			data.PrintToFile = (pd.Flags & win32.OSPD_PRINTTOFILE) != 0
			if data.PrintToFile {
				data.FileName = this.printerData.FileName
			}
			data.CopyCount = int32(pd.NCopies)
			data.Collate = (pd.Flags & win32.OSPD_COLLATE) != 0
			hMem = pd.HDevMode
			size = win32.OSGlobalSize(hMem)
			ptr = win32.OSGlobalLock(hMem)
			data.otherData = make([]int8, size)
			win32.OSMoveMemoryOverload3(data.otherData, ptr, size)
			devmode = win32.NewDEVMODE()
			win32.OSMoveMemoryOverload31(devmode, ptr, win32.DEVMODESizeof)
			if (devmode.DmFields & win32.OSDM_ORIENTATION) != 0 {
				var dmOrientation int32 = int32(devmode.DmOrientation)
				if dmOrientation == int32(win32.OSDMORIENT_LANDSCAPE) {
					data.Orientation = PrinterDataLANDSCAPE
				} else {
					data.Orientation = PrinterDataPORTRAIT
				}
			}
			if (devmode.DmFields & win32.OSDM_DUPLEX) != 0 {
				var dmDuplex int16 = devmode.DmDuplex
				if int32(dmDuplex) == int32(win32.OSDMDUP_SIMPLEX) {
					data.Duplex = PrinterDataDUPLEX_NONE
				} else {
					var cond675 int32
					if int32(dmDuplex) == int32(win32.OSDMDUP_HORIZONTAL) {
						cond675 = PrinterDataDUPLEX_SHORT_EDGE
					} else {
						cond675 = PrinterDataDUPLEX_LONG_EDGE
					}
					data.Duplex = cond675
				}
			}
			win32.OSGlobalUnlock(hMem)
			this.printerData = data
		}
	}
	if pd.HDevNames != 0 {
		win32.OSGlobalFree(pd.HDevNames)
		pd.HDevNames = int64(0)
	}
	if pd.HDevMode != 0 {
		win32.OSGlobalFree(pd.HDevMode)
		pd.HDevMode = int64(0)
	}
	if hwndParent != hwndOwner {
		if enabled {
			win32.OSEnableWindow(hwndParent, true)
		}
		win32.OSSetActiveWindow(hwndParent)
		win32.OSDestroyWindow(hwndOwner)
	}
	return data
}

func PrintDialogCheckBits(style int32, int0 int32, int1 int32, int2 int32, int3 int32, int4 int32, int5 int32) int32 {
	var mask int32 = int0 | int1 | int2 | int3 | int4 | int5
	if (style & mask) == 0 {
		style |= int0
	}
	if (style & int0) != 0 {
		style = (style & ^mask) | int0
	}
	if (style & int1) != 0 {
		style = (style & ^mask) | int1
	}
	if (style & int2) != 0 {
		style = (style & ^mask) | int2
	}
	if (style & int3) != 0 {
		style = (style & ^mask) | int3
	}
	if (style & int4) != 0 {
		style = (style & ^mask) | int4
	}
	if (style & int5) != 0 {
		style = (style & ^mask) | int5
	}
	return style
}

func PrintDialogCheckStyle(parentLike ShellLike, style int32) int32 {
	var parent *Shell
	if parentLike != nil {
		parent = parentLike.AsShell()
	}
	_ = parent
	var mask int32 = PRIMARY_MODAL | APPLICATION_MODAL | SYSTEM_MODAL
	if (style & SHEET) != 0 {
		style &= ^SHEET
		if (style & mask) == 0 {
			var cond676 int32
			if parent == (nil) {
				cond676 = APPLICATION_MODAL
			} else {
				cond676 = PRIMARY_MODAL
			}
			style |= cond676
		}
	}
	if (style & mask) == 0 {
		style |= APPLICATION_MODAL
	}
	style &= ^MIRRORED
	if (style & (LEFT_TO_RIGHT | RIGHT_TO_LEFT)) == 0 {
		if parent != (nil) {
			if (parent.impl.getStyle_() & LEFT_TO_RIGHT) != 0 {
				style |= LEFT_TO_RIGHT
			}
			if (parent.impl.getStyle_() & RIGHT_TO_LEFT) != 0 {
				style |= RIGHT_TO_LEFT
			}
		}
	}
	return PrintDialogCheckBits(style, LEFT_TO_RIGHT, RIGHT_TO_LEFT, 0, 0, 0, 0)
}
