// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/MenuItem.java @ af630a9093. DO NOT EDIT.

package swt

import (
	"fmt"
	"github.com/haiodo/gowt/internal/jrt"
	"github.com/haiodo/gowt/internal/win32"
	"math"
	"os"
	"strconv"
	"strings"
)

type MenuItem struct {
	Item
	parent          *Menu
	menu            *Menu
	hBitmap         int64
	imageSelected   *Image
	hBitmapSelected int64
	id              int32
	accelerator     int32
	userId          int32
	itemToolTip     *ToolTip
}

func (this *MenuItem) AsMenuItem() *MenuItem { return this }

type MenuItemLike interface {
	AsMenuItem() *MenuItem
}

const MenuItemMARGIN_WIDTH int32 = 1

const MenuItemMARGIN_HEIGHT int32 = 1

const MenuItemLEFT_TEXT_MARGIN int32 = 7

const MenuItemIMAGE_TEXT_GAP int32 = 3

const MenuItemWINDOWS_OVERHEAD int32 = 6

var MenuItemCUSTOM_SELECTION_IMAGE int32 = func() (r int32) {
	defer func() {
		if e := recover(); e != nil {
			fmt.Fprintln(os.Stderr, "gowt: deferred init MenuItemCUSTOM_SELECTION_IMAGE:", e)
		}
	}()
	var cond1 int32
	if win32.OsVersionIS_WIN11_21H2 {
		cond1 = jrt.Cast[int32](func() int32 {
			_ = []any{"org.eclipse.swt.internal.win32.menu.customSelectionImage", 2}
			panic("j2go: unresolved call getInteger")
		}())
	} else {
		cond1 = 0
	}
	r = cond1
	return
}()

func NewMenuItem(parentLike MenuLike, style int32) *MenuItem {
	var parent *Menu
	if parentLike != nil {
		parent = parentLike.AsMenu()
	}
	_ = parent
	this := &MenuItem{}
	this.impl = this
	this.initMenuItem(parent, style)
	return this
}

func (this *MenuItem) initMenuItem(parent *Menu, style int32) {
	this.Item.initItem(upcastMenuToWidget(parent), MenuItemCheckStyle(style))
	this.parent = parent
	parent.CreateItem(this, parent.GetItemCount())
}

func NewMenuItemParentStyleIndex(parentLike MenuLike, style int32, index int32) *MenuItem {
	var parent *Menu
	if parentLike != nil {
		parent = parentLike.AsMenu()
	}
	_ = parent
	this := &MenuItem{}
	this.impl = this
	this.initMenuItemParentStyleIndex(parent, style, index)
	return this
}

func (this *MenuItem) initMenuItemParentStyleIndex(parent *Menu, style int32, index int32) {
	this.Item.initItem(upcastMenuToWidget(parent), MenuItemCheckStyle(style))
	this.parent = parent
	parent.CreateItem(this, index)
}

func (this *MenuItem) AddArmListener(listener ArmListener) {
	this.AddTypedListener(listener, []int32{Arm})
}

func (this *MenuItem) AddHelpListener(listener HelpListener) {
	this.AddTypedListener(listener, []int32{Help})
}

func (this *MenuItem) AddSelectionListener(listener SelectionListener) {
	this.AddTypedListener(listener, []int32{Selection, DefaultSelection})
}

func (this *MenuItem) checkSubclass_() {
	if !this.IsValidSubclass() {
		this.Error(ERROR_INVALID_SUBCLASS)
	}
}

func (this *MenuItem) destroyWidget_() {
	this.parent.DestroyItem(this)
	this.impl.releaseHandle_()
}

func (this *MenuItem) FillAccel(accel *win32.ACCEL) bool {
	accel.FVirt = int8(0)
	accel.Key = int16(accel.FVirt)
	accel.Cmd = accel.Key
	if this.accelerator == 0 || !this.GetEnabled() {
		return false
	}
	if (this.accelerator & COMMAND) != 0 {
		return false
	}
	var fVirt int32 = win32.OSFVIRTKEY
	var key int32 = this.accelerator & KEY_MASK
	var vKey int32 = DisplayUntranslateKey(key)
	if vKey != 0 {
		key = vKey
	} else {
		switch key {
		case 27:
			key = win32.OSVK_ESCAPE
			break
		case 127:
			key = win32.OSVK_DELETE
			break
		default:
			{
				if key == 0 {
					return false
				}
				vKey = int32(win32.OSVkKeyScan(int16(key)))
				if vKey == -1 {
					if key != int32(win32.OSCharUpper(int64(win32.OSLOWORD(int64(key))))) {
						fVirt = 0
					}
				} else {
					key = vKey & 0xFF
				}
			}
		}
	}
	accel.Key = int16(key)
	accel.Cmd = int16(this.id)
	accel.FVirt = int8(fVirt)
	if (this.accelerator & ALT) != 0 {
		accel.FVirt |= int8(win32.OSFALT)
	}
	if (this.accelerator & SHIFT) != 0 {
		accel.FVirt |= int8(win32.OSFSHIFT)
	}
	if (this.accelerator & CONTROL) != 0 {
		accel.FVirt |= int8(win32.OSFCONTROL)
	}
	return true
}

func (this *MenuItem) FixMenus(newParentLike DecorationsLike) {
	var newParent *Decorations
	if newParentLike != nil {
		newParent = newParentLike.AsDecorations()
	}
	_ = newParent
	this.NativeZoom = newParent.NativeZoom
	if this.menu != (nil) && !this.menu.IsDisposed() && !newParent.IsDisposed() {
		this.menu.FixMenus(newParent)
	}
}

func (this *MenuItem) GetAccelerator() int32 {
	this.CheckWidget()
	return this.accelerator
}

func (this *MenuItem) GetBounds() *Rectangle {
	this.CheckWidget()
	var index int32 = this.parent.IndexOf(this)
	if index == -1 {
		return NewRectangle(0, 0, 0, 0)
	}
	if (this.parent.style & BAR) != 0 {
		var shell *Decorations = this.parent.parent
		if shell.menuBar != this.parent {
			return NewRectangle(0, 0, 0, 0)
		}
		var hwndShell int64 = shell.Handle
		var info1 *win32.MENUBARINFO = win32.NewMENUBARINFO()
		info1.CbSize = win32.MENUBARINFOSizeof
		if !win32.OSGetMenuBarInfo(hwndShell, win32.OSOBJID_MENU, 1, info1) {
			return NewRectangle(0, 0, 0, 0)
		}
		var info2 *win32.MENUBARINFO = win32.NewMENUBARINFO()
		info2.CbSize = win32.MENUBARINFOSizeof
		if !win32.OSGetMenuBarInfo(hwndShell, win32.OSOBJID_MENU, index+1, info2) {
			return NewRectangle(0, 0, 0, 0)
		}
		var x int32 = info2.Left - info1.Left
		var y int32 = info2.Top - info1.Top
		var width int32 = info2.Right - info2.Left
		var height int32 = info2.Bottom - info2.Top
		return NewRectangle(x, y, width, height)
	} else {
		var hMenu int64 = this.parent.Handle
		var rect1 *win32.RECT = win32.NewRECT()
		if !win32.OSGetMenuItemRect(int64(0), hMenu, 0, rect1) {
			return NewRectangle(0, 0, 0, 0)
		}
		var rect2 *win32.RECT = win32.NewRECT()
		if !win32.OSGetMenuItemRect(int64(0), hMenu, index, rect2) {
			return NewRectangle(0, 0, 0, 0)
		}
		var x int32 = rect2.Left - rect1.Left + 2
		var y int32 = rect2.Top - rect1.Top + 2
		var width int32 = rect2.Right - rect2.Left
		var height int32 = rect2.Bottom - rect2.Top
		return NewRectangle(x, y, width, height)
	}
}

func (this *MenuItem) GetEnabled() bool {
	this.CheckWidget()
	if (this.style & SEPARATOR) != 0 {
		return (this.state & WidgetDISABLED) == 0
	}
	var hMenu int64 = this.parent.Handle
	var info *win32.MENUITEMINFO = win32.NewMENUITEMINFO()
	info.CbSize = win32.MENUITEMINFOSizeof
	info.FMask = win32.OSMIIM_STATE
	var success bool = win32.OSGetMenuItemInfo(hMenu, this.id, false, info)
	if !success {
		this.Error(ERROR_CANNOT_GET_ENABLED)
	}
	return (info.FState & (win32.OSMFS_DISABLED | win32.OSMFS_GRAYED)) == 0
}

func (this *MenuItem) GetID() int32 {
	this.CheckWidget()
	return this.userId
}

func (this *MenuItem) getMenu_() *Menu {
	this.CheckWidget()
	return this.menu
}

func (this *MenuItem) getNameText_() string {
	if (this.style & SEPARATOR) != 0 {
		return "|"
	}
	return this.Item.getNameText_()
}

func (this *MenuItem) GetParent() *Menu {
	this.CheckWidget()
	return this.parent
}

func (this *MenuItem) GetSelection() bool {
	this.CheckWidget()
	if (this.style & (CHECK | RADIO)) == 0 {
		return false
	}
	var hMenu int64 = this.parent.Handle
	var info *win32.MENUITEMINFO = win32.NewMENUITEMINFO()
	info.CbSize = win32.MENUITEMINFOSizeof
	info.FMask = win32.OSMIIM_STATE
	var success bool = win32.OSGetMenuItemInfo(hMenu, this.id, false, info)
	if !success {
		this.Error(ERROR_CANNOT_GET_SELECTION)
	}
	return (info.FState & win32.OSMFS_CHECKED) != 0
}

func (this *MenuItem) GetToolTipText() string {
	this.CheckWidget()
	var cond2 string
	if this.itemToolTip == (nil) || this.itemToolTip.IsDisposed() {
		cond2 = ""
	} else {
		cond2 = this.itemToolTip.GetMessage()
	}
	return cond2
}

func (this *MenuItem) HideToolTip() {
	if this.itemToolTip == (nil) || this.itemToolTip.IsDisposed() {
		return
	}
	this.itemToolTip.SetVisible(false)
}

func (this *MenuItem) IsEnabled() bool {
	return this.GetEnabled() && this.parent.IsEnabled()
}

func (this *MenuItem) releaseChildren_(destroy bool) {
	if this.menu != (nil) {
		this.menu.impl.release_(false)
		this.menu = nil
	}
	this.Item.releaseChildren_(destroy)
}

func (this *MenuItem) releaseHandle_() {
	this.Item.releaseHandle_()
	this.parent = nil
	this.id = -1
}

func (this *MenuItem) releaseParent_() {
	this.Item.releaseParent_()
	if this.menu != (nil) {
		this.menu.impl.dispose_()
	}
	this.menu = nil
}

func (this *MenuItem) releaseWidget_() {
	this.Item.releaseWidget_()
	if this.hBitmap != 0 {
		win32.OSDeleteObject(this.hBitmap)
	}
	this.hBitmap = int64(0)
	if this.hBitmapSelected != 0 {
		win32.OSDeleteObject(this.hBitmapSelected)
	}
	this.hBitmapSelected = int64(0)
	if this.imageSelected != (nil) {
		this.imageSelected.impl.dispose_()
		this.imageSelected = nil
	}
	if this.accelerator != 0 {
		this.parent.DestroyAccelerators()
	}
	this.accelerator = 0
	if this.itemToolTip != (nil) && !this.itemToolTip.IsDisposed() {
		this.itemToolTip.SetVisible(false)
		this.itemToolTip.impl.dispose_()
		this.itemToolTip = nil
	}
	this.display.RemoveMenuItem(this)
}

func (this *MenuItem) RemoveArmListener(listener ArmListener) {
	this.CheckWidget()
	if listener == (nil) {
		this.Error(ERROR_NULL_ARGUMENT)
	}
	if this.eventTable == (nil) {
		return
	}
	this.eventTable.UnhookEventTypeListener(Arm, listener)
}

func (this *MenuItem) RemoveHelpListener(listener HelpListener) {
	this.CheckWidget()
	if listener == (nil) {
		this.Error(ERROR_NULL_ARGUMENT)
	}
	if this.eventTable == (nil) {
		return
	}
	this.eventTable.UnhookEventTypeListener(Help, listener)
}

func (this *MenuItem) RemoveSelectionListener(listener SelectionListener) {
	this.CheckWidget()
	if listener == (nil) {
		this.Error(ERROR_NULL_ARGUMENT)
	}
	if this.eventTable == (nil) {
		return
	}
	this.eventTable.UnhookEventTypeListener(Selection, listener)
	this.eventTable.UnhookEventTypeListener(DefaultSelection, listener)
}

func (this *MenuItem) reskinChildren_(flags int32) {
	if this.menu != (nil) {
		this.menu.impl.reskin_(flags)
	}
	this.Item.reskinChildren_(flags)
}

func (this *MenuItem) SelectRadio() {
	var index int32 = 0
	var items []*MenuItem = this.parent.GetItems()
	for index < int32(len(items)) && items[index] != this {
		index++
	}
	var i int32 = index - 1
	for i >= 0 && items[i].SetRadioSelection(false) {
		i--
	}
	var j int32 = index + 1
	for j < int32(len(items)) && items[j].SetRadioSelection(false) {
		j++
	}
	this.SetSelection(true)
}

func (this *MenuItem) SetAccelerator(accelerator int32) {
	this.CheckWidget()
	if this.accelerator == accelerator {
		return
	}
	this.accelerator = accelerator
	this.parent.DestroyAccelerators()
}

func (this *MenuItem) SetEnabled(enabled bool) {
	this.CheckWidget()
	if (this.style & SEPARATOR) != 0 {
		if enabled {
			this.state &= ^WidgetDISABLED
		} else {
			this.state |= WidgetDISABLED
		}
	}
	var hMenu int64 = this.parent.Handle
	var info *win32.MENUITEMINFO = win32.NewMENUITEMINFO()
	info.CbSize = win32.MENUITEMINFOSizeof
	info.FMask = win32.OSMIIM_STATE
	var success bool = win32.OSGetMenuItemInfo(hMenu, this.id, false, info)
	if !success {
		var error_ int32 = win32.OSGetLastError()
		ErrorCodeThrowableDetail(ERROR_CANNOT_SET_ENABLED, nil, fmt.Sprintf(" [GetLastError=0x%s]", strconv.FormatUint(uint64(uint32(error_)), 16)))
	}
	var bits int32 = win32.OSMFS_DISABLED | win32.OSMFS_GRAYED
	if enabled {
		if (info.FState & bits) == 0 {
			return
		}
		info.FState &= ^bits
	} else {
		if (info.FState & bits) == bits {
			return
		}
		info.FState |= bits
	}
	success = win32.OSSetMenuItemInfo(hMenu, this.id, false, info)
	if !success {
		success = this.id == win32.OSGetMenuDefaultItem(hMenu, win32.OSMF_BYCOMMAND, win32.OSGMDI_USEDISABLED)
		if !success {
			var error_ int32 = win32.OSGetLastError()
			ErrorCodeThrowableDetail(ERROR_CANNOT_SET_ENABLED, nil, fmt.Sprintf(" [GetLastError=0x%s]", strconv.FormatUint(uint64(uint32(error_)), 16)))
		}
	}
	this.parent.DestroyAccelerators()
	this.parent.Redraw()
}

func (this *MenuItem) SetID(id int32) {
	this.CheckWidget()
	if id < 0 {
		this.Error(ERROR_INVALID_ARGUMENT)
	}
	this.userId = id
}

func (this *MenuItem) setImageOnItem_(image *Image) {
	this.CheckWidget()
	if this.image == image {
		return
	}
	if (this.style & SEPARATOR) != 0 {
		return
	}
	this.Item.setImageOnItem_(image)
	if this.imageSelected != (nil) {
		this.imageSelected.impl.dispose_()
		this.imageSelected = nil
	}
	if (this.style&(CHECK|RADIO)) != 0 && MenuItemCUSTOM_SELECTION_IMAGE > 1 && image != (nil) && this.GetSelection() {
		this.InitCustomSelectedImage()
	}
	this.UpdateImage()
}

func (this *MenuItem) UpdateImage() {
	var info *win32.MENUITEMINFO = win32.NewMENUITEMINFO()
	info.CbSize = win32.MENUITEMINFOSizeof
	info.FMask = win32.OSMIIM_BITMAP
	if this.parent.NeedsMenuCallback() {
		info.HbmpItem = win32.OSHBMMENU_CALLBACK
	} else {
		if this.hBitmap != 0 {
			win32.OSDeleteObject(this.hBitmap)
		}
		this.hBitmap = this.GetMenuItemIconBitmapHandle(this.image)
		if (this.style&(CHECK|RADIO)) != 0 && MenuItemCUSTOM_SELECTION_IMAGE > 0 {
			info.FMask |= win32.OSMIIM_CHECKMARKS
			info.HbmpUnchecked = this.hBitmap
			info.HbmpChecked = this.GetMenuItemIconSelectedBitmapHandle()
		} else {
			info.HbmpItem = this.hBitmap
		}
	}
	var hMenu int64 = this.parent.Handle
	win32.OSSetMenuItemInfo(hMenu, this.id, false, info)
	this.parent.Redraw()
}

func (this *MenuItem) InitCustomSelectedImage() {
	var image *Image = this.image
	if image == (nil) {
		return
	}
	var imageBounds *Rectangle = image.GetBounds()
	var cond3 *Color
	if this.display.menuBarForegroundPixel != -1 {
		cond3 = ColorWin32_new(upcastDisplayToDevice(this.display), this.display.menuBarForegroundPixel)
	} else {
		cond3 = this.parent.GetForeground()
	}
	var foregroundColor *Color = this.IncreaseContrast(cond3)
	var cond4 *Color
	if this.display.menuBarBackgroundPixel != -1 {
		cond4 = ColorWin32_new(upcastDisplayToDevice(this.display), this.display.menuBarBackgroundPixel)
	} else {
		cond4 = this.parent.GetBackground()
	}
	var backgroundColor *Color = this.IncreaseContrast(cond4)
	anon5 := &MenuItemAnon1{}
	anon5.fnGetGcStyle = func() int32 {
		return TRANSPARENT
	}
	anon5.fnDrawOn = func(gc *GC, imageWidth int32, imageHeight int32) {
		gc.SetAdvanced(true)
		gc.DrawImage(image, imageWidth-imageBounds.Width, (imageHeight-imageBounds.Height)/2)
		gc.SetAntialias(ON)
		var x int32 = imageWidth - 16
		var y int32 = imageHeight/2 - 8
		if (this.style & CHECK) != 0 {
			this.DrawCheck(gc, foregroundColor, backgroundColor, x, y)
		} else {
			this.DrawRadio(gc, foregroundColor, backgroundColor, x, y)
		}
	}
	var drawer ImageGcDrawer = anon5
	this.imageSelected = NewImageDeviceImageGcDrawerWidthHeight(image.impl.getDevice_(), drawer, int32(math.Max(float64(imageBounds.Width), float64(16))), int32(math.Max(float64(imageBounds.Height), float64(16))))
}

func (this *MenuItem) DrawCheck(gcLike GCLike, foregroundColorLike ColorLike, backgroundColorLike ColorLike, x int32, y int32) {
	var gc *GC
	if gcLike != nil {
		gc = gcLike.AsGC()
	}
	_ = gc
	var foregroundColor *Color
	if foregroundColorLike != nil {
		foregroundColor = foregroundColorLike.AsColor()
	}
	_ = foregroundColor
	var backgroundColor *Color
	if backgroundColorLike != nil {
		backgroundColor = backgroundColorLike.AsColor()
	}
	_ = backgroundColor
	var points []int32 = []int32{x + 4, y + 10, x + 6, y + 12, x + 12, y + 6}
	gc.SetLineStyle(LINE_SOLID)
	gc.SetForeground(backgroundColor)
	gc.SetLineCap(CAP_ROUND)
	gc.SetLineJoin(JOIN_ROUND)
	gc.SetAlpha(127)
	gc.SetLineWidth(6)
	gc.DrawPolyline(points)
	gc.SetLineJoin(JOIN_MITER)
	gc.SetAlpha(255)
	gc.SetLineWidth(3)
	gc.DrawPolyline(points)
	gc.SetForeground(foregroundColor)
	gc.SetLineWidth(1)
	gc.SetLineCap(CAP_FLAT)
	gc.DrawPolyline(points)
}

func (this *MenuItem) DrawRadio(gcLike GCLike, foregroundColorLike ColorLike, backgroundColorLike ColorLike, x int32, y int32) {
	var gc *GC
	if gcLike != nil {
		gc = gcLike.AsGC()
	}
	_ = gc
	var foregroundColor *Color
	if foregroundColorLike != nil {
		foregroundColor = foregroundColorLike.AsColor()
	}
	_ = foregroundColor
	var backgroundColor *Color
	if backgroundColorLike != nil {
		backgroundColor = backgroundColorLike.AsColor()
	}
	_ = backgroundColor
	gc.SetBackground(backgroundColor)
	gc.SetAlpha(127)
	gc.FillOval(x+4, y+5, 8, 8)
	gc.SetAlpha(255)
	gc.FillOval(x+5, y+6, 6, 6)
	gc.SetBackground(foregroundColor)
	gc.FillOval(x+6, y+7, 4, 4)
}

func (this *MenuItem) IncreaseContrast(colorLike ColorLike) *Color {
	var color *Color
	if colorLike != nil {
		color = colorLike.AsColor()
	}
	_ = color
	var cond6 *Color
	if color.GetRed()+color.GetGreen()+color.GetBlue() > 127*3 {
		cond6 = this.display.impl.getSystemColor_(COLOR_WHITE)
	} else {
		cond6 = color
	}
	return cond6
}

func (this *MenuItem) GetMenuItemIconBitmapHandle(imageLike ImageLike) int64 {
	var image *Image
	if imageLike != nil {
		image = imageLike.AsImage()
	}
	_ = image
	if image == (nil) {
		return int64(0)
	}
	var zoom int32 = this.AdaptZoomForMenuItem(this.NativeZoom, image)
	return DisplayCreate32bitDIB(image, zoom)
}

func (this *MenuItem) GetMenuItemIconSelectedBitmapHandle() int64 {
	var image *Image = this.imageSelected
	if image == (nil) {
		return int64(0)
	}
	if this.hBitmapSelected != 0 {
		win32.OSDeleteObject(this.hBitmapSelected)
	}
	var zoom int32 = this.AdaptZoomForMenuItem(this.NativeZoom, image)
	cond7 := DisplayCreate32bitDIB(image, zoom)
	this.hBitmapSelected = cond7
	return cond7
}

func (this *MenuItem) AdaptZoomForMenuItem(currentZoom int32, imageLike ImageLike) int32 {
	var image *Image
	if imageLike != nil {
		image = imageLike.AsImage()
	}
	_ = image
	if !this.display.IsRescalingAtRuntime() {
		return DPIUtilGetZoomForAutoscaleProperty(currentZoom)
	}
	var primaryMonitorZoomAtAppStartUp int32 = Win32DPIUtilsGetPrimaryMonitorZoomAtStartup()
	if primaryMonitorZoomAtAppStartUp > currentZoom && MenuItemIsQuarterZoom(currentZoom) {
		return currentZoom - 25
	}
	if !MenuItemIsHalfZoom(primaryMonitorZoomAtAppStartUp) && MenuItemIsHalfZoom(currentZoom) {
		var expectedSize float64 = float64(this.impl.getSystemMetrics_(win32.OSSM_CYMENUCHECK))
		return int32(((expectedSize / float64(image.GetBounds().Height)) * 100))
	}
	return currentZoom
}

func (this *MenuItem) SetMenu(menuLike MenuLike) {
	var menu *Menu
	if menuLike != nil {
		menu = menuLike.AsMenu()
	}
	_ = menu
	this.CheckWidget()
	if (this.style & CASCADE) == 0 {
		this.Error(ERROR_MENUITEM_NOT_CASCADE)
	}
	if menu != (nil) {
		if menu.IsDisposed() {
			this.Error(ERROR_INVALID_ARGUMENT)
		}
		if (menu.style & DROP_DOWN) == 0 {
			this.Error(ERROR_MENU_NOT_DROP_DOWN)
		}
		if menu.parent != this.parent.parent {
			this.Error(ERROR_INVALID_PARENT)
		}
	}
	this.SetMenuMenuDispose(menu, false)
}

func (this *MenuItem) SetMenuMenuDispose(menuLike MenuLike, dispose bool) {
	var menu *Menu
	if menuLike != nil {
		menu = menuLike.AsMenu()
	}
	_ = menu
	var oldMenu *Menu = this.menu
	if oldMenu == menu {
		return
	}
	if oldMenu != (nil) {
		oldMenu.cascade = nil
	}
	this.menu = menu
	var hMenu int64 = this.parent.Handle
	var info *win32.MENUITEMINFO = win32.NewMENUITEMINFO()
	info.CbSize = win32.MENUITEMINFOSizeof
	info.FMask = win32.OSMIIM_DATA
	var index int32 = 0
	for win32.OSGetMenuItemInfo(hMenu, index, true, info) {
		if info.DwItemData == int64(this.id) {
			break
		}
		index++
	}
	if info.DwItemData != int64(this.id) {
		return
	}
	var cch int32 = 128
	var hHeap int64 = win32.OSGetProcessHeap()
	var byteCount int32 = cch * 2
	var pszText int64 = win32.OSHeapAlloc(hHeap, win32.OSHEAP_ZERO_MEMORY, byteCount)
	info.FMask = win32.OSMIIM_STATE | win32.OSMIIM_ID | win32.OSMIIM_DATA
	info.FMask |= win32.OSMIIM_BITMAP | win32.OSMIIM_STRING
	info.DwTypeData = pszText
	info.Cch = cch
	var success bool = win32.OSGetMenuItemInfo(hMenu, index, true, info)
	if menu != (nil) {
		menu.cascade = this
		info.FMask |= win32.OSMIIM_SUBMENU
		info.HSubMenu = menu.Handle
	}
	if dispose || oldMenu == (nil) {
		success = win32.OSSetMenuItemInfo(hMenu, index, true, info)
	} else {
		win32.OSRemoveMenu(hMenu, index, win32.OSMF_BYPOSITION)
		success = win32.OSInsertMenuItem(hMenu, index, true, info)
	}
	if pszText != 0 {
		win32.OSHeapFree(hHeap, 0, pszText)
	}
	if !success {
		var error_ int32 = win32.OSGetLastError()
		ErrorCodeThrowableDetail(ERROR_CANNOT_SET_MENU, nil, fmt.Sprintf(" [GetLastError=0x%s]", strconv.FormatUint(uint64(uint32(error_)), 16)))
	}
	this.parent.DestroyAccelerators()
}

func (this *MenuItem) SetRadioSelection(value bool) bool {
	if (this.style & RADIO) == 0 {
		return false
	}
	if this.GetSelection() != value {
		this.SetSelection(value)
		this.SendSelectionEvent(Selection)
	}
	return true
}

func (this *MenuItem) SetOrientation(orientation int32) {
	var hMenu int64 = this.parent.Handle
	var info *win32.MENUITEMINFO = win32.NewMENUITEMINFO()
	info.CbSize = win32.MENUITEMINFOSizeof
	info.FMask = win32.OSMIIM_FTYPE
	info.FType = this.WidgetStyle()
	win32.OSSetMenuItemInfo(hMenu, this.id, false, info)
	if this.menu != (nil) {
		this.menu._setOrientation(orientation)
	}
}

func (this *MenuItem) SetSelection(selected bool) {
	this.CheckWidget()
	if (this.style & (CHECK | RADIO)) == 0 {
		return
	}
	var hMenu int64 = this.parent.Handle
	var info *win32.MENUITEMINFO = win32.NewMENUITEMINFO()
	info.CbSize = win32.MENUITEMINFOSizeof
	info.FMask = win32.OSMIIM_STATE
	var success bool = win32.OSGetMenuItemInfo(hMenu, this.id, false, info)
	if !success {
		this.Error(ERROR_CANNOT_SET_SELECTION)
	}
	info.FState &= ^win32.OSMFS_CHECKED
	if selected {
		info.FState |= win32.OSMFS_CHECKED
	}
	if selected && MenuItemCUSTOM_SELECTION_IMAGE > 1 && this.hBitmap != 0 && this.imageSelected == (nil) {
		this.InitCustomSelectedImage()
		info.FMask |= win32.OSMIIM_CHECKMARKS
		info.HbmpUnchecked = this.hBitmap
		info.HbmpChecked = this.GetMenuItemIconSelectedBitmapHandle()
	}
	success = win32.OSSetMenuItemInfo(hMenu, this.id, false, info)
	if !success {
		success = this.id == win32.OSGetMenuDefaultItem(hMenu, win32.OSMF_BYCOMMAND, win32.OSGMDI_USEDISABLED)
		if !success {
			var error_ int32 = win32.OSGetLastError()
			ErrorCodeThrowableDetail(ERROR_CANNOT_SET_SELECTION, nil, fmt.Sprintf(" [GetLastError=0x%s]", strconv.FormatUint(uint64(uint32(error_)), 16)))
		}
	}
	this.parent.Redraw()
}

func (this *MenuItem) setText_(string_ string) {
	this.CheckWidget()
	if string_ == jrt.NullString {
		this.Error(ERROR_NULL_ARGUMENT)
	}
	if (this.style & SEPARATOR) != 0 {
		return
	}
	if this.text == string_ {
		return
	}
	this.Item.setText_(string_)
	var hHeap int64 = win32.OSGetProcessHeap()
	var pszText int64 = int64(0)
	var info *win32.MENUITEMINFO = win32.NewMENUITEMINFO()
	info.CbSize = win32.MENUITEMINFOSizeof
	var hMenu int64 = this.parent.Handle
	var buffer *win32.TCHAR = win32.NewTCHARStringTerminate(string_, true)
	var byteCount int32 = buffer.Length() * win32.TCHARSizeof
	pszText = win32.OSHeapAlloc(hHeap, win32.OSHEAP_ZERO_MEMORY, byteCount)
	win32.OSMoveMemory(pszText, buffer, byteCount)
	info.FMask = win32.OSMIIM_STRING
	info.DwTypeData = pszText
	var success bool = win32.OSSetMenuItemInfo(hMenu, this.id, false, info)
	if pszText != 0 {
		win32.OSHeapFree(hHeap, 0, pszText)
	}
	if !success {
		var error_ int32 = win32.OSGetLastError()
		ErrorCodeThrowableDetail(ERROR_CANNOT_SET_TEXT, nil, fmt.Sprintf(" [GetLastError=0x%s]", strconv.FormatUint(uint64(uint32(error_)), 16)))
	}
	this.parent.Redraw()
}

func (this *MenuItem) SetToolTipText(toolTip string) {
	this.CheckWidget()
	if toolTip == "" && this.itemToolTip != (nil) {
		if !this.itemToolTip.IsDisposed() {
			this.itemToolTip.SetVisible(false)
			this.itemToolTip.impl.dispose_()
		}
		this.itemToolTip = nil
	}
	if toolTip == "" || jrt.StringLength(strings.TrimSpace(toolTip)) == 0 || (this.itemToolTip != (nil) && !this.itemToolTip.IsDisposed() && (toolTip == this.itemToolTip.GetMessage())) {
		return
	}
	if this.itemToolTip != (nil) {
		this.itemToolTip.impl.dispose_()
	}
	this.itemToolTip = upcastMenuItem_MenuItemToolTipToToolTip(NewMenuItemMenuItemToolTip(this.GetParent().GetShell()))
	this.itemToolTip.SetMessage(toolTip)
	this.itemToolTip.SetVisible(false)
}

func (this *MenuItem) ShowTooltip(x int32, y int32) {
	if this.itemToolTip == (nil) || this.itemToolTip.IsDisposed() {
		return
	}
	this.itemToolTip.SetLocationInPixels(x, y)
	this.itemToolTip.SetVisible(true)
}

func (this *MenuItem) WidgetStyle() int32 {
	var bits int32 = 0
	var shell *Decorations = this.parent.parent
	if (shell.style & MIRRORED) != 0 {
		if (this.parent.style & LEFT_TO_RIGHT) != 0 {
			bits |= win32.OSMFT_RIGHTJUSTIFY | win32.OSMFT_RIGHTORDER
		}
	} else {
		if (this.parent.style & RIGHT_TO_LEFT) != 0 {
			bits |= win32.OSMFT_RIGHTJUSTIFY | win32.OSMFT_RIGHTORDER
		}
	}
	if (this.style & SEPARATOR) != 0 {
		return bits | win32.OSMFT_SEPARATOR
	}
	if (this.style & RADIO) != 0 {
		return bits | win32.OSMFT_RADIOCHECK
	}
	return bits | win32.OSMFT_STRING
}

func (this *MenuItem) WmCommandChild(wParam int64, lParam int64) *win32.LRESULT {
	if (this.style & CHECK) != 0 {
		this.SetSelection(!this.GetSelection())
	} else {
		if (this.style & RADIO) != 0 {
			if (this.parent.impl.getStyle_() & NO_RADIO_GROUP) != 0 {
				this.SetSelection(!this.GetSelection())
			} else {
				this.SelectRadio()
			}
		}
	}
	this.SendSelectionEvent(Selection)
	return nil
}

func (this *MenuItem) createNewGC_(hDC int64, data *GCData) *GC {
	if this.GetDisplay().IsRescalingAtRuntime() {
		return this.Item.createNewGC_(hDC, data)
	} else {
		data.NativeZoom = this.GetMonitorZoom()
		return GCWin32_newHDCData(hDC, data)
	}
}

func (this *MenuItem) GetMonitorZoom() int32 {
	return this.GetParent().GetShell().GetMonitor().zoom
}

func (this *MenuItem) GetMenuZoom() int32 {
	if this.GetDisplay().IsRescalingAtRuntime() {
		return this.Item.getAutoscalingZoom_()
	} else {
		return DPIUtilGetZoomForAutoscaleProperty(this.GetMonitorZoom())
	}
}

func (this *MenuItem) WmDrawChild(wParam int64, lParam int64) *win32.LRESULT {
	var struct_ *win32.DRAWITEMSTRUCT = win32.NewDRAWITEMSTRUCT()
	win32.OSMoveMemoryOverload33(struct_, lParam, win32.DRAWITEMSTRUCTSizeof)
	if this.text != "" || this.image != (nil) {
		var data *GCData = NewGCData()
		data.Device = upcastDisplayToDevice(this.display)
		var gc *GC = this.impl.createNewGC_(struct_.HDC, data)
		var x int32
		if (this.parent.style & BAR) == 0 {
			x = MenuItemMARGIN_WIDTH * 2
		} else {
			x = struct_.Left
		}
		var zoom int32 = this.GetMenuZoom()
		var menuItemArea *Rectangle = nil
		if this.text != "" {
			this.GetParent().Redraw()
			var flags int32 = DRAW_DELIMITER
			var isInactive bool = ((struct_.ItemState & win32.OSODS_INACTIVE) != 0)
			var isSelected bool = ((struct_.ItemState & win32.OSODS_SELECTED) != 0)
			var isNoAccel bool = ((struct_.ItemState & win32.OSODS_NOACCEL) != 0)
			var drawnText string = ""
			if isNoAccel {
				drawnText = strings.ReplaceAll(this.text, "&", "")
			} else {
				drawnText = this.text
				flags |= DRAW_MNEMONIC
			}
			var menuItemBounds *Rectangle = this.GetBounds()
			var fillMenuWidth int32 = DPIUtilPixelToPoint(menuItemBounds.Width, zoom)
			var fillMenuHeight int32 = DPIUtilPixelToPoint(menuItemBounds.Height, zoom)
			menuItemArea = NewRectangle(DPIUtilPixelToPoint(x, zoom), DPIUtilPixelToPoint(struct_.Top, zoom), fillMenuWidth, fillMenuHeight)
			var cond8 *Color
			if isInactive {
				cond8 = this.display.impl.getSystemColor_(COLOR_GRAY)
			} else {
				cond8 = this.display.impl.getSystemColor_(COLOR_WHITE)
			}
			gc.SetForeground(cond8)
			var cond9 *Color
			if isSelected {
				cond9 = this.display.impl.getSystemColor_(COLOR_DARK_GRAY)
			} else {
				cond9 = this.parent.GetBackground()
			}
			gc.SetBackground(cond9)
			gc.FillRectangleRect(menuItemArea)
			var cond10 int32
			if this.image != (nil) {
				cond10 = this.image.GetBounds().Width + MenuItemIMAGE_TEXT_GAP
			} else {
				cond10 = 0
			}
			var xPositionText int32 = MenuItemLEFT_TEXT_MARGIN + DPIUtilPixelToPoint(x, zoom) + (cond10)
			var yPositionText int32 = DPIUtilPixelToPoint(struct_.Top, zoom) + MenuItemMARGIN_HEIGHT
			gc.DrawTextStringXYFlags(drawnText, xPositionText, yPositionText, flags)
		}
		if this.image != (nil) {
			var image *Image
			if this.GetEnabled() {
				image = this.image
			} else {
				image = NewImageDeviceSrcImageFlag(upcastDisplayToDevice(this.display), this.image, IMAGE_DISABLE)
			}
			var gap int32 = (menuItemArea.Height - image.GetBounds().Height) / 2
			gc.DrawImage(image, MenuItemLEFT_TEXT_MARGIN+DPIUtilPixelToPoint(x, zoom), gap+DPIUtilPixelToPoint(struct_.Top, zoom))
			if this.image != image {
				image.impl.dispose_()
			}
		}
		gc.impl.dispose_()
	}
	if this.parent.foreground != -1 {
		win32.OSSetTextColor(struct_.HDC, this.parent.foreground)
	}
	return nil
}

func (this *MenuItem) WmMeasureChild(wParam int64, lParam int64) *win32.LRESULT {
	var struct_ *win32.MEASUREITEMSTRUCT = win32.NewMEASUREITEMSTRUCT()
	win32.OSMoveMemoryOverload39(struct_, lParam, win32.MEASUREITEMSTRUCTSizeof)
	if (this.parent.style & BAR) != 0 {
		if this.parent.NeedsMenuCallback() {
			var point *Point = this.CalculateRenderedTextSize()
			var menuZoom int32
			if this.GetDisplay().IsRescalingAtRuntime() {
				menuZoom = this.Item.getAutoscalingZoom_()
			} else {
				menuZoom = this.GetMonitorZoom()
			}
			struct_.ItemHeight = DPIUtilPointToPixel(point.Y, menuZoom)
			var horizontalSpaceImage int32
			if this.image != (nil) {
				horizontalSpaceImage = this.image.GetBounds().Width + MenuItemIMAGE_TEXT_GAP
			} else {
				horizontalSpaceImage = 0
			}
			struct_.ItemWidth = DPIUtilPointToPixel(MenuItemLEFT_TEXT_MARGIN+point.X-MenuItemWINDOWS_OVERHEAD+horizontalSpaceImage, menuZoom)
			win32.OSMoveMemoryOverload19(lParam, struct_, win32.MEASUREITEMSTRUCTSizeof)
			return nil
		}
	}
	var width int32 = 0
	var height int32 = 0
	if this.image != (nil) {
		var rect *Rectangle = Win32DPIUtilsPointToPixelOverload8(this.image.GetBounds(), this.impl.getAutoscalingZoom_())
		width = rect.Width
		height = rect.Height
	} else {
		var lpcmi *win32.MENUINFO = win32.NewMENUINFO()
		lpcmi.CbSize = win32.MENUINFOSizeof
		lpcmi.FMask = win32.OSMIM_STYLE
		var hMenu int64 = this.parent.Handle
		win32.OSGetMenuInfo(hMenu, lpcmi)
		if (lpcmi.DwStyle & win32.OSMNS_CHECKORBMP) == 0 {
			for _, item := range this.parent.GetItems() {
				if item.image != (nil) {
					var rect *Rectangle = Win32DPIUtilsPointToPixelOverload8(item.image.GetBounds(), this.impl.getAutoscalingZoom_())
					width = int32(math.Max(float64(width), float64(rect.Width)))
				}
			}
		}
	}
	if width != 0 || height != 0 {
		struct_.ItemWidth = width + MenuItemMARGIN_WIDTH*2
		struct_.ItemHeight = height + MenuItemMARGIN_HEIGHT*2
		win32.OSMoveMemoryOverload19(lParam, struct_, win32.MEASUREITEMSTRUCTSizeof)
	}
	return nil
}

func (this *MenuItem) CalculateRenderedTextSize() *Point {
	var gc *GC = NewGCDrawable(this.GetParent().GetShell())
	var textWithoutMnemonicCharacter string = strings.ReplaceAll(this.impl.getText_(), "&", "")
	var points *Point = gc.TextExtent(textWithoutMnemonicCharacter)
	gc.impl.dispose_()
	if !this.GetDisplay().IsRescalingAtRuntime() {
		var primaryMonitorZoom int32 = this.GetDisplay().impl.getDeviceZoom_()
		var adjustedPrimaryMonitorZoom int32 = DPIUtilGetZoomForAutoscaleProperty(primaryMonitorZoom)
		if primaryMonitorZoom != adjustedPrimaryMonitorZoom {
			points = Win32DPIUtilsPixelToPointAsSizePointZoom(Win32DPIUtilsPointToPixelAsSizePointZoom(points, adjustedPrimaryMonitorZoom), primaryMonitorZoom)
		}
	}
	return points
}

func (this *MenuItem) handleDPIChangeEventScalingFactor_(event *Event, scalingFactor float32) {
	this.Item.handleDPIChangeEventScalingFactor_(event, scalingFactor)
	if this.impl.getImage_() != (nil) {
		this.UpdateImage()
	}
	var subMenu *Menu = this.impl.getMenu_()
	if subMenu != (nil) && !subMenu.IsDisposed() {
		subMenu.NotifyListeners(ZoomChanged, event)
	}
}

func MenuItemCheckStyle(style int32) int32 {
	return WidgetCheckBits(style, PUSH, CHECK, RADIO, SEPARATOR, CASCADE, 0)
}

func MenuItemIsHalfZoom(zoom int32) bool {
	return zoom%50 == 0 && zoom%100 != 0
}

func MenuItemIsQuarterZoom(zoom int32) bool {
	return zoom%10 != 0 && zoom%25 == 0
}

type MenuItem_MenuItemToolTip struct {
	ToolTip
}

func (this *MenuItem_MenuItemToolTip) AsMenuItem_MenuItemToolTip() *MenuItem_MenuItemToolTip {
	return this
}

type MenuItem_MenuItemToolTipLike interface {
	AsMenuItem_MenuItemToolTip() *MenuItem_MenuItemToolTip
}

func NewMenuItemMenuItemToolTip(parentLike ShellLike) *MenuItem_MenuItemToolTip {
	var parent *Shell
	if parentLike != nil {
		parent = parentLike.AsShell()
	}
	_ = parent
	this := &MenuItem_MenuItemToolTip{}
	this.impl = this
	this.initMenuItemMenuItemToolTip(parent)
	return this
}

func (this *MenuItem_MenuItemToolTip) initMenuItemMenuItemToolTip(parent *Shell) {
	this.ToolTip.initToolTip(parent, 0)
	this.MaybeEnableDarkSystemThemeHandle(this.impl.hwndToolTip_())
}

func (this *MenuItem_MenuItemToolTip) hwndToolTip_() int64 {
	return this.parent.MenuItemToolTipHandle()
}

// j2go: anonymous ImageGcDrawer subclass.
type MenuItemAnon1 struct {
	fnGetGcStyle func() int32
	fnDrawOn     func(a0 *GC, a1 int32, a2 int32)
}

func (this *MenuItemAnon1) GetGcStyle() int32 {
	return this.fnGetGcStyle()
}

func (this *MenuItemAnon1) DrawOn(a0 *GC, a1 int32, a2 int32) {
	this.fnDrawOn(a0, a1, a2)
}

func (this *MenuItemAnon1) PostProcess(a0 *ImageData) {
	ImageGcDrawerDefaultPostProcess(this, a0)
}

func upcastMenuItem_MenuItemToolTipToToolTip(x *MenuItem_MenuItemToolTip) *ToolTip {
	if x == nil {
		return nil
	}
	return &x.ToolTip
}
