// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/DirectoryDialog.java @ af630a9093. DO NOT EDIT.

package swt

import (
	"github.com/haiodo/gowt/internal/gtk"
	"github.com/haiodo/gowt/internal/jrt"
	"strings"
	"unicode/utf16"
)

type DirectoryDialog struct {
	Dialog
	message    string
	filterPath string
}

func (this *DirectoryDialog) AsDirectoryDialog() *DirectoryDialog { return this }

type DirectoryDialogLike interface {
	AsDirectoryDialog() *DirectoryDialog
}

var DirectoryDialogSEPARATOR string = jrt.FileSeparator

func NewDirectoryDialog(parentLike ShellLike) *DirectoryDialog {
	var parent *Shell
	if parentLike != nil {
		parent = parentLike.AsShell()
	}
	_ = parent
	this := &DirectoryDialog{}
	this.impl = this
	this.initDirectoryDialog(parent)
	return this
}

func (this *DirectoryDialog) initDirectoryDialog(parent *Shell) {
	this.initDirectoryDialogParentStyle(parent, APPLICATION_MODAL)
}

func NewDirectoryDialogParentStyle(parentLike ShellLike, style int32) *DirectoryDialog {
	var parent *Shell
	if parentLike != nil {
		parent = parentLike.AsShell()
	}
	_ = parent
	this := &DirectoryDialog{}
	this.impl = this
	this.initDirectoryDialogParentStyle(parent, style)
	return this
}

func (this *DirectoryDialog) initDirectoryDialogParentStyle(parent *Shell, style int32) {
	this.Dialog.initDialogParentStyle(parent, DialogCheckStyle(parent, style))
	this.message = ""
	this.filterPath = ""
	this.impl.checkSubclass_()
}

func (this *DirectoryDialog) GetFilterPath() string {
	return this.filterPath
}

func (this *DirectoryDialog) GetMessage() string {
	return this.message
}

func (this *DirectoryDialog) Open() string {
	var tret610 string
	tretd611 := false
	func() {
		defer func() {
			r := recover()
			if r == nil {
				return
			}
			if func() bool {
				switch r.(type) {
				case *SWTException:
					return true
				}
				return false
			}() {
				e := r.(*SWTException)
				_ = e
				if e.Code == ERROR_INVALID_RETURN_VALUE {
					tret610 = ""
					tretd611 = true
					return
				}
				panic(e)
			} else {
				panic(r)
			}
		}()
		tret610 = jrt.Cast[string](this.OpenDialog().OrElse(""))
		tretd611 = true
		return
	}()
	_ = tretd611
	return tret610
}

func (this *DirectoryDialog) OpenDialog() *jrt.Optional {
	return this.OpenNativeChooserDialog()
}

func (this *DirectoryDialog) OpenNativeChooserDialog() *jrt.Optional {
	var titleBytes []int8 = gtk.ConverterWcsToMbcs(this.title, true)
	var shellHandle int64 = this.parent.impl.topHandle_()
	var display *Display
	if this.parent != (nil) {
		display = this.parent.GetDisplay()
	} else {
		display = DisplayGetCurrent()
	}
	var handle int64
	if gtk.GTKGTK_VERSION >= gtk.OSVERSION(4, 10, 0) {
		handle = gtk.GTK4Gtk_file_dialog_new()
		gtk.GTK4Gtk_file_dialog_set_title(handle, titleBytes)
	} else {
		handle = gtk.GTKGtk_file_chooser_native_new(titleBytes, shellHandle, gtk.GTKGTK_FILE_CHOOSER_ACTION_SELECT_FOLDER, nil, nil)
	}
	if handle == 0 {
		this.Error(ERROR_NO_HANDLES)
	}
	if this.filterPath != "" && jrt.StringLength(this.filterPath) > 0 {
		var stringBuilder *jrt.StringBuilder = jrt.NewStringBuilder()
		if !strings.HasPrefix(this.filterPath, DirectoryDialogSEPARATOR) {
			stringBuilder.Append(DirectoryDialogSEPARATOR)
		}
		stringBuilder.Append(this.filterPath)
		var buffer []int8 = gtk.ConverterWcsToMbcs(stringBuilder.ToString(), true)
		var ptr int64 = gtk.OSRealpath(buffer, nil)
		if ptr != 0 {
			if gtk.GTKGTK4 {
				var file int64 = gtk.OSG_file_new_for_path(buffer)
				if gtk.GTKGTK_VERSION >= gtk.OSVERSION(4, 10, 0) {
					gtk.GTK4Gtk_file_dialog_set_initial_folder(handle, file)
				} else {
					gtk.GTK4Gtk_file_chooser_set_current_folder(handle, file, int64(0))
				}
				gtk.OSG_object_unref(file)
			} else {
				gtk.GTK3Gtk_file_chooser_set_current_folder(handle, ptr)
			}
			gtk.OSG_free(ptr)
		}
	}
	this.GTK3setNativeDialogMessage(handle, this.message)
	var selectedPath string = ""
	display.AddIdleProc()
	var signalId int32 = 0
	var hookId int64 = int64(0)
	if (this.style & RIGHT_TO_LEFT) != 0 {
		signalId = gtk.OSG_signal_lookup(gtk.OSMap, gtk.GTKGTK_TYPE_WIDGET())
		hookId = gtk.OSG_signal_add_emission_hook(signalId, 0, display.emissionProc, handle, int64(0))
	}
	var response int32
	var file int64 = int64(0)
	if gtk.GTKGTK4 {
		if gtk.GTKGTK_VERSION >= gtk.OSVERSION(4, 10, 0) {
			anon612 := &DirectoryDialogAnon1{}
			anon612.fnAsync = func(result int64) {
				gtk.GTK4Gtk_file_dialog_select_folder(handle, shellHandle, int64(0), result, int64(0))
			}
			anon612.fnAwait = func(result int64) int64 {
				return gtk.GTK4Gtk_file_dialog_select_folder_finish(handle, result, nil)
			}
			file = SyncDialogUtilRun(display, anon612)
			if file != 0 {
				response = gtk.GTKGTK_RESPONSE_ACCEPT
			} else {
				response = gtk.GTKGTK_RESPONSE_CANCEL
			}
		} else {
			response = SyncDialogUtilRunDisplayHandleIsNativeDialog(display, handle, true)
		}
	} else {
		display.externalEventLoop = true
		display.SendPreExternalEventDispatchEvent()
		response = gtk.GTK3Gtk_native_dialog_run(handle)
		display.externalEventLoop = false
		display.SendPostExternalEventDispatchEvent()
	}
	if (this.style & RIGHT_TO_LEFT) != 0 {
		gtk.OSG_signal_remove_emission_hook(signalId, hookId)
	}
	if response == gtk.GTKGTK_RESPONSE_ACCEPT {
		var path int64
		if gtk.GTKGTK4 {
			if gtk.GTKGTK_VERSION < gtk.OSVERSION(4, 10, 0) {
				file = gtk.GTK4Gtk_file_chooser_get_file(handle)
			}
			path = gtk.OSG_file_get_path(file)
		} else {
			path = gtk.GTK3Gtk_file_chooser_get_filename(handle)
		}
		if path != 0 {
			var utf8Ptr int64 = gtk.OSG_filename_to_utf8(path, int64(-1), nil, nil, nil)
			if utf8Ptr == 0 {
				utf8Ptr = gtk.OSG_filename_display_name(path)
			}
			if path != utf8Ptr {
				gtk.OSG_free(path)
			}
			if utf8Ptr != 0 {
				var items_written []int64 = make([]int64, 1)
				var utf16Ptr int64 = gtk.OSG_utf8_to_utf16StrLenItems_readItems_writtenError(utf8Ptr, int64(-1), nil, items_written, nil)
				gtk.OSG_free(utf8Ptr)
				if utf16Ptr != 0 {
					var clength int32 = int32(items_written[0])
					var chars []uint16 = make([]uint16, clength)
					gtk.CMemmoveOverload10(chars, utf16Ptr, int64(clength*2))
					gtk.OSG_free(utf16Ptr)
					selectedPath = string(utf16.Decode(chars))
					this.filterPath = selectedPath
				}
			}
		}
	}
	var result *jrt.Optional = jrt.OptionalEmpty()
	if response == gtk.GTKGTK_RESPONSE_ACCEPT {
		result = jrt.OptionalOfNullable(selectedPath)
	}
	display.RemoveIdleProc()
	gtk.OSG_object_unref(handle)
	if result.IsPresent() || response == gtk.GTKGTK_RESPONSE_CANCEL {
		return result
	}
	panic(NewSWTExceptionCode(ERROR_INVALID_RETURN_VALUE))
}

func (this *DirectoryDialog) GTK3setNativeDialogMessage(handle int64, message string) {
	if gtk.GTKGTK4 {
		return
	}
	if jrt.StringLength(message) > 0 {
		var buffer []int8 = gtk.ConverterWcsToMbcs(message, true)
		var box int64 = gtk.GTKGtk_box_new(gtk.GTKGTK_ORIENTATION_HORIZONTAL, 0)
		if box == 0 {
			this.Error(ERROR_NO_HANDLES)
		}
		var label int64 = gtk.GTKGtk_label_new(buffer)
		if label == 0 {
			this.Error(ERROR_NO_HANDLES)
		}
		gtk.GTK3Gtk_container_add(box, label)
		gtk.GTK3Gtk_widget_show(label)
		gtk.GTK3Gtk_label_set_line_wrap(label, true)
		gtk.GTKGtk_box_set_homogeneous(box, false)
		gtk.GTKGtk_label_set_justify(label, gtk.GTKGTK_JUSTIFY_CENTER)
		gtk.GTK3Gtk_file_chooser_set_extra_widget(handle, box)
	}
}

func (this *DirectoryDialog) SetFilterPath(string_ string) {
	this.filterPath = string_
}

func (this *DirectoryDialog) SetMessage(string_ string) {
	if string_ == jrt.NullString {
		this.Error(ERROR_NULL_ARGUMENT)
	}
	this.message = string_
}

// j2go: anonymous AsyncReadyCallback subclass.
type DirectoryDialogAnon1 struct {
	fnAsync func(a0 int64)
	fnAwait func(a0 int64) int64
}

func (this *DirectoryDialogAnon1) Async(a0 int64) {
	this.fnAsync(a0)
}

func (this *DirectoryDialogAnon1) Await(a0 int64) int64 {
	return this.fnAwait(a0)
}
