// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Slider.java @ af630a9093. DO NOT EDIT.

package swt

import (
	"fmt"
	"github.com/haiodo/gowt/internal/win32"
	"math"
	"os"
)

type Slider struct {
	Control
	increment     int32
	pageIncrement int32
	ignoreFocus   bool
}

func (this *Slider) AsSlider() *Slider { return this }

type SliderLike interface {
	AsSlider() *Slider
}

var SliderScrollBarProc int64 = 0

var SliderScrollBarClass *win32.TCHAR = win32.NewTCHARStringTerminate("SCROLLBAR", true)

func NewSlider(parentLike CompositeLike, style int32) *Slider {
	var parent *Composite
	if parentLike != nil {
		parent = parentLike.AsComposite()
	}
	_ = parent
	this := &Slider{}
	this.impl = this
	this.initSlider(parent, style)
	return this
}

func (this *Slider) initSlider(parent *Composite, style int32) {
	this.Control.initControlParentStyle(parent, SliderCheckStyle(style))
}

func (this *Slider) AddSelectionListener(listener SelectionListener) {
	this.AddTypedListener(listener, []int32{Selection, DefaultSelection})
}

func (this *Slider) callWindowProc_(hwnd int64, msg int32, wParam int64, lParam int64) int64 {
	if this.Handle == 0 {
		return int64(0)
	}
	switch msg {
	case win32.OSWM_LBUTTONDOWN, win32.OSWM_LBUTTONDBLCLK:
		this.display.RunDeferredEvents()
	}
	return win32.OSCallWindowProc(SliderScrollBarProc, hwnd, msg, wParam, lParam)
}

func (this *Slider) computeSizeInPixels_(hintInPoints *Point, zoom int32, changed bool) *Point {
	this.CheckWidget()
	var hintInPixels *Point = Win32DPIUtilsPointToPixelAsSufficientlyLargeSize(hintInPoints, zoom)
	var border int32 = this.impl.getBorderWidthInPixels_()
	var width int32 = border * 2
	var height int32 = border * 2
	if (this.style & HORIZONTAL) != 0 {
		width += this.impl.getSystemMetrics_(win32.OSSM_CXHSCROLL) * 10
		height += this.impl.getSystemMetrics_(win32.OSSM_CYHSCROLL)
	} else {
		width += this.impl.getSystemMetrics_(win32.OSSM_CXVSCROLL)
		height += this.impl.getSystemMetrics_(win32.OSSM_CYVSCROLL) * 10
	}
	if hintInPoints.X != DEFAULT {
		width = hintInPixels.X + (border * 2)
	}
	if hintInPoints.Y != DEFAULT {
		height = hintInPixels.Y + (border * 2)
	}
	return NewPoint(width, height)
}

func (this *Slider) createHandle_() {
	this.Control.createHandle_()
	this.impl.maybeEnableDarkSystemThemeNoArgs_()
}

func (this *Slider) createWidget_() {
	this.Control.createWidget_()
	this.increment = 1
	this.pageIncrement = 10
	var info *win32.SCROLLINFO = win32.NewSCROLLINFO()
	info.CbSize = win32.SCROLLINFOSizeof
	info.FMask = win32.OSSIF_ALL
	info.NMax = 100
	info.NPage = 11
	win32.OSSetScrollInfo(this.Handle, win32.OSSB_CTL, info, true)
}

func (this *Slider) defaultBackground_() int32 {
	return win32.OSGetSysColor(win32.OSCOLOR_SCROLLBAR)
}

func (this *Slider) defaultForeground_() int32 {
	return win32.OSGetSysColor(win32.OSCOLOR_BTNFACE)
}

func (this *Slider) enableWidget_(enabled bool) {
	this.Control.enableWidget_(enabled)
	var flags int32
	if enabled {
		flags = win32.OSESB_ENABLE_BOTH
	} else {
		flags = win32.OSESB_DISABLE_BOTH
	}
	win32.OSEnableScrollBar(this.Handle, win32.OSSB_CTL, flags)
	if enabled {
		this.state &= ^WidgetDISABLED
	} else {
		this.state |= WidgetDISABLED
	}
}

func (this *Slider) getEnabled_() bool {
	this.CheckWidget()
	return (this.state & WidgetDISABLED) == 0
}

func (this *Slider) GetIncrement() int32 {
	this.CheckWidget()
	return this.increment
}

func (this *Slider) GetMaximum() int32 {
	this.CheckWidget()
	var info *win32.SCROLLINFO = win32.NewSCROLLINFO()
	info.CbSize = win32.SCROLLINFOSizeof
	info.FMask = win32.OSSIF_RANGE
	win32.OSGetScrollInfo(this.Handle, win32.OSSB_CTL, info)
	return info.NMax
}

func (this *Slider) GetMinimum() int32 {
	this.CheckWidget()
	var info *win32.SCROLLINFO = win32.NewSCROLLINFO()
	info.CbSize = win32.SCROLLINFOSizeof
	info.FMask = win32.OSSIF_RANGE
	win32.OSGetScrollInfo(this.Handle, win32.OSSB_CTL, info)
	return info.NMin
}

func (this *Slider) GetPageIncrement() int32 {
	this.CheckWidget()
	return this.pageIncrement
}

func (this *Slider) GetSelection() int32 {
	this.CheckWidget()
	var info *win32.SCROLLINFO = win32.NewSCROLLINFO()
	info.CbSize = win32.SCROLLINFOSizeof
	info.FMask = win32.OSSIF_POS
	win32.OSGetScrollInfo(this.Handle, win32.OSSB_CTL, info)
	return info.NPos
}

func (this *Slider) GetThumb() int32 {
	this.CheckWidget()
	var info *win32.SCROLLINFO = win32.NewSCROLLINFO()
	info.CbSize = win32.SCROLLINFOSizeof
	info.FMask = win32.OSSIF_PAGE
	win32.OSGetScrollInfo(this.Handle, win32.OSSB_CTL, info)
	if info.NPage != 0 {
		info.NPage--
	}
	return info.NPage
}

func (this *Slider) RemoveSelectionListener(listener SelectionListener) {
	this.CheckWidget()
	if listener == (nil) {
		this.Error(ERROR_NULL_ARGUMENT)
	}
	if this.eventTable == (nil) {
		return
	}
	this.eventTable.UnhookEventTypeListener(Selection, listener)
	this.eventTable.UnhookEventTypeListener(DefaultSelection, listener)
}

func (this *Slider) setBoundsInPixelsXYWidthHeightFlags_(x int32, y int32, width int32, height int32, flags int32) {
	this.Control.setBoundsInPixelsXYWidthHeightFlags_(x, y, width, height, flags)
	if win32.OSGetFocus() == this.Handle {
		this.ignoreFocus = true
		win32.OSSendMessageOverload4(this.Handle, win32.OSWM_SETFOCUS, int64(0), int64(0))
		this.ignoreFocus = false
	}
}

func (this *Slider) SetIncrement(value int32) {
	this.CheckWidget()
	if value < 1 {
		return
	}
	this.increment = value
}

func (this *Slider) SetMaximum(value int32) {
	this.CheckWidget()
	if value < 0 {
		return
	}
	var info *win32.SCROLLINFO = win32.NewSCROLLINFO()
	info.CbSize = win32.SCROLLINFOSizeof
	info.FMask = win32.OSSIF_RANGE | win32.OSSIF_DISABLENOSCROLL
	win32.OSGetScrollInfo(this.Handle, win32.OSSB_CTL, info)
	if value-info.NMin-info.NPage < 1 {
		return
	}
	info.NMax = value
	this.SetScrollInfo(this.Handle, win32.OSSB_CTL, info, true)
}

func (this *Slider) SetMinimum(value int32) {
	this.CheckWidget()
	if value < 0 {
		return
	}
	var info *win32.SCROLLINFO = win32.NewSCROLLINFO()
	info.CbSize = win32.SCROLLINFOSizeof
	info.FMask = win32.OSSIF_RANGE | win32.OSSIF_DISABLENOSCROLL
	win32.OSGetScrollInfo(this.Handle, win32.OSSB_CTL, info)
	if info.NMax-value-info.NPage < 1 {
		return
	}
	info.NMin = value
	this.SetScrollInfo(this.Handle, win32.OSSB_CTL, info, true)
}

func (this *Slider) SetPageIncrement(value int32) {
	this.CheckWidget()
	if value < 1 {
		return
	}
	this.pageIncrement = value
}

func (this *Slider) SetScrollInfo(hwnd int64, flags int32, info *win32.SCROLLINFO, fRedraw bool) bool {
	if (this.state & WidgetDISABLED) != 0 {
		fRedraw = false
	}
	var result bool = win32.OSSetScrollInfo(hwnd, flags, info, fRedraw)
	if (this.state & WidgetDISABLED) != 0 {
		win32.OSEnableWindow(this.Handle, false)
		win32.OSEnableScrollBar(this.Handle, win32.OSSB_CTL, win32.OSESB_DISABLE_BOTH)
	}
	if win32.OSGetFocus() == this.Handle {
		this.ignoreFocus = true
		win32.OSSendMessageOverload4(this.Handle, win32.OSWM_SETFOCUS, int64(0), int64(0))
		this.ignoreFocus = false
	}
	return result
}

func (this *Slider) SetSelection(value int32) {
	this.CheckWidget()
	var info *win32.SCROLLINFO = win32.NewSCROLLINFO()
	info.CbSize = win32.SCROLLINFOSizeof
	info.FMask = win32.OSSIF_POS
	info.NPos = value
	this.SetScrollInfo(this.Handle, win32.OSSB_CTL, info, true)
}

func (this *Slider) SetThumb(value int32) {
	this.CheckWidget()
	if value < 1 {
		return
	}
	var info *win32.SCROLLINFO = win32.NewSCROLLINFO()
	info.CbSize = win32.SCROLLINFOSizeof
	info.FMask = win32.OSSIF_PAGE | win32.OSSIF_RANGE | win32.OSSIF_DISABLENOSCROLL
	win32.OSGetScrollInfo(this.Handle, win32.OSSB_CTL, info)
	info.NPage = value
	if info.NPage != 0 {
		info.NPage++
	}
	this.SetScrollInfo(this.Handle, win32.OSSB_CTL, info, true)
}

func (this *Slider) SetValues(selection int32, minimum int32, maximum int32, thumb int32, increment int32, pageIncrement int32) {
	this.CheckWidget()
	if minimum < 0 {
		return
	}
	if maximum < 0 {
		return
	}
	if thumb < 1 {
		return
	}
	if increment < 1 {
		return
	}
	if pageIncrement < 1 {
		return
	}
	this.increment = increment
	this.pageIncrement = pageIncrement
	var info *win32.SCROLLINFO = win32.NewSCROLLINFO()
	info.CbSize = win32.SCROLLINFOSizeof
	info.FMask = win32.OSSIF_POS | win32.OSSIF_PAGE | win32.OSSIF_RANGE | win32.OSSIF_DISABLENOSCROLL
	info.NPos = selection
	info.NMin = minimum
	info.NMax = maximum
	info.NPage = thumb
	if info.NPage != 0 {
		info.NPage++
	}
	this.SetScrollInfo(this.Handle, win32.OSSB_CTL, info, true)
}

func (this *Slider) widgetExtStyle_() int32 {
	var bits int32 = this.Control.widgetExtStyle_()
	if (this.style & BORDER) != 0 {
		bits &= ^win32.OSWS_EX_CLIENTEDGE
	}
	return bits
}

func (this *Slider) widgetStyle_() int32 {
	var bits int32 = this.Control.widgetStyle_() | win32.OSWS_TABSTOP
	if (this.style & BORDER) != 0 {
		bits &= ^win32.OSWS_BORDER
	}
	if (this.style & HORIZONTAL) != 0 {
		return bits | win32.OSSBS_HORZ
	}
	return bits | win32.OSSBS_VERT
}

func (this *Slider) windowClass_() *win32.TCHAR {
	return SliderScrollBarClass
}

func (this *Slider) windowProc_() int64 {
	return SliderScrollBarProc
}

func (this *Slider) wM_KEYDOWN_(wParam int64, lParam int64) *win32.LRESULT {
	var result *win32.LRESULT = this.Control.wM_KEYDOWN_(wParam, lParam)
	if result != (nil) {
		return result
	}
	if (this.style & VERTICAL) != 0 {
		return result
	}
	if (this.style & MIRRORED) != 0 {
		switch int32(wParam) {
		case win32.OSVK_LEFT, win32.OSVK_RIGHT:
			{
				var key int32
				if wParam == int64(win32.OSVK_LEFT) {
					key = win32.OSVK_RIGHT
				} else {
					key = win32.OSVK_LEFT
				}
				var code int64 = this.impl.callWindowProc_(this.Handle, win32.OSWM_KEYDOWN, int64(key), lParam)
				return win32.NewLRESULT(code)
			}
		}
	}
	return result
}

func (this *Slider) wM_LBUTTONDBLCLK_(wParam int64, lParam int64) *win32.LRESULT {
	var oldBits int32 = win32.OSGetWindowLong(this.Handle, win32.OSGWL_STYLE)
	var newBits int32 = oldBits & ^win32.OSWS_TABSTOP
	win32.OSSetWindowLong(this.Handle, win32.OSGWL_STYLE, newBits)
	var result *win32.LRESULT = this.Control.wM_LBUTTONDBLCLK_(wParam, lParam)
	if this.IsDisposed() {
		return win32.LRESULTZERO
	}
	win32.OSSetWindowLong(this.Handle, win32.OSGWL_STYLE, oldBits)
	if result == win32.LRESULTZERO {
		return result
	}
	if win32.OSGetCapture() == this.Handle {
		win32.OSReleaseCapture()
	}
	if !this.SendMouseEvent(MouseUp, 1, this.Handle, lParam) {
		return win32.LRESULTZERO
	}
	return result
}

func (this *Slider) wM_LBUTTONDOWN_(wParam int64, lParam int64) *win32.LRESULT {
	var oldBits int32 = win32.OSGetWindowLong(this.Handle, win32.OSGWL_STYLE)
	var newBits int32 = oldBits & ^win32.OSWS_TABSTOP
	win32.OSSetWindowLong(this.Handle, win32.OSGWL_STYLE, newBits)
	var result *win32.LRESULT = this.Control.wM_LBUTTONDOWN_(wParam, lParam)
	if this.IsDisposed() {
		return win32.LRESULTZERO
	}
	win32.OSSetWindowLong(this.Handle, win32.OSGWL_STYLE, oldBits)
	if result == win32.LRESULTZERO {
		return result
	}
	if win32.OSGetCapture() == this.Handle {
		win32.OSReleaseCapture()
	}
	if !this.SendMouseEvent(MouseUp, 1, this.Handle, lParam) {
		return win32.LRESULTONE
	}
	return result
}

func (this *Slider) wM_SETFOCUS_(wParam int64, lParam int64) *win32.LRESULT {
	if this.ignoreFocus {
		return nil
	}
	return this.Control.wM_SETFOCUS_(wParam, lParam)
}

func (this *Slider) wmScrollChild_(wParam int64, lParam int64) *win32.LRESULT {
	var code int32 = win32.OSLOWORD(wParam)
	if code == win32.OSSB_ENDSCROLL {
		return nil
	}
	var event *Event = NewEvent()
	var info *win32.SCROLLINFO = win32.NewSCROLLINFO()
	info.CbSize = win32.SCROLLINFOSizeof
	info.FMask = win32.OSSIF_TRACKPOS | win32.OSSIF_POS | win32.OSSIF_RANGE
	win32.OSGetScrollInfo(this.Handle, win32.OSSB_CTL, info)
	info.FMask = win32.OSSIF_POS
	switch code {
	case win32.OSSB_THUMBPOSITION:
		event.Detail = NONE
		info.NPos = info.NTrackPos
		break
	case win32.OSSB_THUMBTRACK:
		event.Detail = DRAG
		info.NPos = info.NTrackPos
		break
	case win32.OSSB_TOP:
		event.Detail = HOME
		info.NPos = info.NMin
		break
	case win32.OSSB_BOTTOM:
		event.Detail = END
		info.NPos = info.NMax
		break
	case win32.OSSB_LINEDOWN:
		event.Detail = ARROW_DOWN
		info.NPos += this.increment
		break
	case win32.OSSB_LINEUP:
		event.Detail = ARROW_UP
		info.NPos = int32(math.Max(float64(info.NMin), float64(info.NPos-this.increment)))
		break
	case win32.OSSB_PAGEDOWN:
		event.Detail = PAGE_DOWN
		info.NPos += this.pageIncrement
		break
	case win32.OSSB_PAGEUP:
		event.Detail = PAGE_UP
		info.NPos = int32(math.Max(float64(info.NMin), float64(info.NPos-this.pageIncrement)))
		break
	}
	win32.OSSetScrollInfo(this.Handle, win32.OSSB_CTL, info, true)
	this.SendSelectionEventEventTypeEventSend(Selection, event, true)
	return nil
}

func SliderCheckStyle(style int32) int32 {
	return WidgetCheckBits(style, HORIZONTAL, VERTICAL, 0, 0, 0, 0)
}

func init() {
	func() {
		defer func() {
			if r := recover(); r != nil {
				fmt.Fprintln(os.Stderr, "gowt: deferred init Slider static{}:", r)
			}
		}()
		var lpWndClass *win32.WNDCLASS = win32.NewWNDCLASS()
		win32.OSGetClassInfo(int64(0), SliderScrollBarClass, lpWndClass)
		SliderScrollBarProc = lpWndClass.LpfnWndProc
	}()
}
