// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Shell.java @ af630a9093. DO NOT EDIT.

package swt

import (
	"github.com/haiodo/gowt/internal/cocoa"
	"github.com/haiodo/gowt/internal/jrt"
	"math"
	"unicode/utf16"
)

type Shell struct {
	Decorations
	window            *cocoa.NSWindow
	windowDelegate    *cocoa.SWTWindowDelegate
	hostWindowClass   int64
	hostWindow        *cocoa.NSWindow
	tooltipOwner      int64
	tooltipTag        int64
	tooltipUserData   int64
	glContextCount    int32
	opened            bool
	moved             bool
	resized           bool
	fullScreen        bool
	center            bool
	deferFlushing     bool
	scrolling         bool
	isPopup           bool
	lastActive        *Control
	normalBounds      *Rectangle
	keyInputHappened  bool
	currentFrame      cocoa.NSRect
	fullScreenFrame   cocoa.NSRect
	toolBar           *ToolBar
	windowEmbedCounts *jrt.Map
	escMenuItem       *MenuItem
}

func (this *Shell) AsShell() *Shell { return this }

type ShellLike interface {
	AsShell() *Shell
}

var ShellDEFAULT_CLIENT_WIDTH int32 = -1

var ShellDEFAULT_CLIENT_HEIGHT int32 = -1

func NewShell() *Shell {
	this := &Shell{}
	this.impl = this
	this.initShell()
	return this
}

func (this *Shell) initShell() {
	this.initShellDisplay(nil)
}

func NewShellStyle(style int32) *Shell {
	this := &Shell{}
	this.impl = this
	this.initShellStyle(style)
	return this
}

func (this *Shell) initShellStyle(style int32) {
	this.initShellDisplayStyle(nil, style)
}

func NewShellDisplay(displayLike DisplayLike) *Shell {
	var display *Display
	if displayLike != nil {
		display = displayLike.AsDisplay()
	}
	_ = display
	this := &Shell{}
	this.impl = this
	this.initShellDisplay(display)
	return this
}

func (this *Shell) initShellDisplay(display *Display) {
	this.initShellDisplayStyle(display, SHELL_TRIM)
}

func NewShellDisplayStyle(displayLike DisplayLike, style int32) *Shell {
	var display *Display
	if displayLike != nil {
		display = displayLike.AsDisplay()
	}
	_ = display
	this := &Shell{}
	this.impl = this
	this.initShellDisplayStyle(display, style)
	return this
}

func (this *Shell) initShellDisplayStyle(display *Display, style int32) {
	this.initShellDisplayParentStyleHandleEmbedded(display, nil, style, int64(0), false)
}

func newShellDisplayParentStyleHandleEmbedded(display *Display, parent *Shell, style int32, handle int64, embedded bool) *Shell {
	this := &Shell{}
	this.impl = this
	this.initShellDisplayParentStyleHandleEmbedded(display, parent, style, handle, embedded)
	return this
}

func (this *Shell) initShellDisplayParentStyleHandleEmbedded(display *Display, parent *Shell, style int32, handle int64, embedded bool) {
	this.Decorations.initDecorations()
	this.impl.CheckSubclass()
	if display == (nil) {
		display = DisplayGetCurrent()
	}
	if display == (nil) {
		display = DisplayGetDefault()
	}
	if !display.IsValidThread() {
		this.Error(ERROR_THREAD_INVALID_ACCESS)
	}
	if parent != (nil) && parent.IsDisposed() {
		this.Error(ERROR_INVALID_ARGUMENT)
	}
	if !DisplayGetSheetEnabled() {
		this.center = parent != (nil) && (style&SHEET) != 0
	}
	this.style = ShellCheckStyle(parent, style)
	this.parent = upcastShellToComposite(parent)
	this.display = display
	if handle != 0 {
		if embedded {
			this.View = cocoa.NewNSViewOverload1(handle)
		} else {
			this.window = cocoa.NewNSWindowOverload1(handle)
			this.state |= WidgetFOREIGN_HANDLE
		}
	}
	this.ReskinWidget()
	this.impl.CreateWidget()
}

func NewShellParent(parentLike ShellLike) *Shell {
	var parent *Shell
	if parentLike != nil {
		parent = parentLike.AsShell()
	}
	_ = parent
	this := &Shell{}
	this.impl = this
	this.initShellParent(parent)
	return this
}

func (this *Shell) initShellParent(parent *Shell) {
	this.initShellParentStyle(parent, DIALOG_TRIM)
}

func NewShellParentStyle(parentLike ShellLike, style int32) *Shell {
	var parent *Shell
	if parentLike != nil {
		parent = parentLike.AsShell()
	}
	_ = parent
	this := &Shell{}
	this.impl = this
	this.initShellParentStyle(parent, style)
	return this
}

func (this *Shell) initShellParentStyle(parent *Shell, style int32) {
	var cond149 *Display
	if parent != (nil) {
		cond149 = parent.display
	} else {
		cond149 = nil
	}
	this.initShellDisplayParentStyleHandleEmbedded(cond149, parent, style, int64(0), false)
}

func (this *Shell) AccessibilityIsIgnored(id int64, sel int64) bool {
	if id == this.View.Id {
		return true
	}
	return this.Decorations.AccessibilityIsIgnored(id, sel)
}

func (this *Shell) AddShellListener(listener ShellListener) {
	this.AddTypedListener(listener, []int32{Activate, Close, Deactivate, Iconify, Deiconify})
}

func (this *Shell) AttachObserversToWindow(newWindow *cocoa.NSWindow) {
	if newWindow == (nil) || newWindow.Id == 0 {
		return
	}
	var newHostWindowClass int64 = cocoa.OSObject_getClass(newWindow.Id)
	var sendEventImpl int64 = cocoa.OSClass_getMethodImplementation(newHostWindowClass, cocoa.OSSel_sendEvent_)
	if sendEventImpl == DisplayWindowCallback3.GetAddress() {
		return
	}
	this.hostWindow = newWindow
	this.hostWindow.Retain()
	var embeddedSubclass int64 = this.display.CreateWindowSubclass(newHostWindowClass, "SWTAWTWindow", true)
	cocoa.OSObject_setClass(this.hostWindow.Id, embeddedSubclass)
	this.display.AddWidget(upcastcocoaNSWindowTococoaNSObject(this.hostWindow), upcastShellToWidget(this))
	this.hostWindowClass = newHostWindowClass
	if this.windowEmbedCounts == (nil) {
		this.windowEmbedCounts = jrt.NewMap()
	}
	var embedCount any = this.windowEmbedCounts.Get(this.hostWindow)
	if embedCount == (nil) {
		embedCount = 0
	}
	embedCount = jrt.Cast[int32](embedCount) + 1
	this.windowEmbedCounts.Put(this.hostWindow, embedCount)
	var defaultCenter *cocoa.NSNotificationCenter = cocoa.NSNotificationCenterDefaultCenter()
	defaultCenter.AddObserver(upcastcocoaSWTWindowDelegateTococoaId(this.windowDelegate), cocoa.OSSel_windowDidBecomeKey_, cocoa.OSNSWindowDidBecomeKeyNotification_, upcastcocoaNSWindowTococoaId(this.hostWindow))
	defaultCenter.AddObserver(upcastcocoaSWTWindowDelegateTococoaId(this.windowDelegate), cocoa.OSSel_windowDidDeminiaturize_, cocoa.OSNSWindowDidDeminiaturizeNotification_, upcastcocoaNSWindowTococoaId(this.hostWindow))
	defaultCenter.AddObserver(upcastcocoaSWTWindowDelegateTococoaId(this.windowDelegate), cocoa.OSSel_windowDidMiniaturize_, cocoa.OSNSWindowDidMiniaturizeNotification_, upcastcocoaNSWindowTococoaId(this.hostWindow))
	defaultCenter.AddObserver(upcastcocoaSWTWindowDelegateTococoaId(this.windowDelegate), cocoa.OSSel_windowDidMove_, cocoa.OSNSWindowDidMoveNotification_, upcastcocoaNSWindowTococoaId(this.hostWindow))
	defaultCenter.AddObserver(upcastcocoaSWTWindowDelegateTococoaId(this.windowDelegate), cocoa.OSSel_windowDidResize_, cocoa.OSNSWindowDidResizeNotification_, upcastcocoaNSWindowTococoaId(this.hostWindow))
	defaultCenter.AddObserver(upcastcocoaSWTWindowDelegateTococoaId(this.windowDelegate), cocoa.OSSel_windowDidResignKey_, cocoa.OSNSWindowDidResignKeyNotification_, upcastcocoaNSWindowTococoaId(this.hostWindow))
	defaultCenter.AddObserver(upcastcocoaSWTWindowDelegateTococoaId(this.windowDelegate), cocoa.OSSel_windowWillClose_, cocoa.OSNSWindowWillCloseNotification_, upcastcocoaNSWindowTococoaId(this.hostWindow))
}

func (this *Shell) BecomeKeyWindow(id int64, sel int64) {
	var modal *Shell = this.GetModalShell()
	if modal != (nil) && modal.window != (nil) {
		modal.window.MakeKeyAndOrderFront(nil)
		return
	}
	var display *Display = this.display
	display.keyWindow = this.View.Window()
	this.Decorations.BecomeKeyWindow(id, sel)
	display.CheckFocus()
	display.keyWindow = nil
}

func (this *Shell) BringToTop(force bool) {
	if this.impl.GetMinimized() {
		return
	}
	if force {
		this.ForceActive()
	} else {
		this.SetActive()
	}
}

func (this *Shell) CanBecomeKeyWindow(id int64, sel int64) bool {
	if this.isPopup {
		return false
	}
	if this.window != (nil) {
		if (this.style & NO_FOCUS) != 0 {
			var nsEvent *cocoa.NSEvent = cocoa.NSApplicationSharedApplication().CurrentEvent()
			if nsEvent != (nil) && nsEvent.Type() == int64(cocoa.OSNSLeftMouseDown) {
				var contentView *cocoa.NSView = this.window.ContentView()
				if contentView != (nil) {
					var view *cocoa.NSView = contentView.HitTest(nsEvent.LocationInWindow())
					if view == contentView {
						return false
					}
				}
			}
		}
		var styleMask int64 = this.window.StyleMask()
		if styleMask == int64(cocoa.OSNSWindowStyleMaskBorderless) || (styleMask&int64((cocoa.OSNSWindowStyleMaskNonactivatingPanel|cocoa.OSNSWindowStyleMaskDocModalWindow|cocoa.OSNSWindowStyleMaskResizable))) != 0 {
			return true
		}
	}
	return this.Decorations.CanBecomeKeyWindow(id, sel)
}

func (this *Shell) CheckOpen() {
	if !this.opened {
		this.resized = false
	}
}

func (this *Shell) Center() {
	if this.parent == (nil) {
		return
	}
	var rect *Rectangle = this.impl.GetBounds()
	var parentRect *Rectangle = this.display.MapFromToRectangle(upcastCompositeToControl(this.parent), nil, this.parent.impl.GetClientArea())
	var x int32 = int32(math.Max(float64(parentRect.X), float64(parentRect.X+(parentRect.Width-rect.Width)/2)))
	var y int32 = int32(math.Max(float64(parentRect.Y), float64(parentRect.Y+(parentRect.Height-rect.Height)/2)))
	var monitorRect *Rectangle = this.parent.GetMonitor().GetClientArea()
	if x+rect.Width > monitorRect.X+monitorRect.Width {
		x = int32(math.Max(float64(monitorRect.X), float64(monitorRect.X+monitorRect.Width-rect.Width)))
	} else {
		x = int32(math.Max(float64(x), float64(monitorRect.X)))
	}
	if y+rect.Height > monitorRect.Y+monitorRect.Height {
		y = int32(math.Max(float64(monitorRect.Y), float64(monitorRect.Y+monitorRect.Height-rect.Height)))
	} else {
		y = int32(math.Max(float64(y), float64(monitorRect.Y)))
	}
	this.SetLocation(x, y)
}

func (this *Shell) ClearDeferFlushing(id int64, sel int64) {
	this.deferFlushing = false
	this.scrolling = false
	if this.window != (nil) {
		this.window.FlushWindowIfNeeded()
	}
}

func (this *Shell) Close() {
	this.CheckWidget()
	this.CloseWidget(false)
}

func (this *Shell) CloseWidget(force bool) {
	if this.display.IsDisposed() {
		return
	}
	var event *Event = NewEvent()
	this.SendEventEventTypeEvent(Close, event)
	if (force || event.Doit) && !this.IsDisposed() {
		this.Dispose()
	}
}

func (this *Shell) ComputeSizeWHintHHintChangedOnControl(wHint int32, hHint int32, changed bool) *Point {
	var size *Point = this.Decorations.ComputeSizeWHintHHintChangedOnControl(wHint, hHint, changed)
	if this.toolBar != (nil) {
		if wHint == DEFAULT && this.toolBar.itemCount > 0 {
			var tbSize *Point = this.toolBar.ComputeSize(DEFAULT, DEFAULT)
			size.X = int32(math.Max(float64(tbSize.X), float64(size.X)))
		}
	}
	return size
}

func (this *Shell) ComputeTrim(x int32, y int32, width int32, height int32) *Rectangle {
	this.CheckWidget()
	var trim *Rectangle = this.Decorations.ComputeTrim(x, y, width, height)
	var rect cocoa.NSRect = cocoa.NSRect{}
	rect.X = float64(trim.X)
	rect.Y = float64(trim.Y)
	rect.Width = float64(trim.Width)
	rect.Height = float64(trim.Height)
	if this.window != (nil) {
		if !this._getFullScreen() && !this.FixResize() {
			var h float64 = rect.Height
			rect = this.window.FrameRectForContentRect(rect)
			rect.Y += h - rect.Height
		}
	}
	return NewRectangle(int32(rect.X), int32(rect.Y), int32(rect.Width), int32(rect.Height))
}

func (this *Shell) CreateHandle() {
	this.state |= WidgetHIDDEN
	if this.window == (nil) && this.View == (nil) {
		var styleMask int32 = cocoa.OSNSWindowStyleMaskBorderless
		if (this.style & (TOOL | SHEET)) != 0 {
			this.window = castcocoaNSObjectTococoaNSWindow(cocoa.NewSWTPanel().Alloc())
			if (this.style & SHEET) != 0 {
				styleMask |= cocoa.OSNSWindowStyleMaskDocModalWindow
			} else {
				styleMask |= cocoa.OSNSWindowStyleMaskUtilityWindow | cocoa.OSNSWindowStyleMaskNonactivatingPanel
			}
		} else {
			this.window = castcocoaNSObjectTococoaNSWindow(cocoa.NewSWTWindow().Alloc())
		}
		if (this.style & NO_TRIM) == 0 {
			if (this.style & TITLE) != 0 {
				styleMask |= cocoa.OSNSWindowStyleMaskTitled
			}
			if (this.style & CLOSE) != 0 {
				styleMask |= cocoa.OSNSWindowStyleMaskClosable
			}
			if (this.style & MIN) != 0 {
				styleMask |= cocoa.OSNSWindowStyleMaskMiniaturizable
			}
			if (this.style & MAX) != 0 {
				styleMask |= cocoa.OSNSWindowStyleMaskResizable
			}
			if (this.style & RESIZE) != 0 {
				styleMask |= cocoa.OSNSWindowStyleMaskResizable
			}
		}
		var screen *cocoa.NSScreen = nil
		var primaryScreen *cocoa.NSScreen = cocoa.NewNSScreenOverload2(cocoa.NSScreenScreens().ObjectAtIndex(int64(0)))
		if this.parent != (nil) {
			screen = this.ParentWindow().Screen()
		}
		if screen == (nil) {
			screen = primaryScreen
		}
		this.window = this.window.InitWithContentRectContentRectAStyleBufferingTypeFlagScreen(cocoa.NSRect{}, int64(styleMask), int64(cocoa.OSNSBackingStoreBuffered), (this.style&ON_TOP) != 0, screen)
		if (this.style&(NO_TRIM|BORDER|SHELL_TRIM)) == 0 || (this.style&(TOOL|SHEET)) != 0 {
			this.window.SetHasShadow(true)
		}
		if (this.style & NO_MOVE) != 0 {
			this.window.SetMovable(false)
		}
		if (this.style & TOOL) != 0 {
			(castcocoaNSWindowTococoaNSPanel(this.window)).SetFloatingPanel(false)
			(castcocoaNSWindowTococoaNSPanel(this.window)).SetHidesOnDeactivate(false)
			(castcocoaNSWindowTococoaNSPanel(this.window)).SetBecomesKeyOnlyIfNeeded(false)
		}
		this.window.SetReleasedWhenClosed(true)
		if (this.style & NO_TRIM) == 0 {
			var size cocoa.NSSize = this.window.MinSize()
			size.Width = cocoa.NSWindowMinFrameWidthWithTitle(cocoa.NSStringString(), int64(styleMask))
			this.window.SetMinSize(size)
		}
		if this.FixResize() {
			if this.window.RespondsToSelector(cocoa.OSSel_setMovable_) {
				cocoa.OSObjc_msgSendOverload41(this.window.Id, cocoa.OSSel_setMovable_, 0)
			}
		}
		cocoa.OSObjc_msgSendOverload27(cocoa.OSClass_NSWindow, cocoa.OSSel_setAllowsAutomaticWindowTabbing_, false)
		this.display.CascadeWindow(this.window, screen)
		var screenFrame cocoa.NSRect = screen.Frame()
		var width float64 = screenFrame.Width * 5 / 8
		var height float64 = screenFrame.Height * 5 / 8
		var frame cocoa.NSRect = this.window.Frame()
		var primaryFrame cocoa.NSRect = primaryScreen.Frame()
		frame.Y = primaryFrame.Height - ((primaryFrame.Height - (frame.Y + frame.Height)) + height)
		frame.Width = width
		frame.Height = height
		this.window.SetFrame(frame, false)
		if (this.style & ON_TOP) != 0 {
			this.window.SetLevel(int64(cocoa.OSNSStatusWindowLevel))
		}
		this.Decorations.CreateHandle()
		this.impl.TopView().SetHidden(true)
	} else {
		this.state &= ^WidgetHIDDEN
		if this.window != (nil) {
			this.View = this.window.ContentView()
			if this.View == (nil) {
				this.Decorations.CreateHandle()
			} else {
				this.View.Retain()
			}
		} else {
			var parentView *cocoa.NSView = this.View
			this.Decorations.CreateHandle()
			parentView.AddSubview(this.impl.TopView())
		}
		this.style |= NO_BACKGROUND
	}
	this.windowDelegate = castcocoaNSObjectTococoaSWTWindowDelegate(cocoa.NewSWTWindowDelegate().Alloc().Init())
	if this.window == (nil) {
		var hostWindow *cocoa.NSWindow = this.View.Window()
		this.AttachObserversToWindow(hostWindow)
	} else {
		var behavior int32
		if this.parent != (nil) {
			behavior = cocoa.OSNSWindowCollectionBehaviorMoveToActiveSpace
		} else {
			if (this.style & TOOL) != 0 {
				behavior = cocoa.OSNSWindowCollectionBehaviorFullScreenAuxiliary
			} else {
				behavior = cocoa.OSNSWindowCollectionBehaviorFullScreenPrimary
			}
		}
		this.window.SetCollectionBehavior(int64(behavior))
		this.window.SetAcceptsMouseMovedEvents(true)
		this.window.SetDelegate(upcastcocoaSWTWindowDelegateTococoaId(this.windowDelegate))
	}
	var fieldEditorWindow *cocoa.NSWindow = this.window
	if fieldEditorWindow == (nil) {
		fieldEditorWindow = this.View.Window()
	}
	var id *cocoa.Id = upcastcocoaNSTextTococoaId(fieldEditorWindow.FieldEditor(true, nil))
	if id != (nil) {
		cocoa.OSObject_setClass(id.Id, cocoa.OSObjc_getClass("SWTEditorView"))
		cocoa.NewNSTextViewOverload2(id).SetAllowsUndo(true)
	}
}

func (this *Shell) DeferFlushing() {
	this.deferFlushing = true
	this.View.PerformSelector(cocoa.OSSel_clearDeferFlushing, nil, 0.0, this.display.RunLoopModes())
}

func (this *Shell) Deregister() {
	this.Decorations.Deregister()
	if this.window != (nil) {
		this.display.RemoveWidget(upcastcocoaNSWindowTococoaNSObject(this.window))
	}
	if this.windowDelegate != (nil) {
		this.display.RemoveWidget(upcastcocoaSWTWindowDelegateTococoaNSObject(this.windowDelegate))
	}
}

func (this *Shell) DestroyWidget() {
	var window *cocoa.NSWindow = this.window
	if window != (nil) {
		window.Retain()
	}
	var display *Display = this.display
	var view *cocoa.NSView = this.impl.TopView()
	if view != (nil) {
		view.Retain()
	}
	var sheet bool = (this.style & (SHEET)) != 0
	this.impl.ReleaseHandle()
	if window != (nil) {
		if sheet {
			var application *cocoa.NSApplication = cocoa.NSApplicationSharedApplication()
			application.EndSheet(window, int64(0))
		}
		window.Close()
	} else {
		if view != (nil) {
			view.RemoveFromSuperview()
		}
	}
	if view != (nil) {
		view.Release()
	}
	if window != (nil) {
		if !display.IsDisposed() && int32(len(display.GetShells())) == 0 {
			display.SetMenuBar(nil)
		}
		window.Release()
	}
}

func (this *Shell) DrawBackgroundOnWidget(id int64, context *cocoa.NSGraphicsContext, rect cocoa.NSRect) {
	if id != this.View.Id {
		return
	}
	if this.regionPath != (nil) && this.background == (nil) {
		context.SaveGraphicsState()
		cocoa.NSColorWindowBackgroundColor().SetFill()
		cocoa.NSBezierPathFillRect(rect)
		context.RestoreGraphicsState()
		return
	}
	this.Decorations.DrawBackgroundOnWidget(id, context, rect)
}

func (this *Shell) FindBackgroundControl() *Control {
	var cond150 *Control
	if this.background != (nil) || this.backgroundImage != (nil) {
		cond150 = upcastShellToControl(this)
	} else {
		cond150 = nil
	}
	return cond150
}

func (this *Shell) FindDeferredControl() *Composite {
	var cond151 *Composite
	if this.layoutCount > 0 {
		cond151 = upcastShellToComposite(this)
	} else {
		cond151 = nil
	}
	return cond151
}

func (this *Shell) FindCursor() *Cursor {
	return this.cursor
}

func (this *Shell) FixResize() bool {
	if this.window == (nil) {
		return false
	}
	if (this.style & NO_TRIM) == 0 {
		if (this.style&RESIZE) != 0 && (this.style&(SHEET|TITLE|CLOSE|MIN|MAX)) == 0 {
			return true
		}
	}
	return false
}

func (this *Shell) FixShell(newShellLike ShellLike, controlLike ControlLike) {
	var newShell *Shell
	if newShellLike != nil {
		newShell = newShellLike.AsShell()
	}
	_ = newShell
	var control *Control
	if controlLike != nil {
		control = controlLike.AsControl()
	}
	_ = control
	if this == newShell {
		return
	}
	if control == this.lastActive {
		this.SetActiveControl(nil)
	}
}

func (this *Shell) ForceActive() {
	this.CheckWidget()
	if !this.impl.IsVisible() {
		return
	}
	if this.window == (nil) {
		return
	}
	this.MakeKeyAndOrderFront()
	var application *cocoa.NSApplication = cocoa.NSApplicationSharedApplication()
	application.ActivateIgnoringOtherApps(true)
}

func (this *Shell) GetAlpha() int32 {
	this.CheckWidget()
	if this.window == (nil) {
		return 255
	}
	return int32((this.window.AlphaValue() * 255))
}

func (this *Shell) GetBounds() *Rectangle {
	this.CheckWidget()
	if this.window != (nil) {
		var frame cocoa.NSRect = this.window.Frame()
		var y float64 = this.display.GetPrimaryFrame().Height - float64(int32((frame.Y + frame.Height)))
		return NewRectangle(int32(frame.X), int32(y), int32(frame.Width), int32(frame.Height))
	} else {
		var frame cocoa.NSRect = this.View.Frame()
		var pt cocoa.NSPoint = cocoa.NSPoint{}
		var primaryFrame cocoa.NSRect = this.display.GetPrimaryFrame()
		if !this.View.IsFlipped() {
			pt.Y = this.View.Bounds().Height - pt.Y
		}
		pt = this.View.ConvertPoint_toView_(pt, nil)
		pt = this.View.Window().ConvertBaseToScreen(pt)
		pt.Y = primaryFrame.Height - pt.Y
		return NewRectangle(int32(pt.X), int32(pt.Y), int32(frame.Width), int32(frame.Height))
	}
}

func (this *Shell) GetClientArea() *Rectangle {
	this.CheckWidget()
	var rect cocoa.NSRect
	if this.window != (nil) {
		if !this.FixResize() {
			rect = this.window.ContentView().Frame()
		} else {
			rect = this.window.Frame()
		}
	} else {
		rect = this.impl.TopView().Frame()
	}
	var width int32 = int32(rect.Width)
	var height int32 = int32(rect.Height)
	if this.scrollView != (nil) {
		var size cocoa.NSSize = cocoa.NSSize{}
		size.Width = float64(width)
		size.Height = float64(height)
		size = cocoa.NSScrollViewContentSizeForFrameSize(size, (this.style&H_SCROLL) != 0, (this.style&V_SCROLL) != 0, int64(cocoa.OSNSNoBorder))
		width = int32(size.Width)
		height = int32(size.Height)
	}
	return NewRectangle(0, 0, width, height)
}

func (this *Shell) GetFullScreen() bool {
	this.CheckWidget()
	return this._getFullScreen()
}

func (this *Shell) _getFullScreen() bool {
	if (this.window.CollectionBehavior() & int64(cocoa.OSNSWindowCollectionBehaviorFullScreenPrimary)) != 0 {
		var cond152 bool
		if (this.window.StyleMask() & int64(cocoa.OSNSWindowStyleMaskFullScreen)) != 0 {
			cond152 = true
		} else {
			cond152 = false
		}
		return cond152
	}
	return this.fullScreen
}

func (this *Shell) GetImeInputMode() int32 {
	this.CheckWidget()
	return NONE
}

func (this *Shell) GetLocation() *Point {
	this.CheckWidget()
	if this.window != (nil) {
		var frame cocoa.NSRect = this.window.Frame()
		var y float64 = this.display.GetPrimaryFrame().Height - float64(int32((frame.Y + frame.Height)))
		return NewPoint(int32(frame.X), int32(y))
	} else {
		var pt cocoa.NSPoint = cocoa.NSPoint{}
		var primaryFrame cocoa.NSRect = this.display.GetPrimaryFrame()
		if !this.View.IsFlipped() {
			pt.Y = this.View.Bounds().Height - pt.Y
		}
		pt = this.View.ConvertPoint_toView_(pt, nil)
		pt = this.View.Window().ConvertBaseToScreen(pt)
		pt.Y = primaryFrame.Height - pt.Y
		return NewPoint(int32(pt.X), int32(pt.Y))
	}
}

func (this *Shell) GetMaximized() bool {
	this.CheckWidget()
	if this.window == (nil) {
		return false
	}
	return !this._getFullScreen() && this.window.IsZoomed()
}

func (this *Shell) GetModalShell() *Shell {
	var shell *Shell = nil
	var modalShells []*Shell = this.display.modalShells
	if modalShells != (nil) {
		var bits int32 = APPLICATION_MODAL | SYSTEM_MODAL
		var index int32 = int32(len(modalShells))
		for {
			index--
			if !(index >= 0) {
				break
			}
			var modal *Shell = modalShells[index]
			if modal != (nil) {
				if (modal.style & bits) != 0 {
					var control *Control = upcastShellToControl(this)
					for control != (nil) {
						if control == upcastShellToControl(modal) {
							break
						}
						control = upcastCompositeToControl(control.parent)
					}
					if control != upcastShellToControl(modal) {
						return modal
					}
					break
				}
				if (modal.style & PRIMARY_MODAL) != 0 {
					if shell == (nil) {
						shell = this.impl.GetShell()
					}
					if modal.parent == upcastShellToComposite(shell) {
						return modal
					}
				}
			}
		}
	}
	return nil
}

func (this *Shell) GetModified() bool {
	this.CheckWidget()
	return this.window.IsDocumentEdited()
}

func (this *Shell) GetMinimized() bool {
	this.CheckWidget()
	if !this.GetVisible() {
		return this.Decorations.GetMinimized()
	}
	if this.window == (nil) {
		return false
	}
	return this.window.IsMiniaturized()
}

func (this *Shell) GetMaximumSize() *Point {
	this.CheckWidget()
	if this.window == (nil) {
		return NewPoint(0, 0)
	}
	var size cocoa.NSSize = this.window.MaxSize()
	return NewPoint(int32(size.Width), int32(size.Height))
}

func (this *Shell) GetMinimumSize() *Point {
	this.CheckWidget()
	if this.window == (nil) {
		return NewPoint(0, 0)
	}
	var size cocoa.NSSize = this.window.MinSize()
	return NewPoint(int32(size.Width), int32(size.Height))
}

func (this *Shell) GetRegion() *Region {
	this.CheckWidget()
	return this.region
}

func (this *Shell) GetShell() *Shell {
	this.CheckWidget()
	return this
}

func (this *Shell) GetShells() []*Shell {
	this.CheckWidget()
	var count int32 = 0
	var shells []*Shell = this.display.GetShells()
	for _, activeshell := range shells {
		var shell *Control = upcastShellToControl(activeshell)
		for {
			shell = upcastCompositeToControl(shell.GetParent())
			if !(shell != (nil) && shell != upcastShellToControl(this)) {
				break
			}
		}
		if shell == upcastShellToControl(this) {
			count++
		}
	}
	var index int32 = 0
	var result []*Shell = make([]*Shell, count)
	for _, activeshell := range shells {
		var shell *Control = upcastShellToControl(activeshell)
		for {
			shell = upcastCompositeToControl(shell.GetParent())
			if !(shell != (nil) && shell != upcastShellToControl(this)) {
				break
			}
		}
		if shell == upcastShellToControl(this) {
			t153 := index
			index++
			result[t153] = activeshell
		}
	}
	return result
}

func (this *Shell) GetSize() *Point {
	this.CheckWidget()
	var cond154 cocoa.NSRect
	if this.window != (nil) {
		cond154 = this.window.Frame()
	} else {
		cond154 = this.View.Frame()
	}
	var frame cocoa.NSRect = (cond154)
	return NewPoint(int32(frame.Width), int32(frame.Height))
}

func (this *Shell) GetThemeAlpha() float32 {
	return float32(1)
}

func (this *Shell) GetToolBar() *ToolBar {
	this.CheckWidget()
	if (this.style & NO_TRIM) == 0 {
		if this.toolBar == (nil) {
			this.toolBar = NewToolBar(upcastShellToComposite(this), HORIZONTAL|SMOOTH, true)
		}
	}
	return this.toolBar
}

func (this *Shell) HasBorder() bool {
	return false
}

func (this *Shell) HasRegion() bool {
	return this.region != (nil)
}

func (this *Shell) HelpRequested(id int64, sel int64, theEvent int64) {
	var control *Control = this.display.GetFocusControl()
	for control != (nil) {
		if control.Hooks(Help) {
			control.PostEvent(Help)
			break
		}
		control = upcastCompositeToControl(control.parent)
	}
}

func (this *Shell) InvalidateVisibleRegion() {
	this.impl.ResetVisibleRegion()
	if this.toolBar != (nil) {
		this.toolBar.ResetVisibleRegion()
	}
	this.impl.InvalidateChildrenVisibleRegion()
}

func (this *Shell) IsDrawing() bool {
	return this.impl.GetDrawing()
}

func (this *Shell) IsEnabled() bool {
	this.CheckWidget()
	return this.GetEnabled()
}

func (this *Shell) IsEnabledCursor() bool {
	return true
}

func (this *Shell) IsResizing() bool {
	return (this.state & WidgetRESIZING) != 0
}

func (this *Shell) IsTransparent() bool {
	return false
}

func (this *Shell) IsVisible() bool {
	this.CheckWidget()
	return this.GetVisible()
}

func (this *Shell) MakeFirstResponder(id int64, sel int64, responder int64) bool {
	var display *Display = this.display
	var result bool = this.Decorations.MakeFirstResponder(id, sel, responder)
	if !display.IsDisposed() {
		display.CheckFocus()
	}
	return result
}

func (this *Shell) MakeKeyAndOrderFront() {
	if this.parent != (nil) {
		var parentWindow *cocoa.NSWindow = this.ParentWindow()
		if parentWindow.IsMiniaturized() {
			parentWindow.Deminiaturize(nil)
		}
	}
	this.window.MakeKeyAndOrderFront(nil)
}

func (this *Shell) MouseMoved(id int64, sel int64, theEvent int64) {
	this.Decorations.MouseMoved(id, sel, theEvent)
	if id == this.View.Id && this.window == (nil) {
		this.View.Window().MouseMoved(cocoa.NewNSEventOverload1(theEvent))
	}
}

func (this *Shell) NoResponderFor(id int64, sel int64, selector int64) {
	if selector != cocoa.OSSel_keyDown_ {
		this.Decorations.NoResponderFor(id, sel, selector)
	}
}

func (this *Shell) Open() {
	this.CheckWidget()
	var mask int32 = PRIMARY_MODAL | APPLICATION_MODAL | SYSTEM_MODAL
	if (this.style & mask) != 0 {
		this.display.SetModalShell(this)
	} else {
		this.UpdateModal()
	}
	this.impl.BringToTop(false)
	this.SetWindowVisible(true, true)
	if this.IsDisposed() {
		return
	}
	if !this.RestoreFocus() && !this.TraverseGroup(true) {
		if this.parent == (nil) || !this.ParentWindow().IsMiniaturized() {
			this.impl.SetFocus()
		}
	}
}

func (this *Shell) ParentWindow() *cocoa.NSWindow {
	if this.parent == (nil) {
		return nil
	}
	return this.parent.View.Window()
}

func (this *Shell) Print(gc *GC) bool {
	this.CheckWidget()
	if gc == (nil) {
		this.Error(ERROR_NULL_ARGUMENT)
	}
	if gc.IsDisposed() {
		this.Error(ERROR_INVALID_ARGUMENT)
	}
	var children []*Control = this._getChildren()
	for _, child := range children {
		var bounds *Rectangle = child.impl.GetBounds()
		cocoa.NSGraphicsContextStatic_saveGraphicsState()
		cocoa.NSGraphicsContextSetCurrentContext(gc.Handle)
		var transform *cocoa.NSAffineTransform = cocoa.NSAffineTransformTransform()
		transform.TranslateXBy(float64(bounds.X), float64(bounds.Y))
		transform.Concat()
		child.impl.Print(gc)
		cocoa.NSGraphicsContextStatic_restoreGraphicsState()
	}
	return true
}

func (this *Shell) Register() {
	this.Decorations.Register()
	if this.window != (nil) {
		this.display.AddWidget(upcastcocoaNSWindowTococoaNSObject(this.window), upcastShellToWidget(this))
	}
	if this.windowDelegate != (nil) {
		this.display.AddWidget(upcastcocoaSWTWindowDelegateTococoaNSObject(this.windowDelegate), upcastShellToWidget(this))
	}
}

func (this *Shell) ReleaseChildren(destroy bool) {
	var shells []*Shell = this.GetShells()
	for i := int32(0); i < int32(len(shells)); i++ {
		var shell *Shell = shells[i]
		if shell != (nil) && !shell.IsDisposed() {
			shell.Dispose()
		}
	}
	this.Decorations.ReleaseChildren(destroy)
}

func (this *Shell) ReleaseHandle() {
	if this.window != (nil) {
		this.window.SetDelegate(nil)
	}
	this.RemoveObserversFromWindow()
	if this.windowDelegate != (nil) {
		this.windowDelegate.Release()
	}
	this.windowDelegate = nil
	this.Decorations.ReleaseHandle()
	this.window = nil
}

func (this *Shell) ReleaseParent() {
}

func (this *Shell) ReleaseWidget() {
	this.Decorations.ReleaseWidget()
	if this.toolBar != (nil) {
		this.toolBar.Dispose()
		this.toolBar = nil
	}
	if this.tooltipTag != 0 {
		this.View.Window().ContentView().RemoveToolTip(this.tooltipTag)
		this.tooltipTag = int64(0)
	}
	this.display.ClearModal(this)
	this.UpdateParent(false)
	this.display.UpdateQuitMenu()
	this.lastActive = nil
}

func (this *Shell) RemoveObserversFromWindow() {
	cocoa.NSNotificationCenterDefaultCenter().RemoveObserver(upcastcocoaSWTWindowDelegateTococoaId(this.windowDelegate))
	if this.hostWindow != (nil) {
		var embedCount any = any(this.windowEmbedCounts.Get(this.hostWindow))
		if embedCount == (nil) {
			embedCount = 0
		}
		embedCount = jrt.Cast[int32](embedCount) - 1
		this.windowEmbedCounts.Put(this.hostWindow, embedCount)
		if jrt.Cast[int32](embedCount) <= 0 {
			this.windowEmbedCounts.Remove(this.hostWindow)
			if this.hostWindowClass != 0 {
				cocoa.OSObject_setClass(this.hostWindow.Id, this.hostWindowClass)
			}
			this.display.RemoveWidget(upcastcocoaNSWindowTococoaNSObject(this.hostWindow))
			this.hostWindow.Release()
			this.hostWindow = nil
			this.hostWindowClass = int64(0)
		}
	}
}

func (this *Shell) RemoveShellListener(listener ShellListener) {
	this.CheckWidget()
	if listener == (nil) {
		this.Error(ERROR_NULL_ARGUMENT)
	}
	if this.eventTable == (nil) {
		return
	}
	this.eventTable.UnhookEventTypeListener(Activate, listener)
	this.eventTable.UnhookEventTypeListener(Close, listener)
	this.eventTable.UnhookEventTypeListener(Deactivate, listener)
	this.eventTable.UnhookEventTypeListener(Iconify, listener)
	this.eventTable.UnhookEventTypeListener(Deiconify, listener)
}

func (this *Shell) RequestLayout() {
	this.LayoutOverload4(nil, DEFER)
}

func (this *Shell) ReskinChildren(flags int32) {
	if this.toolBar != (nil) {
		this.toolBar.Reskin(flags)
	}
	var shells []*Shell = this.GetShells()
	for i := int32(0); i < int32(len(shells)); i++ {
		var shell *Shell = shells[i]
		if shell != (nil) {
			shell.Reskin(flags)
		}
	}
	this.Decorations.ReskinChildren(flags)
}

func (this *Shell) SendToolTipEvent(enter bool) {
	if !this.impl.IsVisible() {
		return
	}
	var eventWindow *cocoa.NSWindow = this.View.Window()
	if this.tooltipTag == 0 {
		var view *cocoa.NSView = eventWindow.ContentView()
		this.tooltipTag = view.AddToolTipRect(cocoa.NSRect{}, upcastcocoaNSWindowTococoaId(eventWindow), int64(0))
		if this.tooltipTag != 0 {
			var trackingArea *cocoa.NSTrackingArea = cocoa.NewNSTrackingAreaOverload1(this.tooltipTag)
			var owner *cocoa.Id = trackingArea.Owner()
			if owner != (nil) {
				this.tooltipOwner = owner.Id
			}
			var userInfo *cocoa.Id = upcastcocoaNSDictionaryTococoaId(trackingArea.UserInfo())
			if userInfo != (nil) {
				this.tooltipUserData = userInfo.Id
			} else {
				var value []int64 = make([]int64, 1)
				cocoa.OSObject_getInstanceVariable(this.tooltipTag, []int8{int8('_'), int8('u'), int8('s'), int8('e'), int8('r'), int8('I'), int8('n'), int8('f'), int8('o')}, value)
				this.tooltipUserData = value[0]
			}
		}
	}
	if this.tooltipTag == 0 || this.tooltipOwner == 0 || this.tooltipUserData == 0 {
		return
	}
	var pt cocoa.NSPoint = eventWindow.ConvertScreenToBase(cocoa.NSEventMouseLocation())
	var cond155 int32
	if enter {
		cond155 = cocoa.OSNSMouseEntered
	} else {
		cond155 = cocoa.OSNSMouseExited
	}
	var event *cocoa.NSEvent = cocoa.NSEventEnterExitEventWithType(int64(cond155), pt, int64(0), float64(0), eventWindow.WindowNumber(), nil, int64(0), this.tooltipTag, this.tooltipUserData)
	var cond156 int64
	if enter {
		cond156 = cocoa.OSSel_mouseEntered_
	} else {
		cond156 = cocoa.OSSel_mouseExited_
	}
	cocoa.OSObjc_msgSendOverload44(this.tooltipOwner, cond156, event.Id)
}

func (this *Shell) SetActive() {
	if this.window == (nil) {
		return
	}
	this.CheckWidget()
	if !this.impl.IsVisible() {
		return
	}
	this.MakeKeyAndOrderFront()
}

func (this *Shell) SetActiveControl(controlLike ControlLike) {
	var control *Control
	if controlLike != nil {
		control = controlLike.AsControl()
	}
	_ = control
	this.SetActiveControlControlType(control, None)
}

func (this *Shell) SetActiveControlControlType(controlLike ControlLike, type_ int32) {
	var control *Control
	if controlLike != nil {
		control = controlLike.AsControl()
	}
	_ = control
	if control != (nil) && control.IsDisposed() {
		control = nil
	}
	if this.lastActive != (nil) && this.lastActive.IsDisposed() {
		this.lastActive = nil
	}
	if this.lastActive == control {
		return
	}
	var activate []*Control
	if control == (nil) {
		activate = make([]*Control, 0)
	} else {
		activate = control.GetPath()
	}
	var deactivate []*Control
	if this.lastActive == (nil) {
		deactivate = make([]*Control, 0)
	} else {
		deactivate = this.lastActive.GetPath()
	}
	this.lastActive = control
	var index int32 = 0
	var length int32 = int32(math.Min(float64(int32(len(activate))), float64(int32(len(deactivate)))))
	for index < length {
		if activate[index] != deactivate[index] {
			break
		}
		index++
	}
	for i := int32(int32(len(deactivate)) - 1); i >= index; i-- {
		if !deactivate[i].IsDisposed() {
			deactivate[i].SendEventEventType(Deactivate)
		}
	}
	for i := int32(int32(len(activate)) - 1); i >= index; i-- {
		if !activate[i].IsDisposed() {
			var event *Event = NewEvent()
			event.Detail = type_
			activate[i].SendEventEventTypeEvent(Activate, event)
		}
	}
}

func (this *Shell) SetAlpha(alpha int32) {
	if this.window == (nil) {
		return
	}
	this.CheckWidget()
	alpha &= 0xF
	this.window.SetAlphaValue(float64(float32(alpha) / 255))
}

func (this *Shell) SetBoundsXYWidthHeightMoveResizeOnControl(x int32, y int32, width int32, height int32, move bool, resize bool) {
	if this.window == (nil) {
		if move {
			return
		}
		if resize {
			var frameSize cocoa.NSSize = cocoa.NSSize{}
			frameSize.Width = float64(width)
			frameSize.Height = float64(height)
			this.View.SetFrameSize(frameSize)
			return
		}
	}
	if this._getFullScreen() {
		this.SetFullScreen(false)
	}
	var sheet bool = this.window.IsSheet()
	if sheet && move && !resize {
		return
	}
	var screenHeight int32 = int32(this.display.GetPrimaryFrame().Height)
	var frame cocoa.NSRect = this.window.Frame()
	if !move {
		x = int32(frame.X)
		y = screenHeight - int32((frame.Y + frame.Height))
	}
	if resize {
		var minSize cocoa.NSSize = this.window.MinSize()
		width = int32(math.Max(float64(width), float64(int32(minSize.Width))))
		height = int32(math.Max(float64(height), float64(int32(minSize.Height))))
	} else {
		width = int32(frame.Width)
		height = int32(frame.Height)
	}
	if sheet {
		y = screenHeight - int32((frame.Y + frame.Height))
		var parentRect cocoa.NSRect = this.parent.impl.GetShell().window.Frame()
		frame.Width = float64(width)
		frame.Height = float64(height)
		frame.X = parentRect.X + (parentRect.Width-frame.Width)/2
		frame.Y = float64(screenHeight - int32((float64(y) + frame.Height)))
		this.window.SetFrameFrameRectDisplayFlagAnimateFlag(frame, this.impl.IsVisible(), true)
	} else {
		frame.X = float64(x)
		frame.Y = float64(screenHeight - int32((y + height)))
		frame.Width = float64(width)
		frame.Height = float64(height)
		this.window.SetFrame(frame, this.impl.IsVisible())
	}
}

func (this *Shell) SetClipRegion(view *cocoa.NSView) {
	if this.regionPath != (nil) {
		var rgnView *cocoa.NSView = this.impl.TopView()
		if !rgnView.IsFlipped() {
			rgnView = this.impl.EventView()
		}
		var pt cocoa.NSPoint = view.ConvertPoint_toView_(cocoa.NSPoint{}, rgnView)
		var transform *cocoa.NSAffineTransform = cocoa.NSAffineTransformTransform()
		transform.TranslateXBy(-pt.X, -pt.Y)
		this.regionPath.TransformUsingAffineTransform(transform)
		this.regionPath.AddClip()
		transform.TranslateXBy(2*pt.X, 2*pt.Y)
		this.regionPath.TransformUsingAffineTransform(transform)
	}
}

func (this *Shell) SetEnabled(enabled bool) {
	this.CheckWidget()
	if ((this.state & WidgetDISABLED) == 0) == enabled {
		return
	}
	this.Decorations.SetEnabled(enabled)
	if enabled && this.window != (nil) && this.window.IsMainWindow() {
		if !this.RestoreFocus() {
			this.TraverseGroup(false)
		}
	}
}

func (this *Shell) SetFullScreen(fullScreen bool) {
	this.CheckWidget()
	if this.window == (nil) {
		return
	}
	if this._getFullScreen() == fullScreen {
		return
	}
	if (this.window.CollectionBehavior() & int64(cocoa.OSNSWindowCollectionBehaviorFullScreenPrimary)) != 0 {
		this.window.ToggleFullScreen(upcastcocoaSWTApplicationDelegateTococoaId(DisplayApplicationDelegate))
		return
	}
	this.fullScreen = fullScreen
	if fullScreen {
		this.currentFrame = this.window.Frame()
		this.window.SetShowsResizeIndicator(false)
		if this.window.RespondsToSelector(cocoa.OSSel_setMovable_) {
			cocoa.OSObjc_msgSendOverload41(this.window.Id, cocoa.OSSel_setMovable_, 0)
		}
		this.fullScreenFrame = cocoa.NSScreenMainScreen().Frame()
		if this.GetMonitor().Equals(this.display.GetPrimaryMonitor()) {
			if this.menuBar != (nil) {
				var menuBarHt float64 = cocoa.NSStatusBarSystemStatusBar().Thickness()
				this.fullScreenFrame.Height -= menuBarHt
				cocoa.OSSetSystemUIMode(cocoa.OSKUIModeContentHidden, 0)
			} else {
				cocoa.OSSetSystemUIMode(cocoa.OSKUIModeAllHidden, 0)
			}
		}
		this.window.SetFrame(this.fullScreenFrame, true)
		var contentViewFrame cocoa.NSRect = cocoa.NSRect{}
		contentViewFrame.Width = this.fullScreenFrame.Width
		contentViewFrame.Height = this.fullScreenFrame.Height
		this.window.ContentView().SetFrame(contentViewFrame)
	} else {
		this.window.SetShowsResizeIndicator(true)
		if this.window.RespondsToSelector(cocoa.OSSel_setMovable_) {
			cocoa.OSObjc_msgSendOverload41(this.window.Id, cocoa.OSSel_setMovable_, 1)
		}
		cocoa.OSSetSystemUIMode(cocoa.OSKUIModeNormal, 0)
		this.window.SetFrame(this.currentFrame, true)
	}
}

func (this *Shell) SetMenuBar(menu *Menu) {
	this.CheckWidget()
	this.Decorations.SetMenuBar(menu)
	if this.display.GetActiveShell() == this {
		this.display.SetMenuBar(this.menuBar)
	}
}

func (this *Shell) SetImeInputMode(mode int32) {
	this.CheckWidget()
}

func (this *Shell) SetMaximized(maximized bool) {
	this.CheckWidget()
	this.Decorations.SetMaximized(maximized)
	if this.window == (nil) {
		return
	}
	if this.window.IsZoomed() == maximized {
		return
	}
	this.window.Zoom(nil)
}

func (this *Shell) SetMaximumSize(width int32, height int32) {
	this.CheckWidget()
	if this.window == (nil) {
		return
	}
	var size cocoa.NSSize = cocoa.NSSize{}
	size.Width = float64(width)
	size.Height = float64(height)
	this.window.SetMaxSize(size)
	var frame cocoa.NSRect = this.window.Frame()
	if float64(width) < frame.Width || float64(height) < frame.Height {
		var cond157 float64
		if float64(width) < frame.Width {
			cond157 = float64(width)
		} else {
			cond157 = frame.Width
		}
		width = int32((cond157))
		var cond158 float64
		if float64(height) < frame.Height {
			cond158 = float64(height)
		} else {
			cond158 = frame.Height
		}
		height = int32((cond158))
		this.impl.SetBoundsXYWidthHeightMoveResizeOnControl(0, 0, width, height, false, true)
	}
}

func (this *Shell) SetMaximumSizeSize(sizeLike PointLike) {
	var size *Point
	if sizeLike != nil {
		size = sizeLike.AsPoint()
	}
	_ = size
	this.CheckWidget()
	if size == (nil) {
		this.Error(ERROR_NULL_ARGUMENT)
	}
	this.SetMaximumSize(size.X, size.Y)
}

func (this *Shell) SetMinimized(minimized bool) {
	this.CheckWidget()
	this.Decorations.SetMinimized(minimized)
	if this.window == (nil) {
		return
	}
	if !this.GetVisible() {
		return
	}
	if minimized {
		this.window.Miniaturize(nil)
	} else {
		this.window.Deminiaturize(nil)
	}
}

func (this *Shell) SetMinimumSize(width int32, height int32) {
	this.CheckWidget()
	if this.window == (nil) {
		return
	}
	var size cocoa.NSSize = cocoa.NSSize{}
	size.Width = float64(width)
	size.Height = float64(height)
	this.window.SetMinSize(size)
	var frame cocoa.NSRect = this.window.Frame()
	if float64(width) > frame.Width || float64(height) > frame.Height {
		var cond159 float64
		if float64(width) > frame.Width {
			cond159 = float64(width)
		} else {
			cond159 = frame.Width
		}
		width = int32((cond159))
		var cond160 float64
		if float64(height) > frame.Height {
			cond160 = float64(height)
		} else {
			cond160 = frame.Height
		}
		height = int32((cond160))
		this.impl.SetBoundsXYWidthHeightMoveResizeOnControl(0, 0, width, height, false, true)
	}
}

func (this *Shell) SetMinimumSizeSize(sizeLike PointLike) {
	var size *Point
	if sizeLike != nil {
		size = sizeLike.AsPoint()
	}
	_ = size
	this.CheckWidget()
	if size == (nil) {
		this.Error(ERROR_NULL_ARGUMENT)
	}
	this.SetMinimumSize(size.X, size.Y)
}

func (this *Shell) SetModified(modified bool) {
	this.CheckWidget()
	this.window.SetDocumentEdited(modified)
}

func (this *Shell) GetZoom() int32 {
	return DPIUtilGetNativeDeviceZoom()
}

func (this *Shell) SetRegion(region *Region) {
	this.CheckWidget()
	if (this.style & NO_TRIM) == 0 {
		return
	}
	if this.window == (nil) {
		return
	}
	if region != (nil) {
		if region.IsDisposed() {
			this.Error(ERROR_INVALID_ARGUMENT)
		}
		var bounds *Rectangle = region.GetBounds()
		this.SetSize(bounds.X+bounds.Width, bounds.Y+bounds.Height)
	}
	this.region = region
	if this.regionPath != (nil) {
		this.regionPath.Release()
	}
	this.regionPath = this.GetPathOverload1(region)
	if region != (nil) {
		this.window.SetBackgroundColor(cocoa.NSColorClearColor())
	} else {
		this.window.SetBackgroundColor(cocoa.NSColorWindowBackgroundColor())
	}
	this.UpdateOpaque()
	this.window.ContentView().SetNeedsDisplay(true)
	if this.impl.IsVisible() && this.window.HasShadow() {
		this.window.Display()
		this.window.InvalidateShadow()
	}
}

func (this *Shell) SetScrolling() {
	this.scrolling = true
	this.View.PerformSelector(cocoa.OSSel_clearDeferFlushing, nil, 0.0, this.display.RunLoopModes())
}

func (this *Shell) SetDarkThemePreferred(preferred bool) {
	this.CheckWidget()
	if this.window == (nil) {
		return
	}
	var appearanceName string
	if preferred {
		appearanceName = "NSAppearanceNameDarkAqua"
	} else {
		appearanceName = "NSAppearanceNameAqua"
	}
	var appearance *cocoa.NSAppearance = cocoa.NSAppearanceAppearanceNamed(cocoa.NSStringStringWith(appearanceName))
	if appearance != (nil) {
		cocoa.OSObjc_msgSendOverload44(this.window.Id, cocoa.OSSel_setAppearance_, appearance.Id)
	}
}

func (this *Shell) SetText(string_ string) {
	this.CheckWidget()
	if string_ == "" {
		this.Error(ERROR_NULL_ARGUMENT)
	}
	if this.window == (nil) {
		return
	}
	this.Decorations.SetText(string_)
	var str *cocoa.NSString = cocoa.NSStringStringWith(string_)
	this.window.Impl().SetTitle(str)
}

func (this *Shell) SetVisible(visible bool) {
	this.CheckWidget()
	var mask int32 = PRIMARY_MODAL | APPLICATION_MODAL | SYSTEM_MODAL
	if (this.style & mask) != 0 {
		if visible {
			this.display.SetModalShell(this)
		} else {
			this.display.ClearModal(this)
		}
	} else {
		this.UpdateModal()
	}
	if this.window == (nil) {
		this.Decorations.SetVisible(visible)
	} else {
		this.SetWindowVisible(visible, false)
	}
}

func (this *Shell) PreventShellActivateJvmCrash() {
	DisplayCancelRootMenuTracking()
}

func (this *Shell) SetWindowVisible(visible bool, key bool) {
	if visible {
		if (this.state & WidgetHIDDEN) == 0 {
			return
		}
		this.state &= ^WidgetHIDDEN
	} else {
		if (this.state & WidgetHIDDEN) != 0 {
			return
		}
		this.state |= WidgetHIDDEN
	}
	if this.window != (nil) && (this.window.IsVisible() == visible) {
		return
	}
	if visible {
		this.display.ClearPool()
		if this.center && !this.moved {
			if this.IsDisposed() {
				return
			}
			this.Center()
		}
		this.SendEventEventType(Show)
		if this.IsDisposed() {
			return
		}
		this.impl.TopView().SetHidden(false)
		this.impl.InvalidateVisibleRegion()
		if this.window != (nil) {
			this.PreventShellActivateJvmCrash()
			if (this.style & (SHEET)) != 0 {
				var application *cocoa.NSApplication = cocoa.NSApplicationSharedApplication()
				application.BeginSheet(this.window, this.ParentWindow(), nil, int64(0), int64(0))
			} else {
				var parentMinimized bool = this.parent != (nil) && this.ParentWindow().IsMiniaturized()
				if !parentMinimized {
					if key && (this.style&NO_FOCUS) == 0 {
						this.MakeKeyAndOrderFront()
					} else {
						this.window.OrderFront(nil)
					}
					if this.IsDisposed() {
						return
					}
					if this.minimized != this.window.IsMiniaturized() {
						if this.minimized {
							this.window.Miniaturize(nil)
						} else {
							this.window.Deminiaturize(nil)
						}
					}
				}
			}
		}
		if this.IsDisposed() {
			return
		}
		this.UpdateParent(visible)
		this.opened = true
		if !this.moved {
			this.moved = true
			this.SendEventEventType(Move)
			if this.IsDisposed() {
				return
			}
		}
		if !this.resized {
			this.resized = true
			this.SendEventEventType(Resize)
			if this.IsDisposed() {
				return
			}
			if this.layout != (nil) {
				this.impl.MarkLayout(false, false)
				this.impl.UpdateLayout(false)
			}
		}
	} else {
		this.UpdateParent(visible)
		if this.window != (nil) {
			if (this.style & (SHEET)) != 0 {
				var application *cocoa.NSApplication = cocoa.NSApplicationSharedApplication()
				application.EndSheet(this.window, int64(0))
			}
			this.window.OrderOut(nil)
		}
		if this.IsDisposed() {
			return
		}
		this.impl.TopView().SetHidden(true)
		this.impl.InvalidateVisibleRegion()
		this.SendEventEventType(Hide)
	}
	if this.IsDisposed() {
		return
	}
	this.display.UpdateQuitMenu()
	if this.IsDisposed() {
		return
	}
	var hitView []*cocoa.NSView = make([]*cocoa.NSView, 1)
	var control *Control = this.display.FindControlCheckTrimHitView(false, hitView)
	if control != (nil) && (!control.impl.IsActive() || !control.impl.IsEnabled()) {
		control = nil
	}
	var trimControl *Control = control
	if trimControl != (nil) && trimControl.impl.IsTrim(hitView[0]) {
		trimControl = nil
	}
	this.display.CheckEnterExit(trimControl, nil, false)
}

func (this *Shell) SetZOrderOnControl() {
	if this.scrollView != (nil) {
		this.scrollView.SetDocumentView(upcastcocoaNSViewTococoaId(this.View))
	}
	if this.window == (nil) {
		return
	}
	var cond161 *cocoa.NSView
	if this.scrollView != (nil) {
		cond161 = upcastcocoaNSScrollViewTococoaNSView(this.scrollView)
	} else {
		cond161 = this.View
	}
	this.window.SetContentView(cond161)
	if this.FixResize() {
		var rect cocoa.NSRect = this.window.Frame()
		rect.Y = float64(0)
		rect.X = rect.Y
		this.window.ContentView().SetFrame(rect)
	}
}

func (this *Shell) SetZOrderSiblingAboveOnControl(control *Control, above bool) {
	if this.window == (nil) {
		return
	}
	if !this.GetVisible() {
		return
	}
	if control == (nil) {
		if above {
			this.window.OrderFront(nil)
		} else {
			this.window.OrderBack(nil)
		}
	} else {
		var otherWindow *cocoa.NSWindow = control.impl.GetShell().window
		var cond162 int32
		if above {
			cond162 = cocoa.OSNSWindowAbove
		} else {
			cond162 = cocoa.OSNSWindowBelow
		}
		this.window.OrderWindow(int64(cond162), otherWindow.WindowNumber())
	}
}

func (this *Shell) TraverseEscape() bool {
	if this.parent == (nil) {
		return false
	}
	if !this.impl.IsVisible() || !this.impl.IsEnabled() {
		return false
	}
	this.Close()
	return true
}

func (this *Shell) UpdateCursorRectsOnControl(enabled bool) {
	this.Decorations.UpdateCursorRectsOnControl(enabled)
	if this.toolBar != (nil) {
		this.toolBar.UpdateCursorRectsOnControl(enabled)
	}
}

func (this *Shell) UpdateModal() {
}

func (this *Shell) UpdateOpaque() {
	if this.window == (nil) {
		return
	}
	this.window.SetOpaque(this.region == (nil) && this.glContextCount == 0)
}

func (this *Shell) UpdateParent(visible bool) {
	if this.window != (nil) {
		if visible {
			if this.parent != (nil) && this.parent.GetVisible() {
				var parentWindow *cocoa.NSWindow
				if this.display.modalPanel != (nil) {
					parentWindow = upcastcocoaNSPanelTococoaNSWindow(this.display.modalPanel)
				} else {
					parentWindow = this.ParentWindow()
				}
				parentWindow.AddChildWindow(this.window, int64(cocoa.OSNSWindowAbove))
				if (this.style & ON_TOP) != 0 {
					this.window.SetLevel(int64(cocoa.OSNSStatusWindowLevel))
				} else {
					var parentShell *Shell = castCompositeToShell(this.parent)
					for parentShell.parent != (nil) {
						parentShell = castCompositeToShell(parentShell.parent)
						if parentShell._getFullScreen() {
							this.window.SetLevel(int64(cocoa.OSNSSubmenuWindowLevel))
							break
						}
					}
				}
			}
		} else {
			var parentWindow *cocoa.NSWindow = this.window.ParentWindow()
			if parentWindow != (nil) {
				parentWindow.RemoveChildWindow(this.window)
			}
		}
	}
	var shells []*Shell = this.GetShells()
	for i := int32(0); i < int32(len(shells)); i++ {
		var shell *Shell = shells[i]
		if shell.parent == upcastShellToComposite(this) && shell.GetVisible() {
			shell.UpdateParent(visible)
		}
	}
}

func (this *Shell) UpdateSystemUIMode() {
	if (this.window.CollectionBehavior() & int64(cocoa.OSNSWindowCollectionBehaviorFullScreenPrimary)) != 0 {
		return
	}
	if !this.GetMonitor().Equals(this.display.GetPrimaryMonitor()) {
		return
	}
	var mode int32 = this.display.systemUIMode
	var options int32 = this.display.systemUIOptions
	if this.fullScreen {
		mode = cocoa.OSKUIModeAllHidden
		if this.menuBar != (nil) {
			mode = cocoa.OSKUIModeContentHidden
		}
		options = 0
	}
	var uiMode []int32 = make([]int32, 1)
	var uiOptions []int32 = make([]int32, 1)
	cocoa.OSGetSystemUIMode(uiMode, uiOptions)
	if uiMode[0] != mode || uiOptions[0] != options {
		cocoa.OSSetSystemUIMode(mode, options)
	}
	if this.fullScreen {
		this.window.SetFrame(this.fullScreenFrame, true)
	}
}

func (this *Shell) View_stringForToolTip_point_userData(id int64, sel int64, view int64, tag int64, point int64, userData int64) int64 {
	var pt cocoa.NSPoint = cocoa.NSPoint{}
	cocoa.OSMemmoveOverload3(&pt, point, int64(cocoa.NSPointSizeof))
	var control *Control = this.display.FindControl(false)
	if control == (nil) {
		return int64(0)
	}
	var target *Widget = control.FindTooltip(cocoa.NewNSViewOverload1(view).ConvertPoint_toView_(pt, nil))
	var string_ string = target.impl.TooltipText()
	if string_ == "" {
		return int64(0)
	}
	var chars []uint16 = make([]uint16, int32(len(string_)))
	copy(chars, utf16.Encode([]rune(string_)))
	var length int32 = this.FixMnemonic(chars)
	return cocoa.NSStringStringWithCharacters(chars, int64(length)).Id
}

func (this *Shell) ViewWillMoveToWindow(id int64, sel int64, newWindow int64) {
	if this.window == (nil) {
		var currentWindow int64
		if this.hostWindow != (nil) {
			currentWindow = this.hostWindow.Id
		} else {
			currentWindow = int64(0)
		}
		if currentWindow != 0 {
			this.RemoveObserversFromWindow()
		}
		if newWindow != 0 {
			this.AttachObserversToWindow(cocoa.NewNSWindowOverload1(newWindow))
		}
	}
}

func (this *Shell) WindowDidBecomeKey(id int64, sel int64, notification int64) {
	if this.window != (nil) {
		var display *Display = this.display
		display.SetMenuBar(this.menuBar)
	}
	this.SendEventEventType(Activate)
	if this.IsDisposed() {
		return
	}
	if !this.RestoreFocus() && !this.TraverseGroup(true) {
		this.impl.SetFocus()
	}
	if this.IsDisposed() {
		return
	}
	if (this.window.CollectionBehavior() & int64(cocoa.OSNSWindowCollectionBehaviorFullScreenPrimary)) == 0 {
		var parentShell *Shell = this
		for parentShell.parent != (nil) {
			parentShell = castCompositeToShell(parentShell.parent)
			if parentShell._getFullScreen() {
				break
			}
		}
		if !parentShell._getFullScreen() || this.menuBar != (nil) {
			this.UpdateSystemUIMode()
		} else {
			parentShell.UpdateSystemUIMode()
		}
	}
}

func (this *Shell) WindowDidDeminiturize(id int64, sel int64, notification int64) {
	this.minimized = false
	this.SendEventEventType(Deiconify)
}

func (this *Shell) WindowDidMiniturize(id int64, sel int64, notification int64) {
	this.minimized = true
	this.SendEventEventType(Iconify)
}

func (this *Shell) WindowDidMove(id int64, sel int64, notification int64) {
	this.moved = true
	this.SendEventEventType(Move)
}

func (this *Shell) WindowDidResize(id int64, sel int64, notification int64) {
	if ((this.window.CollectionBehavior() & int64(cocoa.OSNSWindowCollectionBehaviorFullScreenPrimary)) == 0) && this.fullScreen {
		this.window.SetFrame(this.fullScreenFrame, true)
		var contentViewFrame cocoa.NSRect = cocoa.NSRect{}
		contentViewFrame.Width = this.fullScreenFrame.Width
		contentViewFrame.Height = this.fullScreenFrame.Height
		this.window.ContentView().SetFrame(contentViewFrame)
	}
	if this.FixResize() {
		var rect cocoa.NSRect = this.window.Frame()
		rect.Y = float64(0)
		rect.X = rect.Y
		this.window.ContentView().SetFrame(rect)
	}
	this.resized = true
	this.SendEventEventType(Resize)
	if this.IsDisposed() {
		return
	}
	if this.layout != (nil) {
		this.impl.MarkLayout(false, false)
		this.impl.UpdateLayout(false)
	}
}

func (this *Shell) WindowDidResignKey(id int64, sel int64, notification int64) {
	if this.display.IsDisposed() {
		return
	}
	this.SendEventEventType(Deactivate)
	if this.IsDisposed() {
		return
	}
	this.SetActiveControl(nil)
	if this.IsDisposed() {
		return
	}
	this.SaveFocus()
}

func (this *Shell) WindowSendEvent(id int64, sel int64, event int64) {
	var nsEvent *cocoa.NSEvent = cocoa.NewNSEventOverload1(event)
	var type_ int32 = int32(nsEvent.Type())
	switch type_ {
	case cocoa.OSNSLeftMouseDown, cocoa.OSNSRightMouseDown, cocoa.OSNSOtherMouseDown:
		var cond163 int64
		if int64(this.display.clickCountButton) == nsEvent.ButtonNumber() {
			cond163 = nsEvent.ClickCount()
		} else {
			cond163 = int64(1)
		}
		this.display.clickCount = int32((cond163))
		this.display.clickCountButton = int32(nsEvent.ButtonNumber())
		break
	case cocoa.OSNSLeftMouseUp, cocoa.OSNSRightMouseUp, cocoa.OSNSOtherMouseUp, cocoa.OSNSMouseMoved:
		var hitView []*cocoa.NSView = make([]*cocoa.NSView, 1)
		var control *Control = this.display.FindControlCheckTrimHitView(false, hitView)
		if control != (nil) && (!control.impl.IsActive() || !control.impl.IsEnabled()) {
			control = nil
		}
		if type_ == cocoa.OSNSMouseMoved {
			var trimControl *Control = control
			if trimControl != (nil) && trimControl.impl.IsTrim(hitView[0]) {
				trimControl = nil
			}
			this.display.CheckEnterExit(trimControl, nsEvent, false)
			if trimControl != (nil) && (trimControl.state&WidgetWEBKIT_EVENTS_FIX) != 0 {
				trimControl = nil
			}
			if trimControl != (nil) {
				trimControl.SendMouseEvent(nsEvent, type_, false)
			}
		}
		var target *Widget = nil
		if control != (nil) {
			var eventPoint cocoa.NSPoint = nsEvent.LocationInWindow()
			if hitView[0] != (nil) {
				var eventWindow *cocoa.NSWindow = nsEvent.Window()
				if eventWindow != (nil) && eventWindow != hitView[0].Window() {
					eventPoint = eventWindow.ConvertBaseToScreen(eventPoint)
					eventPoint = hitView[0].Window().ConvertScreenToBase(eventPoint)
				}
			}
			target = control.FindTooltip(eventPoint)
		}
		if this.display.tooltipControl != control || this.display.tooltipTarget != target {
			var oldControl *Control = this.display.tooltipControl
			var oldShell *Shell
			if oldControl != (nil) && !oldControl.IsDisposed() {
				oldShell = oldControl.impl.GetShell()
			} else {
				oldShell = nil
			}
			var shell *Shell
			if control != (nil) && !control.IsDisposed() {
				shell = control.impl.GetShell()
			} else {
				shell = nil
			}
			if oldShell != (nil) {
				oldShell.SendToolTipEvent(false)
			}
			if shell != (nil) {
				shell.SendToolTipEvent(true)
			}
		}
		this.display.tooltipControl = control
		this.display.tooltipTarget = target
		break
	case cocoa.OSNSKeyDown:
		if this.display.escAsAcceleratorPresent && int32(nsEvent.KeyCode()) == 53 {
			if this.escMenuItem == (nil) || this.escMenuItem.GetAccelerator() != int32(ESC) {
				this.UpdateEscMenuItem()
			}
			if this.escMenuItem != (nil) {
				var parentMenu *Menu = this.escMenuItem.GetParent()
				if parentMenu != (nil) {
					var escNSMenu *cocoa.NSMenu = parentMenu.nsMenu
					if escNSMenu != (nil) {
						escNSMenu.PerformKeyEquivalent(nsEvent)
					}
				}
			}
		}
		if (nsEvent.ModifierFlags() & int64(cocoa.OSNSEventModifierFlagControl)) != 0 {
			var chars *cocoa.NSString = nsEvent.Characters()
			if chars != (nil) && chars.Length() == 1 {
				var firstChar int32 = int32(chars.CharacterAtIndex(int64(0)))
				switch firstChar {
				case int32('\u0009'), 25, cocoa.OSNSPageDownFunctionKey, cocoa.OSNSPageUpFunctionKey:
					this.View.Window().FirstResponder().KeyDown(nsEvent)
					return
				}
			}
		}
		break
	}
	if this.IsDisposed() {
		return
	}
	this.Decorations.WindowSendEvent(id, sel, event)
}

func (this *Shell) UpdateEscMenuItem() {
	if this.menuBar != (nil) && !this.menuBar.IsDisposed() {
		this.SearchForEscMenuItem(this.menuBar)
	} else {
		if this.display.appMenuBar != (nil) && !this.display.appMenuBar.IsDisposed() {
			this.SearchForEscMenuItem(this.display.appMenuBar)
		}
	}
}

func (this *Shell) SearchForEscMenuItem(menuLike MenuLike) bool {
	var menu *Menu
	if menuLike != nil {
		menu = menuLike.AsMenu()
	}
	_ = menu
	if menu == (nil) || menu.IsDisposed() {
		return false
	}
	var items []*MenuItem = menu.GetItems()
	if items == (nil) {
		return false
	}
	for _, item := range items {
		if item == (nil) || item.IsDisposed() {
			continue
		} else {
			if item.GetAccelerator() == int32(ESC) {
				this.escMenuItem = item
				return true
			} else {
				if (item.GetStyle() & CASCADE) != 0 {
					var subMenu *Menu = item.GetMenu()
					if this.SearchForEscMenuItem(subMenu) {
						return true
					}
				}
			}
		}
	}
	return false
}

func (this *Shell) WindowShouldClose(id int64, sel int64, window int64) bool {
	if this.impl.IsEnabled() {
		this.CloseWidget(false)
	}
	return false
}

func (this *Shell) WindowWillClose(id int64, sel int64, notification int64) {
	this.CloseWidget(true)
}

func ShellInternal_new(displayLike DisplayLike, handle int64) *Shell {
	var display *Display
	if displayLike != nil {
		display = displayLike.AsDisplay()
	}
	_ = display
	return newShellDisplayParentStyleHandleEmbedded(display, nil, NO_TRIM, handle, false)
}

func ShellCocoa_new(displayLike DisplayLike, handle int64) *Shell {
	var display *Display
	if displayLike != nil {
		display = displayLike.AsDisplay()
	}
	_ = display
	return newShellDisplayParentStyleHandleEmbedded(display, nil, NO_TRIM, handle, true)
}

func ShellCheckStyle(parentLike ShellLike, style int32) int32 {
	var parent *Shell
	if parentLike != nil {
		parent = parentLike.AsShell()
	}
	_ = parent
	style = DecorationsCheckStyle(style)
	style &= ^TRANSPARENT
	var mask int32 = SYSTEM_MODAL | APPLICATION_MODAL | PRIMARY_MODAL
	if (style & SHEET) != 0 {
		if DisplayGetSheetEnabled() {
			style &= ^(CLOSE | TITLE | MIN | MAX)
			if parent == (nil) {
				style &= ^SHEET
				style |= SHELL_TRIM
			}
		} else {
			style &= ^SHEET
			var cond164 int32
			if parent == (nil) {
				cond164 = SHELL_TRIM
			} else {
				cond164 = DIALOG_TRIM
			}
			style |= cond164
		}
		if (style & mask) == 0 {
			var cond165 int32
			if parent == (nil) {
				cond165 = APPLICATION_MODAL
			} else {
				cond165 = PRIMARY_MODAL
			}
			style |= cond165
		}
	}
	var bits int32 = style & ^mask
	if (style & SYSTEM_MODAL) != 0 {
		return bits | SYSTEM_MODAL
	}
	if (style & APPLICATION_MODAL) != 0 {
		return bits | APPLICATION_MODAL
	}
	if (style & PRIMARY_MODAL) != 0 {
		return bits | PRIMARY_MODAL
	}
	return bits
}

func upcastcocoaNSWindowTococoaNSObject(x *cocoa.NSWindow) *cocoa.NSObject {
	if x == nil {
		return nil
	}
	return &x.NSObject
}

func upcastShellToWidget(x *Shell) *Widget {
	if x == nil {
		return nil
	}
	return &x.Widget
}

func upcastcocoaSWTWindowDelegateTococoaId(x *cocoa.SWTWindowDelegate) *cocoa.Id {
	if x == nil {
		return nil
	}
	return x.AsId()
}

func upcastcocoaNSWindowTococoaId(x *cocoa.NSWindow) *cocoa.Id {
	if x == nil {
		return nil
	}
	return x.AsId()
}

// j2go: instanceof helper for cocoa.NSWindow and its subclasses within the translated set.
func idImplAsNSWindow(x any) (*cocoa.NSWindow, bool) {
	switch v := x.(type) {
	case *cocoa.NSWindow:
		return v, true
	case *cocoa.NSPanel:
		return &v.NSWindow, true
	case *cocoa.NSColorPanel:
		return &v.NSWindow, true
	case *cocoa.NSFontPanel:
		return &v.NSWindow, true
	case *cocoa.NSSavePanel:
		return &v.NSWindow, true
	case *cocoa.NSOpenPanel:
		return &v.NSWindow, true
	case *cocoa.SFCertificatePanel:
		return &v.NSWindow, true
	case *cocoa.SFCertificateTrustPanel:
		return &v.NSWindow, true
	case *cocoa.SWTPanel:
		return &v.NSWindow, true
	case *cocoa.SWTWindow:
		return &v.NSWindow, true
	}
	return nil, false
}

func castcocoaNSObjectTococoaNSWindow(x *cocoa.NSObject) *cocoa.NSWindow {
	if x == nil {
		return nil
	}
	v, ok := idImplAsNSWindow(x.Impl())
	if !ok {
		panic("java.lang.ClassCastException: cocoa.NSWindow")
	}
	return v
}

// j2go: instanceof helper for cocoa.NSPanel and its subclasses within the translated set.
func idImplAsNSPanel(x any) (*cocoa.NSPanel, bool) {
	switch v := x.(type) {
	case *cocoa.NSPanel:
		return v, true
	case *cocoa.NSColorPanel:
		return &v.NSPanel, true
	case *cocoa.NSFontPanel:
		return &v.NSPanel, true
	case *cocoa.NSSavePanel:
		return &v.NSPanel, true
	case *cocoa.NSOpenPanel:
		return &v.NSPanel, true
	case *cocoa.SFCertificatePanel:
		return &v.NSPanel, true
	case *cocoa.SFCertificateTrustPanel:
		return &v.NSPanel, true
	case *cocoa.SWTPanel:
		return &v.NSPanel, true
	}
	return nil, false
}

func castcocoaNSWindowTococoaNSPanel(x *cocoa.NSWindow) *cocoa.NSPanel {
	if x == nil {
		return nil
	}
	v, ok := idImplAsNSPanel(x.Impl())
	if !ok {
		panic("java.lang.ClassCastException: cocoa.NSPanel")
	}
	return v
}

// j2go: instanceof helper for cocoa.SWTWindowDelegate and its subclasses within the translated set.
func idImplAsSWTWindowDelegate(x any) (*cocoa.SWTWindowDelegate, bool) {
	switch v := x.(type) {
	case *cocoa.SWTWindowDelegate:
		return v, true
	}
	return nil, false
}

func castcocoaNSObjectTococoaSWTWindowDelegate(x *cocoa.NSObject) *cocoa.SWTWindowDelegate {
	if x == nil {
		return nil
	}
	v, ok := idImplAsSWTWindowDelegate(x.Impl())
	if !ok {
		panic("java.lang.ClassCastException: cocoa.SWTWindowDelegate")
	}
	return v
}

func upcastcocoaNSTextTococoaId(x *cocoa.NSText) *cocoa.Id {
	if x == nil {
		return nil
	}
	return x.AsId()
}

func upcastcocoaSWTWindowDelegateTococoaNSObject(x *cocoa.SWTWindowDelegate) *cocoa.NSObject {
	if x == nil {
		return nil
	}
	return &x.NSObject
}

func upcastcocoaNSDictionaryTococoaId(x *cocoa.NSDictionary) *cocoa.Id {
	if x == nil {
		return nil
	}
	return x.AsId()
}

func upcastcocoaSWTApplicationDelegateTococoaId(x *cocoa.SWTApplicationDelegate) *cocoa.Id {
	if x == nil {
		return nil
	}
	return x.AsId()
}

func upcastcocoaNSPanelTococoaNSWindow(x *cocoa.NSPanel) *cocoa.NSWindow {
	if x == nil {
		return nil
	}
	return &x.NSWindow
}

func castCompositeToShell(x *Composite) *Shell {
	if x == nil {
		return nil
	}
	v, ok := widgetImplAsShell(x.impl)
	if !ok {
		panic("java.lang.ClassCastException: Shell")
	}
	return v
}
