// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/DirectoryDialog.java @ af630a9093. DO NOT EDIT.

package swt

import (
	"github.com/haiodo/gowt/internal/jrt"
	"github.com/haiodo/gowt/internal/win32"
	"strings"
	"unicode/utf16"
)

type DirectoryDialog struct {
	Dialog
	message       string
	filterPath    string
	directoryPath string
}

func (this *DirectoryDialog) AsDirectoryDialog() *DirectoryDialog { return this }

type DirectoryDialogLike interface {
	AsDirectoryDialog() *DirectoryDialog
}

func NewDirectoryDialog(parentLike ShellLike) *DirectoryDialog {
	var parent *Shell
	if parentLike != nil {
		parent = parentLike.AsShell()
	}
	_ = parent
	this := &DirectoryDialog{}
	this.impl = this
	this.initDirectoryDialog(parent)
	return this
}

func (this *DirectoryDialog) initDirectoryDialog(parent *Shell) {
	this.initDirectoryDialogParentStyle(parent, APPLICATION_MODAL)
}

func NewDirectoryDialogParentStyle(parentLike ShellLike, style int32) *DirectoryDialog {
	var parent *Shell
	if parentLike != nil {
		parent = parentLike.AsShell()
	}
	_ = parent
	this := &DirectoryDialog{}
	this.impl = this
	this.initDirectoryDialogParentStyle(parent, style)
	return this
}

func (this *DirectoryDialog) initDirectoryDialogParentStyle(parent *Shell, style int32) {
	this.Dialog.initDialogParentStyle(parent, DialogCheckStyle(parent, style))
	this.message = ""
	this.filterPath = ""
	this.impl.checkSubclass_()
}

func (this *DirectoryDialog) GetFilterPath() string {
	return this.filterPath
}

func (this *DirectoryDialog) GetMessage() string {
	return this.message
}

func (this *DirectoryDialog) Open() string {
	var tret673 string
	tretd674 := false
	func() {
		defer func() {
			r := recover()
			if r == nil {
				return
			}
			if func() bool {
				switch r.(type) {
				case *SWTException:
					return true
				}
				return false
			}() {
				e := r.(*SWTException)
				_ = e
				if e.Code == ERROR_INVALID_RETURN_VALUE {
					tret673 = ""
					tretd674 = true
					return
				}
				panic(e)
			} else {
				panic(r)
			}
		}()
		tret673 = jrt.Cast[string](this.OpenDialog().OrElse(""))
		tretd674 = true
		return
	}()
	_ = tretd674
	return tret673
}

func (this *DirectoryDialog) OpenDialog() *jrt.Optional {
	this.directoryPath = ""
	var ppv []int64 = make([]int64, 1)
	var hr int32 = win32.COME_FAIL
	if win32.COMCoCreateInstance(win32.COMCLSID_FileOpenDialog, int64(0), win32.COMCLSCTX_INPROC_SERVER, win32.COMIID_IFileOpenDialog, ppv) == win32.OSS_OK {
		var fileDialog *win32.IFileDialog = win32.NewIFileDialog(ppv[0])
		var options []int32 = make([]int32, 1)
		if fileDialog.GetOptions(options) == win32.OSS_OK {
			options[0] |= win32.OSFOS_PICKFOLDERS | win32.OSFOS_FORCEFILESYSTEM | win32.OSFOS_NOCHANGEDIR
			fileDialog.SetOptions(options[0])
		}
		if this.title == "" {
			this.title = ""
		}
		if jrt.StringLength(this.title) > 0 {
			var buffer []uint16 = make([]uint16, jrt.StringLength(this.title)+1)
			jrt.GetChars(this.title, 0, jrt.StringLength(this.title), buffer, 0)
			fileDialog.SetTitle(buffer)
		}
		if this.filterPath != "" && jrt.StringLength(this.filterPath) > 0 {
			var path string = strings.ReplaceAll(this.filterPath, string(rune('/')), string(rune('\u005c')))
			var buffer []uint16 = make([]uint16, jrt.StringLength(path)+1)
			jrt.GetChars(path, 0, jrt.StringLength(path), buffer, 0)
			if win32.COMSHCreateItemFromParsingName(buffer, int64(0), win32.COMIID_IShellItem, ppv) == win32.OSS_OK {
				var psi *win32.IShellItem = win32.NewIShellItem(ppv[0])
				fileDialog.ClearClientData()
				fileDialog.SetDefaultFolder(psi)
				psi.Release()
			}
		}
		var display *Display = this.parent.GetDisplay()
		var hwndOwner int64 = this.parent.Handle
		display.externalEventLoop = true
		hr = fileDialog.Show(hwndOwner)
		if hr == win32.OSS_OK {
			if fileDialog.GetResult(ppv) == win32.OSS_OK {
				var psi *win32.IShellItem = win32.NewIShellItem(ppv[0])
				if psi.GetDisplayName(win32.OSSIGDN_FILESYSPATH, ppv) == win32.OSS_OK {
					var wstr int64 = ppv[0]
					var length int32 = win32.OSWcslen(wstr)
					var buffer []uint16 = make([]uint16, length)
					win32.OSMoveMemoryOverload2(buffer, wstr, length*2)
					win32.OSCoTaskMemFree(wstr)
					this.directoryPath = string(utf16.Decode(buffer))
				}
				psi.Release()
			}
		}
		display.externalEventLoop = false
		fileDialog.Release()
	}
	if hr == win32.COMS_OK {
		return jrt.OptionalOfNullable(this.directoryPath)
	} else {
		if hr == win32.OSHRESULT_FROM_WIN32(win32.OSERROR_CANCELED) {
			return jrt.OptionalEmpty()
		}
	}
	panic(NewSWTExceptionCode(ERROR_INVALID_RETURN_VALUE))
}

func (this *DirectoryDialog) SetFilterPath(string_ string) {
	this.filterPath = string_
}

func (this *DirectoryDialog) SetMessage(string_ string) {
	if string_ == jrt.NullString {
		this.Error(ERROR_NULL_ARGUMENT)
	}
	this.message = string_
}
