// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Decorations.java @ af630a9093. DO NOT EDIT.

package swt

import (
	"github.com/haiodo/gowt/internal/cocoa"
)

type Decorations struct {
	Canvas
	image         *Image
	images        []*Image
	menuBar       *Menu
	text          string
	minimized     bool
	maximized     bool
	savedFocus    *Control
	defaultButton *Button
}

func (this *Decorations) AsDecorations() *Decorations { return this }

type DecorationsLike interface {
	AsDecorations() *Decorations
}

func newDecorations() *Decorations {
	this := &Decorations{}
	this.impl = this
	this.initDecorations()
	return this
}

func (this *Decorations) initDecorations() {
	this.Canvas.initCanvas()
	this.images = make([]*Image, 0)
	this.text = ""
}

func NewDecorationsParentStyle(parentLike CompositeLike, style int32) *Decorations {
	var parent *Composite
	if parentLike != nil {
		parent = parentLike.AsComposite()
	}
	_ = parent
	this := &Decorations{}
	this.impl = this
	this.initDecorationsParentStyle(parent, style)
	return this
}

func (this *Decorations) initDecorationsParentStyle(parent *Composite, style int32) {
	this.Canvas.initCanvasParentStyle(parent, DecorationsCheckStyle(style))
	this.images = make([]*Image, 0)
	this.text = ""
}

func (this *Decorations) BringToTop(force bool) {
	this.MoveAbove(nil)
}

func (this *Decorations) CheckSubclass() {
	if !this.IsValidSubclass() {
		this.Error(ERROR_INVALID_SUBCLASS)
	}
}

func (this *Decorations) Compare(data1Like ImageDataLike, data2Like ImageDataLike) int32 {
	var data1 *ImageData
	if data1Like != nil {
		data1 = data1Like.AsImageData()
	}
	_ = data1
	var data2 *ImageData
	if data2Like != nil {
		data2 = data2Like.AsImageData()
	}
	_ = data2
	if data1.Width == data2.Width && data1.Height == data2.Height {
		var transparent1 int32 = data1.GetTransparencyType()
		var transparent2 int32 = data2.GetTransparencyType()
		if transparent1 == TRANSPARENCY_ALPHA {
			return -1
		}
		if transparent2 == TRANSPARENCY_ALPHA {
			return 1
		}
		if transparent1 == TRANSPARENCY_MASK {
			return -1
		}
		if transparent2 == TRANSPARENCY_MASK {
			return 1
		}
		if transparent1 == TRANSPARENCY_PIXEL {
			return -1
		}
		if transparent2 == TRANSPARENCY_PIXEL {
			return 1
		}
		return 0
	}
	var cond147 int32
	if data1.Width > data2.Width || data1.Height > data2.Height {
		cond147 = -1
	} else {
		cond147 = 1
	}
	return cond147
}

func (this *Decorations) ComputeTabGroup() *Widget {
	return upcastDecorationsToWidget(this)
}

func (this *Decorations) ComputeTabRoot() *Control {
	return upcastDecorationsToControl(this)
}

func (this *Decorations) FixDecorations(newDecorationsLike DecorationsLike, controlLike ControlLike, menus []*Menu) {
	var newDecorations *Decorations
	if newDecorationsLike != nil {
		newDecorations = newDecorationsLike.AsDecorations()
	}
	_ = newDecorations
	var control *Control
	if controlLike != nil {
		control = controlLike.AsControl()
	}
	_ = control
	if this == newDecorations {
		return
	}
	if control == this.savedFocus {
		this.savedFocus = nil
	}
	if control == upcastButtonToControl(this.defaultButton) {
		this.defaultButton = nil
	}
	if menus == (nil) {
		return
	}
	var menu *Menu = control.menu
	if menu != (nil) {
		var index int32 = 0
		for index < int32(len(menus)) {
			if menus[index] == menu {
				control.SetMenu(nil)
				return
			}
			index++
		}
		menu.FixMenus(newDecorations)
	}
}

func (this *Decorations) GetDefaultButton() *Button {
	this.CheckWidget()
	if this.defaultButton != (nil) && this.defaultButton.IsDisposed() {
		return nil
	}
	return this.defaultButton
}

func (this *Decorations) GetImage() *Image {
	this.CheckWidget()
	return this.image
}

func (this *Decorations) GetImages() []*Image {
	this.CheckWidget()
	if this.images == (nil) {
		return make([]*Image, 0)
	}
	var result []*Image = make([]*Image, int32(len(this.images)))
	copy(result[0:], this.images[0:0+int32(len(this.images))])
	return result
}

func (this *Decorations) GetMaximized() bool {
	this.CheckWidget()
	return this.maximized
}

func (this *Decorations) GetMenuBar() *Menu {
	this.CheckWidget()
	return this.menuBar
}

func (this *Decorations) GetMinimized() bool {
	this.CheckWidget()
	return this.minimized
}

func (this *Decorations) GetNameText() string {
	return this.GetText()
}

func (this *Decorations) GetText() string {
	this.CheckWidget()
	return this.text
}

func (this *Decorations) IsReparentable() bool {
	this.CheckWidget()
	return false
}

func (this *Decorations) IsTabGroup() bool {
	return true
}

func (this *Decorations) IsTabItem() bool {
	return false
}

func (this *Decorations) MenuShell() *Decorations {
	return this
}

func (this *Decorations) ReleaseChildren(destroy bool) {
	if this.menuBar != (nil) {
		this.menuBar.Dispose()
		this.menuBar = nil
	}
	var display *Display = this.display
	if display == (nil) || display.IsDisposed() {
		return
	}
	this.Canvas.ReleaseChildren(destroy)
	var menus []*Menu = display.GetMenus(this)
	if menus != (nil) {
		for i := int32(0); i < int32(len(menus)); i++ {
			var menu *Menu = menus[i]
			if menu != (nil) && !menu.IsDisposed() {
				menu.Dispose()
			}
		}
		menus = nil
	}
}

func (this *Decorations) ReleaseWidget() {
	this.Canvas.ReleaseWidget()
	this.image = nil
	this.images = nil
	this.savedFocus = nil
	this.defaultButton = nil
}

func (this *Decorations) ReskinChildren(flags int32) {
	if this.menuBar != (nil) {
		this.menuBar.Reskin(flags)
	}
	var menus []*Menu = this.display.GetMenus(this)
	if menus != (nil) {
		for i := int32(0); i < int32(len(menus)); i++ {
			var menu *Menu = menus[i]
			if menu != (nil) {
				menu.Reskin(flags)
			}
		}
	}
	this.Canvas.ReskinChildren(flags)
}

func (this *Decorations) RestoreFocus() bool {
	if this.savedFocus != (nil) && this.savedFocus.IsDisposed() {
		this.savedFocus = nil
	}
	if this.savedFocus == (nil) {
		return false
	}
	return this.savedFocus.impl.SetFocus()
}

func (this *Decorations) SaveFocus() {
	var control *Control = this.display._getFocusControl(this.View.Window())
	if control != (nil) && control != upcastDecorationsToControl(this) && this == control.impl.MenuShell() {
		this.SetSavedFocus(control)
	}
}

func (this *Decorations) SetDefaultButton(buttonLike ButtonLike) {
	var button *Button
	if buttonLike != nil {
		button = buttonLike.AsButton()
	}
	_ = button
	this.CheckWidget()
	if button != (nil) {
		if button.IsDisposed() {
			this.Error(ERROR_INVALID_ARGUMENT)
		}
		if button.impl.MenuShell() != this {
			this.Error(ERROR_INVALID_PARENT)
		}
		if (button.style & PUSH) == 0 {
			return
		}
	}
	if button == this.defaultButton {
		return
	}
	this.defaultButton = button
	var cell *cocoa.NSButtonCell = nil
	if this.defaultButton != (nil) && (this.defaultButton.style&PUSH) != 0 {
		cell = cocoa.NewNSButtonCellOverload2(upcastcocoaNSCellTococoaId((castcocoaNSViewTococoaNSButton(this.defaultButton.View)).Cell()))
	}
	this.View.Window().SetDefaultButtonCell(cell)
	this.display.UpdateDefaultButton()
}

func (this *Decorations) SetImage(imageLike ImageLike) {
	var image *Image
	if imageLike != nil {
		image = imageLike.AsImage()
	}
	_ = image
	this.CheckWidget()
	if image != (nil) && image.impl.IsDisposed() {
		this.Error(ERROR_INVALID_ARGUMENT)
	}
	this.image = image
	if this.parent != (nil) {
		return
	}
	if this.display.dockImage == (nil) && !this.display.IsBundledIconSet() {
		var cond148 *cocoa.NSImage
		if image != (nil) {
			cond148 = image.Handle
		} else {
			cond148 = nil
		}
		this.display.application.SetApplicationIconImage(cond148)
	}
}

func (this *Decorations) SetImages(images []*Image) {
	this.CheckWidget()
	if images == (nil) {
		this.Error(ERROR_INVALID_ARGUMENT)
	}
	for i := int32(0); i < int32(len(images)); i++ {
		if images[i] == (nil) || images[i].impl.IsDisposed() {
			this.Error(ERROR_INVALID_ARGUMENT)
		}
	}
	this.images = images
	if this.parent != (nil) {
		return
	}
	if this.display.dockImage == (nil) && !this.display.IsBundledIconSet() {
		if images != (nil) && int32(len(images)) > 1 {
			var bestImages []*Image = make([]*Image, int32(len(images)))
			copy(bestImages[0:], images[0:0+int32(len(images))])
			this.Sort(bestImages)
			images = bestImages
		}
		if images != (nil) && int32(len(images)) > 0 {
			this.display.application.SetApplicationIconImage(images[0].Handle)
		} else {
			this.display.application.SetApplicationIconImage(nil)
		}
	}
}

func (this *Decorations) SetMaximized(maximized bool) {
	this.CheckWidget()
	this.maximized = maximized
}

func (this *Decorations) SetMenuBar(menu *Menu) {
	this.CheckWidget()
	if this.menuBar == menu {
		return
	}
	if menu != (nil) {
		if menu.IsDisposed() {
			this.Error(ERROR_INVALID_ARGUMENT)
		}
		if (menu.style & BAR) == 0 {
			this.Error(ERROR_MENU_NOT_BAR)
		}
		if menu.parent != this {
			this.Error(ERROR_INVALID_PARENT)
		}
	}
	this.menuBar = menu
}

func (this *Decorations) SetMinimized(minimized bool) {
	this.CheckWidget()
	this.minimized = minimized
}

func (this *Decorations) SetSavedFocus(controlLike ControlLike) {
	var control *Control
	if controlLike != nil {
		control = controlLike.AsControl()
	}
	_ = control
	this.savedFocus = control
}

func (this *Decorations) SetText(string_ string) {
	this.CheckWidget()
	if string_ == "" {
		this.Error(ERROR_NULL_ARGUMENT)
	}
	this.text = string_
}

func (this *Decorations) Sort(images []*Image) {
	var length int32 = int32(len(images))
	if length <= 1 {
		return
	}
	var datas []*ImageData = make([]*ImageData, length)
	for i := int32(0); i < length; i++ {
		datas[i] = images[i].GetImageData()
	}
	for gap := int32(length / 2); gap > 0; gap /= 2 {
		for i := int32(gap); i < length; i++ {
			for j := int32(i - gap); j >= 0; j -= gap {
				if this.Compare(datas[j], datas[j+gap]) >= 0 {
					var swap *Image = images[j]
					images[j] = images[j+gap]
					images[j+gap] = swap
					var swapData *ImageData = datas[j]
					datas[j] = datas[j+gap]
					datas[j+gap] = swapData
				}
			}
		}
	}
}

func (this *Decorations) TraverseItem(next bool) bool {
	return false
}

func (this *Decorations) TraverseReturn() bool {
	if this.defaultButton == (nil) || this.defaultButton.IsDisposed() {
		return false
	}
	if !this.defaultButton.impl.IsVisible() || !this.defaultButton.impl.IsEnabled() {
		return false
	}
	this.defaultButton.Click()
	return true
}

func DecorationsCheckStyle(style int32) int32 {
	if (style & NO_TRIM) != 0 {
		style &= ^(CLOSE | TITLE | MIN | MAX | RESIZE | BORDER)
	} else {
		if (style & NO_MOVE) != 0 {
			style |= TITLE
		}
	}
	if (style & (MENU | MIN | MAX | CLOSE)) != 0 {
		style |= TITLE
	}
	return style
}

func upcastDecorationsToWidget(x *Decorations) *Widget {
	if x == nil {
		return nil
	}
	return &x.Widget
}

func upcastDecorationsToControl(x *Decorations) *Control {
	if x == nil {
		return nil
	}
	return &x.Control
}

func upcastButtonToControl(x *Button) *Control {
	if x == nil {
		return nil
	}
	return &x.Control
}

// j2go: instanceof helper for cocoa.NSButton and its subclasses within the translated set.
func idImplAsNSButton(x any) (*cocoa.NSButton, bool) {
	switch v := x.(type) {
	case *cocoa.NSButton:
		return v, true
	case *cocoa.NSPopUpButton:
		return &v.NSButton, true
	case *cocoa.SWTPopUpButton:
		return &v.NSButton, true
	case *cocoa.SWTButton:
		return &v.NSButton, true
	}
	return nil, false
}

func castcocoaNSViewTococoaNSButton(x *cocoa.NSView) *cocoa.NSButton {
	if x == nil {
		return nil
	}
	v, ok := idImplAsNSButton(x.Impl())
	if !ok {
		panic("java.lang.ClassCastException: cocoa.NSButton")
	}
	return v
}

func upcastcocoaNSCellTococoaId(x *cocoa.NSCell) *cocoa.Id {
	if x == nil {
		return nil
	}
	return x.AsId()
}
