// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Menu.java @ af630a9093. DO NOT EDIT.

package swt

import (
	"fmt"
	"github.com/haiodo/gowt/internal/cocoa"
	"github.com/haiodo/gowt/internal/jrt"
	"math"
	"reflect"
	"strings"
)

type Menu struct {
	Widget
	nsMenu      *cocoa.NSMenu
	x           int32
	y           int32
	itemCount   int32
	hasLocation bool
	visible     bool
	items       []*MenuItem
	cascade     *MenuItem
	defaultItem *MenuItem
	parent      *Decorations
}

func (this *Menu) AsMenu() *Menu { return this }

type MenuLike interface {
	AsMenu() *Menu
}

const MenuGAP int32 = 4

func NewMenu(parentLike ControlLike) *Menu {
	var parent *Control
	if parentLike != nil {
		parent = parentLike.AsControl()
	}
	_ = parent
	this := &Menu{}
	this.impl = this
	this.initMenu(parent)
	return this
}

func (this *Menu) initMenu(parent *Control) {
	this.initMenuParentStyle(MenuCheckNull(parent).impl.menuShell_(), POP_UP)
}

func NewMenuParentStyle(parentLike DecorationsLike, style int32) *Menu {
	var parent *Decorations
	if parentLike != nil {
		parent = parentLike.AsDecorations()
	}
	_ = parent
	this := &Menu{}
	this.impl = this
	this.initMenuParentStyle(parent, style)
	return this
}

func (this *Menu) initMenuParentStyle(parent *Decorations, style int32) {
	this.Widget.initWidget()
	this.impl.checkSubclass_()
	this.impl.checkParent_(upcastDecorationsToWidget(parent))
	this.style = MenuCheckStyle(style)
	if parent != (nil) {
		this.display = parent.display
	} else {
		this.display = DisplayGetCurrent()
		if this.display == (nil) {
			this.display = DisplayGetDefault()
		}
		if !this.display.IsValidThread() {
			this.Error(ERROR_THREAD_INVALID_ACCESS)
		}
	}
	this.parent = parent
	this.ReskinWidget()
	this.impl.createWidget_()
}

func NewMenuParentMenu(parentMenuLike MenuLike) *Menu {
	var parentMenu *Menu
	if parentMenuLike != nil {
		parentMenu = parentMenuLike.AsMenu()
	}
	_ = parentMenu
	this := &Menu{}
	this.impl = this
	this.initMenuParentMenu(parentMenu)
	return this
}

func (this *Menu) initMenuParentMenu(parentMenu *Menu) {
	this.initMenuParentStyle(MenuCheckNullMenu(parentMenu).parent, DROP_DOWN)
}

func NewMenuParentItem(parentItemLike MenuItemLike) *Menu {
	var parentItem *MenuItem
	if parentItemLike != nil {
		parentItem = parentItemLike.AsMenuItem()
	}
	_ = parentItem
	this := &Menu{}
	this.impl = this
	this.initMenuParentItem(parentItem)
	return this
}

func (this *Menu) initMenuParentItem(parentItem *MenuItem) {
	this.initMenuParentMenu(MenuCheckNullItem(parentItem).parent)
}

func newMenuDisplay(display *Display) *Menu {
	this := &Menu{}
	this.impl = this
	this.initMenuDisplay(display)
	return this
}

func (this *Menu) initMenuDisplay(display *Display) {
	this.Widget.initWidget()
	if display == (nil) {
		display = DisplayGetCurrent()
	}
	if display == (nil) {
		display = DisplayGetDefault()
	}
	if !display.IsValidThread() {
		this.Error(ERROR_THREAD_INVALID_ACCESS)
	}
	this.display = display
	this.style = BAR
	this.ReskinWidget()
	this.impl.createWidget_()
}

func newMenuDisplayNativeMenu(display *Display, nativeMenu *cocoa.NSMenu) *Menu {
	this := &Menu{}
	this.impl = this
	this.initMenuDisplayNativeMenu(display, nativeMenu)
	return this
}

func (this *Menu) initMenuDisplayNativeMenu(display *Display, nativeMenu *cocoa.NSMenu) {
	this.Widget.initWidget()
	this.display = display
	this.style = DROP_DOWN
	this.nsMenu = nativeMenu
	this.ReskinWidget()
	this.impl.createWidget_()
}

func (this *Menu) checkParent_(parent *Widget) {
	if parent == (nil) && DisplayGetDefault().appMenuBar == (nil) {
		this.Error(ERROR_NULL_ARGUMENT)
	}
	if parent != (nil) {
		if parent.IsDisposed() {
			this.Error(ERROR_INVALID_ARGUMENT)
		}
		parent.CheckWidget()
		parent.impl.checkOpen_()
	}
}

func (this *Menu) _setVisible(visible bool) {
	if (this.style & (BAR | DROP_DOWN)) != 0 {
		return
	}
	var trayItem *TrayItem = this.display.currentTrayItem
	if trayItem != (nil) && visible {
		trayItem.ShowMenu(this)
		return
	}
	if visible {
		var shell *Shell = this.GetShell()
		var window *cocoa.NSWindow = shell.View.Window()
		var location cocoa.NSPoint = cocoa.NSPoint{}
		if this.hasLocation {
			var topView *cocoa.NSView = window.ContentView()
			var shellCoord *Point = this.display.Map(nil, upcastShellToControl(shell), NewPoint(this.x, this.y))
			location = cocoa.NSPoint{}
			location.X = float64(shellCoord.X)
			location.Y = topView.Frame().Height - float64(shellCoord.Y)
		} else {
			location = window.MouseLocationOutsideOfEventStream()
		}
		this.hasLocation = false
		window.Retain()
		var display *Display = this.display
		display.SendPreExternalEventDispatchEvent()
		var nsEvent *cocoa.NSEvent = cocoa.NSEventOtherEventWithType(int64(cocoa.OSNSApplicationDefined), location, int64(0), 0.0, window.WindowNumber(), window.GraphicsContext(), int16(0), int64(0), int64(0))
		cocoa.NSMenuPopUpContextMenu(this.nsMenu, nsEvent, shell.View)
		display.SendPostExternalEventDispatchEvent()
		window.Release()
	} else {
		this.nsMenu.CancelTracking()
	}
}

func (this *Menu) AddHelpListener(listener HelpListener) {
	this.AddTypedListener(listener, []int32{Help})
}

func (this *Menu) AddMenuListener(listener MenuListener) {
	this.AddTypedListener(listener, []int32{Hide, Show})
}

func (this *Menu) createHandle_() {
	this.display.AddMenu(this)
	if this.nsMenu == (nil) {
		var widget *cocoa.NSMenu = castcocoaNSObjectTococoaNSMenu(cocoa.NewSWTMenu().Alloc())
		widget = widget.InitWithTitle(cocoa.NSStringString())
		widget.SetAutoenablesItems(false)
		widget.SetDelegate(upcastcocoaNSMenuTococoaId(widget))
		this.nsMenu = widget
	} else {
		this.nsMenu.Retain()
		var cls int64 = cocoa.OSObject_getClass(this.nsMenu.Id)
		var dynNSMenu_class int64 = this.display.CreateMenuSubclass(cls, "SWTSystemMenu", true)
		if cls != dynNSMenu_class {
			cocoa.OSObject_setClass(this.nsMenu.Id, dynNSMenu_class)
		}
		this.nsMenu.SetDelegate(upcastcocoaNSMenuTococoaId(this.nsMenu))
	}
}

func (this *Menu) CreateItem(itemLike MenuItemLike, index int32) {
	var item *MenuItem
	if itemLike != nil {
		item = itemLike.AsMenuItem()
	}
	_ = item
	if !(0 <= index && index <= this.itemCount) {
		this.Error(ERROR_INVALID_RANGE)
	}
	var add bool = true
	var nsItem *cocoa.NSMenuItem = item.nsItem
	if nsItem == (nil) {
		if (item.style & SEPARATOR) != 0 {
			nsItem = cocoa.NSMenuItemSeparatorItem()
			nsItem.Retain()
		} else {
			nsItem = castcocoaNSObjectTococoaNSMenuItem(cocoa.NewSWTMenuItem().Alloc())
			var empty *cocoa.NSString = cocoa.NSStringString()
			nsItem.InitWithTitle(empty, int64(0), empty)
			nsItem.SetTarget(upcastcocoaNSMenuItemTococoaId(nsItem))
			nsItem.SetAction(cocoa.OSSel_sendSelection)
		}
		item.nsItem = nsItem
	} else {
		var cls int64 = cocoa.OSObject_getClass(nsItem.Id)
		var dynNSMenuItem_class int64 = this.display.CreateMenuItemSubclass(cls, "SWTSystemMenuItem", true)
		if cls != dynNSMenuItem_class {
			cocoa.OSObject_setClass(nsItem.Id, dynNSMenuItem_class)
		}
		nsItem.Retain()
		item.nsItemAction = nsItem.Action()
		item.nsItemTarget = nsItem.Target()
		nsItem.SetTarget(upcastcocoaNSMenuItemTococoaId(nsItem))
		nsItem.SetAction(cocoa.OSSel_sendSelection)
		var type_ int32 = PUSH
		if nsItem.IsSeparatorItem() {
			type_ = SEPARATOR
		}
		if nsItem.Submenu() != (nil) {
			type_ = CASCADE
		}
		item.style |= type_
		item.text = nsItem.Title().GetString()
		var keyMask int64 = nsItem.KeyEquivalentModifierMask()
		var keyEquivString *cocoa.NSString = nsItem.KeyEquivalent()
		var keyEquiv int64 = int64(0)
		if keyEquivString != (nil) {
			keyEquiv = int64(keyEquivString.CharacterAtIndex(int64(0)))
			if (keyMask & int64(cocoa.OSNSEventModifierFlagCommand)) != 0 {
				keyEquiv |= int64(COMMAND)
			}
			if (keyMask & int64(cocoa.OSNSAlternateKeyMask)) != 0 {
				keyEquiv |= int64(ALT)
			}
			item.accelerator = int32(keyEquiv)
		}
		add = false
	}
	item.CreateJNIRef()
	item.impl.register_()
	if add {
		this.nsMenu.InsertItem(nsItem, int64(index))
	}
	if this.itemCount == int32(len(this.items)) {
		var newItems []*MenuItem = make([]*MenuItem, int32(len(this.items))+4)
		copy(newItems[0:], this.items[0:0+int32(len(this.items))])
		this.items = newItems
	}
	t175 := this.itemCount
	this.itemCount++
	copy(this.items[index+1:], this.items[index:index+t175-index])
	this.items[index] = item
	if add {
		var emptyMenu *cocoa.NSMenu = item.CreateEmptyMenu()
		if emptyMenu != (nil) {
			nsItem.SetSubmenu(emptyMenu)
			emptyMenu.Release()
		}
		if this.display.menuBar == this {
			var application *cocoa.NSApplication = this.display.application
			var menubar *cocoa.NSMenu = application.MainMenu()
			if menubar != (nil) {
				nsItem.SetMenu(nil)
				menubar.InsertItem(nsItem, int64(index+1))
			}
		}
	}
	if !this.GetEnabled() {
		nsItem.SetEnabled(false)
	}
}

func (this *Menu) createWidget_() {
	this.CheckOrientation(upcastDecorationsToWidget(this.parent))
	this.Widget.createWidget_()
	this.items = make([]*MenuItem, 4)
}

func (this *Menu) deregister_() {
	this.Widget.deregister_()
	this.display.RemoveWidget(upcastcocoaNSMenuTococoaNSObject(this.nsMenu))
}

func (this *Menu) DestroyItem(itemLike MenuItemLike) {
	var item *MenuItem
	if itemLike != nil {
		item = itemLike.AsMenuItem()
	}
	_ = item
	var index int32 = 0
	for index < this.itemCount {
		if this.items[index] == item {
			break
		}
		index++
	}
	if index == this.itemCount {
		return
	}
	this.itemCount--
	copy(this.items[index:], this.items[index+1:index+1+this.itemCount-index])
	this.items[this.itemCount] = nil
	if this.itemCount == 0 {
		this.items = make([]*MenuItem, 4)
	}
	this.nsMenu.RemoveItem(item.nsItem)
	if this.display.menuBar == this {
		var application *cocoa.NSApplication = this.display.application
		var menubar *cocoa.NSMenu = application.MainMenu()
		if menubar != (nil) {
			var nsItem *cocoa.NSMenuItem = item.nsItem
			menubar.RemoveItem(nsItem)
		}
	}
}

func (this *Menu) FixMenus(newParentLike DecorationsLike) {
	var newParent *Decorations
	if newParentLike != nil {
		newParent = newParentLike.AsDecorations()
	}
	_ = newParent
	this.parent = newParent
}

func (this *Menu) GetDefaultItem() *MenuItem {
	this.CheckWidget()
	return this.defaultItem
}

func (this *Menu) GetEnabled() bool {
	this.CheckWidget()
	return (this.state & WidgetDISABLED) == 0
}

func (this *Menu) GetItem(index int32) *MenuItem {
	this.CheckWidget()
	if !(0 <= index && index < this.itemCount) {
		this.Error(ERROR_INVALID_RANGE)
	}
	return this.items[index]
}

func (this *Menu) GetItemCount() int32 {
	this.CheckWidget()
	return this.itemCount
}

func (this *Menu) GetItems() []*MenuItem {
	this.CheckWidget()
	var result []*MenuItem = make([]*MenuItem, this.itemCount)
	var index int32 = 0
	if this.items != (nil) {
		for i := int32(0); i < this.itemCount; i++ {
			var item *MenuItem = this.items[i]
			if item != (nil) && !item.IsDisposed() {
				t176 := index
				index++
				result[t176] = item
			}
		}
	}
	if index != int32(len(result)) {
		var newItems []*MenuItem = make([]*MenuItem, index)
		copy(newItems[0:], result[0:0+index])
		result = newItems
	}
	return result
}

func (this *Menu) getNameText_() string {
	var result string = ""
	var items []*MenuItem = this.GetItems()
	var length int32 = int32(len(items))
	if length > 0 {
		for i := int32(0); i < length-1; i++ {
			result = fmt.Sprintf("%s%s, ", result, items[i].impl.getNameText_())
		}
		result = fmt.Sprintf("%s%s", result, items[length-1].impl.getNameText_())
	}
	return result
}

func (this *Menu) GetOrientation() int32 {
	this.CheckWidget()
	return this.style & (LEFT_TO_RIGHT | RIGHT_TO_LEFT)
}

func (this *Menu) GetParent() *Decorations {
	this.CheckWidget()
	return this.parent
}

func (this *Menu) GetParentItem() *MenuItem {
	this.CheckWidget()
	return this.cascade
}

func (this *Menu) GetParentMenu() *Menu {
	this.CheckWidget()
	if this.cascade != (nil) {
		return this.cascade.parent
	}
	return nil
}

func (this *Menu) GetShell() *Shell {
	this.CheckWidget()
	if this.parent != (nil) {
		return this.parent.impl.getShell_()
	}
	return nil
}

func (this *Menu) GetVisible() bool {
	this.CheckWidget()
	if (this.style & BAR) != 0 {
		if this == this.display.appMenuBar {
			return this.display.application.IsActive()
		} else {
			return this == this.parent.impl.menuShell_().menuBar
		}
	}
	if (this.style & POP_UP) != 0 {
		var popups []*Menu = this.display.popups
		if popups == (nil) {
			return false
		}
		for i := int32(0); i < int32(len(popups)); i++ {
			if popups[i] == this {
				return true
			}
		}
	}
	return this.visible
}

func (this *Menu) IndexOf(itemLike MenuItemLike) int32 {
	var item *MenuItem
	if itemLike != nil {
		item = itemLike.AsMenuItem()
	}
	_ = item
	this.CheckWidget()
	if item == (nil) {
		this.Error(ERROR_NULL_ARGUMENT)
	}
	for i := int32(0); i < this.itemCount; i++ {
		if this.items[i] == item {
			return i
		}
	}
	return -1
}

func (this *Menu) IsEnabled() bool {
	this.CheckWidget()
	if this == this.display.appMenuBar {
		return this.GetEnabled()
	}
	if this == this.display.appMenu {
		return this.GetEnabled()
	}
	var parentMenu *Menu = this.GetParentMenu()
	if parentMenu == (nil) {
		return this.GetEnabled() && this.parent.impl.isEnabled_()
	}
	return this.GetEnabled() && parentMenu.IsEnabled()
}

func (this *Menu) IsVisible() bool {
	this.CheckWidget()
	return this.GetVisible()
}

func (this *Menu) menu_willHighlightItem_(id int64, sel int64, menu int64, itemID int64) {
	var widget *Widget = this.display.GetWidget(itemID)
	item, ok177 := isWidgetToMenuItem(widget)
	if ok177 {
		item.SendEventEventType(Arm)
	}
}

func (this *Menu) menuNeedsUpdate_(id int64, sel int64, menu int64) {
}

func (this *Menu) menuWillOpen_(id int64, sel int64, menu int64) {
	this.visible = true
	this.SendEventEventType(Show)
	if this.IsDisposed() {
		return
	}
	var width float64 = float64(0)
	var strs []*cocoa.NSAttributedString = make([]*cocoa.NSAttributedString, this.itemCount)
	for i := int32(0); i < this.itemCount; i++ {
		var item *MenuItem = this.items[i]
		var nsItem *cocoa.NSMenuItem = item.nsItem
		strs[i] = nsItem.AttributedTitle()
		var nsImage *cocoa.NSImage = nsItem.Image()
		var w float64 = float64(MenuGAP)
		if strs[i] != (nil) {
			w += strs[i].Size().Width
		}
		if nsImage != (nil) {
			w += (nsImage.Size().Width + float64(MenuGAP))
		}
		if strs[i] != (nil) {
			width = float64(math.Max(float64(width), float64(w)))
		}
	}
	for i := int32(0); i < this.itemCount; i++ {
		var item *MenuItem = this.items[i]
		if item.UpdateAccelerator(true) {
			continue
		}
		if item.accelerator != 0 || strs[i] == (nil) || (this.style&BAR) != 0 || (item.style&CASCADE) != 0 {
			continue
		}
		var accelIndex int32 = int32(strings.Index(item.text, string(rune('\u0009'))))
		if accelIndex != -1 {
			var accelText string = item.text[accelIndex:]
			var length int32 = int32(len(accelText))
			if length > 1 {
				var nsItem *cocoa.NSMenuItem = item.nsItem
				var nsImage *cocoa.NSImage = nsItem.Image()
				var tab float64 = width
				if nsImage != (nil) {
					tab -= (nsImage.Size().Width + float64(MenuGAP))
				}
				var str *cocoa.NSMutableAttributedString = cocoa.NewNSMutableAttributedStringOverload2(strs[i].MutableCopy())
				var label *cocoa.NSString = castcocoaNSObjectTococoaNSString(cocoa.NewNSString().Alloc())
				label = label.InitWithString(accelText)
				var dict *cocoa.NSMutableDictionary = (castcocoaNSObjectTococoaNSMutableDictionary(cocoa.NewNSMutableDictionary().Alloc())).InitWithCapacity(int64(1))
				dict.SetObject(upcastcocoaNSFontTococoaId(cocoa.NSFontMenuBarFontOfSize(float64(0))), upcastcocoaNSStringTococoaId(cocoa.OSNSFontAttributeName_))
				var attribStr *cocoa.NSAttributedString = (castcocoaNSObjectTococoaNSAttributedString(cocoa.NewNSAttributedString().Alloc())).InitWithStringStrAttrs(label, upcastcocoaNSMutableDictionaryTococoaNSDictionary(dict))
				dict.Release()
				label.Release()
				str.AppendAttributedString(attribStr)
				attribStr.Release()
				var range_ cocoa.NSRange = cocoa.NSRange{}
				range_.Length = str.Length()
				var paragraphStyle *cocoa.NSMutableParagraphStyle = castcocoaNSObjectTococoaNSMutableParagraphStyle(cocoa.NewNSMutableParagraphStyle().Alloc().Init())
				paragraphStyle.SetTabStops(cocoa.NSArrayArray())
				var stop *cocoa.NSTextTab = castcocoaNSObjectTococoaNSTextTab(cocoa.NewNSTextTab().Alloc())
				stop = stop.InitWithType(int64(cocoa.OSNSLeftTabStopType), tab)
				paragraphStyle.AddTabStop(stop)
				stop.Release()
				str.AddAttribute(cocoa.OSNSParagraphStyleAttributeName_, upcastcocoaNSMutableParagraphStyleTococoaId(paragraphStyle), range_)
				paragraphStyle.Release()
				nsItem.SetAttributedTitle(upcastcocoaNSMutableAttributedStringTococoaNSAttributedString(str))
				str.Release()
			}
		}
	}
}

func (this *Menu) menuDidClose_(id int64, sel int64, menu int64) {
	this.SendEventEventType(Hide)
	if this.IsDisposed() {
		return
	}
	this.visible = false
	for i := int32(0); i < this.itemCount; i++ {
		var item *MenuItem = this.items[i]
		item.UpdateAccelerator(false)
		if (item.style & SEPARATOR) != 0 {
			continue
		}
		item.UpdateText()
	}
}

func (this *Menu) register_() {
	this.Widget.register_()
	this.display.AddWidget(upcastcocoaNSMenuTococoaNSObject(this.nsMenu), upcastMenuToWidget(this))
}

func (this *Menu) releaseChildren_(destroy bool) {
	if this.items != (nil) {
		for i := int32(0); i < int32(len(this.items)); i++ {
			var item *MenuItem = this.items[i]
			if item != (nil) && !item.IsDisposed() {
				item.impl.release_(false)
			}
		}
		this.items = nil
	}
	this.Widget.releaseChildren_(destroy)
}

func (this *Menu) releaseHandle_() {
	this.Widget.releaseHandle_()
	if this.nsMenu != (nil) {
		this.nsMenu.Release()
	}
	this.nsMenu = nil
}

func (this *Menu) releaseParent_() {
	this.Widget.releaseParent_()
	if this.cascade != (nil) {
		this.cascade.SetMenu(nil)
	}
	if (this.style&BAR) != 0 && this.parent != (nil) && this == this.parent.menuBar {
		this.parent.impl.setMenuBar_(nil)
	}
}

func (this *Menu) releaseWidget_() {
	this.Widget.releaseWidget_()
	this.display.RemoveMenu(this)
	this.parent = nil
	this.defaultItem = nil
	this.cascade = this.defaultItem
}

func (this *Menu) RemoveHelpListener(listener HelpListener) {
	this.CheckWidget()
	if listener == (nil) {
		this.Error(ERROR_NULL_ARGUMENT)
	}
	if this.eventTable == (nil) {
		return
	}
	this.eventTable.UnhookEventTypeListener(Help, listener)
}

func (this *Menu) RemoveMenuListener(listener MenuListener) {
	this.CheckWidget()
	if listener == (nil) {
		this.Error(ERROR_NULL_ARGUMENT)
	}
	if this.eventTable == (nil) {
		return
	}
	this.eventTable.UnhookEventTypeListener(Hide, listener)
	this.eventTable.UnhookEventTypeListener(Show, listener)
}

func (this *Menu) reskinChildren_(flags int32) {
	var items []*MenuItem = this.GetItems()
	for i := int32(0); i < int32(len(items)); i++ {
		var item *MenuItem = items[i]
		item.Reskin(flags)
	}
	this.Widget.reskinChildren_(flags)
}

func (this *Menu) SetDefaultItem(itemLike MenuItemLike) {
	var item *MenuItem
	if itemLike != nil {
		item = itemLike.AsMenuItem()
	}
	_ = item
	this.CheckWidget()
	if item != (nil) && item.IsDisposed() {
		this.Error(ERROR_INVALID_ARGUMENT)
	}
	this.defaultItem = item
}

func (this *Menu) SetEnabled(enabled bool) {
	this.CheckWidget()
	if enabled {
		this.state &= ^WidgetDISABLED
	} else {
		this.state |= WidgetDISABLED
	}
	for i := int32(0); i < int32(len(this.items)); i++ {
		var item *MenuItem = this.items[i]
		if item != (nil) {
			item.nsItem.SetEnabled(enabled && item.GetEnabled())
		}
	}
}

func (this *Menu) SetLocation(x int32, y int32) {
	this.CheckWidget()
	this.x = x
	this.y = y
	this.hasLocation = true
}

func (this *Menu) SetLocationLocation(locationLike PointLike) {
	var location *Point
	if locationLike != nil {
		location = locationLike.AsPoint()
	}
	_ = location
	this.CheckWidget()
	if location == (nil) {
		this.Error(ERROR_NULL_ARGUMENT)
	}
	this.SetLocation(location.X, location.Y)
}

func (this *Menu) SetOrientation(orientation int32) {
	this.CheckWidget()
}

func (this *Menu) SetVisible(visible bool) {
	this.CheckWidget()
	if (this.style & (BAR | DROP_DOWN)) != 0 {
		return
	}
	if visible {
		this.display.AddPopup(this)
	} else {
		this.display.RemovePopup(this)
		this._setVisible(false)
	}
}

func MenuCheckNull(controlLike ControlLike) *Control {
	var control *Control
	if controlLike != nil {
		control = controlLike.AsControl()
	}
	_ = control
	if control == (nil) {
		Error(ERROR_NULL_ARGUMENT)
	}
	return control
}

func MenuCheckNullMenu(menuLike MenuLike) *Menu {
	var menu *Menu
	if menuLike != nil {
		menu = menuLike.AsMenu()
	}
	_ = menu
	if menu == (nil) {
		Error(ERROR_NULL_ARGUMENT)
	}
	return menu
}

func MenuCheckNullItem(itemLike MenuItemLike) *MenuItem {
	var item *MenuItem
	if itemLike != nil {
		item = itemLike.AsMenuItem()
	}
	_ = item
	if item == (nil) {
		Error(ERROR_NULL_ARGUMENT)
	}
	return item
}

func MenuCheckStyle(style int32) int32 {
	return WidgetCheckBits(style, POP_UP, BAR, DROP_DOWN, 0, 0, 0)
}

func init() {
	jrt.RegisterMethod(reflect.TypeFor[*Menu](), "addHelpListener", []reflect.Type{reflect.TypeFor[HelpListener]()}, nil, func(target any, args []any) any {
		jrt.Narrow[*Menu](target).AddHelpListener(jrt.ArgAs[HelpListener](args[0]))
		return nil
	})
	jrt.RegisterMethod(reflect.TypeFor[*Menu](), "addMenuListener", []reflect.Type{reflect.TypeFor[MenuListener]()}, nil, func(target any, args []any) any {
		jrt.Narrow[*Menu](target).AddMenuListener(jrt.ArgAs[MenuListener](args[0]))
		return nil
	})
	jrt.RegisterMethod(reflect.TypeFor[*Menu](), "getDefaultItem", nil, reflect.TypeFor[*MenuItem](), func(target any, args []any) any { return jrt.Narrow[*Menu](target).GetDefaultItem() })
	jrt.RegisterMethod(reflect.TypeFor[*Menu](), "getEnabled", nil, reflect.TypeFor[bool](), func(target any, args []any) any { return jrt.Narrow[*Menu](target).GetEnabled() })
	jrt.RegisterMethod(reflect.TypeFor[*Menu](), "getItem", []reflect.Type{reflect.TypeFor[int32]()}, reflect.TypeFor[*MenuItem](), func(target any, args []any) any { return jrt.Narrow[*Menu](target).GetItem(jrt.ArgAs[int32](args[0])) })
	jrt.RegisterMethod(reflect.TypeFor[*Menu](), "getItemCount", nil, reflect.TypeFor[int32](), func(target any, args []any) any { return jrt.Narrow[*Menu](target).GetItemCount() })
	jrt.RegisterMethod(reflect.TypeFor[*Menu](), "getItems", nil, reflect.TypeFor[[]*MenuItem](), func(target any, args []any) any { return jrt.Narrow[*Menu](target).GetItems() })
	jrt.RegisterMethod(reflect.TypeFor[*Menu](), "getOrientation", nil, reflect.TypeFor[int32](), func(target any, args []any) any { return jrt.Narrow[*Menu](target).GetOrientation() })
	jrt.RegisterMethod(reflect.TypeFor[*Menu](), "getParent", nil, reflect.TypeFor[*Decorations](), func(target any, args []any) any { return jrt.Narrow[*Menu](target).GetParent() })
	jrt.RegisterMethod(reflect.TypeFor[*Menu](), "getParentItem", nil, reflect.TypeFor[*MenuItem](), func(target any, args []any) any { return jrt.Narrow[*Menu](target).GetParentItem() })
	jrt.RegisterMethod(reflect.TypeFor[*Menu](), "getParentMenu", nil, reflect.TypeFor[*Menu](), func(target any, args []any) any { return jrt.Narrow[*Menu](target).GetParentMenu() })
	jrt.RegisterMethod(reflect.TypeFor[*Menu](), "getShell", nil, reflect.TypeFor[*Shell](), func(target any, args []any) any { return jrt.Narrow[*Menu](target).GetShell() })
	jrt.RegisterMethod(reflect.TypeFor[*Menu](), "getVisible", nil, reflect.TypeFor[bool](), func(target any, args []any) any { return jrt.Narrow[*Menu](target).GetVisible() })
	jrt.RegisterMethod(reflect.TypeFor[*Menu](), "indexOf", []reflect.Type{reflect.TypeFor[MenuItemLike]()}, reflect.TypeFor[int32](), func(target any, args []any) any {
		return jrt.Narrow[*Menu](target).IndexOf(jrt.ArgAs[MenuItemLike](args[0]))
	})
	jrt.RegisterMethod(reflect.TypeFor[*Menu](), "isEnabled", nil, reflect.TypeFor[bool](), func(target any, args []any) any { return jrt.Narrow[*Menu](target).IsEnabled() })
	jrt.RegisterMethod(reflect.TypeFor[*Menu](), "isVisible", nil, reflect.TypeFor[bool](), func(target any, args []any) any { return jrt.Narrow[*Menu](target).IsVisible() })
	jrt.RegisterMethod(reflect.TypeFor[*Menu](), "removeHelpListener", []reflect.Type{reflect.TypeFor[HelpListener]()}, nil, func(target any, args []any) any {
		jrt.Narrow[*Menu](target).RemoveHelpListener(jrt.ArgAs[HelpListener](args[0]))
		return nil
	})
	jrt.RegisterMethod(reflect.TypeFor[*Menu](), "removeMenuListener", []reflect.Type{reflect.TypeFor[MenuListener]()}, nil, func(target any, args []any) any {
		jrt.Narrow[*Menu](target).RemoveMenuListener(jrt.ArgAs[MenuListener](args[0]))
		return nil
	})
	jrt.RegisterMethod(reflect.TypeFor[*Menu](), "setDefaultItem", []reflect.Type{reflect.TypeFor[MenuItemLike]()}, nil, func(target any, args []any) any {
		jrt.Narrow[*Menu](target).SetDefaultItem(jrt.ArgAs[MenuItemLike](args[0]))
		return nil
	})
	jrt.RegisterMethod(reflect.TypeFor[*Menu](), "setEnabled", []reflect.Type{reflect.TypeFor[bool]()}, nil, func(target any, args []any) any {
		jrt.Narrow[*Menu](target).SetEnabled(jrt.ArgAs[bool](args[0]))
		return nil
	})
	jrt.RegisterMethod(reflect.TypeFor[*Menu](), "setLocation", []reflect.Type{reflect.TypeFor[int32](), reflect.TypeFor[int32]()}, nil, func(target any, args []any) any {
		jrt.Narrow[*Menu](target).SetLocation(jrt.ArgAs[int32](args[0]), jrt.ArgAs[int32](args[1]))
		return nil
	})
	jrt.RegisterMethod(reflect.TypeFor[*Menu](), "setLocation", []reflect.Type{reflect.TypeFor[PointLike]()}, nil, func(target any, args []any) any {
		jrt.Narrow[*Menu](target).SetLocationLocation(jrt.ArgAs[PointLike](args[0]))
		return nil
	})
	jrt.RegisterMethod(reflect.TypeFor[*Menu](), "setOrientation", []reflect.Type{reflect.TypeFor[int32]()}, nil, func(target any, args []any) any {
		jrt.Narrow[*Menu](target).SetOrientation(jrt.ArgAs[int32](args[0]))
		return nil
	})
	jrt.RegisterMethod(reflect.TypeFor[*Menu](), "setVisible", []reflect.Type{reflect.TypeFor[bool]()}, nil, func(target any, args []any) any {
		jrt.Narrow[*Menu](target).SetVisible(jrt.ArgAs[bool](args[0]))
		return nil
	})
}

// j2go: instanceof helper for cocoa.NSMenu and its subclasses within the translated set.
func idImplAsNSMenu(x any) (*cocoa.NSMenu, bool) {
	switch v := x.(type) {
	case *cocoa.NSMenu:
		return v, true
	case *cocoa.SWTMenu:
		return &v.NSMenu, true
	}
	return nil, false
}

func castcocoaNSObjectTococoaNSMenu(x *cocoa.NSObject) *cocoa.NSMenu {
	if x == nil {
		return nil
	}
	v, ok := idImplAsNSMenu(x.Impl())
	if !ok {
		panic("java.lang.ClassCastException: cocoa.NSMenu")
	}
	return v
}

func upcastcocoaNSMenuTococoaId(x *cocoa.NSMenu) *cocoa.Id {
	if x == nil {
		return nil
	}
	return x.AsId()
}

// j2go: instanceof helper for cocoa.NSMenuItem and its subclasses within the translated set.
func idImplAsNSMenuItem(x any) (*cocoa.NSMenuItem, bool) {
	switch v := x.(type) {
	case *cocoa.NSMenuItem:
		return v, true
	case *cocoa.SWTMenuItem:
		return &v.NSMenuItem, true
	}
	return nil, false
}

func castcocoaNSObjectTococoaNSMenuItem(x *cocoa.NSObject) *cocoa.NSMenuItem {
	if x == nil {
		return nil
	}
	v, ok := idImplAsNSMenuItem(x.Impl())
	if !ok {
		panic("java.lang.ClassCastException: cocoa.NSMenuItem")
	}
	return v
}

func upcastcocoaNSMenuItemTococoaId(x *cocoa.NSMenuItem) *cocoa.Id {
	if x == nil {
		return nil
	}
	return x.AsId()
}

func upcastcocoaNSMenuTococoaNSObject(x *cocoa.NSMenu) *cocoa.NSObject {
	if x == nil {
		return nil
	}
	return &x.NSObject
}

// j2go: instanceof helper for MenuItem and its subclasses within the translated set.
func widgetImplAsMenuItem(x any) (*MenuItem, bool) {
	switch v := x.(type) {
	case *MenuItem:
		return v, true
	}
	return nil, false
}

func isWidgetToMenuItem(x *Widget) (*MenuItem, bool) {
	if x == nil {
		return nil, false
	}
	return widgetImplAsMenuItem(x.impl)
}

// j2go: instanceof helper for cocoa.NSTextTab and its subclasses within the translated set.
func idImplAsNSTextTab(x any) (*cocoa.NSTextTab, bool) {
	switch v := x.(type) {
	case *cocoa.NSTextTab:
		return v, true
	}
	return nil, false
}

func castcocoaNSObjectTococoaNSTextTab(x *cocoa.NSObject) *cocoa.NSTextTab {
	if x == nil {
		return nil
	}
	v, ok := idImplAsNSTextTab(x.Impl())
	if !ok {
		panic("java.lang.ClassCastException: cocoa.NSTextTab")
	}
	return v
}

func upcastcocoaNSMutableAttributedStringTococoaNSAttributedString(x *cocoa.NSMutableAttributedString) *cocoa.NSAttributedString {
	if x == nil {
		return nil
	}
	return &x.NSAttributedString
}

func upcastMenuToWidget(x *Menu) *Widget {
	if x == nil {
		return nil
	}
	return &x.Widget
}
