// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT PI/cocoa/org/eclipse/swt/internal/cocoa/DOMDocument.java @ af630a9093. DO NOT EDIT.

package cocoa

type DOMDocument struct {
	NSObject
}

func NewDOMDocument() *DOMDocument {
	this := &DOMDocument{}
	this.Impl = this
	this.initDOMDocument()
	return this
}

func (this *DOMDocument) initDOMDocument() {
	this.NSObject.initNSObject()
}

func NewDOMDocumentOverload1(id int64) *DOMDocument {
	this := &DOMDocument{}
	this.Impl = this
	this.initDOMDocumentOverload1(id)
	return this
}

func (this *DOMDocument) initDOMDocumentOverload1(id int64) {
	this.NSObject.initNSObjectOverload1(id)
}

func NewDOMDocumentOverload2(id *id) *DOMDocument {
	this := &DOMDocument{}
	this.Impl = this
	this.initDOMDocumentOverload2(id)
	return this
}

func (this *DOMDocument) initDOMDocumentOverload2(id *id) {
	this.NSObject.initNSObjectOverload2(id)
}

func (this *DOMDocument) WebFrame() *WebFrame {
	var result int64 = OSObjc_msgSend(this.Id, OSSel_webFrame)
	var cond1 *WebFrame
	if result != 0 {
		cond1 = NewWebFrameOverload1(result)
	} else {
		cond1 = nil
	}
	return cond1
}
