// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT PI/cocoa/org/eclipse/swt/internal/cocoa/NSInputManager.java @ af630a9093. DO NOT EDIT.

package cocoa

type NSInputManager struct {
	NSObject
}

func NewNSInputManager() *NSInputManager {
	this := &NSInputManager{}
	this.Impl = this
	this.initNSInputManager()
	return this
}

func (this *NSInputManager) initNSInputManager() {
	this.NSObject.initNSObject()
}

func NewNSInputManagerOverload1(id int64) *NSInputManager {
	this := &NSInputManager{}
	this.Impl = this
	this.initNSInputManagerOverload1(id)
	return this
}

func (this *NSInputManager) initNSInputManagerOverload1(id int64) {
	this.NSObject.initNSObjectOverload1(id)
}

func NewNSInputManagerOverload2(id *id) *NSInputManager {
	this := &NSInputManager{}
	this.Impl = this
	this.initNSInputManagerOverload2(id)
	return this
}

func (this *NSInputManager) initNSInputManagerOverload2(id *id) {
	this.NSObject.initNSObjectOverload2(id)
}

func (this *NSInputManager) HandleMouseEvent(theMouseEvent *NSEvent) bool {
	var cond342 int64
	if theMouseEvent != nil {
		cond342 = theMouseEvent.Id
	} else {
		cond342 = int64(0)
	}
	return OSObjc_msgSend_boolOverload5(this.Id, OSSel_handleMouseEvent_, cond342)
}

func (this *NSInputManager) WantsToHandleMouseEvents() bool {
	return OSObjc_msgSend_bool(this.Id, OSSel_wantsToHandleMouseEvents)
}

func NSInputManagerCurrentInputManager() *NSInputManager {
	var result int64 = OSObjc_msgSend(OSClass_NSInputManager, OSSel_currentInputManager)
	var cond343 *NSInputManager
	if result != 0 {
		cond343 = NewNSInputManagerOverload1(result)
	} else {
		cond343 = nil
	}
	return cond343
}
