// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT PI/cocoa/org/eclipse/swt/internal/cocoa/DOMUIEvent.java @ af630a9093. DO NOT EDIT.

package cocoa

type DOMUIEvent struct {
	DOMEvent
}

func NewDOMUIEvent() *DOMUIEvent {
	this := &DOMUIEvent{}
	this.Impl = this
	this.initDOMUIEvent()
	return this
}

func (this *DOMUIEvent) initDOMUIEvent() {
	this.DOMEvent.initDOMEvent()
}

func NewDOMUIEventOverload1(id int64) *DOMUIEvent {
	this := &DOMUIEvent{}
	this.Impl = this
	this.initDOMUIEventOverload1(id)
	return this
}

func (this *DOMUIEvent) initDOMUIEventOverload1(id int64) {
	this.DOMEvent.initDOMEventOverload1(id)
}

func NewDOMUIEventOverload2(id *id) *DOMUIEvent {
	this := &DOMUIEvent{}
	this.Impl = this
	this.initDOMUIEventOverload2(id)
	return this
}

func (this *DOMUIEvent) initDOMUIEventOverload2(id *id) {
	this.DOMEvent.initDOMEventOverload2(id)
}

func (this *DOMUIEvent) Detail() int32 {
	return int32(OSObjc_msgSend(this.Id, OSSel_detail))
}
