// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT PI/cocoa/org/eclipse/swt/internal/cocoa/NSFontPanel.java @ af630a9093. DO NOT EDIT.

package cocoa

type NSFontPanel struct {
	NSPanel
}

func NewNSFontPanel() *NSFontPanel {
	this := &NSFontPanel{}
	this.impl = this
	this.initNSFontPanel()
	return this
}

func (this *NSFontPanel) initNSFontPanel() {
	this.NSPanel.initNSPanel()
}

func NewNSFontPanelOverload1(id int64) *NSFontPanel {
	this := &NSFontPanel{}
	this.impl = this
	this.initNSFontPanelOverload1(id)
	return this
}

func (this *NSFontPanel) initNSFontPanelOverload1(id int64) {
	this.NSPanel.initNSPanelOverload1(id)
}

func NewNSFontPanelOverload2(id *id) *NSFontPanel {
	this := &NSFontPanel{}
	this.impl = this
	this.initNSFontPanelOverload2(id)
	return this
}

func (this *NSFontPanel) initNSFontPanelOverload2(id *id) {
	this.NSPanel.initNSPanelOverload2(id)
}

func (this *NSFontPanel) PanelConvertFont(fontObj *NSFont) *NSFont {
	var cond279 int64
	if fontObj != (nil) {
		cond279 = fontObj.Id
	} else {
		cond279 = int64(0)
	}
	var result int64 = OSObjc_msgSendOverload44(this.Id, OSSel_panelConvertFont_, cond279)
	var cond280 *NSFont
	if result != 0 {
		cond280 = NewNSFontOverload1(result)
	} else {
		cond280 = nil
	}
	return cond280
}

func (this *NSFontPanel) SetPanelFont(fontObj *NSFont, flag bool) {
	var cond281 int64
	if fontObj != (nil) {
		cond281 = fontObj.Id
	} else {
		cond281 = int64(0)
	}
	OSObjc_msgSendOverload52(this.Id, OSSel_setPanelFont_isMultiple_, cond281, flag)
}

func NSFontPanelSharedFontPanel() *NSFontPanel {
	var result int64 = OSObjc_msgSend(OSClass_NSFontPanel, OSSel_sharedFontPanel)
	var cond282 *NSFontPanel
	if result != 0 {
		cond282 = NewNSFontPanelOverload1(result)
	} else {
		cond282 = nil
	}
	return cond282
}

func NSFontPanelMinFrameWidthWithTitle(aTitle *NSString, aStyle int64) float64 {
	var cond283 int64
	if aTitle != (nil) {
		cond283 = aTitle.Id
	} else {
		cond283 = int64(0)
	}
	return OSObjc_msgSend_fpretIdSelArg0Arg1(OSClass_NSFontPanel, OSSel_minFrameWidthWithTitle_styleMask_, cond283, aStyle)
}

func NSFontPanelWindowNumberAtPoint(point NSPoint, windowNumber int64) int64 {
	return OSObjc_msgSendOverload6(OSClass_NSFontPanel, OSSel_windowNumberAtPoint_belowWindowWithWindowNumber_, point, windowNumber)
}
