// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT PI/cocoa/org/eclipse/swt/internal/cocoa/NSImage.java @ af630a9093. DO NOT EDIT.

package cocoa

type NSImage struct {
	NSObject
}

func NewNSImage() *NSImage {
	this := &NSImage{}
	this.Impl = this
	this.initNSImage()
	return this
}

func (this *NSImage) initNSImage() {
	this.NSObject.initNSObject()
}

func NewNSImageOverload1(id int64) *NSImage {
	this := &NSImage{}
	this.Impl = this
	this.initNSImageOverload1(id)
	return this
}

func (this *NSImage) initNSImageOverload1(id int64) {
	this.NSObject.initNSObjectOverload1(id)
}

func NewNSImageOverload2(id *id) *NSImage {
	this := &NSImage{}
	this.Impl = this
	this.initNSImageOverload2(id)
	return this
}

func (this *NSImage) initNSImageOverload2(id *id) {
	this.NSObject.initNSObjectOverload2(id)
}

func (this *NSImage) TIFFRepresentation() *NSData {
	var result int64 = OSObjc_msgSend(this.Id, OSSel_TIFFRepresentation)
	var cond313 *NSData
	if result != 0 {
		cond313 = NewNSDataOverload1(result)
	} else {
		cond313 = nil
	}
	return cond313
}

func (this *NSImage) AddRepresentation(imageRep *NSImageRep) {
	var cond314 int64
	if imageRep != nil {
		cond314 = imageRep.Id
	} else {
		cond314 = int64(0)
	}
	OSObjc_msgSendOverload44(this.Id, OSSel_addRepresentation_, cond314)
}

func (this *NSImage) BestRepresentationForDevice(deviceDescription *NSDictionary) *NSImageRep {
	var cond315 int64
	if deviceDescription != nil {
		cond315 = deviceDescription.Id
	} else {
		cond315 = int64(0)
	}
	var result int64 = OSObjc_msgSendOverload44(this.Id, OSSel_bestRepresentationForDevice_, cond315)
	var cond316 *NSImageRep
	if result != 0 {
		cond316 = NewNSImageRepOverload1(result)
	} else {
		cond316 = nil
	}
	return cond316
}

func (this *NSImage) DrawInRect(rect NSRect, fromRect NSRect, op int64, delta float64) {
	OSObjc_msgSendOverload15(this.Id, OSSel_drawInRect_fromRect_operation_fraction_, rect, fromRect, op, delta)
}

func (this *NSImage) InitByReferencingFile(fileName *NSString) *NSImage {
	var cond317 int64
	if fileName != nil {
		cond317 = fileName.Id
	} else {
		cond317 = int64(0)
	}
	var result int64 = OSObjc_msgSendOverload44(this.Id, OSSel_initByReferencingFile_, cond317)
	var cond318 *NSImage
	var cond319 *NSImage
	if result != 0 {
		cond319 = NewNSImageOverload1(result)
	} else {
		cond319 = nil
	}
	if result == this.Id {
		cond318 = this
	} else {
		cond318 = (cond319)
	}
	return cond318
}

func (this *NSImage) InitWithContentsOfFile(fileName *NSString) *NSImage {
	var cond320 int64
	if fileName != nil {
		cond320 = fileName.Id
	} else {
		cond320 = int64(0)
	}
	var result int64 = OSObjc_msgSendOverload44(this.Id, OSSel_initWithContentsOfFile_, cond320)
	var cond321 *NSImage
	var cond322 *NSImage
	if result != 0 {
		cond322 = NewNSImageOverload1(result)
	} else {
		cond322 = nil
	}
	if result == this.Id {
		cond321 = this
	} else {
		cond321 = (cond322)
	}
	return cond321
}

func (this *NSImage) InitWithData(data *NSData) *NSImage {
	var cond323 int64
	if data != nil {
		cond323 = data.Id
	} else {
		cond323 = int64(0)
	}
	var result int64 = OSObjc_msgSendOverload44(this.Id, OSSel_initWithData_, cond323)
	var cond324 *NSImage
	var cond325 *NSImage
	if result != 0 {
		cond325 = NewNSImageOverload1(result)
	} else {
		cond325 = nil
	}
	if result == this.Id {
		cond324 = this
	} else {
		cond324 = (cond325)
	}
	return cond324
}

func (this *NSImage) InitWithIconRef(iconRef int64) *NSImage {
	var result int64 = OSObjc_msgSendOverload44(this.Id, OSSel_initWithIconRef_, iconRef)
	var cond326 *NSImage
	var cond327 *NSImage
	if result != 0 {
		cond327 = NewNSImageOverload1(result)
	} else {
		cond327 = nil
	}
	if result == this.Id {
		cond326 = this
	} else {
		cond326 = (cond327)
	}
	return cond326
}

func (this *NSImage) InitWithSize(aSize NSSize) *NSImage {
	var result int64 = OSObjc_msgSendOverload26(this.Id, OSSel_initWithSize_, aSize)
	var cond328 *NSImage
	var cond329 *NSImage
	if result != 0 {
		cond329 = NewNSImageOverload1(result)
	} else {
		cond329 = nil
	}
	if result == this.Id {
		cond328 = this
	} else {
		cond328 = (cond329)
	}
	return cond328
}

func (this *NSImage) LockFocus() {
	OSObjc_msgSend(this.Id, OSSel_lockFocus)
}

func (this *NSImage) RemoveRepresentation(imageRep *NSImageRep) {
	var cond330 int64
	if imageRep != nil {
		cond330 = imageRep.Id
	} else {
		cond330 = int64(0)
	}
	OSObjc_msgSendOverload44(this.Id, OSSel_removeRepresentation_, cond330)
}

func (this *NSImage) Representations() *NSArray {
	var result int64 = OSObjc_msgSend(this.Id, OSSel_representations)
	var cond331 *NSArray
	if result != 0 {
		cond331 = NewNSArrayOverload1(result)
	} else {
		cond331 = nil
	}
	return cond331
}

func (this *NSImage) SetCacheMode(cacheMode int64) {
	OSObjc_msgSendOverload44(this.Id, OSSel_setCacheMode_, cacheMode)
}

func (this *NSImage) SetScalesWhenResized(flag bool) {
	OSObjc_msgSendOverload27(this.Id, OSSel_setScalesWhenResized_, flag)
}

func (this *NSImage) SetSize(size NSSize) {
	OSObjc_msgSendOverload26(this.Id, OSSel_setSize_, size)
}

func (this *NSImage) Size() NSSize {
	var result NSSize = NSSize{}
	OSObjc_msgSend_stretOverload18(&result, this.Id, OSSel_size)
	return result
}

func (this *NSImage) UnlockFocus() {
	OSObjc_msgSend(this.Id, OSSel_unlockFocus)
}

func NSImageImageNamed(name *NSString) *NSImage {
	var cond332 int64
	if name != nil {
		cond332 = name.Id
	} else {
		cond332 = int64(0)
	}
	var result int64 = OSObjc_msgSendOverload44(OSClass_NSImage, OSSel_imageNamed_, cond332)
	var cond333 *NSImage
	if result != 0 {
		cond333 = NewNSImageOverload1(result)
	} else {
		cond333 = nil
	}
	return cond333
}
