// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT PI/cocoa/org/eclipse/swt/internal/cocoa/NSMutableAttributedString.java @ af630a9093. DO NOT EDIT.
//go:build darwin

package cocoa

type NSMutableAttributedString struct {
	NSAttributedString
}

func NewNSMutableAttributedString() *NSMutableAttributedString {
	this := &NSMutableAttributedString{}
	this.impl = this
	this.initNSMutableAttributedString()
	return this
}

func (this *NSMutableAttributedString) initNSMutableAttributedString() {
	this.NSAttributedString.initNSAttributedString()
}

func NewNSMutableAttributedStringOverload1(id int64) *NSMutableAttributedString {
	this := &NSMutableAttributedString{}
	this.impl = this
	this.initNSMutableAttributedStringOverload1(id)
	return this
}

func (this *NSMutableAttributedString) initNSMutableAttributedStringOverload1(id int64) {
	this.NSAttributedString.initNSAttributedStringOverload1(id)
}

func NewNSMutableAttributedStringOverload2(id *id) *NSMutableAttributedString {
	this := &NSMutableAttributedString{}
	this.impl = this
	this.initNSMutableAttributedStringOverload2(id)
	return this
}

func (this *NSMutableAttributedString) initNSMutableAttributedStringOverload2(id *id) {
	this.NSAttributedString.initNSAttributedStringOverload2(id)
}

func (this *NSMutableAttributedString) AddAttribute(name *NSString, value *id, range_ NSRange) {
	var cond418 int64
	if name != (nil) {
		cond418 = name.Id
	} else {
		cond418 = int64(0)
	}
	var cond419 int64
	if value != (nil) {
		cond419 = value.Id
	} else {
		cond419 = int64(0)
	}
	OSObjc_msgSendOverload55(this.Id, OSSel_addAttribute_value_range_, cond418, cond419, range_)
}

func (this *NSMutableAttributedString) AppendAttributedString(attrString *NSAttributedString) {
	var cond420 int64
	if attrString != (nil) {
		cond420 = attrString.Id
	} else {
		cond420 = int64(0)
	}
	OSObjc_msgSendOverload44(this.Id, OSSel_appendAttributedString_, cond420)
}

func (this *NSMutableAttributedString) BeginEditing() {
	OSObjc_msgSend(this.Id, OSSel_beginEditing)
}

func (this *NSMutableAttributedString) EndEditing() {
	OSObjc_msgSend(this.Id, OSSel_endEditing)
}

func (this *NSMutableAttributedString) RemoveAttribute(name *NSString, range_ NSRange) {
	var cond421 int64
	if name != (nil) {
		cond421 = name.Id
	} else {
		cond421 = int64(0)
	}
	OSObjc_msgSendOverload50(this.Id, OSSel_removeAttribute_range_, cond421, range_)
}

func (this *NSMutableAttributedString) ReplaceCharactersInRange(range_ NSRange, str *NSString) {
	var cond422 int64
	if str != (nil) {
		cond422 = str.Id
	} else {
		cond422 = int64(0)
	}
	OSObjc_msgSendOverload11(this.Id, OSSel_replaceCharactersInRange_withString_, range_, cond422)
}

func (this *NSMutableAttributedString) SetAttributedString(attrString *NSAttributedString) {
	var cond423 int64
	if attrString != (nil) {
		cond423 = attrString.Id
	} else {
		cond423 = int64(0)
	}
	OSObjc_msgSendOverload44(this.Id, OSSel_setAttributedString_, cond423)
}
