// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT PI/cocoa/org/eclipse/swt/internal/cocoa/NSError.java @ af630a9093. DO NOT EDIT.

package cocoa

type NSError struct {
	NSObject
}

func NewNSError() *NSError {
	this := &NSError{}
	this.Impl = this
	this.initNSError()
	return this
}

func (this *NSError) initNSError() {
	this.NSObject.initNSObject()
}

func NewNSErrorOverload1(id int64) *NSError {
	this := &NSError{}
	this.Impl = this
	this.initNSErrorOverload1(id)
	return this
}

func (this *NSError) initNSErrorOverload1(id int64) {
	this.NSObject.initNSObjectOverload1(id)
}

func NewNSErrorOverload2(id *id) *NSError {
	this := &NSError{}
	this.Impl = this
	this.initNSErrorOverload2(id)
	return this
}

func (this *NSError) initNSErrorOverload2(id *id) {
	this.NSObject.initNSObjectOverload2(id)
}

func (this *NSError) Code() int64 {
	return OSObjc_msgSend(this.Id, OSSel_code)
}

func (this *NSError) LocalizedDescription() *NSString {
	var result int64 = OSObjc_msgSend(this.Id, OSSel_localizedDescription)
	var cond247 *NSString
	if result != 0 {
		cond247 = NewNSStringOverload1(result)
	} else {
		cond247 = nil
	}
	return cond247
}

func (this *NSError) UserInfo() *NSDictionary {
	var result int64 = OSObjc_msgSend(this.Id, OSSel_userInfo)
	var cond248 *NSDictionary
	if result != 0 {
		cond248 = NewNSDictionaryOverload1(result)
	} else {
		cond248 = nil
	}
	return cond248
}
