// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT PI/cocoa/org/eclipse/swt/internal/cocoa/NSSavePanel.java @ af630a9093. DO NOT EDIT.
//go:build darwin

package cocoa

type NSSavePanel struct {
	NSPanel
}

func NewNSSavePanel() *NSSavePanel {
	this := &NSSavePanel{}
	this.impl = this
	this.initNSSavePanel()
	return this
}

func (this *NSSavePanel) initNSSavePanel() {
	this.NSPanel.initNSPanel()
}

func NewNSSavePanelOverload1(id int64) *NSSavePanel {
	this := &NSSavePanel{}
	this.impl = this
	this.initNSSavePanelOverload1(id)
	return this
}

func (this *NSSavePanel) initNSSavePanelOverload1(id int64) {
	this.NSPanel.initNSPanelOverload1(id)
}

func NewNSSavePanelOverload2(id *id) *NSSavePanel {
	this := &NSSavePanel{}
	this.impl = this
	this.initNSSavePanelOverload2(id)
	return this
}

func (this *NSSavePanel) initNSSavePanelOverload2(id *id) {
	this.NSPanel.initNSPanelOverload2(id)
}

func (this *NSSavePanel) Filename() *NSString {
	var result int64 = OSObjc_msgSend(this.Id, OSSel_filename)
	var cond1 *NSString
	if result != 0 {
		cond1 = NewNSStringOverload1(result)
	} else {
		cond1 = nil
	}
	return cond1
}

func (this *NSSavePanel) NameFieldStringValue() *NSString {
	var result int64 = OSObjc_msgSend(this.Id, OSSel_nameFieldStringValue)
	var cond2 *NSString
	if result != 0 {
		cond2 = NewNSStringOverload1(result)
	} else {
		cond2 = nil
	}
	return cond2
}

func (this *NSSavePanel) RunModal() int64 {
	return OSObjc_msgSend(this.Id, OSSel_runModal)
}

func (this *NSSavePanel) RunModalForDirectory(path *NSString, name *NSString) int64 {
	var cond3 int64
	if path != (nil) {
		cond3 = path.Id
	} else {
		cond3 = int64(0)
	}
	var cond4 int64
	if name != (nil) {
		cond4 = name.Id
	} else {
		cond4 = int64(0)
	}
	return OSObjc_msgSendOverload54(this.Id, OSSel_runModalForDirectory_file_, cond3, cond4)
}

func (this *NSSavePanel) SetAccessoryView(accessoryView *NSView) {
	var cond5 int64
	if accessoryView != (nil) {
		cond5 = accessoryView.Id
	} else {
		cond5 = int64(0)
	}
	OSObjc_msgSendOverload44(this.Id, OSSel_setAccessoryView_, cond5)
}

func (this *NSSavePanel) SetAllowedFileTypes(allowedFileTypes *NSArray) {
	var cond6 int64
	if allowedFileTypes != (nil) {
		cond6 = allowedFileTypes.Id
	} else {
		cond6 = int64(0)
	}
	OSObjc_msgSendOverload44(this.Id, OSSel_setAllowedFileTypes_, cond6)
}

func (this *NSSavePanel) SetAllowsOtherFileTypes(allowsOtherFileTypes bool) {
	OSObjc_msgSendOverload27(this.Id, OSSel_setAllowsOtherFileTypes_, allowsOtherFileTypes)
}

func (this *NSSavePanel) SetCanCreateDirectories(canCreateDirectories bool) {
	OSObjc_msgSendOverload27(this.Id, OSSel_setCanCreateDirectories_, canCreateDirectories)
}

func (this *NSSavePanel) SetDirectory(path *NSString) {
	var cond7 int64
	if path != (nil) {
		cond7 = path.Id
	} else {
		cond7 = int64(0)
	}
	OSObjc_msgSendOverload44(this.Id, OSSel_setDirectory_, cond7)
}

func (this *NSSavePanel) SetDirectoryURL(directoryURL *NSURL) {
	var cond8 int64
	if directoryURL != (nil) {
		cond8 = directoryURL.Id
	} else {
		cond8 = int64(0)
	}
	OSObjc_msgSendOverload44(this.Id, OSSel_setDirectoryURL_, cond8)
}

func (this *NSSavePanel) SetMessage(message *NSString) {
	var cond9 int64
	if message != (nil) {
		cond9 = message.Id
	} else {
		cond9 = int64(0)
	}
	OSObjc_msgSendOverload44(this.Id, OSSel_setMessage_, cond9)
}

func (this *NSSavePanel) SetNameFieldStringValue(nameFieldStringValue *NSString) {
	var cond10 int64
	if nameFieldStringValue != (nil) {
		cond10 = nameFieldStringValue.Id
	} else {
		cond10 = int64(0)
	}
	OSObjc_msgSendOverload44(this.Id, OSSel_setNameFieldStringValue_, cond10)
}

func (this *NSSavePanel) SetTitle(title *NSString) {
	var cond11 int64
	if title != (nil) {
		cond11 = title.Id
	} else {
		cond11 = int64(0)
	}
	OSObjc_msgSendOverload44(this.Id, OSSel_setTitle_, cond11)
}

func (this *NSSavePanel) SetTreatsFilePackagesAsDirectories(treatsFilePackagesAsDirectories bool) {
	OSObjc_msgSendOverload27(this.Id, OSSel_setTreatsFilePackagesAsDirectories_, treatsFilePackagesAsDirectories)
}

func (this *NSSavePanel) ValidateVisibleColumns() {
	OSObjc_msgSend(this.Id, OSSel_validateVisibleColumns)
}

func NSSavePanelSavePanel() *NSSavePanel {
	var result int64 = OSObjc_msgSend(OSClass_NSSavePanel, OSSel_savePanel)
	var cond12 *NSSavePanel
	if result != 0 {
		cond12 = NewNSSavePanelOverload1(result)
	} else {
		cond12 = nil
	}
	return cond12
}

func NSSavePanelMinFrameWidthWithTitle(aTitle *NSString, aStyle int64) float64 {
	var cond13 int64
	if aTitle != (nil) {
		cond13 = aTitle.Id
	} else {
		cond13 = int64(0)
	}
	return OSObjc_msgSend_fpretIdSelArg0Arg1(OSClass_NSSavePanel, OSSel_minFrameWidthWithTitle_styleMask_, cond13, aStyle)
}

func NSSavePanelWindowNumberAtPoint(point NSPoint, windowNumber int64) int64 {
	return OSObjc_msgSendOverload6(OSClass_NSSavePanel, OSSel_windowNumberAtPoint_belowWindowWithWindowNumber_, point, windowNumber)
}
