// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT PI/cocoa/org/eclipse/swt/internal/cocoa/NSTextTab.java @ af630a9093. DO NOT EDIT.

package cocoa

type NSTextTab struct {
	NSObject
}

func NewNSTextTab() *NSTextTab {
	this := &NSTextTab{}
	this.Impl = this
	this.initNSTextTab()
	return this
}

func (this *NSTextTab) initNSTextTab() {
	this.NSObject.initNSObject()
}

func NewNSTextTabOverload1(id int64) *NSTextTab {
	this := &NSTextTab{}
	this.Impl = this
	this.initNSTextTabOverload1(id)
	return this
}

func (this *NSTextTab) initNSTextTabOverload1(id int64) {
	this.NSObject.initNSObjectOverload1(id)
}

func NewNSTextTabOverload2(id *id) *NSTextTab {
	this := &NSTextTab{}
	this.Impl = this
	this.initNSTextTabOverload2(id)
	return this
}

func (this *NSTextTab) initNSTextTabOverload2(id *id) {
	this.NSObject.initNSObjectOverload2(id)
}

func (this *NSTextTab) InitWithType(type_ int64, loc float64) *NSTextTab {
	var result int64 = OSObjc_msgSendOverload53(this.Id, OSSel_initWithType_location_, type_, loc)
	var cond775 *NSTextTab
	var cond776 *NSTextTab
	if result != 0 {
		cond776 = NewNSTextTabOverload1(result)
	} else {
		cond776 = nil
	}
	if result == this.Id {
		cond775 = this
	} else {
		cond775 = (cond776)
	}
	return cond775
}
