// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT PI/cocoa/org/eclipse/swt/internal/cocoa/NSDatePicker.java @ af630a9093. DO NOT EDIT.

package cocoa

type NSDatePicker struct {
	NSControl
}

func NewNSDatePicker() *NSDatePicker {
	this := &NSDatePicker{}
	this.impl = this
	this.initNSDatePicker()
	return this
}

func (this *NSDatePicker) initNSDatePicker() {
	this.NSControl.initNSControl()
}

func NewNSDatePickerOverload1(id int64) *NSDatePicker {
	this := &NSDatePicker{}
	this.impl = this
	this.initNSDatePickerOverload1(id)
	return this
}

func (this *NSDatePicker) initNSDatePickerOverload1(id int64) {
	this.NSControl.initNSControlOverload1(id)
}

func NewNSDatePickerOverload2(id *id) *NSDatePicker {
	this := &NSDatePicker{}
	this.impl = this
	this.initNSDatePickerOverload2(id)
	return this
}

func (this *NSDatePicker) initNSDatePickerOverload2(id *id) {
	this.NSControl.initNSControlOverload2(id)
}

func (this *NSDatePicker) DateValue() *NSDate {
	var result int64 = OSObjc_msgSend(this.Id, OSSel_dateValue)
	var cond230 *NSDate
	if result != 0 {
		cond230 = NewNSDateOverload1(result)
	} else {
		cond230 = nil
	}
	return cond230
}

func (this *NSDatePicker) SetBackgroundColor(backgroundColor *NSColor) {
	var cond231 int64
	if backgroundColor != (nil) {
		cond231 = backgroundColor.Id
	} else {
		cond231 = int64(0)
	}
	OSObjc_msgSendOverload44(this.Id, OSSel_setBackgroundColor_, cond231)
}

func (this *NSDatePicker) SetBezeled(bezeled bool) {
	OSObjc_msgSendOverload27(this.Id, OSSel_setBezeled_, bezeled)
}

func (this *NSDatePicker) SetBordered(bordered bool) {
	OSObjc_msgSendOverload27(this.Id, OSSel_setBordered_, bordered)
}

func (this *NSDatePicker) SetDatePickerElements(datePickerElements int64) {
	OSObjc_msgSendOverload44(this.Id, OSSel_setDatePickerElements_, datePickerElements)
}

func (this *NSDatePicker) SetDatePickerStyle(datePickerStyle int64) {
	OSObjc_msgSendOverload44(this.Id, OSSel_setDatePickerStyle_, datePickerStyle)
}

func (this *NSDatePicker) SetDateValue(dateValue *NSDate) {
	var cond232 int64
	if dateValue != (nil) {
		cond232 = dateValue.Id
	} else {
		cond232 = int64(0)
	}
	OSObjc_msgSendOverload44(this.Id, OSSel_setDateValue_, cond232)
}

func (this *NSDatePicker) SetDrawsBackground(drawsBackground bool) {
	OSObjc_msgSendOverload27(this.Id, OSSel_setDrawsBackground_, drawsBackground)
}

func (this *NSDatePicker) SetTextColor(textColor *NSColor) {
	var cond233 int64
	if textColor != (nil) {
		cond233 = textColor.Id
	} else {
		cond233 = int64(0)
	}
	OSObjc_msgSendOverload44(this.Id, OSSel_setTextColor_, cond233)
}

func NSDatePickerCellClass() int64 {
	return OSObjc_msgSend(OSClass_NSDatePicker, OSSel_cellClass)
}

func NSDatePickerSetCellClass(factoryId int64) {
	OSObjc_msgSendOverload44(OSClass_NSDatePicker, OSSel_setCellClass_, factoryId)
}
