// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT PI/cocoa/org/eclipse/swt/internal/cocoa/NSWorkspace.java @ af630a9093. DO NOT EDIT.

package cocoa

type NSWorkspace struct {
	NSObject
}

func NewNSWorkspace() *NSWorkspace {
	this := &NSWorkspace{}
	this.Impl = this
	this.initNSWorkspace()
	return this
}

func (this *NSWorkspace) initNSWorkspace() {
	this.NSObject.initNSObject()
}

func NewNSWorkspaceOverload1(id int64) *NSWorkspace {
	this := &NSWorkspace{}
	this.Impl = this
	this.initNSWorkspaceOverload1(id)
	return this
}

func (this *NSWorkspace) initNSWorkspaceOverload1(id int64) {
	this.NSObject.initNSObjectOverload1(id)
}

func NewNSWorkspaceOverload2(id *id) *NSWorkspace {
	this := &NSWorkspace{}
	this.Impl = this
	this.initNSWorkspaceOverload2(id)
	return this
}

func (this *NSWorkspace) initNSWorkspaceOverload2(id *id) {
	this.NSObject.initNSObjectOverload2(id)
}

func (this *NSWorkspace) URLForApplicationToOpenURL(url *NSURL) *NSURL {
	var cond925 int64
	if url != nil {
		cond925 = url.Id
	} else {
		cond925 = int64(0)
	}
	var result int64 = OSObjc_msgSendOverload44(this.Id, OSSel_URLForApplicationToOpenURL_, cond925)
	var cond926 *NSURL
	if result != 0 {
		cond926 = NewNSURLOverload1(result)
	} else {
		cond926 = nil
	}
	return cond926
}

func (this *NSWorkspace) URLForApplicationToOpenContentType(contentType *UTType) *NSURL {
	var cond927 int64
	if contentType != nil {
		cond927 = contentType.Id
	} else {
		cond927 = int64(0)
	}
	var result int64 = OSObjc_msgSendOverload44(this.Id, OSSel_URLForApplicationToOpenContentType_, cond927)
	var cond928 *NSURL
	if result != 0 {
		cond928 = NewNSURLOverload1(result)
	} else {
		cond928 = nil
	}
	return cond928
}

func (this *NSWorkspace) FullPathForApplication(appName *NSString) *NSString {
	var cond929 int64
	if appName != nil {
		cond929 = appName.Id
	} else {
		cond929 = int64(0)
	}
	var result int64 = OSObjc_msgSendOverload44(this.Id, OSSel_fullPathForApplication_, cond929)
	var cond930 *NSString
	if result != 0 {
		cond930 = NewNSStringOverload1(result)
	} else {
		cond930 = nil
	}
	return cond930
}

func (this *NSWorkspace) IconForFile(fullPath *NSString) *NSImage {
	var cond931 int64
	if fullPath != nil {
		cond931 = fullPath.Id
	} else {
		cond931 = int64(0)
	}
	var result int64 = OSObjc_msgSendOverload44(this.Id, OSSel_iconForFile_, cond931)
	var cond932 *NSImage
	if result != 0 {
		cond932 = NewNSImageOverload1(result)
	} else {
		cond932 = nil
	}
	return cond932
}

func (this *NSWorkspace) IsFilePackageAtPath(fullPath *NSString) bool {
	var cond933 int64
	if fullPath != nil {
		cond933 = fullPath.Id
	} else {
		cond933 = int64(0)
	}
	return OSObjc_msgSend_boolOverload5(this.Id, OSSel_isFilePackageAtPath_, cond933)
}

func (this *NSWorkspace) OpenURL(url *NSURL) bool {
	var cond934 int64
	if url != nil {
		cond934 = url.Id
	} else {
		cond934 = int64(0)
	}
	return OSObjc_msgSend_boolOverload5(this.Id, OSSel_openURL_, cond934)
}

func (this *NSWorkspace) OpenURLs(urls *NSArray, bundleIdentifier *NSString, options int64, descriptor *NSAppleEventDescriptor, identifiers int64) bool {
	var cond935 int64
	if urls != nil {
		cond935 = urls.Id
	} else {
		cond935 = int64(0)
	}
	var cond936 int64
	if bundleIdentifier != nil {
		cond936 = bundleIdentifier.Id
	} else {
		cond936 = int64(0)
	}
	var cond937 int64
	if descriptor != nil {
		cond937 = descriptor.Id
	} else {
		cond937 = int64(0)
	}
	return OSObjc_msgSend_boolOverload11(this.Id, OSSel_openURLs_withAppBundleIdentifier_options_additionalEventParamDescriptor_launchIdentifiers_, cond935, cond936, options, cond937, identifiers)
}

func (this *NSWorkspace) Type(firstTypeName *NSString, secondTypeName *NSString) bool {
	var cond938 int64
	if firstTypeName != nil {
		cond938 = firstTypeName.Id
	} else {
		cond938 = int64(0)
	}
	var cond939 int64
	if secondTypeName != nil {
		cond939 = secondTypeName.Id
	} else {
		cond939 = int64(0)
	}
	return OSObjc_msgSend_boolOverload8(this.Id, OSSel_type_conformsToType_, cond938, cond939)
}

func (this *NSWorkspace) TypeOfFile(absoluteFilePath *NSString, outError int64) *NSString {
	var cond940 int64
	if absoluteFilePath != nil {
		cond940 = absoluteFilePath.Id
	} else {
		cond940 = int64(0)
	}
	var result int64 = OSObjc_msgSendOverload54(this.Id, OSSel_typeOfFile_error_, cond940, outError)
	var cond941 *NSString
	if result != 0 {
		cond941 = NewNSStringOverload1(result)
	} else {
		cond941 = nil
	}
	return cond941
}

func NSWorkspaceSharedWorkspace() *NSWorkspace {
	var result int64 = OSObjc_msgSend(OSClass_NSWorkspace, OSSel_sharedWorkspace)
	var cond942 *NSWorkspace
	if result != 0 {
		cond942 = NewNSWorkspaceOverload1(result)
	} else {
		cond942 = nil
	}
	return cond942
}
