// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT PI/cocoa/org/eclipse/swt/internal/cocoa/NSMutableParagraphStyle.java @ af630a9093. DO NOT EDIT.

package cocoa

type NSMutableParagraphStyle struct {
	NSParagraphStyle
}

func NewNSMutableParagraphStyle() *NSMutableParagraphStyle {
	this := &NSMutableParagraphStyle{}
	this.impl = this
	this.initNSMutableParagraphStyle()
	return this
}

func (this *NSMutableParagraphStyle) initNSMutableParagraphStyle() {
	this.NSParagraphStyle.initNSParagraphStyle()
}

func NewNSMutableParagraphStyleOverload1(id int64) *NSMutableParagraphStyle {
	this := &NSMutableParagraphStyle{}
	this.impl = this
	this.initNSMutableParagraphStyleOverload1(id)
	return this
}

func (this *NSMutableParagraphStyle) initNSMutableParagraphStyleOverload1(id int64) {
	this.NSParagraphStyle.initNSParagraphStyleOverload1(id)
}

func NewNSMutableParagraphStyleOverload2(id *id) *NSMutableParagraphStyle {
	this := &NSMutableParagraphStyle{}
	this.impl = this
	this.initNSMutableParagraphStyleOverload2(id)
	return this
}

func (this *NSMutableParagraphStyle) initNSMutableParagraphStyleOverload2(id *id) {
	this.NSParagraphStyle.initNSParagraphStyleOverload2(id)
}

func (this *NSMutableParagraphStyle) AddTabStop(anObject *NSTextTab) {
	var cond437 int64
	if anObject != (nil) {
		cond437 = anObject.Id
	} else {
		cond437 = int64(0)
	}
	OSObjc_msgSendOverload44(this.Id, OSSel_addTabStop_, cond437)
}

func (this *NSMutableParagraphStyle) SetAlignment(alignment int64) {
	OSObjc_msgSendOverload44(this.Id, OSSel_setAlignment_, alignment)
}

func (this *NSMutableParagraphStyle) SetBaseWritingDirection(baseWritingDirection int64) {
	OSObjc_msgSendOverload44(this.Id, OSSel_setBaseWritingDirection_, baseWritingDirection)
}

func (this *NSMutableParagraphStyle) SetDefaultTabInterval(defaultTabInterval float64) {
	OSObjc_msgSendOverload35(this.Id, OSSel_setDefaultTabInterval_, defaultTabInterval)
}

func (this *NSMutableParagraphStyle) SetFirstLineHeadIndent(firstLineHeadIndent float64) {
	OSObjc_msgSendOverload35(this.Id, OSSel_setFirstLineHeadIndent_, firstLineHeadIndent)
}

func (this *NSMutableParagraphStyle) SetHeadIndent(headIndent float64) {
	OSObjc_msgSendOverload35(this.Id, OSSel_setHeadIndent_, headIndent)
}

func (this *NSMutableParagraphStyle) SetLineBreakMode(lineBreakMode int64) {
	OSObjc_msgSendOverload44(this.Id, OSSel_setLineBreakMode_, lineBreakMode)
}

func (this *NSMutableParagraphStyle) SetLineSpacing(lineSpacing float64) {
	OSObjc_msgSendOverload35(this.Id, OSSel_setLineSpacing_, lineSpacing)
}

func (this *NSMutableParagraphStyle) SetTabStops(tabStops *NSArray) {
	var cond438 int64
	if tabStops != (nil) {
		cond438 = tabStops.Id
	} else {
		cond438 = int64(0)
	}
	OSObjc_msgSendOverload44(this.Id, OSSel_setTabStops_, cond438)
}
