// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT PI/cocoa/org/eclipse/swt/internal/cocoa/NSView.java @ af630a9093. DO NOT EDIT.

package cocoa

type NSView struct {
	NSResponder
}

func NewNSView() *NSView {
	this := &NSView{}
	this.impl = this
	this.initNSView()
	return this
}

func (this *NSView) initNSView() {
	this.NSResponder.initNSResponder()
}

func NewNSViewOverload1(id int64) *NSView {
	this := &NSView{}
	this.impl = this
	this.initNSViewOverload1(id)
	return this
}

func (this *NSView) initNSViewOverload1(id int64) {
	this.NSResponder.initNSResponderOverload1(id)
}

func NewNSViewOverload2(id *id) *NSView {
	this := &NSView{}
	this.impl = this
	this.initNSViewOverload2(id)
	return this
}

func (this *NSView) initNSViewOverload2(id *id) {
	this.NSResponder.initNSResponderOverload2(id)
}

func (this *NSView) AcceptsFirstMouse(theEvent *NSEvent) bool {
	var cond851 int64
	if theEvent != (nil) {
		cond851 = theEvent.Id
	} else {
		cond851 = int64(0)
	}
	return OSObjc_msgSend_boolOverload5(this.Id, OSSel_acceptsFirstMouse_, cond851)
}

func (this *NSView) AddSubview(aView *NSView) {
	var cond852 int64
	if aView != (nil) {
		cond852 = aView.Id
	} else {
		cond852 = int64(0)
	}
	OSObjc_msgSendOverload44(this.Id, OSSel_addSubview_, cond852)
}

func (this *NSView) AddSubviewAViewPlaceOtherView(aView *NSView, place int64, otherView *NSView) {
	var cond853 int64
	if aView != (nil) {
		cond853 = aView.Id
	} else {
		cond853 = int64(0)
	}
	var cond854 int64
	if otherView != (nil) {
		cond854 = otherView.Id
	} else {
		cond854 = int64(0)
	}
	OSObjc_msgSendOverload58(this.Id, OSSel_addSubview_positioned_relativeTo_, cond853, place, cond854)
}

func (this *NSView) AddToolTipRect(aRect NSRect, anObject *id, data int64) int64 {
	var cond855 int64
	if anObject != (nil) {
		cond855 = anObject.Id
	} else {
		cond855 = int64(0)
	}
	return OSObjc_msgSendOverload23(this.Id, OSSel_addToolTipRect_owner_userData_, aRect, cond855, data)
}

func (this *NSView) BeginDocument() {
	OSObjc_msgSend(this.Id, OSSel_beginDocument)
}

func (this *NSView) BeginPageInRect(aRect NSRect, location NSPoint) {
	OSObjc_msgSendOverload14(this.Id, OSSel_beginPageInRect_atPlacement_, aRect, location)
}

func (this *NSView) BitmapImageRepForCachingDisplayInRect(rect NSRect) *NSBitmapImageRep {
	var result int64 = OSObjc_msgSendOverload13(this.Id, OSSel_bitmapImageRepForCachingDisplayInRect_, rect)
	var cond856 *NSBitmapImageRep
	if result != 0 {
		cond856 = NewNSBitmapImageRepOverload1(result)
	} else {
		cond856 = nil
	}
	return cond856
}

func (this *NSView) Bounds() NSRect {
	var result NSRect = NSRect{}
	OSObjc_msgSend_stretOverload9(&result, this.Id, OSSel_bounds)
	return result
}

func (this *NSView) CacheDisplayInRect(rect NSRect, bitmapImageRep *NSBitmapImageRep) {
	var cond857 int64
	if bitmapImageRep != (nil) {
		cond857 = bitmapImageRep.Id
	} else {
		cond857 = int64(0)
	}
	OSObjc_msgSendOverload21(this.Id, OSSel_cacheDisplayInRect_toBitmapImageRep_, rect, cond857)
}

func (this *NSView) CanBecomeKeyView() bool {
	return OSObjc_msgSend_bool(this.Id, OSSel_canBecomeKeyView)
}

func (this *NSView) ConvertPoint_fromView_(aPoint NSPoint, aView *NSView) NSPoint {
	var result NSPoint = NSPoint{}
	var cond858 int64
	if aView != (nil) {
		cond858 = aView.Id
	} else {
		cond858 = int64(0)
	}
	OSObjc_msgSend_stretOverload4(&result, this.Id, OSSel_convertPoint_fromView_, aPoint, cond858)
	return result
}

func (this *NSView) ConvertPoint_toView_(aPoint NSPoint, aView *NSView) NSPoint {
	var result NSPoint = NSPoint{}
	var cond859 int64
	if aView != (nil) {
		cond859 = aView.Id
	} else {
		cond859 = int64(0)
	}
	OSObjc_msgSend_stretOverload4(&result, this.Id, OSSel_convertPoint_toView_, aPoint, cond859)
	return result
}

func (this *NSView) ConvertRect_fromView_(aRect NSRect, aView *NSView) NSRect {
	var result NSRect = NSRect{}
	var cond860 int64
	if aView != (nil) {
		cond860 = aView.Id
	} else {
		cond860 = int64(0)
	}
	OSObjc_msgSend_stretOverload12(&result, this.Id, OSSel_convertRect_fromView_, aRect, cond860)
	return result
}

func (this *NSView) ConvertRect_toView_(aRect NSRect, aView *NSView) NSRect {
	var result NSRect = NSRect{}
	var cond861 int64
	if aView != (nil) {
		cond861 = aView.Id
	} else {
		cond861 = int64(0)
	}
	OSObjc_msgSend_stretOverload12(&result, this.Id, OSSel_convertRect_toView_, aRect, cond861)
	return result
}

func (this *NSView) DiscardCursorRects() {
	OSObjc_msgSend(this.Id, OSSel_discardCursorRects)
}

func (this *NSView) Display() {
	OSObjc_msgSend(this.Id, OSSel_display)
}

func (this *NSView) DisplayIfNeeded() {
	OSObjc_msgSend(this.Id, OSSel_displayIfNeeded)
}

func (this *NSView) DisplayRectIgnoringOpacity(aRect NSRect, context *NSGraphicsContext) {
	var cond862 int64
	if context != (nil) {
		cond862 = context.Id
	} else {
		cond862 = int64(0)
	}
	OSObjc_msgSendOverload21(this.Id, OSSel_displayRectIgnoringOpacity_inContext_, aRect, cond862)
}

func (this *NSView) DragImage(anImage *NSImage, viewLocation NSPoint, initialOffset NSSize, event *NSEvent, pboard *NSPasteboard, sourceObj *id, slideFlag bool) {
	var cond863 int64
	if anImage != (nil) {
		cond863 = anImage.Id
	} else {
		cond863 = int64(0)
	}
	var cond864 int64
	if event != (nil) {
		cond864 = event.Id
	} else {
		cond864 = int64(0)
	}
	var cond865 int64
	if pboard != (nil) {
		cond865 = pboard.Id
	} else {
		cond865 = int64(0)
	}
	var cond866 int64
	if sourceObj != (nil) {
		cond866 = sourceObj.Id
	} else {
		cond866 = int64(0)
	}
	OSObjc_msgSendOverload46(this.Id, OSSel_dragImage_at_offset_event_pasteboard_source_slideBack_, cond863, viewLocation, initialOffset, cond864, cond865, cond866, slideFlag)
}

func (this *NSView) DrawRect(dirtyRect NSRect) {
	OSObjc_msgSendOverload13(this.Id, OSSel_drawRect_, dirtyRect)
}

func (this *NSView) EndDocument() {
	OSObjc_msgSend(this.Id, OSSel_endDocument)
}

func (this *NSView) EndPage() {
	OSObjc_msgSend(this.Id, OSSel_endPage)
}

func (this *NSView) Frame() NSRect {
	var result NSRect = NSRect{}
	OSObjc_msgSend_stretOverload9(&result, this.Id, OSSel_frame)
	return result
}

func (this *NSView) HitTest(aPoint NSPoint) *NSView {
	var result int64 = OSObjc_msgSendOverload2(this.Id, OSSel_hitTest_, aPoint)
	var cond867 *NSView
	var cond868 *NSView
	if result != 0 {
		cond868 = NewNSViewOverload1(result)
	} else {
		cond868 = nil
	}
	if result == this.Id {
		cond867 = this
	} else {
		cond867 = (cond868)
	}
	return cond867
}

func (this *NSView) InitWithFrame(frameRect NSRect) *NSView {
	var result int64 = OSObjc_msgSendOverload13(this.Id, OSSel_initWithFrame_, frameRect)
	var cond869 *NSView
	var cond870 *NSView
	if result != 0 {
		cond870 = NewNSViewOverload1(result)
	} else {
		cond870 = nil
	}
	if result == this.Id {
		cond869 = this
	} else {
		cond869 = (cond870)
	}
	return cond869
}

func (this *NSView) IsDescendantOf(aView *NSView) bool {
	var cond871 int64
	if aView != (nil) {
		cond871 = aView.Id
	} else {
		cond871 = int64(0)
	}
	return OSObjc_msgSend_boolOverload5(this.Id, OSSel_isDescendantOf_, cond871)
}

func (this *NSView) IsFlipped() bool {
	return OSObjc_msgSend_bool(this.Id, OSSel_isFlipped)
}

func (this *NSView) IsHidden() bool {
	return OSObjc_msgSend_bool(this.Id, OSSel_isHidden)
}

func (this *NSView) IsHiddenOrHasHiddenAncestor() bool {
	return OSObjc_msgSend_bool(this.Id, OSSel_isHiddenOrHasHiddenAncestor)
}

func (this *NSView) IsOpaque() bool {
	return OSObjc_msgSend_bool(this.Id, OSSel_isOpaque)
}

func (this *NSView) Layer() *CALayer {
	var result int64 = OSObjc_msgSend(this.Id, OSSel_layer)
	var cond872 *CALayer
	if result != 0 {
		cond872 = NewCALayerOverload1(result)
	} else {
		cond872 = nil
	}
	return cond872
}

func (this *NSView) LockFocus() {
	OSObjc_msgSend(this.Id, OSSel_lockFocus)
}

func (this *NSView) LockFocusIfCanDraw() bool {
	return OSObjc_msgSend_bool(this.Id, OSSel_lockFocusIfCanDraw)
}

func (this *NSView) MenuForEvent(event *NSEvent) *NSMenu {
	var cond873 int64
	if event != (nil) {
		cond873 = event.Id
	} else {
		cond873 = int64(0)
	}
	var result int64 = OSObjc_msgSendOverload44(this.Id, OSSel_menuForEvent_, cond873)
	var cond874 *NSMenu
	if result != 0 {
		cond874 = NewNSMenuOverload1(result)
	} else {
		cond874 = nil
	}
	return cond874
}

func (this *NSView) Mouse(aPoint NSPoint, aRect NSRect) bool {
	return OSObjc_msgSend_boolOverload2(this.Id, OSSel_mouse_inRect_, aPoint, aRect)
}

func (this *NSView) MouseDownCanMoveWindow() bool {
	return OSObjc_msgSend_bool(this.Id, OSSel_mouseDownCanMoveWindow)
}

func (this *NSView) NeedsPanelToBecomeKey() bool {
	return OSObjc_msgSend_bool(this.Id, OSSel_needsPanelToBecomeKey)
}

func (this *NSView) RegisterForDraggedTypes(newTypes *NSArray) {
	var cond875 int64
	if newTypes != (nil) {
		cond875 = newTypes.Id
	} else {
		cond875 = int64(0)
	}
	OSObjc_msgSendOverload44(this.Id, OSSel_registerForDraggedTypes_, cond875)
}

func (this *NSView) RemoveFromSuperview() {
	OSObjc_msgSend(this.Id, OSSel_removeFromSuperview)
}

func (this *NSView) RemoveToolTip(tag int64) {
	OSObjc_msgSendOverload44(this.Id, OSSel_removeToolTip_, tag)
}

func (this *NSView) RemoveTrackingArea(trackingArea *NSTrackingArea) {
	var cond876 int64
	if trackingArea != (nil) {
		cond876 = trackingArea.Id
	} else {
		cond876 = int64(0)
	}
	OSObjc_msgSendOverload44(this.Id, OSSel_removeTrackingArea_, cond876)
}

func (this *NSView) ResetCursorRects() {
	OSObjc_msgSend(this.Id, OSSel_resetCursorRects)
}

func (this *NSView) ScrollClipView(aClipView *NSClipView, aPoint NSPoint) {
	var cond877 int64
	if aClipView != (nil) {
		cond877 = aClipView.Id
	} else {
		cond877 = int64(0)
	}
	OSObjc_msgSendOverload45(this.Id, OSSel_scrollClipView_toPoint_, cond877, aPoint)
}

func (this *NSView) ScrollPoint(aPoint NSPoint) {
	OSObjc_msgSendOverload2(this.Id, OSSel_scrollPoint_, aPoint)
}

func (this *NSView) ScrollRect(aRect NSRect, delta NSSize) {
	OSObjc_msgSendOverload16(this.Id, OSSel_scrollRect_by_, aRect, delta)
}

func (this *NSView) SetAcceptsTouchEvents(acceptsTouchEvents bool) {
	OSObjc_msgSendOverload27(this.Id, OSSel_setAcceptsTouchEvents_, acceptsTouchEvents)
}

func (this *NSView) SetAutoresizesSubviews(autoresizesSubviews bool) {
	OSObjc_msgSendOverload27(this.Id, OSSel_setAutoresizesSubviews_, autoresizesSubviews)
}

func (this *NSView) SetAutoresizingMask(autoresizingMask int64) {
	OSObjc_msgSendOverload44(this.Id, OSSel_setAutoresizingMask_, autoresizingMask)
}

func (this *NSView) SetBoundsRotation(boundsRotation float64) {
	OSObjc_msgSendOverload35(this.Id, OSSel_setBoundsRotation_, boundsRotation)
}

func (this *NSView) SetBoundsSize(newSize NSSize) {
	OSObjc_msgSendOverload26(this.Id, OSSel_setBoundsSize_, newSize)
}

func (this *NSView) SetFocusRingType(focusRingType int64) {
	OSObjc_msgSendOverload44(this.Id, OSSel_setFocusRingType_, focusRingType)
}

func (this *NSView) SetFrame(frame NSRect) {
	OSObjc_msgSendOverload13(this.Id, OSSel_setFrame_, frame)
}

func (this *NSView) SetFrameOrigin(newOrigin NSPoint) {
	OSObjc_msgSendOverload2(this.Id, OSSel_setFrameOrigin_, newOrigin)
}

func (this *NSView) SetFrameSize(newSize NSSize) {
	OSObjc_msgSendOverload26(this.Id, OSSel_setFrameSize_, newSize)
}

func (this *NSView) SetHidden(hidden bool) {
	OSObjc_msgSendOverload27(this.Id, OSSel_setHidden_, hidden)
}

func (this *NSView) SetNeedsDisplay(needsDisplay bool) {
	OSObjc_msgSendOverload27(this.Id, OSSel_setNeedsDisplay_, needsDisplay)
}

func (this *NSView) SetNeedsDisplayInRect(invalidRect NSRect) {
	OSObjc_msgSendOverload13(this.Id, OSSel_setNeedsDisplayInRect_, invalidRect)
}

func (this *NSView) SetToolTip(toolTip *NSString) {
	var cond878 int64
	if toolTip != (nil) {
		cond878 = toolTip.Id
	} else {
		cond878 = int64(0)
	}
	OSObjc_msgSendOverload44(this.Id, OSSel_setToolTip_, cond878)
}

func (this *NSView) SetWantsRestingTouches(wantsRestingTouches bool) {
	OSObjc_msgSendOverload27(this.Id, OSSel_setWantsRestingTouches_, wantsRestingTouches)
}

func (this *NSView) ShouldDelayWindowOrderingForEvent(theEvent *NSEvent) bool {
	var cond879 int64
	if theEvent != (nil) {
		cond879 = theEvent.Id
	} else {
		cond879 = int64(0)
	}
	return OSObjc_msgSend_boolOverload5(this.Id, OSSel_shouldDelayWindowOrderingForEvent_, cond879)
}

func (this *NSView) Subviews() *NSArray {
	var result int64 = OSObjc_msgSend(this.Id, OSSel_subviews)
	var cond880 *NSArray
	if result != 0 {
		cond880 = NewNSArrayOverload1(result)
	} else {
		cond880 = nil
	}
	return cond880
}

func (this *NSView) Superview() *NSView {
	var result int64 = OSObjc_msgSend(this.Id, OSSel_superview)
	var cond881 *NSView
	var cond882 *NSView
	if result != 0 {
		cond882 = NewNSViewOverload1(result)
	} else {
		cond882 = nil
	}
	if result == this.Id {
		cond881 = this
	} else {
		cond881 = (cond882)
	}
	return cond881
}

func (this *NSView) TrackingAreas() *NSArray {
	var result int64 = OSObjc_msgSend(this.Id, OSSel_trackingAreas)
	var cond883 *NSArray
	if result != 0 {
		cond883 = NewNSArrayOverload1(result)
	} else {
		cond883 = nil
	}
	return cond883
}

func (this *NSView) UnlockFocus() {
	OSObjc_msgSend(this.Id, OSSel_unlockFocus)
}

func (this *NSView) UnregisterDraggedTypes() {
	OSObjc_msgSend(this.Id, OSSel_unregisterDraggedTypes)
}

func (this *NSView) UpdateTrackingAreas() {
	OSObjc_msgSend(this.Id, OSSel_updateTrackingAreas)
}

func (this *NSView) ViewDidMoveToWindow() {
	OSObjc_msgSend(this.Id, OSSel_viewDidMoveToWindow)
}

func (this *NSView) ViewWillMoveToWindow(newWindow *NSWindow) {
	var cond884 int64
	if newWindow != (nil) {
		cond884 = newWindow.Id
	} else {
		cond884 = int64(0)
	}
	OSObjc_msgSendOverload44(this.Id, OSSel_viewWillMoveToWindow_, cond884)
}

func (this *NSView) VisibleRect() NSRect {
	var result NSRect = NSRect{}
	OSObjc_msgSend_stretOverload9(&result, this.Id, OSSel_visibleRect)
	return result
}

func (this *NSView) Window() *NSWindow {
	var result int64 = OSObjc_msgSend(this.Id, OSSel_window)
	var cond885 *NSWindow
	if result != 0 {
		cond885 = NewNSWindowOverload1(result)
	} else {
		cond885 = nil
	}
	return cond885
}
