// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT PI/cocoa/org/eclipse/swt/internal/cocoa/NSURLAuthenticationChallenge.java @ af630a9093. DO NOT EDIT.
//go:build darwin

package cocoa

type NSURLAuthenticationChallenge struct {
	NSObject
}

func NewNSURLAuthenticationChallenge() *NSURLAuthenticationChallenge {
	this := &NSURLAuthenticationChallenge{}
	this.impl = this
	this.initNSURLAuthenticationChallenge()
	return this
}

func (this *NSURLAuthenticationChallenge) initNSURLAuthenticationChallenge() {
	this.NSObject.initNSObject()
}

func NewNSURLAuthenticationChallengeOverload1(id int64) *NSURLAuthenticationChallenge {
	this := &NSURLAuthenticationChallenge{}
	this.impl = this
	this.initNSURLAuthenticationChallengeOverload1(id)
	return this
}

func (this *NSURLAuthenticationChallenge) initNSURLAuthenticationChallengeOverload1(id int64) {
	this.NSObject.initNSObjectOverload1(id)
}

func NewNSURLAuthenticationChallengeOverload2(id *id) *NSURLAuthenticationChallenge {
	this := &NSURLAuthenticationChallenge{}
	this.impl = this
	this.initNSURLAuthenticationChallengeOverload2(id)
	return this
}

func (this *NSURLAuthenticationChallenge) initNSURLAuthenticationChallengeOverload2(id *id) {
	this.NSObject.initNSObjectOverload2(id)
}

func (this *NSURLAuthenticationChallenge) PreviousFailureCount() int64 {
	return OSObjc_msgSend(this.Id, OSSel_previousFailureCount)
}

func (this *NSURLAuthenticationChallenge) ProposedCredential() *NSURLCredential {
	var result int64 = OSObjc_msgSend(this.Id, OSSel_proposedCredential)
	var cond1 *NSURLCredential
	if result != 0 {
		cond1 = NewNSURLCredentialOverload1(result)
	} else {
		cond1 = nil
	}
	return cond1
}

func (this *NSURLAuthenticationChallenge) ProtectionSpace() *NSURLProtectionSpace {
	var result int64 = OSObjc_msgSend(this.Id, OSSel_protectionSpace)
	var cond2 *NSURLProtectionSpace
	if result != 0 {
		cond2 = NewNSURLProtectionSpaceOverload1(result)
	} else {
		cond2 = nil
	}
	return cond2
}

func (this *NSURLAuthenticationChallenge) Sender() *id {
	var result int64 = OSObjc_msgSend(this.Id, OSSel_sender)
	var cond3 *id
	if result != 0 {
		cond3 = NewidOverload1(result)
	} else {
		cond3 = nil
	}
	return cond3
}
