// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT PI/cocoa/org/eclipse/swt/internal/cocoa/NSPrintPanel.java @ af630a9093. DO NOT EDIT.
//go:build darwin

package cocoa

type NSPrintPanel struct {
	NSObject
}

func NewNSPrintPanel() *NSPrintPanel {
	this := &NSPrintPanel{}
	this.impl = this
	this.initNSPrintPanel()
	return this
}

func (this *NSPrintPanel) initNSPrintPanel() {
	this.NSObject.initNSObject()
}

func NewNSPrintPanelOverload1(id int64) *NSPrintPanel {
	this := &NSPrintPanel{}
	this.impl = this
	this.initNSPrintPanelOverload1(id)
	return this
}

func (this *NSPrintPanel) initNSPrintPanelOverload1(id int64) {
	this.NSObject.initNSObjectOverload1(id)
}

func NewNSPrintPanelOverload2(id *id) *NSPrintPanel {
	this := &NSPrintPanel{}
	this.impl = this
	this.initNSPrintPanelOverload2(id)
	return this
}

func (this *NSPrintPanel) initNSPrintPanelOverload2(id *id) {
	this.NSObject.initNSObjectOverload2(id)
}

func (this *NSPrintPanel) BeginSheetWithPrintInfo(printInfo *NSPrintInfo, docWindow *NSWindow, delegate *id, didEndSelector int64, contextInfo int64) {
	var cond588 int64
	if printInfo != (nil) {
		cond588 = printInfo.Id
	} else {
		cond588 = int64(0)
	}
	var cond589 int64
	if docWindow != (nil) {
		cond589 = docWindow.Id
	} else {
		cond589 = int64(0)
	}
	var cond590 int64
	if delegate != (nil) {
		cond590 = delegate.Id
	} else {
		cond590 = int64(0)
	}
	OSObjc_msgSendOverload61(this.Id, OSSel_beginSheetWithPrintInfo_modalForWindow_delegate_didEndSelector_contextInfo_, cond588, cond589, cond590, didEndSelector, contextInfo)
}

func (this *NSPrintPanel) Options() int64 {
	return OSObjc_msgSend(this.Id, OSSel_options)
}

func (this *NSPrintPanel) RunModalWithPrintInfo(printInfo *NSPrintInfo) int64 {
	var cond591 int64
	if printInfo != (nil) {
		cond591 = printInfo.Id
	} else {
		cond591 = int64(0)
	}
	return OSObjc_msgSendOverload44(this.Id, OSSel_runModalWithPrintInfo_, cond591)
}

func (this *NSPrintPanel) SetOptions(options int64) {
	OSObjc_msgSendOverload44(this.Id, OSSel_setOptions_, options)
}

func NSPrintPanelPrintPanel() *NSPrintPanel {
	var result int64 = OSObjc_msgSend(OSClass_NSPrintPanel, OSSel_printPanel)
	var cond592 *NSPrintPanel
	if result != 0 {
		cond592 = NewNSPrintPanelOverload1(result)
	} else {
		cond592 = nil
	}
	return cond592
}
