// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT PI/cocoa/org/eclipse/swt/internal/cocoa/NSImageView.java @ af630a9093. DO NOT EDIT.

package cocoa

type NSImageView struct {
	NSControl
}

func NewNSImageView() *NSImageView {
	this := &NSImageView{}
	this.Impl = this
	this.initNSImageView()
	return this
}

func (this *NSImageView) initNSImageView() {
	this.NSControl.initNSControl()
}

func NewNSImageViewOverload1(id int64) *NSImageView {
	this := &NSImageView{}
	this.Impl = this
	this.initNSImageViewOverload1(id)
	return this
}

func (this *NSImageView) initNSImageViewOverload1(id int64) {
	this.NSControl.initNSControlOverload1(id)
}

func NewNSImageViewOverload2(id *id) *NSImageView {
	this := &NSImageView{}
	this.Impl = this
	this.initNSImageViewOverload2(id)
	return this
}

func (this *NSImageView) initNSImageViewOverload2(id *id) {
	this.NSControl.initNSControlOverload2(id)
}

func (this *NSImageView) Image() *NSImage {
	var result int64 = OSObjc_msgSend(this.Id, OSSel_image)
	var cond336 *NSImage
	if result != 0 {
		cond336 = NewNSImageOverload1(result)
	} else {
		cond336 = nil
	}
	return cond336
}

func (this *NSImageView) SetImage(image *NSImage) {
	var cond337 int64
	if image != nil {
		cond337 = image.Id
	} else {
		cond337 = int64(0)
	}
	OSObjc_msgSendOverload44(this.Id, OSSel_setImage_, cond337)
}

func (this *NSImageView) SetImageAlignment(imageAlignment int64) {
	OSObjc_msgSendOverload44(this.Id, OSSel_setImageAlignment_, imageAlignment)
}

func (this *NSImageView) SetImageScaling(imageScaling int64) {
	OSObjc_msgSendOverload44(this.Id, OSSel_setImageScaling_, imageScaling)
}

func NSImageViewCellClass() int64 {
	return OSObjc_msgSend(OSClass_NSImageView, OSSel_cellClass)
}

func NSImageViewSetCellClass(factoryId int64) {
	OSObjc_msgSendOverload44(OSClass_NSImageView, OSSel_setCellClass_, factoryId)
}
