// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT PI/cocoa/org/eclipse/swt/internal/cocoa/NSKeyedArchiver.java @ af630a9093. DO NOT EDIT.

package cocoa

type NSKeyedArchiver struct {
	NSCoder
}

func NewNSKeyedArchiver() *NSKeyedArchiver {
	this := &NSKeyedArchiver{}
	this.Impl = this
	this.initNSKeyedArchiver()
	return this
}

func (this *NSKeyedArchiver) initNSKeyedArchiver() {
	this.NSCoder.initNSCoder()
}

func NewNSKeyedArchiverOverload1(id int64) *NSKeyedArchiver {
	this := &NSKeyedArchiver{}
	this.Impl = this
	this.initNSKeyedArchiverOverload1(id)
	return this
}

func (this *NSKeyedArchiver) initNSKeyedArchiverOverload1(id int64) {
	this.NSCoder.initNSCoderOverload1(id)
}

func NewNSKeyedArchiverOverload2(id *id) *NSKeyedArchiver {
	this := &NSKeyedArchiver{}
	this.Impl = this
	this.initNSKeyedArchiverOverload2(id)
	return this
}

func (this *NSKeyedArchiver) initNSKeyedArchiverOverload2(id *id) {
	this.NSCoder.initNSCoderOverload2(id)
}

func NSKeyedArchiverArchivedDataWithRootObject(rootObject *id) *NSData {
	var cond344 int64
	if rootObject != nil {
		cond344 = rootObject.Id
	} else {
		cond344 = int64(0)
	}
	var result int64 = OSObjc_msgSendOverload44(OSClass_NSKeyedArchiver, OSSel_archivedDataWithRootObject_, cond344)
	var cond345 *NSData
	if result != 0 {
		cond345 = NewNSDataOverload1(result)
	} else {
		cond345 = nil
	}
	return cond345
}
