// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT PI/cocoa/org/eclipse/swt/internal/cocoa/NSPrintOperation.java @ af630a9093. DO NOT EDIT.
//go:build darwin

package cocoa

type NSPrintOperation struct {
	NSObject
}

func NewNSPrintOperation() *NSPrintOperation {
	this := &NSPrintOperation{}
	this.impl = this
	this.initNSPrintOperation()
	return this
}

func (this *NSPrintOperation) initNSPrintOperation() {
	this.NSObject.initNSObject()
}

func NewNSPrintOperationOverload1(id int64) *NSPrintOperation {
	this := &NSPrintOperation{}
	this.impl = this
	this.initNSPrintOperationOverload1(id)
	return this
}

func (this *NSPrintOperation) initNSPrintOperationOverload1(id int64) {
	this.NSObject.initNSObjectOverload1(id)
}

func NewNSPrintOperationOverload2(id *id) *NSPrintOperation {
	this := &NSPrintOperation{}
	this.impl = this
	this.initNSPrintOperationOverload2(id)
	return this
}

func (this *NSPrintOperation) initNSPrintOperationOverload2(id *id) {
	this.NSObject.initNSObjectOverload2(id)
}

func (this *NSPrintOperation) CleanUpOperation() {
	OSObjc_msgSend(this.Id, OSSel_cleanUpOperation)
}

func (this *NSPrintOperation) Context() *NSGraphicsContext {
	var result int64 = OSObjc_msgSend(this.Id, OSSel_context)
	var cond581 *NSGraphicsContext
	if result != 0 {
		cond581 = NewNSGraphicsContextOverload1(result)
	} else {
		cond581 = nil
	}
	return cond581
}

func (this *NSPrintOperation) CreateContext() *NSGraphicsContext {
	var result int64 = OSObjc_msgSend(this.Id, OSSel_createContext)
	var cond582 *NSGraphicsContext
	if result != 0 {
		cond582 = NewNSGraphicsContextOverload1(result)
	} else {
		cond582 = nil
	}
	return cond582
}

func (this *NSPrintOperation) DeliverResult() bool {
	return OSObjc_msgSend_bool(this.Id, OSSel_deliverResult)
}

func (this *NSPrintOperation) DestroyContext() {
	OSObjc_msgSend(this.Id, OSSel_destroyContext)
}

func (this *NSPrintOperation) RunOperation() bool {
	return OSObjc_msgSend_bool(this.Id, OSSel_runOperation)
}

func (this *NSPrintOperation) SetJobTitle(jobTitle *NSString) {
	var cond583 int64
	if jobTitle != (nil) {
		cond583 = jobTitle.Id
	} else {
		cond583 = int64(0)
	}
	OSObjc_msgSendOverload44(this.Id, OSSel_setJobTitle_, cond583)
}

func (this *NSPrintOperation) SetShowsPrintPanel(showsPrintPanel bool) {
	OSObjc_msgSendOverload27(this.Id, OSSel_setShowsPrintPanel_, showsPrintPanel)
}

func (this *NSPrintOperation) SetShowsProgressPanel(showsProgressPanel bool) {
	OSObjc_msgSendOverload27(this.Id, OSSel_setShowsProgressPanel_, showsProgressPanel)
}

func NSPrintOperationPrintOperationWithView(view *NSView, printInfo *NSPrintInfo) *NSPrintOperation {
	var cond584 int64
	if view != (nil) {
		cond584 = view.Id
	} else {
		cond584 = int64(0)
	}
	var cond585 int64
	if printInfo != (nil) {
		cond585 = printInfo.Id
	} else {
		cond585 = int64(0)
	}
	var result int64 = OSObjc_msgSendOverload54(OSClass_NSPrintOperation, OSSel_printOperationWithView_printInfo_, cond584, cond585)
	var cond586 *NSPrintOperation
	if result != 0 {
		cond586 = NewNSPrintOperationOverload1(result)
	} else {
		cond586 = nil
	}
	return cond586
}

func NSPrintOperationSetCurrentOperation(operation *NSPrintOperation) {
	var cond587 int64
	if operation != (nil) {
		cond587 = operation.Id
	} else {
		cond587 = int64(0)
	}
	OSObjc_msgSendOverload44(OSClass_NSPrintOperation, OSSel_setCurrentOperation_, cond587)
}
