// Code generated by j2go from bundles/org.eclipse.swt/Eclipse SWT PI/cocoa/org/eclipse/swt/internal/cocoa/NSURLRequest.java @ af630a9093. DO NOT EDIT.

package cocoa

type NSURLRequest struct {
	NSObject
}

func NewNSURLRequest() *NSURLRequest {
	this := &NSURLRequest{}
	this.impl = this
	this.initNSURLRequest()
	return this
}

func (this *NSURLRequest) initNSURLRequest() {
	this.NSObject.initNSObject()
}

func NewNSURLRequestOverload1(id int64) *NSURLRequest {
	this := &NSURLRequest{}
	this.impl = this
	this.initNSURLRequestOverload1(id)
	return this
}

func (this *NSURLRequest) initNSURLRequestOverload1(id int64) {
	this.NSObject.initNSObjectOverload1(id)
}

func NewNSURLRequestOverload2(id *id) *NSURLRequest {
	this := &NSURLRequest{}
	this.impl = this
	this.initNSURLRequestOverload2(id)
	return this
}

func (this *NSURLRequest) initNSURLRequestOverload2(id *id) {
	this.NSObject.initNSObjectOverload2(id)
}

func (this *NSURLRequest) URL() *NSURL {
	var result int64 = OSObjc_msgSend(this.Id, OSSel_URL)
	var cond837 *NSURL
	if result != 0 {
		cond837 = NewNSURLOverload1(result)
	} else {
		cond837 = nil
	}
	return cond837
}

func NSURLRequestRequestWithURL(URL *NSURL) *NSURLRequest {
	var cond838 int64
	if URL != (nil) {
		cond838 = URL.Id
	} else {
		cond838 = int64(0)
	}
	var result int64 = OSObjc_msgSendOverload44(OSClass_NSURLRequest, OSSel_requestWithURL_, cond838)
	var cond839 *NSURLRequest
	if result != 0 {
		cond839 = NewNSURLRequestOverload1(result)
	} else {
		cond839 = nil
	}
	return cond839
}
