// Code generated by j2go from tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_DateTime.java @ af630a9093. DO NOT EDIT.

package swttests

import (
	"github.com/haiodo/gowt/internal/jrt"
	"github.com/haiodo/gowt/internal/junit"
	"github.com/haiodo/gowt/swt"
)

type Test_org_eclipse_swt_widgets_DateTime struct {
	Test_org_eclipse_swt_widgets_Control
	datetime *swt.DateTime
	style    int32
}

const Test_org_eclipse_swt_widgets_DateTimeJAN int32 = 0
const Test_org_eclipse_swt_widgets_DateTimeFEB int32 = 1
const Test_org_eclipse_swt_widgets_DateTimeAUG int32 = 7
const Test_org_eclipse_swt_widgets_DateTimeNOV int32 = 10

func NewTest_org_eclipse_swt_widgets_DateTime(style int32) *Test_org_eclipse_swt_widgets_DateTime {
	this := &Test_org_eclipse_swt_widgets_DateTime{}
	this.impl = this
	this.initTest_org_eclipse_swt_widgets_DateTime(style)
	return this
}

func (this *Test_org_eclipse_swt_widgets_DateTime) initTest_org_eclipse_swt_widgets_DateTime(style int32) {
	this.Test_org_eclipse_swt_widgets_Control.initTest_org_eclipse_swt_widgets_Control()
	this.style = style
}

func (this *Test_org_eclipse_swt_widgets_DateTime) setUp_() {
	this.Test_org_eclipse_swt_widgets_Control.setUp_()
	this.datetime = swt.NewDateTime(upcastswtShellToswtComposite(this.shell), this.style)
	this.impl.setWidget_(upcastswtDateTimeToswtWidget(this.datetime))
}

func (this *Test_org_eclipse_swt_widgets_DateTime) test_ConstructorLorg_eclipse_swt_widgets_CompositeI_() {
	swt.NewDateTime(upcastswtShellToswtComposite(this.shell), swt.NULL)
	swt.NewDateTime(upcastswtShellToswtComposite(this.shell), swt.DATE)
	swt.NewDateTime(upcastswtShellToswtComposite(this.shell), swt.TIME)
	swt.NewDateTime(upcastswtShellToswtComposite(this.shell), swt.CALENDAR)
	swt.NewDateTime(upcastswtShellToswtComposite(this.shell), swt.DATE|swt.SWTLONG)
	swt.NewDateTime(upcastswtShellToswtComposite(this.shell), swt.TIME|swt.SWTLONG)
	swt.NewDateTime(upcastswtShellToswtComposite(this.shell), swt.CALENDAR|swt.SWTLONG)
	swt.NewDateTime(upcastswtShellToswtComposite(this.shell), swt.DATE|swt.MEDIUM)
	swt.NewDateTime(upcastswtShellToswtComposite(this.shell), swt.TIME|swt.MEDIUM)
	swt.NewDateTime(upcastswtShellToswtComposite(this.shell), swt.CALENDAR|swt.MEDIUM)
	swt.NewDateTime(upcastswtShellToswtComposite(this.shell), swt.DATE|swt.SHORT)
	swt.NewDateTime(upcastswtShellToswtComposite(this.shell), swt.TIME|swt.SHORT)
	swt.NewDateTime(upcastswtShellToswtComposite(this.shell), swt.CALENDAR|swt.SHORT)
	swt.NewDateTime(upcastswtShellToswtComposite(this.shell), swt.DROP_DOWN)
	junit.AssertThrows[*jrt.IllegalArgumentException](func() {
		swt.NewDateTime(nil, 0)
	})
}

func (this *Test_org_eclipse_swt_widgets_DateTime) Test_addSelectionListenerLorg_eclipse_swt_events_SelectionListener() {
	this.listenerCalled = false
	anon134 := &Test_org_eclipse_swt_widgets_DateTimeAnon1{}
	anon134.fnWidgetSelected = func(e *swt.SelectionEvent) {
		this.listenerCalled = true
	}
	anon134.fnWidgetDefaultSelected = func(e *swt.SelectionEvent) {
	}
	var listener swt.SelectionListener = anon134
	junit.AssertThrows[*jrt.IllegalArgumentException](func() {
		this.datetime.AddSelectionListener(nil)
	})
	this.datetime.AddSelectionListener(listener)
	this.datetime.NotifyListeners(swt.Selection, swt.NewEvent())
	junit.AssertTrue(this.listenerCalled)
	junit.AssertThrows[*jrt.IllegalArgumentException](func() {
		this.datetime.RemoveSelectionListener(nil)
	})
	this.listenerCalled = false
	this.datetime.RemoveSelectionListener(listener)
	this.datetime.NotifyListeners(swt.Selection, swt.NewEvent())
	junit.AssertFalse(this.listenerCalled)
}

func (this *Test_org_eclipse_swt_widgets_DateTime) Test_addSelectionListenerWidgetSelectedAdapterLorg_eclipse_swt_events_SelectionListener() {
	this.listenerCalled = false
	var listener swt.SelectionListener = swt.SelectionListenerWidgetSelectedAdapter(func(e *swt.SelectionEvent) {
		this.listenerCalled = true
	})
	this.datetime.AddSelectionListener(listener)
	this.datetime.NotifyListeners(swt.Selection, swt.NewEvent())
	junit.AssertTrue(this.listenerCalled)
	this.listenerCalled = false
	this.datetime.RemoveSelectionListener(listener)
	this.datetime.NotifyListeners(swt.Selection, swt.NewEvent())
	junit.AssertFalse(this.listenerCalled)
}

func (this *Test_org_eclipse_swt_widgets_DateTime) Test_setBackgroundCalendarDateTime() {
	var calendar *swt.DateTime = swt.NewDateTime(upcastswtShellToswtComposite(this.shell), swt.CALENDAR)
	var color *swt.Color = swt.NewColorRedGreenBlue(255, 0, 0)
	calendar.SetBackgroundWithColor(color)
	junit.AssertEquals(color, calendar.GetBackground())
	calendar.SetBackgroundWithColor(nil)
	junit.AssertNotEquals(color, calendar.GetBackground())
	color = swt.NewColorRedGreenBlueAlpha(255, 0, 0, 0)
	calendar.SetBackgroundWithColor(color)
	junit.AssertEquals(color, calendar.GetBackground())
	calendar.SetBackgroundWithColor(nil)
	junit.AssertNotEquals(color, calendar.GetBackground())
	if "gtk" == swt.GetPlatform() {
		var fg *swt.Color = swt.NewColorRedGreenBlue(0, 255, 0)
		calendar.SetBackgroundWithColor(color)
		calendar.SetForeground(fg)
		junit.AssertEquals(color, calendar.GetBackground())
		junit.AssertEquals(fg, calendar.GetForeground())
	}
	calendar.Dispose()
}

func (this *Test_org_eclipse_swt_widgets_DateTime) Test_setBackgroundAlphaCalendarDateTime() {
	var calendar *swt.DateTime = swt.NewDateTime(upcastswtShellToswtComposite(this.shell), swt.CALENDAR)
	var color *swt.Color = swt.NewColorRedGreenBlueAlpha(255, 0, 0, 0)
	calendar.SetBackgroundWithColor(color)
	junit.AssertEquals(color, calendar.GetBackground())
	var fg *swt.Color = swt.NewColorRedGreenBlueAlpha(0, 255, 0, 0)
	calendar.SetForeground(fg)
	junit.AssertEquals(color, calendar.GetBackground())
	calendar.Dispose()
}

func (this *Test_org_eclipse_swt_widgets_DateTime) Test_setBackgroundTimeDateTime() {
	var time *swt.DateTime = swt.NewDateTime(upcastswtShellToswtComposite(this.shell), swt.TIME)
	var color *swt.Color = swt.NewColorRedGreenBlue(255, 0, 0)
	time.SetBackgroundWithColor(color)
	junit.AssertEquals(color, time.GetBackground())
	time.SetBackgroundWithColor(nil)
	junit.AssertNotEquals(color, time.GetBackground())
	color = swt.NewColorRedGreenBlueAlpha(255, 0, 0, 0)
	time.SetBackgroundWithColor(color)
	junit.AssertEquals(color, time.GetBackground())
	time.SetBackgroundWithColor(nil)
	junit.AssertNotEquals(color, time.GetBackground())
	if "gtk" == swt.GetPlatform() {
		var fg *swt.Color = swt.NewColorRedGreenBlue(0, 255, 0)
		time.SetBackgroundWithColor(color)
		time.SetForeground(fg)
		junit.AssertEquals(color, time.GetBackground())
		junit.AssertEquals(fg, time.GetForeground())
	}
	time.Dispose()
}

func (this *Test_org_eclipse_swt_widgets_DateTime) Test_setBackgroundAlphaTimeDateTime() {
	var time *swt.DateTime = swt.NewDateTime(upcastswtShellToswtComposite(this.shell), swt.TIME)
	var color *swt.Color = swt.NewColorRedGreenBlueAlpha(255, 0, 0, 0)
	time.SetBackgroundWithColor(color)
	junit.AssertEquals(color, time.GetBackground())
	var fg *swt.Color = swt.NewColorRedGreenBlueAlpha(0, 255, 0, 0)
	time.SetForeground(fg)
	junit.AssertEquals(color, time.GetBackground())
	time.Dispose()
}

func (this *Test_org_eclipse_swt_widgets_DateTime) Test_setBackgroundDateDateTime() {
	var date *swt.DateTime = swt.NewDateTime(upcastswtShellToswtComposite(this.shell), swt.DATE)
	var color *swt.Color = swt.NewColorRedGreenBlue(255, 0, 0)
	date.SetBackgroundWithColor(color)
	junit.AssertEquals(color, date.GetBackground())
	date.SetBackgroundWithColor(nil)
	junit.AssertNotEquals(color, date.GetBackground())
	color = swt.NewColorRedGreenBlueAlpha(255, 0, 0, 0)
	date.SetBackgroundWithColor(color)
	junit.AssertEquals(color, date.GetBackground())
	date.SetBackgroundWithColor(nil)
	junit.AssertNotEquals(color, date.GetBackground())
	if "gtk" == swt.GetPlatform() {
		var fg *swt.Color = swt.NewColorRedGreenBlue(0, 255, 0)
		date.SetBackgroundWithColor(color)
		date.SetForeground(fg)
		junit.AssertEquals(color, date.GetBackground())
		junit.AssertEquals(fg, date.GetForeground())
	}
	date.Dispose()
}

func (this *Test_org_eclipse_swt_widgets_DateTime) Test_setBackgroundAlphaDateDateTime() {
	var date *swt.DateTime = swt.NewDateTime(upcastswtShellToswtComposite(this.shell), swt.DATE)
	var color *swt.Color = swt.NewColorRedGreenBlueAlpha(255, 0, 0, 0)
	date.SetBackgroundWithColor(color)
	junit.AssertEquals(color, date.GetBackground())
	var fg *swt.Color = swt.NewColorRedGreenBlueAlpha(0, 255, 0, 0)
	date.SetForeground(fg)
	junit.AssertEquals(color, date.GetBackground())
	date.Dispose()
}

func (this *Test_org_eclipse_swt_widgets_DateTime) Test_setDateIII() {
	this.datetime.SetDate(2008, Test_org_eclipse_swt_widgets_DateTimeAUG, 31)
	junit.AssertEquals(int32(31), int32(this.datetime.GetDay()))
	junit.AssertEquals(int32(Test_org_eclipse_swt_widgets_DateTimeAUG), int32(this.datetime.GetMonth()))
	junit.AssertEquals(int32(2008), int32(this.datetime.GetYear()))
	this.datetime.SetDate(2008, Test_org_eclipse_swt_widgets_DateTimeNOV, 30)
	junit.AssertEquals(int32(30), int32(this.datetime.GetDay()))
	junit.AssertEquals(int32(Test_org_eclipse_swt_widgets_DateTimeNOV), int32(this.datetime.GetMonth()))
	junit.AssertEquals(int32(2008), int32(this.datetime.GetYear()))
	this.datetime.SetDate(2008, Test_org_eclipse_swt_widgets_DateTimeFEB, 29)
	junit.AssertEquals(int32(29), int32(this.datetime.GetDay()))
	junit.AssertEquals(int32(Test_org_eclipse_swt_widgets_DateTimeFEB), int32(this.datetime.GetMonth()))
	junit.AssertEquals(int32(2008), int32(this.datetime.GetYear()))
	this.datetime.SetDate(2007, Test_org_eclipse_swt_widgets_DateTimeFEB, 28)
	junit.AssertEquals(int32(28), int32(this.datetime.GetDay()))
	junit.AssertEquals(int32(Test_org_eclipse_swt_widgets_DateTimeFEB), int32(this.datetime.GetMonth()))
	junit.AssertEquals(int32(2007), int32(this.datetime.GetYear()))
	this.datetime.SetDate(2008, Test_org_eclipse_swt_widgets_DateTimeJAN, 1)
	junit.AssertEquals(int32(1), int32(this.datetime.GetDay()))
	junit.AssertEquals(int32(Test_org_eclipse_swt_widgets_DateTimeJAN), int32(this.datetime.GetMonth()))
	junit.AssertEquals(int32(2008), int32(this.datetime.GetYear()))
	this.datetime.SetDate(1752, Test_org_eclipse_swt_widgets_DateTimeNOV, 30)
	junit.AssertEquals(int32(30), int32(this.datetime.GetDay()))
	junit.AssertEquals(int32(Test_org_eclipse_swt_widgets_DateTimeNOV), int32(this.datetime.GetMonth()))
	junit.AssertEquals(int32(1752), int32(this.datetime.GetYear()))
	this.datetime.SetDate(2008, Test_org_eclipse_swt_widgets_DateTimeJAN, 1)
	this.datetime.SetDate(9999, Test_org_eclipse_swt_widgets_DateTimeJAN, 1)
	junit.AssertEquals(int32(1), int32(this.datetime.GetDay()))
	junit.AssertEquals(int32(Test_org_eclipse_swt_widgets_DateTimeJAN), int32(this.datetime.GetMonth()))
	junit.AssertEquals(int32(9999), int32(this.datetime.GetYear()))
	this.datetime.SetDate(2008, 0, 1)
	junit.AssertEquals(int32(1), int32(this.datetime.GetDay()))
	junit.AssertEquals(int32(0), int32(this.datetime.GetMonth()))
	junit.AssertEquals(int32(2008), int32(this.datetime.GetYear()))
	this.datetime.SetDate(2008, 11, 1)
	junit.AssertEquals(int32(1), int32(this.datetime.GetDay()))
	junit.AssertEquals(int32(11), int32(this.datetime.GetMonth()))
	junit.AssertEquals(int32(2008), int32(this.datetime.GetYear()))
	this.datetime.SetDate(2008, Test_org_eclipse_swt_widgets_DateTimeJAN, 1)
	junit.AssertEquals(int32(1), int32(this.datetime.GetDay()))
	junit.AssertEquals(int32(Test_org_eclipse_swt_widgets_DateTimeJAN), int32(this.datetime.GetMonth()))
	junit.AssertEquals(int32(2008), int32(this.datetime.GetYear()))
	this.datetime.SetDate(1999, Test_org_eclipse_swt_widgets_DateTimeFEB, 29)
	junit.AssertEquals(int32(1), int32(this.datetime.GetDay()))
	junit.AssertEquals(int32(Test_org_eclipse_swt_widgets_DateTimeJAN), int32(this.datetime.GetMonth()))
	junit.AssertEquals(int32(2008), int32(this.datetime.GetYear()))
	this.datetime.SetDate(1999, Test_org_eclipse_swt_widgets_DateTimeNOV, 31)
	junit.AssertEquals(int32(1), int32(this.datetime.GetDay()))
	junit.AssertEquals(int32(Test_org_eclipse_swt_widgets_DateTimeJAN), int32(this.datetime.GetMonth()))
	junit.AssertEquals(int32(2008), int32(this.datetime.GetYear()))
	this.datetime.SetDate(1751, Test_org_eclipse_swt_widgets_DateTimeJAN, 1)
	junit.AssertEquals(int32(1), int32(this.datetime.GetDay()))
	junit.AssertEquals(int32(Test_org_eclipse_swt_widgets_DateTimeJAN), int32(this.datetime.GetMonth()))
	junit.AssertEquals(int32(2008), int32(this.datetime.GetYear()))
	this.datetime.SetDate(10000, Test_org_eclipse_swt_widgets_DateTimeJAN, 1)
	junit.AssertEquals(int32(1), int32(this.datetime.GetDay()))
	junit.AssertEquals(int32(Test_org_eclipse_swt_widgets_DateTimeJAN), int32(this.datetime.GetMonth()))
	junit.AssertEquals(int32(2008), int32(this.datetime.GetYear()))
	this.datetime.SetDate(2008, -1, 1)
	junit.AssertEquals(int32(1), int32(this.datetime.GetDay()))
	junit.AssertEquals(int32(Test_org_eclipse_swt_widgets_DateTimeJAN), int32(this.datetime.GetMonth()))
	junit.AssertEquals(int32(2008), int32(this.datetime.GetYear()))
	this.datetime.SetDate(2008, 12, 1)
	junit.AssertEquals(int32(1), int32(this.datetime.GetDay()))
	junit.AssertEquals(int32(Test_org_eclipse_swt_widgets_DateTimeJAN), int32(this.datetime.GetMonth()))
	junit.AssertEquals(int32(2008), int32(this.datetime.GetYear()))
	this.datetime.SetDate(2008, Test_org_eclipse_swt_widgets_DateTimeJAN, 0)
	junit.AssertEquals(int32(1), int32(this.datetime.GetDay()))
	junit.AssertEquals(int32(Test_org_eclipse_swt_widgets_DateTimeJAN), int32(this.datetime.GetMonth()))
	junit.AssertEquals(int32(2008), int32(this.datetime.GetYear()))
	this.datetime.SetDate(2008, Test_org_eclipse_swt_widgets_DateTimeJAN, 99)
	junit.AssertEquals(int32(1), int32(this.datetime.GetDay()))
	junit.AssertEquals(int32(Test_org_eclipse_swt_widgets_DateTimeJAN), int32(this.datetime.GetMonth()))
	junit.AssertEquals(int32(2008), int32(this.datetime.GetYear()))
}

func (this *Test_org_eclipse_swt_widgets_DateTime) Test_setDayI() {
	this.datetime.SetDate(2008, Test_org_eclipse_swt_widgets_DateTimeAUG, 1)
	for day := int32(1); day <= 31; day++ {
		this.datetime.SetDay(day)
		junit.AssertEquals(int32(day), int32(this.datetime.GetDay()))
	}
	var day int32 = this.datetime.GetDay()
	this.datetime.SetDay(32)
	junit.AssertEquals(int32(day), int32(this.datetime.GetDay()))
	this.datetime.SetDay(-5)
	junit.AssertEquals(int32(day), int32(this.datetime.GetDay()))
	this.datetime.SetDate(2008, Test_org_eclipse_swt_widgets_DateTimeFEB, 1)
	this.datetime.SetDay(30)
	junit.AssertEquals(int32(1), int32(this.datetime.GetDay()))
	this.datetime.SetDate(2007, Test_org_eclipse_swt_widgets_DateTimeFEB, 5)
	this.datetime.SetDay(29)
	junit.AssertEquals(int32(5), int32(this.datetime.GetDay()))
}

func (this *Test_org_eclipse_swt_widgets_DateTime) Test_setForegroundCalendarDateTime() {
	var calendar *swt.DateTime = swt.NewDateTime(upcastswtShellToswtComposite(this.shell), swt.CALENDAR)
	var color *swt.Color = swt.NewColorRedGreenBlue(255, 0, 0)
	calendar.SetForeground(color)
	junit.AssertEquals(color, calendar.GetForeground())
	calendar.SetForeground(nil)
	junit.AssertNotEquals(color, calendar.GetForeground())
	if "gtk" == swt.GetPlatform() {
		var bg *swt.Color = swt.NewColorRedGreenBlue(0, 255, 0)
		calendar.SetForeground(color)
		calendar.SetBackgroundWithColor(bg)
		junit.AssertEquals(color, calendar.GetForeground())
		junit.AssertEquals(bg, calendar.GetBackground())
	}
	calendar.Dispose()
}

func (this *Test_org_eclipse_swt_widgets_DateTime) Test_setForegroundAlphaCalendarDateTime() {
	var calendar *swt.DateTime = swt.NewDateTime(upcastswtShellToswtComposite(this.shell), swt.CALENDAR)
	junit.AssumeTrue(SwtTestUtilIsCocoa || SwtTestUtilIsGTK, "Alpha support for foreground colors does not exist on Win32")
	var color *swt.Color = swt.NewColorRedGreenBlueAlpha(255, 0, 0, 0)
	calendar.SetForeground(color)
	junit.AssertEquals(color, calendar.GetForeground())
	var bg *swt.Color = swt.NewColorRedGreenBlueAlpha(0, 255, 0, 0)
	calendar.SetBackgroundWithColor(bg)
	junit.AssertEquals(color, calendar.GetForeground())
	calendar.Dispose()
}

func (this *Test_org_eclipse_swt_widgets_DateTime) Test_setForegroundTimeDateTime() {
	var time *swt.DateTime = swt.NewDateTime(upcastswtShellToswtComposite(this.shell), swt.TIME)
	var color *swt.Color = swt.NewColorRedGreenBlue(255, 0, 0)
	time.SetForeground(color)
	junit.AssertEquals(color, time.GetForeground())
	time.SetForeground(nil)
	junit.AssertNotEquals(color, time.GetForeground())
	if "gtk" == swt.GetPlatform() {
		var bg *swt.Color = swt.NewColorRedGreenBlue(0, 255, 0)
		time.SetForeground(color)
		time.SetBackgroundWithColor(bg)
		junit.AssertEquals(color, time.GetForeground())
		junit.AssertEquals(bg, time.GetBackground())
	}
	time.Dispose()
}

func (this *Test_org_eclipse_swt_widgets_DateTime) Test_setForegroundAlphaTimeDateTime() {
	var time *swt.DateTime = swt.NewDateTime(upcastswtShellToswtComposite(this.shell), swt.TIME)
	junit.AssumeTrue(SwtTestUtilIsCocoa || SwtTestUtilIsGTK, "Alpha support for foreground colors does not exist on Win32")
	var color *swt.Color = swt.NewColorRedGreenBlueAlpha(255, 0, 0, 0)
	time.SetForeground(color)
	junit.AssertEquals(color, time.GetForeground())
	var bg *swt.Color = swt.NewColorRedGreenBlueAlpha(0, 255, 0, 0)
	time.SetBackgroundWithColor(bg)
	junit.AssertEquals(color, time.GetForeground())
	time.Dispose()
}

func (this *Test_org_eclipse_swt_widgets_DateTime) Test_setForegroundDateDateTime() {
	var date *swt.DateTime = swt.NewDateTime(upcastswtShellToswtComposite(this.shell), swt.DATE)
	var color *swt.Color = swt.NewColorRedGreenBlue(255, 0, 0)
	date.SetForeground(color)
	junit.AssertEquals(color, date.GetForeground())
	date.SetForeground(nil)
	junit.AssertNotEquals(color, date.GetForeground())
	if "gtk" == swt.GetPlatform() {
		var bg *swt.Color = swt.NewColorRedGreenBlue(0, 255, 0)
		date.SetForeground(color)
		date.SetBackgroundWithColor(bg)
		junit.AssertEquals(color, date.GetForeground())
		junit.AssertEquals(bg, date.GetBackground())
	}
	date.Dispose()
}

func (this *Test_org_eclipse_swt_widgets_DateTime) Test_setForegroundAlphaDateDateTime() {
	var date *swt.DateTime = swt.NewDateTime(upcastswtShellToswtComposite(this.shell), swt.DATE)
	junit.AssumeTrue(SwtTestUtilIsCocoa || SwtTestUtilIsGTK, "Alpha support for foreground colors does not exist on Win32")
	var color *swt.Color = swt.NewColorRedGreenBlueAlpha(255, 0, 0, 0)
	date.SetForeground(color)
	junit.AssertEquals(color, date.GetForeground())
	var bg *swt.Color = swt.NewColorRedGreenBlueAlpha(0, 255, 0, 0)
	date.SetBackgroundWithColor(bg)
	junit.AssertEquals(color, date.GetForeground())
	date.Dispose()
}

func (this *Test_org_eclipse_swt_widgets_DateTime) Test_setHoursI() {
	this.datetime.SetTime(2, 10, 30)
	this.datetime.SetHours(21)
	junit.AssertEquals(int32(21), int32(this.datetime.GetHours()))
	junit.AssertEquals(int32(10), int32(this.datetime.GetMinutes()))
	junit.AssertEquals(int32(30), int32(this.datetime.GetSeconds()))
	this.datetime.SetHours(24)
	junit.AssertEquals(int32(21), int32(this.datetime.GetHours()))
	junit.AssertEquals(int32(10), int32(this.datetime.GetMinutes()))
	junit.AssertEquals(int32(30), int32(this.datetime.GetSeconds()))
	this.datetime.SetHours(-1)
	junit.AssertEquals(int32(21), int32(this.datetime.GetHours()))
	junit.AssertEquals(int32(10), int32(this.datetime.GetMinutes()))
	junit.AssertEquals(int32(30), int32(this.datetime.GetSeconds()))
}

func (this *Test_org_eclipse_swt_widgets_DateTime) Test_setMinutesI() {
	this.datetime.SetTime(2, 10, 30)
	this.datetime.SetMinutes(22)
	junit.AssertEquals(int32(2), int32(this.datetime.GetHours()))
	junit.AssertEquals(int32(22), int32(this.datetime.GetMinutes()))
	junit.AssertEquals(int32(30), int32(this.datetime.GetSeconds()))
	this.datetime.SetMinutes(0)
	junit.AssertEquals(int32(2), int32(this.datetime.GetHours()))
	junit.AssertEquals(int32(0), int32(this.datetime.GetMinutes()))
	junit.AssertEquals(int32(30), int32(this.datetime.GetSeconds()))
	this.datetime.SetMinutes(59)
	junit.AssertEquals(int32(2), int32(this.datetime.GetHours()))
	junit.AssertEquals(int32(59), int32(this.datetime.GetMinutes()))
	junit.AssertEquals(int32(30), int32(this.datetime.GetSeconds()))
	this.datetime.SetMinutes(-1)
	junit.AssertEquals(int32(2), int32(this.datetime.GetHours()))
	junit.AssertEquals(int32(59), int32(this.datetime.GetMinutes()))
	junit.AssertEquals(int32(30), int32(this.datetime.GetSeconds()))
	this.datetime.SetMinutes(60)
	junit.AssertEquals(int32(2), int32(this.datetime.GetHours()))
	junit.AssertEquals(int32(59), int32(this.datetime.GetMinutes()))
	junit.AssertEquals(int32(30), int32(this.datetime.GetSeconds()))
}

func (this *Test_org_eclipse_swt_widgets_DateTime) Test_setMonthI() {
	this.datetime.SetDate(2008, Test_org_eclipse_swt_widgets_DateTimeNOV, 1)
	this.datetime.SetMonth(Test_org_eclipse_swt_widgets_DateTimeAUG)
	junit.AssertEquals(int32(Test_org_eclipse_swt_widgets_DateTimeAUG), int32(this.datetime.GetMonth()))
	this.datetime.SetMonth(Test_org_eclipse_swt_widgets_DateTimeJAN)
	junit.AssertEquals(int32(Test_org_eclipse_swt_widgets_DateTimeJAN), int32(this.datetime.GetMonth()))
	this.datetime.SetMonth(Test_org_eclipse_swt_widgets_DateTimeFEB)
	junit.AssertEquals(int32(Test_org_eclipse_swt_widgets_DateTimeFEB), int32(this.datetime.GetMonth()))
	this.datetime.SetMonth(Test_org_eclipse_swt_widgets_DateTimeNOV)
	junit.AssertEquals(int32(Test_org_eclipse_swt_widgets_DateTimeNOV), int32(this.datetime.GetMonth()))
	this.datetime.SetDate(2008, Test_org_eclipse_swt_widgets_DateTimeNOV, 30)
	this.datetime.SetMonth(Test_org_eclipse_swt_widgets_DateTimeFEB)
	junit.AssertEquals(int32(Test_org_eclipse_swt_widgets_DateTimeNOV), int32(this.datetime.GetMonth()))
	this.datetime.SetDate(2008, Test_org_eclipse_swt_widgets_DateTimeAUG, 31)
	this.datetime.SetMonth(Test_org_eclipse_swt_widgets_DateTimeNOV)
	junit.AssertEquals(int32(Test_org_eclipse_swt_widgets_DateTimeAUG), int32(this.datetime.GetMonth()))
	this.datetime.SetDate(2007, Test_org_eclipse_swt_widgets_DateTimeNOV, 29)
	this.datetime.SetMonth(Test_org_eclipse_swt_widgets_DateTimeFEB)
	junit.AssertEquals(int32(Test_org_eclipse_swt_widgets_DateTimeNOV), int32(this.datetime.GetMonth()))
}

func (this *Test_org_eclipse_swt_widgets_DateTime) Test_setSecondsI() {
	this.datetime.SetTime(2, 10, 30)
	this.datetime.SetSeconds(52)
	junit.AssertEquals(int32(2), int32(this.datetime.GetHours()))
	junit.AssertEquals(int32(10), int32(this.datetime.GetMinutes()))
	junit.AssertEquals(int32(52), int32(this.datetime.GetSeconds()))
	this.datetime.SetSeconds(0)
	junit.AssertEquals(int32(2), int32(this.datetime.GetHours()))
	junit.AssertEquals(int32(10), int32(this.datetime.GetMinutes()))
	junit.AssertEquals(int32(0), int32(this.datetime.GetSeconds()))
	this.datetime.SetSeconds(59)
	junit.AssertEquals(int32(2), int32(this.datetime.GetHours()))
	junit.AssertEquals(int32(10), int32(this.datetime.GetMinutes()))
	junit.AssertEquals(int32(59), int32(this.datetime.GetSeconds()))
	this.datetime.SetSeconds(-1)
	junit.AssertEquals(int32(2), int32(this.datetime.GetHours()))
	junit.AssertEquals(int32(10), int32(this.datetime.GetMinutes()))
	junit.AssertEquals(int32(59), int32(this.datetime.GetSeconds()))
	this.datetime.SetSeconds(60)
	junit.AssertEquals(int32(2), int32(this.datetime.GetHours()))
	junit.AssertEquals(int32(10), int32(this.datetime.GetMinutes()))
	junit.AssertEquals(int32(59), int32(this.datetime.GetSeconds()))
}

func (this *Test_org_eclipse_swt_widgets_DateTime) Test_setTimeIII() {
	this.datetime.SetTime(2, 10, 30)
	junit.AssertEquals(int32(2), int32(this.datetime.GetHours()))
	junit.AssertEquals(int32(10), int32(this.datetime.GetMinutes()))
	junit.AssertEquals(int32(30), int32(this.datetime.GetSeconds()))
	this.datetime.SetTime(0, 10, 30)
	junit.AssertEquals(int32(0), int32(this.datetime.GetHours()))
	junit.AssertEquals(int32(10), int32(this.datetime.GetMinutes()))
	junit.AssertEquals(int32(30), int32(this.datetime.GetSeconds()))
	this.datetime.SetTime(23, 10, 30)
	junit.AssertEquals(int32(23), int32(this.datetime.GetHours()))
	junit.AssertEquals(int32(10), int32(this.datetime.GetMinutes()))
	junit.AssertEquals(int32(30), int32(this.datetime.GetSeconds()))
	this.datetime.SetTime(2, 0, 30)
	junit.AssertEquals(int32(2), int32(this.datetime.GetHours()))
	junit.AssertEquals(int32(0), int32(this.datetime.GetMinutes()))
	junit.AssertEquals(int32(30), int32(this.datetime.GetSeconds()))
	this.datetime.SetTime(2, 59, 30)
	junit.AssertEquals(int32(2), int32(this.datetime.GetHours()))
	junit.AssertEquals(int32(59), int32(this.datetime.GetMinutes()))
	junit.AssertEquals(int32(30), int32(this.datetime.GetSeconds()))
	this.datetime.SetTime(2, 10, 0)
	junit.AssertEquals(int32(2), int32(this.datetime.GetHours()))
	junit.AssertEquals(int32(10), int32(this.datetime.GetMinutes()))
	junit.AssertEquals(int32(0), int32(this.datetime.GetSeconds()))
	this.datetime.SetTime(2, 10, 59)
	junit.AssertEquals(int32(2), int32(this.datetime.GetHours()))
	junit.AssertEquals(int32(10), int32(this.datetime.GetMinutes()))
	junit.AssertEquals(int32(59), int32(this.datetime.GetSeconds()))
	this.datetime.SetTime(29, 10, 30)
	junit.AssertEquals(int32(2), int32(this.datetime.GetHours()))
	junit.AssertEquals(int32(10), int32(this.datetime.GetMinutes()))
	junit.AssertEquals(int32(59), int32(this.datetime.GetSeconds()))
	this.datetime.SetTime(2, 73, 30)
	junit.AssertEquals(int32(2), int32(this.datetime.GetHours()))
	junit.AssertEquals(int32(10), int32(this.datetime.GetMinutes()))
	junit.AssertEquals(int32(59), int32(this.datetime.GetSeconds()))
	this.datetime.SetTime(2, 10, 95)
	junit.AssertEquals(int32(2), int32(this.datetime.GetHours()))
	junit.AssertEquals(int32(10), int32(this.datetime.GetMinutes()))
	junit.AssertEquals(int32(59), int32(this.datetime.GetSeconds()))
}

func (this *Test_org_eclipse_swt_widgets_DateTime) Test_setYearI() {
	this.datetime.SetDate(2008, Test_org_eclipse_swt_widgets_DateTimeNOV, 1)
	this.datetime.SetYear(1947)
	junit.AssertEquals(int32(1947), int32(this.datetime.GetYear()))
	this.datetime.SetYear(1752)
	junit.AssertEquals(int32(1752), int32(this.datetime.GetYear()))
	this.datetime.SetYear(9999)
	junit.AssertEquals(int32(9999), int32(this.datetime.GetYear()))
	this.datetime.SetYear(2005)
	junit.AssertEquals(int32(2005), int32(this.datetime.GetYear()))
	this.datetime.SetYear(0)
	junit.AssertEquals(int32(2005), int32(this.datetime.GetYear()))
	this.datetime.SetYear(-1947)
	junit.AssertEquals(int32(2005), int32(this.datetime.GetYear()))
	this.datetime.SetDate(2008, Test_org_eclipse_swt_widgets_DateTimeFEB, 29)
	this.datetime.SetYear(2007)
	junit.AssertEquals(int32(2008), int32(this.datetime.GetYear()))
}

func (this *Test_org_eclipse_swt_widgets_DateTime) Test_removeSelectionListenerLorg_eclipse_swt_events_SelectionListener() {
}

func (this *Test_org_eclipse_swt_widgets_DateTime) SetUpStyle(style int32) {
	this.Test_org_eclipse_swt_widgets_Control.setUp_()
	this.datetime = swt.NewDateTime(upcastswtShellToswtComposite(this.shell), style)
	this.impl.setWidget_(upcastswtDateTimeToswtWidget(this.datetime))
}

func (this *Test_org_eclipse_swt_widgets_DateTime) Test_consistency_MenuDetect() {
	this.ConsistencyEventParamAParamBParamCParamDMethod(10, 10, 3, 0, ConsistencyUtilityMOUSE_CLICK)
	this.impl.tearDown_()
	this.SetUpStyle(swt.DATE)
	this.ConsistencyEventParamAParamBParamCParamDMethod(5, 5, 3, 0, ConsistencyUtilityMOUSE_CLICK)
	this.impl.tearDown_()
	this.SetUpStyle(swt.TIME)
	this.ConsistencyEventParamAParamBParamCParamDMethod(5, 5, 3, 0, ConsistencyUtilityMOUSE_CLICK)
	this.impl.tearDown_()
	this.SetUpStyle(swt.CALENDAR)
	this.ConsistencyEventParamAParamBParamCParamDMethod(5, 5, 3, 0, ConsistencyUtilityMOUSE_CLICK)
}

func (this *Test_org_eclipse_swt_widgets_DateTime) Test_consistency_MouseSelection() {
	this.ConsistencyEventParamAParamBParamCParamDMethod(10, 10, 1, 0, ConsistencyUtilityMOUSE_CLICK)
	this.impl.tearDown_()
	this.SetUpStyle(swt.DATE)
	this.ConsistencyEventParamAParamBParamCParamDMethod(5, 5, 1, 0, ConsistencyUtilityMOUSE_CLICK)
	this.impl.tearDown_()
	this.SetUpStyle(swt.TIME)
	this.ConsistencyEventParamAParamBParamCParamDMethod(5, 5, 1, 0, ConsistencyUtilityMOUSE_CLICK)
	this.impl.tearDown_()
	this.SetUpStyle(swt.CALENDAR)
	this.ConsistencyEventParamAParamBParamCParamDMethod(5, 5, 1, 0, ConsistencyUtilityMOUSE_CLICK)
}

func (this *Test_org_eclipse_swt_widgets_DateTime) Test_consistency_EnterSelection() {
	this.impl.tearDown_()
	this.SetUpStyle(swt.DATE)
	this.ConsistencyEventParamAParamBParamCParamDMethod(10, 13, 0, 0, ConsistencyUtilityKEY_PRESS)
	this.impl.tearDown_()
	this.SetUpStyle(swt.TIME)
	this.ConsistencyEventParamAParamBParamCParamDMethod(10, 13, 0, 0, ConsistencyUtilityKEY_PRESS)
	this.impl.tearDown_()
	this.SetUpStyle(swt.CALENDAR)
	this.ConsistencyEventParamAParamBParamCParamDMethod(10, 13, 0, 0, ConsistencyUtilityKEY_PRESS)
}

func (this *Test_org_eclipse_swt_widgets_DateTime) Test_consistency_DragDetect() {
	this.ConsistencyEventParamAParamBParamCParamDMethod(10, 10, 20, 20, ConsistencyUtilityMOUSE_DRAG)
	this.impl.tearDown_()
	this.SetUpStyle(swt.DATE)
	this.ConsistencyEventParamAParamBParamCParamDMethod(5, 5, 15, 15, ConsistencyUtilityMOUSE_DRAG)
	this.impl.tearDown_()
	this.SetUpStyle(swt.TIME)
	this.ConsistencyEventParamAParamBParamCParamDMethod(5, 5, 15, 15, ConsistencyUtilityMOUSE_DRAG)
	this.impl.tearDown_()
	this.SetUpStyle(swt.CALENDAR)
	this.ConsistencyEventParamAParamBParamCParamDMethod(5, 5, 15, 15, ConsistencyUtilityMOUSE_DRAG)
}

func upcastswtDateTimeToswtWidget(x *swt.DateTime) *swt.Widget {
	if x == nil {
		return nil
	}
	return &x.Widget
}

// j2go: anonymous SelectionListener subclass.
type Test_org_eclipse_swt_widgets_DateTimeAnon1 struct {
	fnWidgetSelected        func(a0 *swt.SelectionEvent)
	fnWidgetDefaultSelected func(a0 *swt.SelectionEvent)
}

func (this *Test_org_eclipse_swt_widgets_DateTimeAnon1) WidgetSelected(a0 *swt.SelectionEvent) {
	this.fnWidgetSelected(a0)
}

func (this *Test_org_eclipse_swt_widgets_DateTimeAnon1) WidgetDefaultSelected(a0 *swt.SelectionEvent) {
	this.fnWidgetDefaultSelected(a0)
}
