// Code generated by j2go from tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Scrollable.java @ af630a9093. DO NOT EDIT.

package swttests

import (
	"github.com/haiodo/gowt/swt"
)

type Test_org_eclipse_swt_widgets_Scrollable struct {
	Test_org_eclipse_swt_widgets_Control
	scrollable *swt.Scrollable
}

func NewTest_org_eclipse_swt_widgets_Scrollable() *Test_org_eclipse_swt_widgets_Scrollable {
	this := &Test_org_eclipse_swt_widgets_Scrollable{}
	this.impl = this
	this.initTest_org_eclipse_swt_widgets_Scrollable()
	return this
}

func (this *Test_org_eclipse_swt_widgets_Scrollable) initTest_org_eclipse_swt_widgets_Scrollable() {
	this.Test_org_eclipse_swt_widgets_Control.initTest_org_eclipse_swt_widgets_Control()
}

func (this *Test_org_eclipse_swt_widgets_Scrollable) test_ConstructorLorg_eclipse_swt_widgets_CompositeI_() {
}

func (this *Test_org_eclipse_swt_widgets_Scrollable) Test_computeTrimIIII() {
	this.impl.test_computeTrimIIII_()
}

func (this *Test_org_eclipse_swt_widgets_Scrollable) test_computeTrimIIII_() {
	this.scrollable.ComputeTrim(0, 0, 0, 0)
}

func (this *Test_org_eclipse_swt_widgets_Scrollable) Test_getClientArea() {
	this.impl.test_getClientArea_()
}

func (this *Test_org_eclipse_swt_widgets_Scrollable) test_getClientArea_() {
	this.scrollable.GetClientArea()
}

func (this *Test_org_eclipse_swt_widgets_Scrollable) Test_getHorizontalBar() {
	this.scrollable.GetHorizontalBar()
}

func (this *Test_org_eclipse_swt_widgets_Scrollable) Test_getVerticalBar() {
	this.scrollable.GetVerticalBar()
}

func (this *Test_org_eclipse_swt_widgets_Scrollable) setWidget_(w *swt.Widget) {
	this.scrollable = castswtWidgetToswtScrollable(w)
	this.Test_org_eclipse_swt_widgets_Control.setWidget_(w)
}

// j2go: instanceof helper for swt.Scrollable and its subclasses within the translated set.
func widgetImplAsScrollable(x any) (*swt.Scrollable, bool) {
	switch v := x.(type) {
	case *swt.Scrollable:
		return v, true
	case *swt.Composite:
		return &v.Scrollable, true
	case *swt.Canvas:
		return &v.Scrollable, true
	case *swt.Decorations:
		return &v.Scrollable, true
	case *swt.Shell:
		return &v.Scrollable, true
	case *swt.Group:
		return &v.Scrollable, true
	case *swt.SashForm:
		return &v.Scrollable, true
	case *swt.Tree:
		return &v.Scrollable, true
	case *swt.TabFolder:
		return &v.Scrollable, true
	case *swt.Combo:
		return &v.Scrollable, true
	case *swt.Table:
		return &v.Scrollable, true
	case *swt.ScrolledComposite:
		return &v.Scrollable, true
	case *swt.Text:
		return &v.Scrollable, true
	}
	return nil, false
}

func castswtWidgetToswtScrollable(x *swt.Widget) *swt.Scrollable {
	if x == nil {
		return nil
	}
	v, ok := widgetImplAsScrollable(x.Impl())
	if !ok {
		panic("java.lang.ClassCastException: swt.Scrollable")
	}
	return v
}
