// Code generated by j2go from tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_accessibility_AccessibleControlEvent.java @ af630a9093. DO NOT EDIT.

package swttests

import (
	"github.com/haiodo/gowt/internal/junit"
	"github.com/haiodo/gowt/swt"
)

type Test_org_eclipse_swt_accessibility_AccessibleControlEvent struct {
	Shell *swt.Shell
}

func NewTest_org_eclipse_swt_accessibility_AccessibleControlEvent() *Test_org_eclipse_swt_accessibility_AccessibleControlEvent {
	this := &Test_org_eclipse_swt_accessibility_AccessibleControlEvent{}
	this.initTest_org_eclipse_swt_accessibility_AccessibleControlEvent()
	return this
}

func (this *Test_org_eclipse_swt_accessibility_AccessibleControlEvent) initTest_org_eclipse_swt_accessibility_AccessibleControlEvent() {
}

func (this *Test_org_eclipse_swt_accessibility_AccessibleControlEvent) SetUp() {
	this.Shell = swt.NewShell()
}

func (this *Test_org_eclipse_swt_accessibility_AccessibleControlEvent) TearDown() {
	this.Shell.Dispose()
}

func (this *Test_org_eclipse_swt_accessibility_AccessibleControlEvent) Test_ConstructorLjava_lang_Object() {
	var event *swt.AccessibleControlEvent = swt.NewAccessibleControlEvent(this.Shell.GetAccessible())
	junit.AssertNotNull(event)
	event = swt.NewAccessibleControlEvent(5)
	junit.AssertNotNull(event)
}

func (this *Test_org_eclipse_swt_accessibility_AccessibleControlEvent) Test_toString() {
	var event *swt.AccessibleControlEvent = swt.NewAccessibleControlEvent(this.Shell.GetAccessible())
	junit.AssertNotNull(event.String())
	junit.AssertFalse((len(event.String()) == 0))
}

func init() {
	junit.Register(&junit.Class{
		Name: "Test_org_eclipse_swt_accessibility_AccessibleControlEvent",
		New:  func() any { return NewTest_org_eclipse_swt_accessibility_AccessibleControlEvent() },
		BeforeEach: []func(any){
			func(t any) { t.(*Test_org_eclipse_swt_accessibility_AccessibleControlEvent).SetUp() },
		},
		AfterEach: []func(any){
			func(t any) { t.(*Test_org_eclipse_swt_accessibility_AccessibleControlEvent).TearDown() },
		},
		Tests: []junit.Test{
			{Name: "test_ConstructorLjava_lang_Object", Run: func(t any) {
				t.(*Test_org_eclipse_swt_accessibility_AccessibleControlEvent).Test_ConstructorLjava_lang_Object()
			}},
			{Name: "test_toString", Run: func(t any) { t.(*Test_org_eclipse_swt_accessibility_AccessibleControlEvent).Test_toString() }},
		},
	})
}
